### ISSUE TITLE
cannot terminate minisatip

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#1]
Hi,
minisatip works as far as expected, but i'am not able to terminate it:

>satip ~ # pidof minisatip
>1773
>satip ~ # kill -9 1773
>satip ~ # pidof minisatip
>1773
>satip ~ #

**Comment by catalinii** [comment]
Hi,

the application does not ignore kill signals (in fact it cannot ignore kill -9), which makes me think that the app is inside of a syscall.

Do you have any issues before killing the app ?
Does 'killall minisatip' works ?

Also, can you try running compiling the last commit and run:

./minisatip -l -l
and provide me /tmp/log 
 
Thanks

**Comment by 3PO** [comment]
Now it works! :)

It seems there was a Problem with my USB DVB Devices. I changed the USB Hub and now it works as expected.

**Comment by 3PO** [comment]
The Problem still exist.

minisatip is in a "uninterruptible sleep state"

>satip ~ # ps -eo ppid,pid,user,stat,pcpu,comm |grep minisatip
>    1  1737 root     D     0.0 minisatip
>satip ~ #


Log: https://paste.lugons.org/show/6404/
Kernel trace: https://bpaste.net/show/e9e11a3bd01e

**Comment by catalinii** [comment]
I suppose the application hangs in the ioctl in set_filter .

When can you reproduce the issue with minisatip, can you use another applications that use pid filtering ?

**Comment by 3PO** [comment]
>When can you reproduce the issue with minisatip...

After a reboot, when minisatip was in a "uninterruptible sleep state", i start minisatip again and sometimes after minutes and sometimes after hours, minisatip goes into  a "uninterruptible sleep state" again,

>[...] can you use another applications that use pid filtering ?

I dont have installed any other DVB applications on this PC.
It is only a Little Intel NUC with 4 USB DVB-S2. and 2 DVB-T Sticks.

This is my quick'n'dirty "Testing set up":  :)

![ov_satipserver](https://cloud.githubusercontent.com/assets/945108/5720092/c259e2a6-9b1f-11e4-937c-a4859b037bdf.jpg)

**Comment by catalinii** [comment]
Is it possible to connect the dvb card that you are using without the usb hub.
My setup involves a tp-link 1043nd and the usb dvb-s2 card connected in the port the router have and I have no problem with it after days of usage.

**Comment by 3PO** [comment]
I have 6 DVB Devices and only 2 USB 2.0 and one USB 3.0 Port.

At the Moment, all 6 Devices pluged in a 10 Port USB 3.0 Hub (-> see Picture above).

I can make at test with only 2 DVB-S2 Devices, one in each USB 2.0 Port.

**Comment by 3PO** [comment]
What does this mean?

--> https://bpaste.net/show/ad1aa59ae0ef

**Comment by catalinii** [comment]
Hi,

Can you provide the whole log?

Did it happen when you pressed ctrl+c?

**Comment by 3PO** [comment]
>Can you provide the whole log?

No, it is deleted after reboot.


>Did it happen when you pressed ctrl+c?

No, minisatip was started in deamon mode.   (via initscript -> start-stop-deamon)

**Comment by 3PO** [comment]
I find out, if i do a channelscan with a Windows Client with DVBViewer, the System lose the DVB Devices and minisatip die with a segfault:

dmesg:
>[ 6809.262993] xhci_hcd 0000:00:14.0: xHCI host not responding to stop endpoint command.
>[ 6809.262997] xhci_hcd 0000:00:14.0: Assuming host is dying, halting host.
>[ 6809.263030] em28178 #1: writing to i2c device at 0xd0 failed (error=-5)
>[ 6809.263035] i2c i2c-3: m88ds3103: i2c wr failed=-5
>[ 6809.263040] xhci_hcd 0000:00:14.0: HC died; cleaning up
>[ 6809.263056] em28178 #0: writing to i2c device at 0xd0 failed (error=-5)
>[ 6809.263060] i2c i2c-1: m88ds3103: i2c rd failed=-5 reg=0d len=1
>[ 6809.263069] usb 2-2: USB disconnect, device number 2
>[ 6809.263115] em28178 #0: Disconnecting em28178 #0
>[ 6809.263118] em28178 #0: Closing DVB extension
>[ 6809.267412] i2c i2c-1: a8293: i2c failed=-19 rd=0
>[ 6809.267486] em28178 #0: Freeing device
>[ 6809.267734] usb 2-3: USB disconnect, device number 3
>[ 6809.267769] em28178 #1: Disconnecting em28178 #1
>[ 6809.267772] em28178 #1: Closing DVB extension
>[ 6809.270658] i2c i2c-3: a8293: i2c failed=-19 rd=0
>[ 6809.270724] em28178 #1: Freeing device
>[ 6809.270861] usb 2-4: USB disconnect, device number 4
>[ 7125.182498] minisatip[1882]: segfault at 3000000030 ip 00000000004065e4 sp 00007fff901aa4a0 error 4 in minisatip[400000+15000]

.
>satip ~ # ls /dev |grep dvb
>satip ~ #

.
Log: http://dreipo.cc/logs/log3.tgz

**Comment by 3PO** [comment]
it seems, the behavior i told above, happens if more the one Client want connect to minisatip.

**Comment by catalinii** [comment]
Hi,

I have fixed a memory problem in the latest commit.
Please check now if the application core dumps again.

The initial issue (minisat stuck in a uninterruptible sleep state) is different from what I have just fixed.

Thanks

**Comment by 3PO** [comment]
Hi,

now i have this issue in kernel log:

--> https://paste.lugons.org/show/6412/

I dont know, if this is a Problem of my Hardware, or minisatip?

Log: --> http://dreipo.cc/logs/log4.tgz

**Comment by catalinii** [comment]
Hi,

In the syslog I see that the usb 3 port is getting disconnected (probably your DVB-S2 card is USB2) and it seems minisatip was not connected to any DVB card at the time the log ends.
In my opinion is a hw issue and I think  connecting the device directly to the NUC can make a difference.
Give it a try with 1 or 2 devices (using NUC's usb ports) leave it for a day or more and see what happens.

Thanks

**Comment by 3PO** [comment]
Hi,

>[...] Give it a try with 1 or 2 devices (using NUC's usb ports) ... 

exactly this is the Setup.
I have connected 2 PCTV 461e Sticks, one on each USB 2.0 Port of my NUC.
Nothing else is connected, but LAN. :)

**Comment by catalinii** [comment]
I was afraid of that :).

I think other than trying one device at a time to see if they behave differently I am out of ideas...

Do you think there is something in minisatip that I could differently?

**Comment by 3PO** [comment]
I think at first i sould find out, if this is a Problem with the (USB-) Hardware.
Linux and USB-DVB-Hardware are not realy good friends. :)
I have a ITX Board and a Dual DVB-S2 PCIe Card (http://tinyurl.com/ps2bd3k)
Maybe i find some time at the Weekend and i'll setup a test Environment.

**Comment by catalinii** [comment]
Any luck with the tests?

**Comment by 3PO** [comment]
New Hardware:

--> https://bpaste.net/show/79c31a5222cc

![ov_satip2](https://cloud.githubusercontent.com/assets/945108/5797493/2f71ee70-9fbb-11e4-8e4e-7a93451c2fa9.jpg)


With DVBViewer it seems working, but not with the VDR.

I dont know, if this is a Problem with minisatip, or the VDR satip-Plugin?

see: --> http://tinyurl.com/nfcfktk

**Comment by catalinii** [comment]
Did you had this issue before? (Vdr seg fault)?

**Comment by 3PO** [comment]
No, not with the "GSS.box DSI 400".

**Comment by catalinii** [comment]
I meant with minisatip.

Recently i upgraded the description xml .

Try the first commit and see if that works.

**Comment by 3PO** [comment]
No, it works not realy. :(

--> https://bpaste.net/show/bc7681585c84


BTW: i think it is better to open a separate issue for "minisatip and VDR".

**Comment by catalinii** [comment]
Can you upload minisatip log and vdr log as well...I see some 404s :)

**Comment by 3PO** [comment]
New, separate issue for VDR and minisatip:

--> https://github.com/catalinii/minisatip/issues/21

**Comment by psyborg55** [comment]
> Is it possible to connect the dvb card that you are using without the usb hub.
> My setup involves a tp-link 1043nd and the usb dvb-s2 card connected in the port the router have and I have no problem with it after days of usage.

Hi

Are you using any kind of USB cord or plug the dvb card directly into the port ?
Have a similar setup here with 461e running on archer c7 with tvheadend and always getting i2c write failures in log, sometimes even FE_READ_STATUS i/o error
FE_READ_STATUS No such device or address

Don't recall ever seeing i2c write failures while used the card in Ubuntu laptop
