### ISSUE TITLE
TEARDOWN

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#10]
is this right to close before sent out?

	else if (strncmp (arg[0], "TEARDOWN", 8) == 0)
{
close_stream (s->sid);
http_response (s->sock, "RTSP", 200, NULL, NULL, cseq);
}

**Comment by catalinii** [comment]
Yes, I am trying to avoid the situation in which the new stream comes before actually closing the socket  the current stream.

Basically I am freeing all the resources first.
