### ISSUE TITLE
Troubles with DVBViewer

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#100]
Hi,

I tested last version (build 83) with DVBViewer and DVB-T, and the minisatip is detected as SAT>IP server but it don't work. No scanning and no tunning (with channels already scanned using another BDA tuner).

Please, can you test with the demo version of DVBViewer?

The most annoying is that DD-TV (OEM version of DVBViewer for Digital Devices) is working (up to now, the only DVB-T SAT>IP client working for Windows), but last version of DVBViewer (most newer) is not working.

**Comment by catalinii** [comment]
Hi,

I have the previous version and it was ok tofay.

I will test the version released today soon and fix it.

Thanks

**Comment by lars18th** [comment]
Hi,

I do tests with builds 82 & 83 (I discovered this project this week, so first version for me is 82), and never works with DVBViewer. Advise: only tested with DVB-T tuners.

Regards!

**Comment by catalinii** [comment]
Generally i test the releases with dvbviewer.
can you please upload the full log?

**Comment by catalinii** [comment]
Hi 

Dvbviewer demo does not support SAT>IP as far as I know (please include the link to the application you are using and the full minisatip logs).
I have tested DVB-T scanning with Dvbviewer pro and it works.

Thanks

**Comment by lars18th** [comment]
Hi,

I'm a customer of DVBViewer Pro with a pay license. I don't know if last version of DVBViewer "demo" has SAT>IP or not. My comments are related to Pro version.

If you check minisatip with DVBViewer Pro, then Great! However, isn't working in my system. I'll do more tests, and I put here the logs.

Regards!

**Comment by lars18th** [comment]
Hi,

Related to the problem with DVBViewer Pro... here my comments:

- Yes, after some new tests, the minisatip is working. But has problems in some circunstances. For example, if you do the scanning process with another device (BDA device) and then enable only the minisatip as input, then you can receive the channels. However, the scanning process has several problems using minisatip. The main problem is a problem with LOW BITRATE STREAMS.

I explain more about this issue: The current code seems to use some type of timers for sending the TS (I don't really check this, It's an assumption). The troubles seems to be with output streams with low bitrates. If you put filters for only receive some tables (PAT, PMT, etc.) then the result is an irregular streaming. In this case the client don't receive correct packets.

For testing I recommend this setup: Download TSReader Lite and use the HTTP interface (don't forget to check "Don't check for HTML5 streams") to receive the TS using the HTTP API of the minisatip. If you include "pids=all" in the URI then all the time the streaming is good, but if you use instead some "pids=" with a list of low biterate tables then you show some discontinuities and/or stops in the streaming.

Please, check this behaviour. In my system I observe this troubles.
Regards!

**Comment by catalinii** [comment]
Hi,

I know what you mean, basically minisatip should send any packet (if received) every 50ms (and it should detect a low bit rate stream and send every time it gets a DVB packet and not buffer them).
DVBViewer Pro has an issue (I see it is fixed in DVBViewer GE) that you cannot scan 1 frequency, just to scan a range of frequencies, because for the first frequency it sends SETUP, waits few seconds,  then PLAY and then immediately it sends TEARDOWN without waiting to receive the stream.

Please try to scan a range and attach the log.

Thanks

**Comment by 3PO** [comment]
DVBViewer (5.3.2.0) is working perfect with minisatip and DVB-T:


![2015-03-10_182223](https://cloud.githubusercontent.com/assets/945108/6580750/d9430b78-c752-11e4-8401-82f7de3aab12.png)

**Comment by lars18th** [comment]
Hi,

> DVBViewer (5.3.2.0) is working perfect with minisatip and DVB-T

Except some troubles with the scanning process... related to low bit rates.

I suggest to test it (minisatip) also with TSReader Lite in HTTP mode. I see more troubles receiving the stream over http (tcp) than with rtsp (rtp/udp).

**Comment by catalinii** [comment]
Hi Lars,

I am rewriting a good part of that area in 0.3 to incorporate new features and after that I will test again (so far I've seen only low bit rate).
If you saw something else please attach screenshots and if u get issues on dvb-s please let me know the satellite/freq.

Thanks

**Comment by lars18th** [comment]
Hi,

I'll do more tests when I have sufficent time! :)

I hope you will commit the new version soon... ;-)

**Comment by catalinii** [comment]
Adding new features.... hopefully everybody will like them ;)

But it goes slower than I expected (lack of time mostly).

**Comment by catalinii** [comment]
Btw did you manage to test this?

I tried today to scan with dvbviewer and it went fine.

Thanks

**Comment by lars18th** [comment]
Hi Catalinii,

At time I'm using the ancient version of minisatpi, because new releases are "under development". The CA support is awesome (untested at time by me). However, for my current needs the support for pids=all in HTTP and the SAT>IP client support has more priority.

However, I'll try soon the current version (very busy at time).

Please, if I can help you let me know.
Regards.

**Comment by lars18th** [comment]
Hi,

I close this thread because after checking it with last releases all is working...

- USB DVB-T Dual tuner
- Minisatip 0.3.37
- DVB Viewer v5.3.2.0
- DVB Source 3.9.1.0

Regards.
