### ISSUE TITLE
Location in SSDP announcements use wrong IP address when -V is used

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#1007]
If a server has two IP addresses, `10.110.4.10` and `10.110.4.13`, and minisatip is started with `-V 10.110.4.13`, it listens on 10.110.4.13 as expected, but the location of the XML in SSDP announcements is 10.110.4.10 unless `-w` is also specified.

`opts.http_host` should inherit the `-V` value.

**Comment by lars18th** [comment]
Hi @Jalle19 ,

Please check my PR #1064 .

**Comment by lars18th** [comment]
Hi @Jalle19 ,

Time to close this issue?
