### ISSUE TITLE
Priority parameter

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#101]
Hi,

I suggest to add a priority parameter for realtime execution.

See exemple of "-i" in DVBlast:
- Documentation: http://github.com/gfto/dvblast/blob/master/README#L285
- Code: http://github.com/gfto/dvblast/blob/e8c528d29ec2700b0e672eb9e7effb37a1a03c6d/dvblast.c#L1112

Easy and efective. :)

Note: DVBlast uses pthreads, and minisatip at time don't use it (perhaps when multithread is added). So if you like use "renice" command for adjust priorities.

**Comment by catalinii** [comment]
I think the thread implementation is close... when I will add it I will keep this in mind.

Thanks

**Comment by lars18th** [comment]
Hi Catalin,

Implemented on v0.3.45. Thank you!

However, please, document it:"-i -10" changes priority INCREASING priority by 10 points!
Positive values are in fact lowering the priority, and Negative values are increasing it.

Regards.

**Comment by catalinii** [comment]
Will add that to the next commit.

Thanks

**Comment by lars18th** [comment]
Great! The parameter is really working, it only needs to be well documented.

Thank you!

**Comment by catalinii** [comment]
It will be added to the next commit (the readme change).
