### ISSUE TITLE
is there a way to set user:password for streaming (in m3u for example)?

### ISSUE THREAD

**Issue by apuokas** [catalinii/minisatip#1024]
i think it can be usefull if stream could be password protected. Sadly, i found nothing about that.

**Comment by Jalle19** [comment]
That is outside the scope of this project. You can use a reverse proxy if you want to provide authentication.

**Comment by catalinii** [comment]
@apuokas can u provide more info related to your use case?

**Comment by apuokas** [comment]
for example if i wish stream over internet, but just for people who know password. Something like this: protokol://my-addres.tv/xxx/yyy?username=USER&password=PASS
