### ISSUE TITLE
Issues on AXE devices with latest builds

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#1025]
See https://github.com/Jalle19/satip-axe/issues/39#issuecomment-1354708663

It seems like the builds done by the CI here work, probably since they're compiled with PMT=0. Should that be the official way to compile for AXE? It didn't use to be necessary to do it.

**Comment by catalinii** [comment]
``

**Comment by catalinii** [comment]
I do not have hw access to look more into this. 
I am not sure there is a point to have PMT=1 because the processor is very weak ...

**Comment by estimadarocha** [comment]
@catalinii i can provide that again....

**Comment by Jalle19** [comment]
I initially re-enables it so it would display service names in the web interface.

**Comment by catalinii** [comment]
I can take a look tomsee what is going on if I can repro

**Comment by Jalle19** [comment]
Closing this for now, will re-open if there are still any issues
