### ISSUE TITLE
BUG: PMT of channel continues after closing

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#1043]
Hi @catalinii ,

Please, reproduce this using three different clients:
- Client 1 opens channel A.
- Client 2 opens channel B _in the same transponder_.
- Client 3 opens channel A.
- In the UI you will see in streams: "Channel A, Channel B"
- Client 1 closes the connection (of chA).
- Client 3 closes the connection (of chA).
- What you see in the UI? "Channel B" ? **NO**, it continues with "Channel A, Channel B".

Therefore a bug exists inside the PMT handling, because when a channel is opened multiple times, but after it will be closed, the PMT continues _selected_ and not removed. Please check it.

Regards.

**Comment by Jalle19** [comment]
Yeah, there's definitely something going on. It's also possible that a running PMT is not mentioned in the UI, especially for CI adapters.

**Comment by lars18th** [comment]
> Yeah, there's definitely something going on. It's also possible that a running PMT is not mentioned in the UI, especially for CI adapters.

I agree. And because I have no proficiency with Unit Tests, maybe someone else could implement a test for PMTs. I feel that this test will expose this bug (and perhaps others too).

**Comment by lars18th** [comment]
Hi @catalinii ,

I've compiled the _last_ commit, and this bugcontinues. See this capture:

![minisatip-pmt-bug](https://user-images.githubusercontent.com/9989964/220418258-d7382d55-ca32-48e4-abda-e29f2f4126ef.png)

This is after I open 3sat with one VLC, then Kika with another VLC, and finally 3sat another time with a third VLC.
After I close first and third VLC instances (both playing 3sat). And while Kika continues playing, the PMTs processed continue to be "3sat HD, KiKa HD".

So please could you check this?
Thank you.

**Comment by catalinii** [comment]
Hi @lars18th, thanks for the repro.
Can you upload a log when this happens ?
-l http

**Comment by lars18th** [comment]
> Hi @lars18th, thanks for the repro. Can you upload a log when this happens ? -l http

Hi @catalinii ,

The log is not necessary at all. This is REPRODUCIBLE. You only need to execute the 5 steps commented at start. With any pair of FTA channels in the same transponder. Please, check it. The problem appears every time with any recent version of minisatip. I prefer that you see it and debug it in realtime.

**Comment by lars18th** [comment]
Hi @catalinii , only for curiosity: What you use to debug/test minisatip ?

**Comment by lars18th** [comment]
> > Hi @lars18th, thanks for the repro. Can you upload a log when this happens ? -l http
> 
> Hi @catalinii ,
> 
> The log is not necessary at all. This is REPRODUCIBLE. You only need to execute the 5 steps commented at start. With any pair of FTA channels in the same transponder. Please, check it. The problem appears every time with any recent version of minisatip. I prefer that you see it and debug it in realtime.

To indentify properly the problem, please see that the pid of the PMT of the stoped program is not in the pid list. Therefore the problem is inside the internal processing of the PMTs. And I repeat: the problem appears every time if a client opens a Channel A, another client a Channel B, and after a third the same Channel A. The error appears then if first client closes the session and then the third... until the second is playing the Channel B the PMT of the Channel A continues inside the list.

Please, check it and try to fix this bug.

**Comment by lars18th** [comment]
Hi @catalinii ,

You done the test?

**Comment by lars18th** [comment]
Hi @catalinii ,

With recent changes, the issue has gone. Thank you.
