### ISSUE TITLE
Crosscompile ... need help please

### ISSUE THREAD

**Issue by SaulGoodman1337** [catalinii/minisatip#1044]
Hi,
i am somehow too stupid to throw minisatip for my Duo2 4K through the crosscompiler.
I need a Current Binary only with this single feature enabled !

minisatip configuration

Linux DVB: enabled
Common Interface (CI) disabled
Embedded system: disabled
DVBCSA (needs libdvbcsa): disabled
Netceiver support: disabled
SatIP Client: disabled
Static: disabled
dvbapi: disabled
axe: disabled

can someone give me a hand here? i am also not sure if i have the right toolchain.

> 
> [XXXXXXXXXXX@daniel-x1 minisatip]$ ./configure CC=~/Dokumente/git/minisatip/stbgcc-4.8-1.7/mipsel-linux-gnu/bin/ --host=mipsel-linux-gnu --disable-dvbapi --disable-satipc --disable-netcv --disable-dvbcsa --disable-dvbca make
> configure: WARNING: you should use --build, --host, --target
> checking for mipsel-linux-gnu-gcc... /home/XXXXXXXXXXX/Dokumente/git/minisatip/stbgcc-4.8-1.7/mipsel-linux-gnu/bin/
> checking whether the C compiler works... no
> configure: error: in `/home/XXXXXXXXXXX/Dokumente/git/minisatip':
> configure: error: C compiler cannot create executables
> See `config.log' for more details

> root@vuduo4kse:~# uname -a
> Linux vuduo4kse 4.1.45-1.17 #1 SMP Fri Jan 13 06:05:30 UTC 2023 armv7l GNU/Linux

**Comment by lars18th** [comment]
Try to compile using Docker... https://github.com/catalinii/minisatip/issues/911#issuecomment-1018721451

**Comment by Jalle19** [comment]
You're probably better off downloading a pre-built MIPS binary from https://github.com/catalinii/minisatip/releases

**Comment by SaulGoodman1337** [comment]
> You're probably better off downloading a pre-built MIPS binary from https://github.com/catalinii/minisatip/releases

Impressive help.

**Comment by lars18th** [comment]
Hi @SaulGoodman1337 ,

> Try to compile using Docker... https://github.com/catalinii/minisatip/issues/911#issuecomment-1018721451

I repeat it: use the Docker compile. With it you can compile for MIPS with whatever configuration that you need.

**Comment by SaulGoodman1337** [comment]
> Hi @SaulGoodman1337 ,
> 
> > Try to compile using Docker... [#911 (comment)](https://github.com/catalinii/minisatip/issues/911#issuecomment-1018721451)
> 
> I repeat it: use the Docker compile. With it you can compile for MIPS with whatever configuration that you need.

Nobody talked to you either ;).
The question has long been clarified therefore leave closed here
