### ISSUE TITLE
info only: vtuner satip client

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#105]
the latest work regarding vtuner satip clients can be found here
http://www.vuplus-support.org/wbb3/index.php?page=Thread&postID=969099#post969099
it's gone from github

**Comment by lars18th** [comment]
Hi,

This is an upgraded version of vtuner for SAT>IP? Where is the github of the project?

**Comment by pbriesch** [comment]
Hi lars18th,

the author of the upgraded versions has deleted his account on GiHub ann will not continue the project for personal reasons. Therefore he was asking people who need his SAT>IP client to copy his Repository before he would delete it.

> ich möchte alle bitten, die den SAT>IP Client noch benötigen, eine Sicherung des Github-Repository anzufertigen.
> Ich werde den kompletten Account in den nächsten Tagen löschen.
> Es wird von mir aus privaten Gründen keine Weiterentwicklung mehr geben.

Paul

**Comment by lars18th** [comment]
Hi,

You're speaking about this project: http://code.google.com/p/satip/ or another one?

In any case, I suggest to canalinii to duplicate the repository and continue with it. :)

**Comment by pbriesch** [comment]
No, I mean the project of the user **Ferranti** to which **9000h** refers to:  http://www.vuplus-support.org/wbb3/index.php?page=Thread&postID=969099#post969099

There you can download the code *satip-client-1.1-r2.tar.gz* if you are a registered board member.

**Comment by lars18th** [comment]
Hi,

I'm not registrered on this board... so, I suggest, please, to upload a copy to another place.

I hope someone will like to continue with the work with a commit to some new github repository. I feel the original author agrees it!

**Comment by pbriesch** [comment]
Well, I'm not registered either.
