### ISSUE TITLE
Release DVB devices for powersaving with Sundtek USB devices

### ISSUE THREAD

**Issue by goldelehr** [catalinii/minisatip#1054]
Hi,

would it be possible for minisatip to fully release currently unused devices? I have a Sundtek USB DVB-S stick which won't go into powersave mode until _/dev/dvb/adapterX/frontend0_ and _/dev/dvb/adapterX/dvr0_ are released by the process. Minisatip permanently keeps these two devices in use and prevents the stick to go into powersave mode. TVHeadend for example directly releases all devices after it doesn't use them anymore for streaming or epg grabbing. 

There is a tool for Sundtek devices which lists devices with their current attachend PIDs. 

This is how it looks when Minisatip is idling:
```
mediaclient --lc
**** List of Media Clients ****
/dev/dvb/adapter2/frontend0:
  4163606 ... minisatip
/dev/dvb/adapter2/dvr0:
  4163606 ... minisatip
/dev/dvb/adapter2/demux0:
  No client connected
/dev/mediainput0:
  No client connected
```

This is how it looks when TVHeadend is idling:
```
mediaclient --lc
**** List of Media Clients ****
/dev/dvb/adapter2/frontend0:
  No client connected
/dev/dvb/adapter2/dvr0:
  No client connected
/dev/dvb/adapter2/demux0:
  No client connected
/dev/mediainput0:
  No client connected
```

I'm really willing to help but unfortunately i'm not great at C. 

Thanks for your help and keep up the good work.

**Comment by catalinii** [comment]
Hi,

Generally minisatip release a device if there are no clients using it.

Can u upload a log showing the adapters being kept open?

Thanks

**Comment by goldelehr** [comment]
I also own a WinTV DualHD stick which gets released fine. It seems to be an issue with the Sundtek devices. 

I enabled "general,adapter" for increased log verbosity. At around 09:20:23 i switched to a channel and watched it until 09:20:47. I waited for another 3 minutes before cutting the log file. 

[minisatip1.log](https://github.com/catalinii/minisatip/files/10791249/minisatip1.log)

The adapter timeout was set to 30 seconds.

**Comment by sundtek** [comment]
Can you try:
/opt/bin/mediaclient --softpidfilter=on -d /dev/dvb/adapter0/dvr0

if all pid filters are closed the tuner is supposed to deliver the entire transport stream.
this behaviour is different than with regular kernel drivers - regular kernel drivers will not deliver any data at that point.

--softpidfilter=on should also stop delivering data once all filters are removed.

The reason for this is that we want to tune to a transponder and allow a simple cat on the DVR interface for reading the transport stream without having to set up any PIDs.

**Comment by Jalle19** [comment]
@goldelehr please try @sundtek 's suggestion and reopen the ticket if the issue persists
