### ISSUE TITLE
Maximum numbers of DVB Devices?

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#106]
Hi, 

is there a Limit for DVB Devices?

I have 10 Devices installed,

>server02 ~ # ll /dev/dvb
>insgesamt 0
>drwxr-xr-x 12 root root  240 18. Mär 16:58 .
>drwxr-xr-x 13 root root 3380 18. Mär 16:58 ..
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter0
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter1
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter2
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter3
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter4
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter5
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter6
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter7
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter8
>drwxr-xr-x  2 root root  120 18. Mär 16:58 adapter9
>server02 ~ #

but on my Client i can see only 8 Devices:

>vdr01_64 ~ # svdrpsend plug satip list
>220 vdr01_64 SVDRP VideoDiskRecorder 2.2.0; Wed Mar 18 18:56:48 2015; UTF-8
>900 192.168.177.11|DVBS2-8|minisatip
>221 vdr01_64 closing connection
>vdr01_64 ~ #

Is this a Problem of minisatip, or VDR?

**Comment by 9000h** [comment]
in adapters.h is the limit set  MAX_ADAPTERS 8

**Comment by 3PO** [comment]
Thanks!

**Comment by 3PO** [comment]
I have set it to 32, but it doesnt work. :(

Ist there a Limitation on the Client side?

**Comment by 3PO** [comment]
[SOLVED]
 
with this Patch it works as expected:

https://bpaste.net/show/1f32d5d5e962

@catalinii,

can you please apply this in the Repo?

**Comment by catalinii** [comment]
Thanks, i will apply this in the next commit.

**Comment by catalinii** [comment]
I will close this as this is fixed.

Thanks for reporting it
