### ISSUE TITLE
[VDR satip-Plugin] Blackscreen in case of a EPG Scan

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#107]
Hi,
If a EPG Scan will trigger, i get a Blackscreen.
When i press the OK Button on my remote, the VDR is swtiching to the former Channel and everythink is ok.

I'am not sure, if this is a Problem of minisatip, or thr satip Plugin? 

VDR Log: --> https://paste.lugons.org/show/7323/

minisatip Log: --> https://paste.lugons.org/show/7322/

Thread in vdrportal: --> http://www.vdr-portal.de/board17-developer/board21-vdr-plugins/126184-satip-plugin-blackscreen-in-case-of-a-epg-scan/

**Comment by vdrtuxnet** [comment]
Hi,

I had this issue twice with vdr-plugin-satip.
In my opinion vdr-plugin-satip or vdr will trigger the black screen issue, other clients don't.

Rolf isn't very helpful, in cases regarding vdr-plugin-satip and non octopus net devices, I already contacted him by email as terms of some other problems and his answers sounds like a tiny god complex.

**Comment by 9000h** [comment]
Hi,
is it only related  to encrypted channels?

**Comment by 3PO** [comment]
Maybe in future, someone can provide a "minisatip Plugin" for the VDR?= ;)

>[...] is it only related to encrypted channels?

It doesn't matter, if the channels are encryted, or FTA.

**Comment by 3PO** [comment]
Really no one any ideas? :(

**Comment by catalinii** [comment]
Hi 3PO,

I looked briefly on this but did not see anything unusual.
I suggest waiting for the new commit and we can look if there is something different and maybe look what minisatip does at the exact time of the blackscreen.

**Comment by 3PO** [comment]
Here the issue with the latest commit of minisasip:

minisatip log: https://bpaste.net/show/22ccd87c3800

vdr log:  https://bpaste.net/show/f39435fbe3ba

**Comment by catalinii** [comment]
Just a quick question, you had this issue with all minisatip versions?

**Comment by 3PO** [comment]
If you mean the Problem with the blackscreen if a EPG scan ist triggert, then yes.

BTW: The Problem still exists also with the latest commit. --> 4cf1ff9

**Comment by 3PO** [comment]
Solved! :)

The Problem was the Setup of the satip Plugin.

If i start the Plugin with the Parameter "-d 4", the Problem is gone.

README:

>[...]
>The plugin accepts a "--devices" (-d) command-line parameter defaulting
>to one. This parameter defines how many simultaneous transponders can
>be received, if there are available SAT>IP tuners.
>...

But i dont understand, why the Plugin dont loading available Tuners by itself, if it is necessary??
