### ISSUE TITLE
SAT>IP over long distance WAN with relay

### ISSUE THREAD

**Issue by Delitants** [catalinii/minisatip#1073]
Hi, I'm looking the way to establish SAT>IP connection over long distance WAN and I would need to have some sort of relay or proxy in the middle to buffer, due to very high latency. Is it possible?

Point A (minisatip server) -> Intermediate point B (here minisatip should receive, buffer and pass further) -> Point C (minisatip client)

**Comment by Jalle19** [comment]
If you connect two instances with TCP it works well even over longer links, have you tried that?

**Comment by Delitants** [comment]
> If you connect two instances with TCP it works well even over longer links, have you tried that?

What's that means? How?

**Comment by lars18th** [comment]
Hi @Delitants ,

> What's that means? How?

From the README:
```
-O --satip-tcp Use RTSP over TCP instead of UDP for data transport
```

Therefore, if your SAT>IP _remote_ server connected to the antenna is a minisatip instance (or any other with RTSP-over-TCP), then you only need to start your _local_ minisatip adding the option `-O`. With this it will connect with the remote indicated with the param `-s --satip-servers` using the TCP transport instead of UDP.

**Comment by Jalle19** [comment]
Could be interesting to add SRT support to minisatip (https://www.haivision.com/products/srt-secure-reliable-transport/)

**Comment by lars18th** [comment]
> Could be interesting to add SRT support to minisatip (https://www.haivision.com/products/srt-secure-reliable-transport/)

That's one of my ideas. But I feel it could be difficult to achieve it. What you think @catalinii ?

**Comment by catalinii** [comment]
I use minisatip over long latency WAN.
The setup (currently) is: 
minisatip A (using DVB cards) -> VPS using xinetd port forwarding (~ 20-40ms away) -> minisatip B (180ms away from vps) -> tvh, enigma2, ...

The reason I use VPS is that the bandwidth from minisatip A to B is small, but I found few local VPs providers where the bandwidth from A to the VPS is high.

To give you a sense of speed:
- minisatip A -> B generally I can do a SD channel
- regular VPS in EU I can watch an HD channel (1.5MB/s)
-  local good VPS I can stream a 4K channel (3-4MB/s)

In case of not enough bandwidth generally the data is buffered on the server side (minisatip A) until it overflows when packet loss/image artifacts happens. In severe cases the connection is reset when minisatip re-establishes the connection.

I used UDP also when the connection is good and the advantage is that I see picture faster (smaller latency) using UDP vs TCP (tcp has something called slow start).

I have a specific network setup (sysctl snd tcp congestion algo modification on minisatip B) but that's about it

We can try SRT if you guys have experience with it...

**Comment by lars18th** [comment]
Hi @catalinii ,

My `satipc` use is in-home only. However, I've do some tests with something similar to you, and the results are not good. The main reason is when the bandwitdh varies a lot and some packets are lost. Anyway, please could you share with us the `sysctl` custom configuration?

> We can try SRT if you guys have experience with it...

I've do a lot tests in the past. And this protocol is rock-solid. If you want to include it inside the minisatip it could be simple to achieve it: the RTP channel can go through the SRT connection without much effort. Therefore you only need to modify the `satipc` module.

Regards.

**Comment by catalinii** [comment]
I am using this:
```
# cat /etc/sysctl.con
net.core.wmem_max=12582912
net.core.rmem_max=12582912
net.ipv4.tcp_rmem= 10240 87380 12582912
net.ipv4.tcp_wmem= 10240 87380 12582912
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1

# head -20 /etc/rc.local
#!/bin/bash

modprobe tcp_scalable
echo "scalable" > /proc/sys/net/ipv4/tcp_congestion_control

**Comment by catalinii** [comment]
It is expected to loose packets, of course you can always increase the buffer sizes (using -B, eg -B 100 - which is 100MB)... but if the BW is not sufficient at some point the buffer will be full and overflow.

**Comment by catalinii** [comment]
@lars18th I tried using srt-live-stransmit to connect 2 instances of minisatip but do not see any improvements:
server A:
```
./minisatip -l http -f -r localhost
```
On a separate console:
```
./srt-live-transmit udp://127.0.0.1:6500 srt://serverB:1234
```
On server B:
```
./minisatip -s serverA -l http
srt-live-transmit srt://0.0.0.0:1234?mode=listener udp://serverB:6500
```

**Comment by Jalle19** [comment]
I'm guessing SRT would perhaps bring improvements only for bad links, not ones where UDP or TCP would otherwise work good enough.

**Comment by Jalle19** [comment]
Closing this since there's nothing actionable here

**Comment by Delitants** [comment]
Still would be nice to have an ability that one minisatip connects to another remote minisatip and act as both client and server at the same time.

**Comment by catalinii** [comment]
As I said above, I am using minisatip over wan with 180ms between client and server and can stream 4k channels

**Comment by Delitants** [comment]
> As I said above, I am using minisatip over wan with 180ms between client and server and can stream 4k channels

Right, but I have other reasons besides that. How to chain remote minisatip instances to act as proxies one for another.?

**Comment by catalinii** [comment]
You can chain as many as you want using -s (as a client)

**Comment by catalinii** [comment]
Can you provide an example of a use case that you want to have working?

**Comment by Delitants** [comment]
> Can you provide an example of a use case that you want to have working?

For example to distribute from a CDN node instead of source server due to limited bandwidth.

**Comment by catalinii** [comment]
What would be needed for that to work?

**Comment by Jalle19** [comment]
Sounds like something that is out of scope for minisatip itself

**Comment by Delitants** [comment]
> What would be needed for that to work?

using -s flag seems does what I was looking for and I was able to connect two minisatips in chain. Thank you.

**Comment by Delitants** [comment]
It looks like documentation doesn't match the behavior.
-s client
	* [*] Use TCP if -O is not specified and UDP if -O is specified

UDP on other hand does not work at all, it keeps using TCP regardless of this flag.

/root/minisatip/minisatip -s dvbs2:remote_server:8888 -I minisatip-export1 -l general -f

[04/09 18:13:33.876 signal]: AD0: Satip device remote_server port 8888 delsys 6: dvbs2 dvbs, fe -1, total number of devices 1
[04/09 18:13:35.917 signal]: tcp_connect: failed: connect to remote_server:8888 failed with errno 115: Operation now in progress
[04/09 18:13:35.917 signal]: could not connect to remote_server:8888
[04/09 18:13:35.917 signal]: opening adapter 0 failed to open the adapter with code 2

**Comment by catalinii** [comment]
-O --satip-tcp Use RTSP over TCP instead of UDP for data transport

you can specify UDP for a specific satip server if -O is specified and then you add * in the argument of -s

**Comment by Jalle19** [comment]
https://github.com/catalinii/minisatip/pull/1388
