### ISSUE TITLE
Old packets left in DDCI buffer sometimes

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#1076]
Lately I've noticed that sometimes when I switch to a channel, the switch happens very quickly and K get about a second of old video/audio from the last time the channel was active. Could be a regression since introducing the new FIFO buffer? @catalinii have you noticed something similar?

**Comment by Jalle19** [comment]
It's of course also possible it's my tvheadend that is acting up.

**Comment by Jalle19** [comment]
I've only seen it when switching back to the same channel as was previously tuned. It doesn't happen every time, but sometimes.

**Comment by Jalle19** [comment]
Reverting seems to fix the issue.

**Comment by catalinii** [comment]
Thx for the report

**Comment by catalinii** [comment]
Can you send me a quick repro?

**Comment by Jalle19** [comment]
Like I said, just switch between a CAM channel and a free channel. When you switch back to the encrypted channel it will start at the same place it started the last time.

**Comment by catalinii** [comment]
can you try next branch ? It should be fixed

**Comment by Jalle19** [comment]
Which commit is supposed to fix it? :thinking:

**Comment by catalinii** [comment]
Sorry forgot to push it.: https://github.com/catalinii/minisatip/commit/303ab856620e6676178efa538f4c7ad34be5dfb4

**Comment by Jalle19** [comment]
Thanks, I'll try to find time to test next week

**Comment by Yuri666** [comment]
For me it fixed

**Comment by Jalle19** [comment]
Seems fixed indeed, thanks @catalinii !
