### ISSUE TITLE
UUID not generated if SSDP discovery is disabled

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#1078]
With discovery disabled, it should still be possible to use the SAT>IP server by providing the URL to `/desc.xml` manually. This currently only kind of works, because the XML is out of spec:

```
<UDN>uuid:</UDN>
```

This at least causes some older tvheadend versions to crash

**Comment by lars18th** [comment]
Interesting, so we need to generate the UUID outside of the SSD function.

**Comment by Jalle19** [comment]
Yep, looks like it. I'm thinking it could also make sense to store the UUID in a file so it could be decoupled from the MAC address completely. But first step would be to separate it from SSDP discovery.

**Comment by lars18th** [comment]
> Yep, looks like it. I'm thinking it could also make sense to store the UUID in a file so it could be decoupled from the MAC address completely. But first step would be to separate it from SSDP discovery.

I don't think so. Storing the UUID in a file will generate troubles. It's preferable to assign it with the command line if the user *needs* it. Remember it: minisatip is _file config free_ !!

**Comment by Jalle19** [comment]
I'm thinking it would auto-generate a random UUID and store it in a file if the file does not exist.

**Comment by lars18th** [comment]
Hi @Jalle19 ,

I implemented the fix in #1119 . 😉

**Comment by lars18th** [comment]
Hi @Jalle19 ,

Please remember to close this issue when PR #1140 will be merged. 👍 

Regards.
