### ISSUE TITLE
New "next" branch?

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#1079]
Hi @catalinii ,

Why the new "next" branch and the regresion of the releases? Please, could you explain the changes on them?

Thank you.

**Comment by catalinii** [comment]
There are few changes that made the master unstable. So I pulled them in next, while the small fixes are in master.
I want to ensure that master is stable and then continue working on next until that one is stable.
The next branch will become 1.3.

**Comment by lars18th** [comment]
Hi,

I feel this commit could be merged with "master": https://github.com/catalinii/minisatip/commit/41ba38c223bf64234e49e7716078897ba540e423

**Comment by catalinii** [comment]
Thanks ...I added that commit too
