### ISSUE TITLE
How to compile for Enigma2?

### ISSUE THREAD

**Issue by Delitants** [catalinii/minisatip#1082]
Hi, I can't find any references in wiki of how to compile it for Enigma2 with FBC tuner.
Thanks.

**Comment by catalinii** [comment]
The arm binary works for enigma, fbc or non enigma devices.

**Comment by Delitants** [comment]
> The arm binary works for enigma, fbc or non enigma devices.

How do you compile for arm? I have DM920

**Comment by catalinii** [comment]
Arm version: https://github.com/catalinii/minisatip/releases

**Comment by Delitants** [comment]
Thanks, those are releases, but how to compile from sources?

**Comment by catalinii** [comment]
minisatip_arm.zip is the binary: https://github.com/catalinii/minisatip/releases/download/v1.2.102/minisatip_arm.zip

**Comment by Jalle19** [comment]
@Delitants here's how the release builds are made: https://github.com/catalinii/minisatip/blob/master/.github/workflows/binaries.yml#L37. You'll need to have a MIPS cross-compilation toolchain installed.

**Comment by Jalle19** [comment]
Closing this
