### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#1086]
Based on the comments in source files it should be GPL 2.0 or later.

**Comment by Jalle19** [comment]
I need a link to a LICENSE file to apply for CLion licenses, so I'll make a PR

**Comment by CvH** [comment]
just use spdx to keep it standard :)
https://spdx.org/licenses/GPL-2.0-or-later.html
```
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2014-2020 Catalin Toda <catalinii@yahoo.com>
```
