### ISSUE TITLE
Damn docker!

### ISSUE THREAD

**Issue by B15cut3r** [catalinii/minisatip#1095]
They will see:
I have Tvheadend running on a pc with Ubuntu 22.04 connected to Oscam and the Digibit Twin sat>ip device to get DVB-S signals. I've heard for quite some time that both TVH and Oscam should ideally be installed in separate Docker containers, so I finally decided to get down to it. More by intuition than by technical knowledge that I do not have, I thought that the communication between TVH and Oscam would be more fluid if both were connected to an internal Docker network created for this purpose; but, as you know, there is a problem for this solution and it is that, apparently due to a lack in Docker, TVH is not able to see the sat>ip device unless it is connected to the host network, so I installed them So.
It occurred to me that minisatip might be the solution to this problem. If minisatip, installed in a container and connected to an internal Docker network, was able to communicate with my Digibit Twin, then TVH and Oscam could connect to that same network and everything would be fine.
I did it like that. I installed minisatip in a container and connected it to an internal network and started it with these arguments; ‘-s 192.168.1.33 -s 192.168.1.33 -o 172.20.0.4:8085 -O --satip-tcp’. And yes, minisatip connected with Digibit Twin. Accessing their web interface I could see the two tuners there, so I connected TVH and Oscam to the same network as minisatip. TVH shows in its list of adapters the 2 tuners managed by minisatip Bravo!
Yet alas! When trying to play a channel there is nothing. Not even Oscam shows the TVH request, although they say they are correctly connected and if I scan the muxes I find FAILURE. When scanning TVH, it shows the active adapters and with good signal intensity and quality, but the minisatip website also shows them active, but the signal intensity and quality bars are empty.
What happen? The system seems to be ready to work, but it is not. Should it work? Actually also minisatip can't connect with Digibit Twin under those conditions or is there a configuration problem?
I would appreciate any answers, although, as you may have noticed, my knowledge is limited.

**Comment by Jalle19** [comment]
See the --satip_xml option for tvheadend, it might be that you don't need minisatip at all.

**Comment by B15cut3r** [comment]
Yeah! I have been testing that option and then Tvheadend finds both the minisatip and Digibit Twin adapters, but neither of them is able to tune channels. Now I have tried another option, minisatip runs on the host and Tvheadend and Oscam in a container connected by a docker network. --satip_xml tells Tvheadend where minisatip is. Works! The next option will be minisatip in a container connected to the host network.

**Comment by Jalle19** [comment]
Okay, glad you made some progress. Can we close this ticket? There doesn't seem to be a bug here.

**Comment by B15cut3r** [comment]
Oh! Sure, sorry. I never thought it was a minisatip error.

Thank you!
