### ISSUE TITLE
minisatip and satipclient on the same ip no longer connect

### ISSUE THREAD

**Issue by uwe5** [catalinii/minisatip#1097]
Hi,

If minisatip and the client (vdr or tvheadend) are running on the same computer (same ip), then the client no longer connects to minisatip.
If the minisatip or the client is started on another computer, it works.
This problem persists after checkout ad307a0. With ad307a0 or older, minisatip runs parallel to the client on the same computer.

**Comment by Jalle19** [comment]
Do you mean that https://github.com/catalinii/minisatip/commit/ad307a0cdbec28cb1a77ece8b055be4cb42a35de is the first broken commit or that it's the last working one?

**Comment by Jalle19** [comment]
@uwe5 ?

**Comment by uwe5** [comment]
If you remove the compiler option "-O2" in "src/Makefile.in", then minisatip and the client run on the same IP.
If I add the -O2 option again, it doesn't work.

**Comment by Jalle19** [comment]
Sounds incredible. Which is the newest commit that works without editing the Makefile?

**Comment by Jalle19** [comment]
@uwe5 is this still an issue?

**Comment by Jalle19** [comment]
Closing this for now, I've been running minisatip and tvheadend on the same system for a long time and haven't stumbled upon this.
