### ISSUE TITLE
-o offset Parameter parser error

### ISSUE THREAD

**Issue by uwe5** [catalinii/minisatip#1098]
Hi,
the offset value with the -o parameter is no longer parsed.

**Comment by Jalle19** [comment]
Do you have an example of a version where it still worked? Might help with tracking down the cause of the breakage.

**Comment by Jalle19** [comment]
Indeed, `-o 192.168.1.100:9001,1` is parsed as `192.16:9000`, offset 1

**Comment by Jalle19** [comment]
So adding an offset screws up the host part, and the port is not recognized at all

**Comment by Jalle19** [comment]
Will factor out the option parsing to separate functions so they can be easily tested

**Comment by Jalle19** [comment]
Additionally there's a bug when passing `~`, it only works correctly if no port or offset is specified

**Comment by Jalle19** [comment]
Fixed in https://github.com/catalinii/minisatip/pull/1105 , will try to remember to backport to master
