### ISSUE TITLE
handling of bootid

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#11]
it's may cosmetic in this stage of the code but it's missing.

the Spec says
The BOOTID.UPNP.ORG value shall increase each time that the device first announces on the network. It shall be stored in non-volatile memory

so it may got stored in a file or the handling could be done via cli option

**Comment by 9000h** [comment]
seems like it's a different issue, with every ssdp_reply BOOTID get incremented which is wrong and should be incremented after starting minisatip only once.

[Thu Jan 15 18:09:45.970 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 18:09:45.970 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 109
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 18:09:45.970 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 18:09:45.970 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 110
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 18:12:30.563 2015]: ssdp_reply -> 192.168.178.124
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 18:12:30.563 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 111
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

**Comment by catalinii** [comment]
Done in the last commit, can you confirm everything is ok ?
