### ISSUE TITLE
Unicable II tuning not working

### ISSUE THREAD

**Issue by Delitants** [catalinii/minisatip#1106]
Hi, this issue was reported several times year ago and still persists.
Unicable II (JESS) is not working! It's not a switch problem, it's not cables, etc... it's minisatip.

http://192.168.20.230:8081/?msys=dvbs2&mtype=8psk&freq=11766&pol=v&sr=29900&pids=all

Suppose to tune 11766V at 29900 but no signal coming.
Tested and confirmed using Tvheadend and Astra Cesbo, which don't have any issues tuning different transponders over defined UB slot (6) and freq (1155) at adapter 18. Minisatip is just does not do anything but hijacking what was tuned in other software on this adapter before minisatip.

/root/minisatip/minisatip -I minisatip3 -O -y 554 -D 3 -x 8081 -e 18 -j 18:6-1155 -l ca -E -t -f
**Tried -u and -j - no difference**
[minisatip.log](https://github.com/catalinii/minisatip/files/11521636/minisatip.log)

**Comment by Delitants** [comment]
Using blind guess I have deducted -1 from actual slot number (on switch side it's 6) and set I set is as 5 (-j 18:**5**-1155) and it tuned as expected.
Please fix.

**Comment by Jalle19** [comment]
Slot numbers start at 0 in minisatip, there's nothing to fix there. The example in the README uses slot 0 as well. So are you saying your years of Unicable troubles were down to this?

**Comment by Delitants** [comment]
> Slot numbers start at 0 in minisatip, there's nothing to fix there. The example in the README uses slot 0 as well. So are you saying your years of Unicable troubles were down to this?

Apparently yes. And why is on Earth you have decided to start it from 0 when every major switch maker start it with 1? There is nothing in readme, at least clear enough to understand that you count it from zero.

**Comment by Jalle19** [comment]
I guess we'll have to make it clearer in the README, I doubt it's worth changing the meaning of the value to start from 1 anymore, that would mean everyone would have to update their settings.

Glad you found the problem, shame it took so long :/
