### ISSUE TITLE
Only "?? ??:0" in stack trace despite addr2line being installed

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#1108]
```
$ addr2line -e /usr/local/bin/minisatip 0x55b506de26a0
??:0
```

Is there anything special needed during compilation to make `addr2line` work? I got a rare crash recently and it sucks to not be able to see what actually happened.

@catalinii help?

**Comment by catalinii** [comment]
-ggdb should generally help.
The other option is to run minisatip inside of gdb:
gdb --args minisatip -f ....

**Comment by Jalle19** [comment]
What do you mean by -gdbg?

**Comment by catalinii** [comment]
-ggdb should be in gcc arguments...this enabled debugging info for gdb

**Comment by Jalle19** [comment]
Seems like tvheadend does this:

```
CFLAGS  += -g
ifeq ($(CONFIG_CCDEBUG),yes)
CFLAGS  += -O0
else
CFLAGS  += -O2 -D_FORTIFY_SOURCE=2
endif
```

**Comment by catalinii** [comment]
Generally is really hard to debug with anything higher than -O0

**Comment by Jalle19** [comment]
Maybe we should just always build with -g -O0 on all builds then so when a crash happens we can always get a trace?

**Comment by catalinii** [comment]
That wht I was thinking too… but on null deference this can still happen if running minisatip outside of gdb

**Comment by catalinii** [comment]
There is also asan which can help with the stack traces but did not invest much time to look into that (make debug)
