### ISSUE TITLE
old tuners have problems with dvb-t2 requests

### ISSUE THREAD

**Issue by jyrts** [catalinii/minisatip#1122]
Mutant HD2400 has 4 physical swappable tuners. I am running minisatip on it.

Usually when a client requests a DVB-T2 stream, the request looks like:
rtsp://@192.168.2.39:554/?freq=634&bw=8000&gi=4&msys=DVBT&mtype=256qam&pids=591,791,18,391,0

This seems to be a problem for some older tuner (at least for Mutant HD2400) minisatip server. It expects the client request to be msys=DVBT2:
rtsp://@192.168.2.39:554/?freq=634&bw=8000&gi=4&msys=DVBT2&mtype=256qam&pids=591,791,18,391,0 (this works)

I know, I know... The Mutant HD2400 is right and the client is wrong... The client IS requesting in reality DVB-T2 but is asking it wrong. Seems to be a problem in the client side? BUT at the same time on newer tuner minisatip server (like the VU+ Zero) the DVB-T2 stream works even when client requests it as msys=DVBT 

It seems to be a tuner driver/client request issue. Can minisatip be used to fake/fix/hack this msys issue?

I'm not getting any stream from my old Mutant HD2400 satip server. Somehow I need to manually over-rider the default msys type... Then it works...

**Comment by Jalle19** [comment]
What client behaves like this?

**Comment by jyrts** [comment]
the satip client is VU+ Zero 4K with OpenATV image.

All DVB-T2 requests are made with msys=DVBT

**Comment by jyrts** [comment]
I checked the Enigma 2 DVB-T config file file /etc/tuxbox/terrestrial.xml and the transponder has system="1" enabled, that means DVB-T2 

More like https://github.com/oe-alliance/satip-client problem...

**Comment by Jalle19** [comment]
Closing for now, feel free to re-open if you still think this issue is actually in minisatip and not in the client
