### ISSUE TITLE
Descrambling ICAM with OSCAM dreambox mode

### ISSUE THREAD

**Issue by djseban** [catalinii/minisatip#1126]
Hey there,

Recently I tried to descramble ICAM packets by minisatip - turns out in dreambox mode it's impossible (or using libdvbcsa in general) - I have to use hardware descrambler, at least on my sh4 box. Unfortunately that makes descrambling ICAM streams impossible.

What I tried is relaying entire stream to TVH for it do descramble - unfortunately the descrambler won't touch the stream it receives from minisatip (TS introduces itself as not scrambled maybe? - at least that's what I get in VLC codec info). How could I handle this issue? Thanks.

**Comment by catalinii** [comment]
You need either a compiled binary from here: https://github.com/catalinii/minisatip/releases or a patched libdvbcsa (https://github.com/catalinii/libdvbcsa)

**Comment by djseban** [comment]
@catalinii Thanks for fast reply :). I am compiling myself. I already patched libdvbcsa and compiled newest commit in your repo.

**Comment by djseban** [comment]
@catalinii I attached gdb to tvheadend process, and in fact the stream appears as descrambled ((tsb[3] & 0xc0) false and scrambled false in tsdemux.c of TVH). Regards

**Comment by djseban** [comment]
I did some research and there were already some SAT>IP issues on SH4 boxes (i.e. not being able to descramble ts on TVH). What I reckoned is that I'd try manipulating CW based on ECM directly in OSCAM:
```
		for(j = 0; j < demux[i].ECMpidcount; j++) // check for matching ecmpid
		{
			if((demux[i].ECMpids[j].CAID == er->caid || demux[i].ECMpids[j].CAID == er->ocaid)
				&& demux[i].ECMpids[j].ECM_PID == er->pid && demux[i].ECMpids[j].PROVID == er->prid
				&& demux[i].ECMpids[j].VPID == er->vpid)
			{
				if (er->icam_csa_ks == NULL) {
					er->icam_csa_ks = get_key_struct();
				}

				if (er->ecm[0] == 0x80) {
					set_even_control_word_ecm(er->icam_csa_ks, er->cw, er->ecm[0x15]);
				} else {
					set_odd_control_word_ecm(er->icam_csa_ks, er->cw + 8, er->ecm[0x15]);
				}
				get_control_words(er->icam_csa_ks, er->cw, er->cw + 8);
				break;
			}
		}
```
As you can see it also involves adding icam_csa_ks to ECM_REQUEST struct.
This way every ECM gets handled by ffdecsa, and if it detects ICAM it will handle the key as needed. Non-ICAM still works, the problem is ICAM hw descrambling still won't work in that configuration. Maybe that gives some info. Regards :)

**Comment by catalinii** [comment]
Which receiver with sh4 are u using?

**Comment by djseban** [comment]
ADB-5800SX (adb_box)

**Comment by Jalle19** [comment]
Is there anything actionable here or can this ticket be closed?

**Comment by lars18th** [comment]
> Is there anything actionable here or can this ticket be closed?

I feel this can be closed.
