### ISSUE TITLE
fill_sockaddr: gethostbyname(localhost): Too many open files

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#113]
Hi,

with the latest commit (c3854bb) i find Messages like.

>fill_sockaddr: gethostbyname(localhost): Too many open files

in the syslog:

https://bpaste.net/show/1c26c4b39d7d

minisatip is started with: 

>-g -l -o localhost:4444

**Comment by catalinii** [comment]
Hi,

Can you upload the full log?

Thanks

**Comment by 3PO** [comment]
Logfile:  --> http://dreipo.cc/logs/log.tgz

**Comment by catalinii** [comment]
I think I know what this issue is.
Will fix it in the next commit.

**Comment by catalinii** [comment]
Is this fixed in the last commit?

Thanks

**Comment by 3PO** [comment]
Sorry, but i've disabled satip at the moment,
 Because of this Problem -> https://github.com/catalinii/minisatip/issues/107 , satip is not very usefully with the VDR.

**Comment by catalinii** [comment]
Hi 3PO,

I will close this case as I believe the issue is fixed .
If you still get the issue if you test again please reopen it.

Thanks
