### ISSUE TITLE
How to dump a full CI module firmware using TBS 6900+minisatip?

### ISSUE THREAD

**Issue by Delitants** [catalinii/minisatip#1131]
Hi, I know that minisatip creates some sort of .bin file in var/cache when connecting CI module. But is there a way to dump a full CI firmware for debugging purposes? I have TBS 6900 available. Thanks.

**Comment by Jalle19** [comment]
Not that I know of. The binary file created is related to the CAM communication, it's not retrieved from the CAM but generated during initialization.
