### ISSUE TITLE
Using minisatipwith multiple tuners

### ISSUE THREAD

**Issue by atallo** [catalinii/minisatip#1133]
When I use minisatip from Plex it indicates that only one tuner is available. This means that I can't watch more than one channel at a time even though my computer has 2 tuners.

I think that the information provided by /desc.xml is not enough to indicate tuners.

~~Would it be possible to add a new "/discover.json" url with that information?~~

~~You can see an example implementation in this file. Line 35~~
~~https://github.com/jkaberg/tvhProxy/blob/master/tvhProxy.py~~

I was testing this file but Plex does not read it. I don't know the reason because only one tuner appears. Do you know what it could be?

Thanks! This app is amazing!

**Comment by Jalle19** [comment]
Do you see two tuners in the minisatip web interface?

**Comment by atallo** [comment]
Yes. I see them. And I can use them. I tried it with VLC.

**Comment by atallo** [comment]
When I use programs other than minisatip I can see all the tuners on Plex.

**Comment by Jalle19** [comment]
What other programs have you tried?
