### ISSUE TITLE
Feature request: Option to select TCP (-s SATIPC) specifically for individual server connections

### ISSUE THREAD

**Issue by Wanninger** [catalinii/minisatip#1138]
It would be helpful if it were possible to select TCP or UDP transport depending on the destination server.

Example:

There are three SATIP servers, one DD-ONet and two minisatip servers in a network. The DD-Onet can only use UDP, but the two minisatip servers can also use TCP.

Maybe something like this:

...-s -TCP 192.168.0.100 -s -TCP 192.168.0.101 -s -UDP 192.168.0.102

The -O option forces all SATIPC connections to speak TCP, which is not helpful here.

-THX

**Comment by Jalle19** [comment]
This is already possible, see the help text for the "-s" parameter. Basically you add an asterisk to indicate TCP mode.
