### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by Wanninger** [catalinii/minisatip#1139]
In the section

-s satip servers

is written
[*] Use TCP if -O is not specified and UDP if -O is specified

but it should be 
[*] Use TCP if -O is specified and UDP if -O is not specified

-THX

**Comment by Wanninger** [comment]
Thanks for the hint with the asterisk - inserted before the server IP without spaces, it works perfectly.

The asterisk in front of the server IP negates the "-O" function. So the readme.md is correct, no typo.

I just interpreted it incorrectly.

-THX

**Comment by Jalle19** [comment]
You're right, I too read it wrong yesterday when I marked this as a bug
