### ISSUE TITLE
Problems tuning China Taiwan ST2-88.0E Multistream channels

### ISSUE THREAD

**Issue by xxj737** [catalinii/minisatip#1142]
Hi @catalinii !
I have a ZGEMMA H7S(openatv 7.3 Enigma2 )   running Minisatip standalone.
My receiver is enhanced with the(si2169d) DVB-S2X dual tuner so I can receive all China Taiwan multistream channels from ST2-88.0E  on Enigma2.

PLS+ISI  Gold 
I've tested the last version (Linux/1.0 UPnP/1.1 minisatip/1.3.6~31e9ba2) with VLC adding the &plsm=gold param and I got VLC can't open url error.
I've tried these URLS:

http://192.168.10.129:8554/?fe=1&src=1&freq=11669&pol=h&msys=dvbs2&sr=30000&fec=35&ro=0.35&mtype=qpsk&plts=off&isi=036&plsc=248232&pids=0,1,16,17,20,1000,1001,1002,1003,1010,1020,1030,8187

**Comment by Jalle19** [comment]
Are you sure 8554 is the HTTP port and not the RTSP port?

**Comment by xxj737** [comment]
My try rtsp is fail 

rtsp://192.168.10.129:8554/?fe=1&src=1&freq=11669&pol=h&msys=dvbs2&sr=30000&fec=35&ro=0.35&mtype=qpsk&plts=off&isi=036&plsc=248232&pids=0,1,16,17,20,1000,1001,1002,1003,1010,1020,1030,8187

![微信截图_20240425192811](https://github.com/catalinii/minisatip/assets/50125219/610097cd-f4ad-4c54-9675-b8911b0cb15f)

**Comment by catalinii** [comment]
Port 8554 is enigma generally. Try port 554 instead

**Comment by Jalle19** [comment]
@xxj737 any luck with port 554?
