### ISSUE TITLE
IPv6 does not work

### ISSUE THREAD

**Issue by MichaelMMS** [catalinii/minisatip#1143]
My Version: **4.3-2323**

I am using a raspi 4, latest **64 bit os debian 12.5**
IPv6 works on rasypi:
```
ip a:
inet6 2xxx:c5:5f45:9400:6866:734a:e91c:ab56/64 scope global dynamic noprefixroute 
       valid_lft 7063sec preferred_lft 1075sec
    inet6 fd00::d955:93b6:6959:f442/64 scope global deprecated dynamic noprefixroute 
       valid_lft 7063sec preferred_lft 0sec
    inet6 fe80::9344:f256:d301:ded8/64 scope link noprefixroute 
```

So:

```
http://[2xxx:c5:5f45:9400:6866:734a:e91c:ab56]:9981 or
http://[fe80::9344:f256:d301:ded8]:9981
```

**does no work.**

`TVH_IPV6=1`
in `/etc/default/tvheadend `is set 

I get no connection to tvh, only IPv4 works.

Any idea?

Thx
Michael

**Comment by catalinii** [comment]
Hi,

minisatip needs -4 to listen in ipv6 connections.

let me know if it works

**Comment by Jalle19** [comment]
I think TVH_IPV6=1 doesn't work anymore, you need to manually specify the `-6` flag in `OPTIONS`.

**Comment by MichaelMMS** [comment]
`-6` works! Thank you!

`http://[2xxx:c5:5f45:9400:6866:734a:e91c:ab56]:9981 `

works

`http://[fe80::9344:f256:d301:ded8]:9981` (lokal lan does not work)

But I read this is due to firefox and chrome. They removed the lokal link support, I don't now why?
In MacOs Safari lockl link ipv6 works.

**Comment by Jalle19** [comment]
Good. Either way, none of this has to do with minisatip, so closing this.
