### ISSUE TITLE
SAT>IP website down: lack of PDF of Specification

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#1157]
Hi,

The document http://satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf  is missing.

I suggest to upload a copy to this repository.

**Comment by Jalle19** [comment]
Yeah I noticed the same. I have a copy, will commit it 👍

**Comment by lars18th** [comment]
Hi @Jalle19 ,

Thank you. However, you need now to edit the README. 😉
