### ISSUE TITLE
v1.3.10 - 14 no signal on GigaBlue UHD X3 4K

### ISSUE THREAD

**Issue by misushot** [catalinii/minisatip#1158]
hi,

i1 have since v1.3.10 no signal on GigaBlue UHD X3 4K.
v1.3.9 works fine.

**Comment by Jalle19** [comment]
Can you post a log with "-l general"? Can you also describe your LNB setup?

**Comment by Jalle19** [comment]
@misushot ?

**Comment by misushot** [comment]
Hi,
was on the way. I'll send it in detail over the weekend.

**Comment by MartB** [comment]
Same problem on the UE 4K
```
-j 0:0-1210,1:1-1420,2:2-1680,3:3-2040,4:7-1140,5:16-1770,6:19-1905,7:18-1860 -S 1:0
```

Is my LNB setup, no obvious errors in the logs, but i will post one later today.

**Comment by Jalle19** [comment]
Thanks, if it fails with default parameters there must be something wrong. I'll have a look.
