### ISSUE TITLE
Issues with EyeTV client due to to PIDs being deleted on stream close

### ISSUE THREAD

**Issue by dmarion** [catalinii/minisatip#116]
EyeTV Client uses pids= statement only during the 1st PLAY, after that it uses addpids=,delpids=.

1st PLAY
PLAY rtsp://192.168.123.30:554/stream=1?pids=0,16,17,18,19,20,121,3211,8190 RTSP/1.0

2nd PLAY
PLAY rtsp://192.168.123.30:554/stream=1?delpids=121,3211&addpids=525,2574

But minisatip deletes all pids after 1st stream is closed.

Sat>IP spec says:
The client should issue a “pids=” statement at least when changing transponders in order to clear the configured pid list and avoid that hanging pids are carried through without ever being removed.
When PIDs values have been defined, it is always possible to remove all PIDs from the filtering process through the “pids=none” attribute-value pair.

This implicitly says that server should not delete pids even when changing transponders...

**Comment by catalinii** [comment]
Hi,

Can you please upload the full log for this?

Thanks

**Comment by catalinii** [comment]
About pids=none, I am not sure if I enable the behaviour of keeping all the pids when changing the freq i might get in a situation of having too many pids open. But the behaviour you are explaining with 2 streams needs to be investigated.

**Comment by dmarion** [comment]
full log:
http://pastebin.com/RugJYTXR

**Comment by catalinii** [comment]
Hi 

in this log I see just one stream, and not 2
# grep stream log | grep done
[13/04 17:46:46.5615]: Setup stream done: sid: 0 (e:1) for sock 6 handle 11

So I think it is normal to close all the pids once there is no active stream, right ?

If I misunderstood the problem, can you please point out the exact lines where you think is the problem ?
Thanks

**Comment by dmarion** [comment]
I changed channel 3 times in that log:

1st change:
SETUP rtsp://192.168.123.30:554/?src=3&freq=10972&pol=v&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=27500&fec=34 RTSP/1.0
PLAY rtsp://192.168.123.30:554/stream=1?**pids=0,17,18,19,20,106,206,3061,8190** RTSP/1.0

2nd change:
SETUP rtsp://192.168.123.30:554/stream=1?src=3&freq=11596&pol=h&ro=0.35&msys=dvbs2&mtype=8psk&plts=off&sr=30000&fec=34 RTSP/1.0
PLAY rtsp://192.168.123.30:554/stream=1?**delpids=206,3061&addpids=525,2574** RTSP/1.0

3rd change:
SETUP rtsp://192.168.123.30:554/stream=1?src=3&freq=10972&pol=v&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=27500&fec=34 RTSP/1.0
PLAY rtsp://192.168.123.30:554/stream=1?**delpids=525,2574&addpids=106,206,3061** RTSP/1.0

So seems that you should not close pids when stream is closed.

Spec says that it is client responsibility is to clear pids which implicitly means that you should not do that automatically on stream close.

**Comment by catalinii** [comment]
Hi,

I am not too sure it is a good idea to keep the pids once the stream is closed, few reasons:

1) There is the possibility of the client dying, or a network issue, then I would keep those pids in different transponders where actually there is no data (or there is something else).  
2) If I do not have a stream where to send the data, why to process it in  the first place ?
3) Another thing is that the number of hardware pid filters are limited.

Do you have a scenario (or more) where this is useful ?

Thanks

**Comment by dmarion** [comment]
No real scenarios, problem here is that this client doesn't work with minisatip.
I just tried same one with tvheadend Sat->IP server and it works fine...

**Comment by catalinii** [comment]
Btw, does it stop at some point, or it doesnt work at all?

**Comment by dmarion** [comment]
Main problem is channel search, as it fails to get PAT after tuning to new freq.
standard zapping mainly works, as PAT is not needed.

BTW EyeTV is one of the first certified Sat>IP clients, so i guess Sat>IP guys belive 
that the way how it works is inline with spec.

**Comment by catalinii** [comment]
Hi,

Can you provide a log with -l -l  -l -l -l -l (6 times)?

Thanks

**Comment by catalinii** [comment]
Hi,

is this still an issue ?

Thanks

**Comment by dmarion** [comment]
Hi, sorry, for long delay.

Yes, it is still the issue. Problem is very simple:
minisatip cleans PID list on each SETUP, but setup can be used for both creating new session and modify existing:

Difference is:

Create new session:
SETUP rtsp://192.168.123.3:554/src=2&freq=....

Update existing session:
SETUP rtsp://192.168.123.3:554/stream=1?src=2&freq=....

in second case minisatip should not tear down session, it should just update parameters.

Reference: Sat>IP spec page 31
