### ISSUE TITLE
Fritzbox response quirk broken due, response code parsed incorrectly

### ISSUE THREAD

**Issue by retrofan1979** [catalinii/minisatip#1164]
Hello,

I noticed when I try to do a channelscan with DVBViewer Pro and TransEdit with minisatip as SAT>IP server, it rejects the connection.
However, when I play an SAT>IP URL it streams just fine.
Also when analyzing a mux with TransEdit it works fine.
Only a channelscan fails. Hope you can fix it.
I'm using a Fritz!Box 6690 cable.
See logfile attached.

**Comment by retrofan1979** [comment]
![Schermafbeelding 2024-07-17 175358](https://github.com/user-attachments/assets/a2d1ab9f-871e-443f-999d-2ef482365962)
[minisatip.log](https://github.com/user-attachments/files/16269179/minisatip.log)

**Comment by retrofan1979** [comment]
No clues? The logfile is attached in previous comment. Thanks!

**Comment by xxj737** [comment]
pid=all  
Not Supported

**Comment by retrofan1979** [comment]
Thanks, but with TransEdit I can scan a mux with over 100 pids, so no problems here. When I want to do a normal channelscan I get this error.

**Comment by xxj737** [comment]
for example
![微信截图_20240727145624](https://github.com/user-attachments/assets/19b97800-5229-40ac-8e8f-f8c3e80f943b)

**Comment by retrofan1979** [comment]
with SAT>IP server of Fritz!Box 6690 Cable I have no problems at all, but with minisatip the channelscan fails, so it seems a bug in minisatip? Hope you can fix it.

**Comment by retrofan1979** [comment]
Fritzbox:

![fritzbox 1](https://github.com/user-attachments/assets/db4a1cb7-f538-4861-8703-3f2d0ae351ea)

![fritzbox 2](https://github.com/user-attachments/assets/dfc2eb49-3979-4254-a40a-2f50744f9d7c)

**Comment by retrofan1979** [comment]
minisatip:

![minisatip 1](https://github.com/user-attachments/assets/38434cd1-9b52-438b-817d-0de21eec6bcf)

![minisatip 2](https://github.com/user-attachments/assets/ff382d2a-0bc4-4fe1-8563-f49c0658deff)

**Comment by retrofan1979** [comment]
I found out when selecting option "Open whole transponder" it will scan one mux at the time. With Fritzbox this option isn't needed.

**Comment by retrofan1979** [comment]
![minisatip 3](https://github.com/user-attachments/assets/2f4f1f3c-602d-4edf-92c1-071b17174694)

![minisatip 4](https://github.com/user-attachments/assets/b0ffa776-d68c-4bd8-8026-cd4c493f369c)

**Comment by Jalle19** [comment]
Have you tried running minisatip with `-k`?
> * -k Emulate pids=all when the hardware does not support it, on enigma boxes is enabled by default

**Comment by retrofan1979** [comment]
Thanks for the suggestion, I tried it now, but still no luck.

**Comment by retrofan1979** [comment]
The Fritz!Box can do it, so it has to be something with minisatip I guess. Maybe it needs a quirck or the implemented quirck in minisatip isn't needed anymore?

**Comment by retrofan1979** [comment]
Another thought: maybe minisatip has to sent teardown command first before scanning the next mux? Otherwise the tuner isn't available/in use?

**Comment by retrofan1979** [comment]
No other suggestions?

**Comment by catalinii** [comment]
Can you add -l satipc to the command oine and upload a poad again?

**Comment by retrofan1979** [comment]
> Can you add -l satipc to the command oine and upload a poad again?

Hi @catalinii : yes, ofcourse ;-) Here it is.

**Comment by Jalle19** [comment]
```
[05/08 08:43:30.814 AD0]: satipc_reply (adapter 0, state 3): receiving from handle 10, sock 13, code 1434
[05/08 08:43:30.815 AD0]: satipc: Received signal status from the server for adapter 0, stength=113 status=0 quality=0
[05/08 08:43:30.815 AD0]: marking device 0 as error, rc = 1434
```

**Comment by retrofan1979** [comment]
Thanks, but what does it mean and how to fix it?

**Comment by retrofan1979** [comment]
> ```
> [05/08 08:43:30.814 AD0]: satipc_reply (adapter 0, state 3): receiving from handle 10, sock 13, code 1434
> [05/08 08:43:30.815 AD0]: satipc: Received signal status from the server for adapter 0, stength=113 status=0 quality=0
> [05/08 08:43:30.815 AD0]: marking device 0 as error, rc = 1434
> ```

Thanks, but what does it mean and more important: how can we fix it? When I stop the stream and restart it again it works fine. Maybe it needs an extra teardown? Does minisatip obey parameters of the satip server? There's an avm parameters which tells one stream can be used per ip address (avm=1) or more (avm=0)

**Comment by Jalle19** [comment]
I don't exactly know what it means, I just pointed it out since it looks suspicious. Maybe @lars18th or @catalinii knows?

**Comment by 9000h** [comment]
Fritz!Box is some kind of sat>ip compatible but not certificated, and some workarounds still needed (for QAM64 channels for example

**Comment by catalinii** [comment]
Let’S try -v satipc

to identify why is the server erroring out

**Comment by retrofan1979** [comment]
> Let’S try -v satipc
> 
> to identify why is the server erroring out
[service.log](https://github.com/user-attachments/files/16550001/service.log)

Here it is.

**Comment by retrofan1979** [comment]
and another logfile, the same as the previous one, but also added with DVBViewer playback via HTTP SAT>IP URLS port 8080.

[service.log](https://github.com/user-attachments/files/16550116/service.log)

**Comment by retrofan1979** [comment]
@catalinii : did you investigate the logs already? What to do next?

**Comment by Jalle19** [comment]
Seems like the server sends invalid RTSP responses with two empty lines between the headers and the body, leading to the packet being processed as two separate packets:

```
[08/08 16:53:45.417 AD0]: MSG process << server :
RTSP/1.0 200 OK
Content-Base: rtsp://192.168.178.1:554/stream=1918
Content-Length: 205
Content-Type: application/sdp
CSeq: 10
Session: 1931


[08/08 16:53:45.417 AD0]: satipc_reply (adapter 0, state 3): receiving from handle 7, sock 8, code 200
[08/08 16:53:45.417 AD0]: satipc 0, expect_reply 0, want_tune 0 want commit 1
[08/08 16:53:45.417 AD0]: satipc: request for adapter 0, state 3, freq 498000, pids to add 0, pids to delete 0, expect_reply 0, want_tune 0, sent_transport 1, closed_rtsp 0
[08/08 16:53:45.417 AD0]: adapter 0: Nothing to commit
[08/08 16:53:45.461 AD0]: MSG process << server :
v=0
o=- 1931 1 IN IP4 192.168.178.1
s=SatIPServer:1 0,0,4
t=0 0
m=video 0 RTP/AVP 33
c=In IP4 0.0.0.0
a=control:stream=1918
a=fmtp:33 ver=1.2;src=1;tuner=1,113,0,0,498.00,8,dvbc,256qam,6900,,,,
a=sendonly

[08/08 16:53:45.461 AD0]: satipc_reply (adapter 0, state 3): receiving from handle 7, sock 8, code 1931
```

Since the logic for determining the status code is fairly naive, it ends up thinking that the 1931 from `o=- 1931 1 IN IP4 192.168.178.1` is the status code.

**Comment by Jalle19** [comment]
The logging mechanism is also broken, `LOGM` in `satipc_reply` works, but not in `satipc_tcp_read`. Probably due to all the various #undef going on.

**Comment by Jalle19** [comment]
Seems our old friend https://github.com/catalinii/minisatip/issues/508#issue-388111162 has resurfaced

**Comment by Jalle19** [comment]
Fixing the return code algorithm to return 0 if a valid return code is not found will fix this

**Comment by Jalle19** [comment]
A better solution would be to parse the device information like tvheadend does (https://github.com/tvheadend/tvheadend/blob/49ac9387186d32b55a399a04155e835eac22c6c1/src/input/mpegts/satip/satip_frontend.c#L2264) and apply quirks based on device, not return code. Could also be useful to show in the web interface instead of just the IP address.

**Comment by retrofan1979** [comment]
@Jalle19 thanks for investigating, much appreciated! So, probably it can be fixed :-)

**Comment by catalinii** [comment]
I think we should force satipc_tcp_read to wait for the payload. The content-length indicates there is a statically sized payload
