### ISSUE TITLE
dvbapi: process_pat() doesn't process whole PAT if bigger than TS packet

### ISSUE THREAD

**Issue by dmarion** [catalinii/minisatip#117]
It is not uncommon that PAT is bigger than one TS packet.
In that case process_pat() will not process whole PAT.

**Comment by catalinii** [comment]
Hi,

I was thinking that it might be the case .. Do you know a channel that has it bigger than 1 ts packet?

Thanks

**Comment by dmarion** [comment]
11591H @16E

BTW I'm working on implementing CAM support and I implemented PAT processing code which takes care for that.

Are you interested in merging in CAM support (it depends on external libdvben50221) ?

**Comment by catalinii** [comment]
Hi,

I will add support for multiple packets PAT in the next commit.

In general I am interested in en50221, so if you have code that can make that happen I will accept it.

If you want me to implement it, as I do not have hardware it will take some time and probably will handle it after some features.

Thanks

**Comment by dmarion** [comment]
I was working a bit on en50221 and I come up to the point when i am able to decode channel.
However currently PMT PID is hardcoded, so code is not complete.

As I will not be able to continue working on this soon, feel free to take any parts if you decide 
to work on that:
https://github.com/dmarion/minisatip/commit/ffcbdfc6b53ad3864dd828b036538a5d02e4f453 <https://github.com/dmarion/minisatip/commit/ffcbdfc6b53ad3864dd828b036538a5d02e4f453>

Generally, in my code CAM initialisation is done. during the runtime decoding is quite simple, it just need
PMT packet of channel which should be decrypted and libdvben50221 will generate CAPMT from it and 
send it to CAM.

There is also my version of PAT parser which takes care for multiple parts...

**Comment by catalinii** [comment]
Can you create a pull request with your code and I can continue work on it?

Thank you

**Comment by catalinii** [comment]
Will close this, as the multipacket PAT is implemented
