### ISSUE TITLE
no audio because wrong PMT?

### ISSUE THREAD

**Issue by jyrts** [catalinii/minisatip#1194]
I want to watch channel "Comedy Central" with English audio (https://en.kingofsat.net/find.php?question=Comedy+Central+HD)

I run minisatip server on 192.168.2.41 with command line: /usr/bin/minisatip -f -o 127.0.0.1:9000,10 --disable-dvb --disable-ssdp -s 192.168.2.16 -s 192.168.2.17 -s 192.168.2.22 -s 192.168.2.20 -s 192.168.2.18 -s 192.168.2.24 -s 192.168.2.23 -s 192.168.2.32 -s 192.168.2.19 -s 192.168.2.25 -s *dvbs2:192.168.2.128 -s dvbt2:192.168.2.34 -s dvbt2:192.168.2.34 -A 0:0:0,1:1:0,2:2:0,3:3:0,4:4:0,5:5:0,6:6:0,7:7:0,8:8:0,9:9:0,10:10:0

There is "Comedy Central HD." on 19.2°E 
The stream URL is http://192.168.2.41:8080/?freq=11973&src=6&sr=27500&pol=V&msys=DVBS&mtype=qpsk&pids=3021,3024,0,412,3029,3027

Minisatip selects PMT 313 (Comedy Central HD AT) instead PMT 412 (Comedy Central HD.) and then I get no English audio (PID 3024).
I only get German audio (PID 3023) because it is on both channels :(

I did not put PMT 313 on my stream request URL. Why do I get it as response? I requested PID 412

Anyway. No English audio :(
It works half way - I can see that the pid 3024 is mentioned in the stream info in VLC but it is empty
![minisatip](https://github.com/user-attachments/assets/c06c692f-4511-4360-82d3-df89c99c67b6)
![vlc](https://github.com/user-attachments/assets/85a36e5d-f4f6-41e8-adc0-9849e1ca811a)

**Comment by jyrts** [comment]
If it is not a PMT problem (i really don't know how minisatip works), then maybe PID 3024 does not get decoded by oscam and it is forwarded in stream as-is? Then it might be oscam problem? The wired thing is that video (PID 3021) and german audio (PID 3023) gets decoded all good.

**Comment by surfcu** [comment]
This is the same issue as [here](https://github.com/catalinii/minisatip/issues/1129)

**Comment by jyrts** [comment]
Yes, I agree. Seems it is the same issue.

**Comment by catalinii** [comment]
Can you upload some logs with -l http,pmt ?

**Comment by catalinii** [comment]
Closing this as duplicate
