### ISSUE TITLE
MTD Implementation

### ISSUE THREAD

**Issue by surfcu** [catalinii/minisatip#1195]
Although it's avaliable for DDCI, Multi Transponder Decryption is not possible for enigma2 devices.

Is it possible to implement [VDR approach](https://github.com/vdr-projects/vdr/blob/master/mtd.h) for MTD to minisatip?

**Comment by catalinii** [comment]
Are you asking for Digital Devices CI or TBS6900?

if yes, this is already supported

**Comment by Jalle19** [comment]
VDRs implementation won't help with Engima devices AFAICT. It uses similar logic to what we have in minisatip already.

**Comment by surfcu** [comment]
> Are you asking for Digital Devices CI or TBS6900?
> 
> if yes, this is already supported

I was asking for enigma2.

**Comment by Jalle19** [comment]
As far as I know it's not possible to do MTD on Enigma.
