### ISSUE TITLE
loop on close sid?

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#12]
this was with DVBViever Lite 
you may can reproduce it by click the stop button when watching a channel

[Thu Jan 15 00:04:57.634 2015]: starting init_hw 1
[Thu Jan 15 00:04:57.634 2015]: detect_dvb_parameters (S)-> addpids=18
[Thu Jan 15 00:04:57.634 2015]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, pltf=-1, bw=-1, inv=-1, pids=NULL - apids=18 - dpids=NULL
[Thu Jan 15 00:04:57.634 2015]: Setup stream 0 parameters, sock_id 6, handle 14
[Thu Jan 15 00:04:57.634 2015]: copy_dvb_param start -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=0, apids=NULL, dpids=NULL
[Thu Jan 15 00:04:57.634 2015]: copy_dvb_parameters -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=0, apids=18, dpids=NULL
[Thu Jan 15 00:04:57.634 2015]: Play for stream 0, adapter -1, sock_id 6 handle 14
[Thu Jan 15 00:04:57.634 2015]: get free adapter -1 - a[0] => e:1 m:-1 sid_cnt:0 f:0

[Thu Jan 15 00:04:57.634 2015]: Got adapter 0 on socket 6
[Thu Jan 15 00:04:57.634 2015]: set adapter 0 for stream 0 m:0 s:1
[Thu Jan 15 00:04:57.634 2015]: setting DVB parameters for adapter 0 - master_sid 0 sid 0 old f:0
[Thu Jan 15 00:04:57.634 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Thu Jan 15 00:04:57.634 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Thu Jan 15 00:04:57.634 2015]: copy_dvb_param start -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=6, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Thu Jan 15 00:04:57.634 2015]: copy_dvb_parameters -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=0, apids=18, dpids=NULL
[Thu Jan 15 00:04:57.634 2015]: found already existing pid 18 on pos 0 flags 2
[Thu Jan 15 00:04:58.581 2015]: tunning to 11954000(1354000) sr:27500000 fec:FEC_3_4 delsys:SYS_DVBS mod:QPSK rolloff:ROLLOFF_35 pilot:PILOT_OFF
[Thu Jan 15 00:04:58.581 2015]: setting filter on PID 18 for fd 16
[Thu Jan 15 00:04:58.582 2015]: reply -> 14:
RTSP/1.0 200 OK
Cseq: 3
Transport: RTP/AVP;unicast;client_port=52042-52043;source=192.168.178.101;server_port=5500-5501
Session:00619d60;timeout=30
com.ses.streamID: 1

[Thu Jan 15 00:04:58.830 2015]: read RTSP (from handle 14 sock_id 6): PLAY rtsp://192.168.178.101:554/stream=1?addpids=210,220,0,200,230 RTSP/1.0
CSeq: 4
Session: 00619d60

[Thu Jan 15 00:04:58.830 2015]: starting init_hw 1
[Thu Jan 15 00:04:58.830 2015]: detect_dvb_parameters (S)-> addpids=210,220,0,200,230
[Thu Jan 15 00:04:58.830 2015]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, pltf=-1, bw=-1, inv=-1, pids=NULL - apids=210,220,0,200,230 - dpids=NULL
[Thu Jan 15 00:04:58.830 2015]: Setup stream 0 parameters, sock_id 6, handle 14
[Thu Jan 15 00:04:58.830 2015]: copy_dvb_param start -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Thu Jan 15 00:04:58.830 2015]: copy_dvb_parameters -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=NULL, apids=210,220,0,200,230, dpids=NULL
[Thu Jan 15 00:04:58.830 2015]: Play for stream 0, adapter 0, sock_id 6 handle 14
[Thu Jan 15 00:04:58.830 2015]: setting DVB parameters for adapter 0 - master_sid 0 sid 0 old f:11954000
[Thu Jan 15 00:04:58.830 2015]: copy_dvb_param start -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=0, apids=210,220,0,200,230, dpids=NULL
[Thu Jan 15 00:04:58.830 2015]: copy_dvb_parameters -> src=1, fe=0, freq=11954000, sr=27500000, pol=H, ro=0, msys=5, mtype=0, pltf=1, bw=8000000, inv=2, pids=NULL, apids=210,220,0,200,230, dpids=NULL
[Thu Jan 15 00:04:58.830 2015]: not tunning for SID 0 (do_tune=0, master_sid=0)
[Thu Jan 15 00:04:58.830 2015]: setting filter on PID 210 for fd 17
[Thu Jan 15 00:04:58.830 2015]: setting filter on PID 220 for fd 18
[Thu Jan 15 00:04:58.830 2015]: setting filter on PID 0 for fd 19
[Thu Jan 15 00:04:58.830 2015]: setting filter on PID 200 for fd 20
[Thu Jan 15 00:04:58.830 2015]: setting filter on PID 230 for fd 21
[Thu Jan 15 00:04:58.830 2015]: reply -> 14:
RTSP/1.0 200 OK
Cseq: 4
Transport: RTP/AVP;unicast;client_port=52042-52043;source=192.168.178.101;server_port=5500-5501
Session:00619d60;timeout=30
com.ses.streamID: 1

[Thu Jan 15 00:04:58.197 2015]: get_signal took 143 ms for adapter 0 handle 9 (status: 1, ber: 0, strength:0, snr: 48200)
[Thu Jan 15 00:04:59.639 2015]: bandwidth 617KB/s, total bandwidth: 0 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:00.649 2015]: bandwidth 744KB/s, total bandwidth: 1 MB, HD: 0 MB, SD: 1 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:01.660 2015]: bandwidth 735KB/s, total bandwidth: 2 MB, HD: 0 MB, SD: 2 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:02.670 2015]: bandwidth 708KB/s, total bandwidth: 2 MB, HD: 0 MB, SD: 2 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:03.680 2015]: bandwidth 699KB/s, total bandwidth: 3 MB, HD: 0 MB, SD: 3 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:04.691 2015]: bandwidth 753KB/s, total bandwidth: 4 MB, HD: 0 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:05.701 2015]: bandwidth 744KB/s, total bandwidth: 5 MB, HD: 0 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Thu Jan 15 00:05:05.070 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 00:05:05.070 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 7
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 00:05:05.070 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 00:05:05.070 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 8
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 00:05:05.070 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 00:05:05.070 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 9
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 00:05:05.070 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 00:05:05.070 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 10
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 00:05:05.072 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 00:05:05.072 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 11
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 00:05:05.072 2015]: ssdp_reply -> 192.168.178.112
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Thu Jan 15 00:05:05.072 2015
EXT:
LOCATION: http://192.168.178.101:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 12
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 1

[Thu Jan 15 00:05:05.076 2015]: sockets_add: handle 22 (type 1) returning socket index 7 [192.168.178.112:50367]
[Thu Jan 15 00:05:05.086 2015]: read HTTP from 22 sid: -1: GET /desc.xml HTTP/1.0
Host: 192.168.178.101:8080
Keep-Alive: 300
Connection: keep-alive
User-Agent: Mozilla/4.0 (compatible; Synapse)

[Thu Jan 15 00:05:05.086 2015]: starting init_hw 1
[Thu Jan 15 00:05:05.087 2015]: starting init_hw 1
[Thu Jan 15 00:05:05.087 2015]: reply -> 22:
HTTP/1.0 200 OK
Cseq: 0
Content-type: text/xml
Content-Length: 1026

<?xml version="1.0"?><root xmlns="urn:schemas-upnp-org:device-1-0" configId="0">
<specVersion><major>1</major><minor>1</minor> </specVersion><device>
<deviceType>urn:ses-com:device:SatIPServer:1</deviceType><friendlyName>minisatip</friendlyName>
<manufacturer>cata</manufacturer><manufacturerURL>http://github.com/catalinii/minisatip</manufacturerURL>
<modelDescription>long user-friendly title</modelDescription> <modelName>minisatip</modelName><modelNumber>0100</modelNumber>
<modelURL>http://github.com/catalinii/minisatip</modelURL> <serialNumber>0100</serialNumber>
<UDN>uuid:11223344-9999-0000-b7ae-00224d9d3805</UDN><UPC>Universal Product Code</UPC><iconList><icon> <mimetype>image/format</mimetype>
<width>horizontal pixels</width> <height>vertical pixels</height><depth>color depth</depth><url>URL to icon</url> </icon> </iconList>
<presentationURL>http://github.com/catalinii/minisatip</presentationURL>
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBS2-2,DVBT-0</satip:X_SATIPCAP>
</device></root>

[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
[Thu Jan 15 00:05:05.088 2015]: select_and_execute[7]: Close on socket 22 (sid:-1) from 192.168.178.112:50367 - type http failure 0:Success
....

**Comment by catalinii** [comment]
I *think* I fixed this, can you check if you can reproduce ?

Thanks
