### ISSUE TITLE
dvbapi clarification 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#120]
dvbapi.h:32 #define AOT_CA_PMT 0x9F803282

should it be not defined as
#define AOT_CA_PMT 0x9F8032

and the 0x82 probably as
#define T_CREATE_TC    0x82

this would make the code better readable

**Comment by catalinii** [comment]
Hi,

For now I leave it just as it is. If I will add additional dvbapi features, I will keep this in mind.

Thanks for the feedback.
