### ISSUE TITLE
Default RTSP Port

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#125]
Hi Catalinii,

I feel this is a typo: http://github.com/catalinii/minisatip/commit/d132f0ebc46c6b68676213e04eaccb5d94c470dc#diff-26fd799ea07494916e9da9b91b2aac64R21

Because the default RTSP port is 554, right?

**Comment by catalinii** [comment]
Yes you are right, it is a typo, but the port in the app is fine.

Will correct this in the next commit.
Thanks
