### ISSUE TITLE
ssdp issue on latest commit

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#127]
since https://github.com/catalinii/minisatip/commit/d77986282b35dd1888ce321810ae8ab0685a9a67
my Panasonic is not able to detect the server after a power cycle.
I will try to catch some logs later this evening.

**Comment by catalinii** [comment]
Try the last commit please.

Thanks

**Comment by 9000h** [comment]
did try the last commit, still issues.
minisatip is started then Panasonic power on all is ok detected, then power off and wait some time before power on again the Panasoinc is not detecting the server. 
need to grab some logs for you.

**Comment by catalinii** [comment]
Can you test now ?

Thanks

**Comment by 9000h** [comment]
it's working again as expected
