### ISSUE TITLE
Fix compilation without CSA support

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#128]
Hi,

I'm compiling the last commit, but I don't like to mix any CSA libraries/headers (more clean). Then in the Makefile I set this:

DVBCSA?=no
DVBCA?=no

Then the error when "make":

cc  -ggdb -fPIC -DDISABLE_DVBCSA -DDISABLE_DVBCA -c -o minisatip.o minisatip.c
In file included from minisatip.c:44:0:
dvbapi.h:6:27: fatal error: dvbcsa/dvbcsa.h: No such file or directory
compilation terminated.
make: *** [minisatip.o] Error 1

Please, can you fix this?
Also, I suggest to make default compilation without any CSA support, as it's more clean.

Finally, if you can put more info about requirements to compile with CSA support (libraries, headers, etc.) it will be profitable.

**Comment by lars18th** [comment]
Hi,

The workaround is protect the file "dvbapi.h" with the conditional compilation:

#if !defined(DISABLE_DVBCSA)
...
#endif

I hope you commit the fix!

**Comment by catalinii** [comment]
Hi,

I was thinking the same...will fix it in the next commit.

The dependency is libdvbcsa.

Thanks

**Comment by catalinii** [comment]
Hi, 

can you test now ?

Thanks

**Comment by lars18th** [comment]
Correct!
Now, it compiles without CSA, but I suggest to DISABLE it by defult: set DVBCSA?=no in the Makefile

Regards.

**Comment by catalinii** [comment]
I believe most of the people are using DVBCSA anyway, maybe in the future will use configure scripts which to detect the presence of libdvbcsa... and then support for DVBCSA will be automatically removed .

Thanks will close this issue.

**Comment by lars18th** [comment]
Hi,

Please, don't care about auto/non-auto compilation. You can leave at is, if the compilation don't fails;   so the default mode ins't relevant. I only suggest to disable DVBCSA because my feeling is only an small number of people is using it (in fact, I don't test it already). Otherwise leave the default option as enabled.

Personally, I hate forced autoconfiguration processes. I prefer to spend efforts on added values  functionalities. ;-)

Regards.
