### ISSUE TITLE
pids=all don't work in last versions

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#129]
Hi,

In last commits the use of the full TS is broken. With version 0.1.84 any client can request "pids=all" and it works, but with version 0.3.31 or more recent it don't work. The logs are correct, but no data is send to the client.

Please, can you fix it?

**Comment by catalinii** [comment]
I could reproduce this and will look into it.

Thanks

**Comment by lars18th** [comment]
Ok,

I hope you can fix it soon.

Thank you!

**Comment by lars18th** [comment]
Hi Catalini,

Please, can you fix this? It's a pain to use two versions because this bug.

I hope this will not be hard to fix it and you can upgrade the main tree with re-enabled support for "pids=all".

Thank you!

**Comment by catalinii** [comment]
Hi,

This should be fixed in the last commit.

Can you check if it's ok ?

Thanks

**Comment by lars18th** [comment]
Thank you! Bug is fixed in last commit (v0.3.37)
