### ISSUE TITLE
X_SATIPCAP doesn't handle correctly DVB-T adapters

### ISSUE THREAD

**Issue by rofafor** [catalinii/minisatip#131]
DVB-T adapters are announced in X_SATIPCAP as DVB-T2 devices that messes up client capability checks.

DVB-T only adapters:
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBT-4</satip:X_SATIPCAP>

DVB-T2 adapters:
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBT2-4</satip:X_SATIPCAP>

**Comment by catalinii** [comment]
This should be ok now, thanks for reporting this.

**Comment by rofafor** [comment]
Much better now, thanks!
