### ISSUE TITLE
cannot play sd channels with vlc

### ISSUE THREAD

**Issue by nfedera** [catalinii/minisatip#132]
... but hd channels are working perfectly fine

**my environment**
minisatip: current master 9afc2da44260f3740d2e3be09d28ab4c1be3d0a5
kernel: 3.14.14-cubox armv7l
os: debian 8.0 (jessie)
vlc version: 2.2.1 (OSX)

**channels tested (Astra 19.2 E)**

ZDF (Failure)
```
rtsp://192.168.18.154/?src=1&freq=11954&sr=27500&pol=h&msys=dvbs2&pids=0,100,110,120,121,125
```
Log: http://pastebin.com/zwfN8Kcn

ZDF-HD (Working)
```
rtsp://192.168.18.154/?src=1&freq=11362&sr=22000&pol=h&msys=dvbs2&pids=0,6100,6110,6120,6121,6122,6123
```
Log: http://pastebin.com/HeVc1Y67

Any hints ?

**Comment by nfedera** [comment]
minisat command line used for this test:
./minisatip -f -e 0 -l -l

**Comment by catalinii** [comment]
Hi,


Zdf is dvb-s on Astra 19, not dvb-s2.

Thanks.

**Comment by nfedera** [comment]
omg ... feeling stupid right now. thx and sorry for the noise ;)

**Comment by catalinii** [comment]
No problem..
