### ISSUE TITLE
Update usage notes in readme.txt

### ISSUE THREAD

**Issue by pbriesch** [catalinii/minisatip#134]
Hello Catalin,

when you have some time, please update the usage notes in the readme.txt. I found some missing or unclear points:
`````
minisatip [-f] [-r remote_rtp_host] [-d device_id] [-w http_server[:port]] [-p public_host] [-s rtp_port] [-a no] [-m mac] [-l] [-a X:Y:Z] [-e X-Y,Z]
`````
-o, -x and -y are missing
-c X: bandwidth capping : -c is missing, unit of X not explained
-b X: set the DVR buffer to X KB (default: XX KB) : -b missing, default not given , it just  says "XX KB"
-u : missing, value ranges for A, S, F and PIN missing
-j and -g are missing
[-s rtp_port], but later in text: -s DELSYS:host:port -> not clear
-t is missing
possible values for DELSYS not listed, just one example, but later in text "msys=..."is mentioned

Thanks, Paul

**Comment by catalinii** [comment]
Hi Paul,

I have changed the readme and the usage a bit.

Please let me know if you have further feedback.

Thanks

**Comment by pbriesch** [comment]
Hi Catalin,

thanks for updating the readme.txt. I still have some points which are not clear to me. It's getting complex ;-)

**in the syntax description:**
**-t** is missing
**-s** is two times mentioned: [-s rtp_port], but later in text: -s DELSYS:host:port 
**[-l]**  **l** is already mentioned at the very beginning: minisatip [-[f**l**zg]]

Furthermore, you might want to mention ISDB-T now as well in the readme.txt where appropriate.

Thanks, Paul

**Comment by CvH** [comment]
a config file would be very handy and much more understandable than the neverending commandline

**Comment by 9000h** [comment]
we do have already a open request for that 
https://github.com/catalinii/minisatip/issues/114

**Comment by pbriesch** [comment]
Good morning Catalin,

one litte thing: [-a x:y:z] [-m mac] [-a X:Y:Z]

Thanks, Paul

**Comment by catalinii** [comment]
Good morning,

updated.

Thanks
