### ISSUE TITLE
README: More streaming examples.

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#138]
Hi,

I suggest to continue improving the documentation. Here my two cents for "Streaming examples":

- In order to listen to a radio on Astra 19.2E, after minisatip is started open the following URL in your favourite media player:

	"http://MINISATIP_HOST:8080/?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,28457,851"

I hope this helps!

**Comment by catalinii** [comment]
Hi,

I have added the changes to the readme, btw 28457 is the SID of the channels and not the pmt pid, but it can be omitted .

thanks
