### ISSUE TITLE
NULL packets with pids=all

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#139]
Hi,

I like to suggest to restore one function already included in ancient versions. First I comment the differencies:

- Version 1.84: With "pids=all" the NULL packets are send.
- Version 0.3.37: With "pids=all" the NULL packets are filtered out.
- Other 0.2.x-0.3.x versions: "pids=all" is broken.

Here the problem: I like to use a TS analyzer that likes to receive the full transport stream. With last versions, the padding is removed; then this is not good.

I suggest to restore the ancient behaviour if the request is "pids=all", because this implies ALL pids, and NULL (8191 or 0x1FFF) is also a valid pid. If this is not acceptable, then I suggest to add a command line parameter for selecting between one or another behaviour (filter or not filter padding).

Please, you accept this?
Thank you for this impresive piece of code!

**Comment by catalinii** [comment]
I will include this in the next release... let's see if there is any feedback.

Thanks

**Comment by lars18th** [comment]
Ok, thank you!

**Comment by lars18th** [comment]
Hi Catalin,

Fixed in last commit. Thank you!
