### ISSUE TITLE
Exclude list of invalid frequencies

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#140]
Hi,

After several weeks testing minisatip with my DVB-T dual tuner I found a problem that I feel can be easy to circumvent.

First the problem: After several hours of use my device, time to time, one of the tuner starts to not deliver any packets. The driver continues to work, but not the device. The only solution is disconnect the device and reconnect it (cold reboot). The device is using the infamous AF9015 chipset.

Then, one exhaustive analisys of the dmesg logs shows this:

[235325.653996] DVB: adapter 0 frontend 0 frequency 1597000 out of range (174000000..860000000)

And then I linked this message to the problem.

So, I suggest one command line parameter to exclude some frecuencies (reject them when requested), or directly don't try to tune "non-valid" frequencies (for DVB-T, values out of [174-860]MHz).

I feel that this small check before any tune call to the device can solve this problem.
You agree?

**Comment by catalinii** [comment]
Yes I think it makes sense, I will add code to do this

**Comment by lars18th** [comment]
Perfect!
Thank you, very much!

I suggest this: Some defines values for MIN and MAX frequencies, like:

```
#define MIN_FRQ_DVBT 174000000
#define MAX_FRQ_DVBT 858000000
#define MIN_FRQ_DVBC 51000000
#define MAX_FRQ_DVBC 860000000
#define MIN_FRQ_DVBS 950000000
#define MAX_FRQ_DVBS 2150000000
```
or simular...

With this, if someone has a trouble, he can modify the values and recompile.

**Comment by lars18th** [comment]
Hi Catalin,

I show the changes in the last commit. But I prefer to do an exhaustive test before close this issue. I hope it fixes the troubles with my DVB-T device.

Thank you!

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you! This is working right! Closed topic.
