### ISSUE TITLE
RFE: Running minisatip even after a crash!

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#143]
Hi Catalin,

I have created a simple script for restarting minisatip when it crashes. I feel it can be interesting for other users that like to run it as a service. Perhaps you like to include it in the repository:

minisatip-infinite.sh

```
#!/bin/bash

# call with "nohup ./minisatip-infinite.sh"
until `./minisatip -f -ll`; do
        echo "Server minisatip crashed with exit code $?.  Respawning.." >&2
        sleep 1
done
```

Then when you like to kill minisatip, first kill the nohup process and after the minisatip instance.

You agree this?

**Comment by 3PO** [comment]
I dont understand the sense of this script, becauce minisatip never crashed on my System.

**Comment by catalinii** [comment]
I think the idea is good in general, as theoretically it could crash, but maybe the best solution would be to write like a watchdog that keeps it running until killed.

I will turn this into an RFE and when I will have time I will look how to achieve this from the code.

**Comment by lars18th** [comment]
Hi Catalin,

Adding a watchdog inside the code can be a little complex. I suggest to use scripts to restart in case of crash because: 1) Is more portable; 2) Has low impact; 3) Can be "disabled".

Perhaps you like to complete the script for better logging and signal control.

In any case, please, don't waste time on it! I put this thread only if someone likes to use it. ;-)

**Comment by CvH** [comment]
Instead of "hacking" scripts around minisatip it would be much more useful if we get Debian/Ubuntu/Redhat... repos and use their systems. The most users (besides OE & IDL4k) use a package management system, why not distribute a package with ready to use implementation.

**Comment by lars18th** [comment]
@CvH 

minisatip is very robust. This script is only for a "forcing" restart in case of a crash!

@catalinii 
Breaking news: at time, tunning a TERRESTRIAL frequency with free-to-air programs the last version of minisatip has tried to call to the Oscam server, and then it crashed! I use the Oscam server only for sat. The only difference now is that at time the signal is very low on this frequency (heat/summer effect), and then when minisatip tries to read the tables, it fails/crash.

**Comment by lars18th** [comment]
Hi,

My updated script, more robust and easy to show logs (I run it in a screen session):

```
#!/bin/bash

# call with "nohup ./run-infinite.sh &"
# exit with "kill -9 [pid script]; kill -9 [pid minisatip];"
# show log with "tail -f minisatip.log

while :
do
        ./minisatip -f -i -10 -e 0-2 -a 1:2:0 -t -o 192.168.210.17:9000 -ll > ./minisatip.log
        echo "Server crashed with exit code $?.  Respawning.." >&2
        /bin/sleep 0.5
done
```

I suggest to use it for "infinite" running of minisatip!

**Comment by Jalle19** [comment]
Replaced by #938
