### ISSUE TITLE
RFE: Client mode over TCP (with persistent HTTP connection)

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#148]
Hi Catalin,

I have a new suggestion: In this case is related to a method for interconnect one minisatip to another minisatip in client mode but using HTTP connection instead of RTP.

I explain more:

* At time it's possible to request one TS stream to a minisatip instance using plain HTTP requests. This is a very useful functionality and very easy to use (for example, from command-line, or using non SAT>IP clients). But this mode implies to stop the streaming if you like to change the pid list. The reason is simple: each HTTP request sends one stream, and all changes implies a new HTTP request. Then a new HTTP request all times implies closing the previous connection. Then allways the streaming is stoped.

* One alternative: When you receive the HTTP request the TCP socket continues open, mainly because you're sending data over it (streaming the TS). However, the client can "send" new data over the socket. This in fact, is not supported by HTTP/1.1 protocol, but it works. When the client sends "new" data, the server can process it, but it can't send any HTTP response until it's stops the streaming. Nevertheless, if the "request" (=new data) is a request for changing the pid list, then the minisatip needs only to update the pid filtering list. In this scenario the streaming of the TS continues over the TCP socket, but no new "HTTP response" (=header) is sended. But this is good for the client, as it's only likes to continue receiving the TS but with a new pids!

Then my suggestion is for implementing this "multiple" or "persistent" HTTP requests without stopping the TS stream. And then, implement in the client side the option to connect to a remote SAT>IP server using not the full SAT>IP protocol over RTP but the "tweaked" HTTP protocol.

Please, what you think about this "simple" but powerful suggestion?

**Comment by catalinii** [comment]
Hi,

this sounds interesting but the problem will be that just minisatip will support this.

The another problem with TCP is that as long as you don't have packet loss, there is no difference between TCP and UDP, but when you start loosing packets TCP is going to behave bad on streaming (meaning all the traffic will be interrupted until you receive missing packets, the tcp window will decrease which will make the transfer slower).

Pottentially with UDP you can see a small artefact and you are done, while with TCP the entire image might stop for a second.

Without a real utility I don't think there is a point to implement this.

**Comment by lars18th** [comment]
Hi Catalin,

Thank you for your comment! I'll try to explain more:

* Real Utility: Wifi channel. For example:

SAT>IP Client ---| Ethernet |---> minisatip ---| WiFi |---> minisatip ---| Ethernet |---> SAT>IP Server

In this case, with a connection with high throughtput but large errors the TCP connection is better than RTP (without retransmission, that is implemented on SAT>IP protocol).

* Implementation: Before try to implement the CLIENT part, pleas, try to support the SERVER side. I'll like to implement some Perl scripts for receive the TS over HTTP changing pids. I already test that send more requests to an HTTP server during the streaming downloading don't create any disturbance. Example:

* Inital call: http://MINISATIP_HOST:8080/?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,851
* Second call: http://MINISATIP_HOST:8080/?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,841
*Third call: http://MINISATIP_HOST:8080/?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,631
etc.

As you see only the change of the pidlist needs to be supported.

Please, can you try to support this? You feel it's difficult?

**Comment by rofafor** [comment]
You don't have to mess with HTTP, but implement RTP over TCP as specified in the specs. Afterwards, clients can specify whether to use TCP or UDP during the SETUP command.

**Comment by lars18th** [comment]
@rofafor 

RTP over TCP: This can be interesting for minisatip-->minisatip. However, where is this described in the specification?

HTTP: This is good for "external" applications. Please, remember that the HTTP interface is the BIGGEST functionality present in minisatip that lacks other SAT>IP servers. This protocol is PERFECT for simple programs (like scripts with ffmpeg/vlc) that likes to read/process a stream. RTP is very complex, and HTTP is fairly simple!

My suggestion: improve the RTP part with TCP support, but also improve HTTP section.

@catalinii 
Please, can you try to implement the server side of this? I like to use it with my scripts... please!

**Comment by catalinii** [comment]
As rofafor said, this will create a custom version of HTTP for which there are no tools (so I do not see much point of going this path).

RTSP over TCP is implemented by minisatip (but not in the satip client), and yes this is more likely to get implemented for minisatip to minisatip connections.

This means that there will be tcp over the wifi channel as you expect.
From my point of view you can do what you want much easier with RTSP over TCP as all the information  (RTP, RTCP and RTSP) is multiplexed over one tcp connection and it's all using the standard protocol (no customization).

**Comment by lars18th** [comment]
@catalinii 

If you don't like to implement this (this is for HTTP clients, not for SAT>IP clients) then I accept it. I'll try to implement it by me (I don't have much experience with C/C++).

However, please, try to implement the RTSP over TCP in the minisatip client implementation.
And remember, please, that the client mode ins't working at time with some SAT>IP servers. I'll help to you to debug the errors. In the meantime I use the vtuner for sat-ip client mode.

Finally, please, can you point to me where the code of minisatip reads the HTTP requests? I'll try to execute a loop (for not only read one time) and process new requests.

Regards!

**Comment by catalinii** [comment]
Hi,

as I said I can try to add (time permitting support) in the satip client for rtsp over tcp.

About minisatip with another satip server, if you can provide access to the hardware I can make it work.

check in minisaitp.c read_http , this is reading the http message.

Thanks

**Comment by lars18th** [comment]
@catalinii 

> as I said I can try to add (time permitting support) in the satip client for rtsp over tcp.

OK, I feel it will be very useful.

> About minisatip with another satip server, if you can provide access to the hardware I can make it work.

At time, it's very dificult for me for enable a VPN. I'll try when I have spare time.

> check in minisaitp.c read_http , this is reading the http message.

Thank you for the info! However, I need more help:

- In this line: http://github.com/catalinii/minisatip/blob/master/minisatip.c#L666 is the end of the HTTP response... but where is the code that continues to send the streaming over the TCP socket opened by the HTTP connection?

- In this line http://github.com/catalinii/minisatip/blob/master/minisatip.c#L831 the HTTP connection is closed just after process the HTTP request. But I feel this is not real, because the streaming is over the same TCP socket.

- Then my question is: If I like to put a "loop" inside the funcion read_http() in minisatip.c, then where is the code that process the streaming over the socket? Or I need to put the loop in the function new_http() to repeat the read_http call if more data is comming? Please, clarify where is the code writing the TS stream in the socket.

Remember that my goal is simple: over the same TCP socket, process more than one HTTP request without interrupt the TS streaming. Really, is fairly simple, no?

**Comment by catalinii** [comment]
See line 604, basically read_rtsp is handling the tcp connection after.

Thanks

**Comment by lars18th** [comment]
@catalinii 

> See line 604, basically read_rtsp is handling the tcp connection after.

Then the function to "hack" is read_rtsp(), as I see in line:
http://github.com/catalinii/minisatip/blob/744fa29b2338f41e17ddd6bb69c679268e5e9d20/minisatip.c#L492
the start of the response to the HTTP client. But I don't know where is the code that process the buffer and sends the packets to the TCP socket. Please, can you point it to me?

Please, don't be disturbed by these questions, I just need to understand well your code before try to modify it!

**Comment by catalinii** [comment]
Well my understanding is that you don't want the second HTTP/1.0 200 OK response.

The next line (493) is sending that reply, you need to make sure are not sending more than once per socket (s)

The reply is sent in flush_streami (stream.c) to the same socket.

**Comment by lars18th** [comment]
@catalinii 

> Well my understanding is that you don't want the second HTTP/1.0 200 OK response.

No, no! The header needs to continue equal, the only that I need is that minisatip processes NEW requests send over the socket.

Here an example (C=client; S=minisatip; >=received by minisatip; <=send by minisatip):

```
> GET /?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,851,852 HTTP/1.1
> User-Agent: curl/7.26.0
> Host: 192.168.210.17:8080
> Accept: */*
>
< HTTP/1.0 200 OK
< Date: Wed, Jul 29 06:36:25 2015 GMT
< Content-Type: video/mp2t
<
... Then TS is send:
< 0x47...

after some time...
> GET /?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,852,853 HTTP/1.1
> User-Agent: curl/7.26.0
> Host: 192.168.210.17:8080
> Accept: */*
>
... the TS continues WITHOUT INTERRUPTION, but the pid list changes from [0,851,852] to [0,852,853]:
< 0x47...

after more time...
> GET /?msys=dvbs&freq=12266&pol=h&sr=27500&pids=0,853,854 HTTP/1.1
> User-Agent: curl/7.26.0
> Host: 192.168.210.17:8080
> Accept: */*
>
... idem, the TS continues, and the new pid list is [0,853,854]:
< 0x47...
```

You know?

> The reply is sent in flush_streami (stream.c) to the same socket.

Then perhaps is here where we need to insert the code for continue reading from the HTTP socket for "new" request:
http://github.com/catalinii/minisatip/blob/744fa29b2338f41e17ddd6bb69c679268e5e9d20/stream.c#L744
For example:
```
	if (sid->type == STREAM_HTTP)
		if is_data_waiting_for_read_in(sid->rsock) then {
                          err=read_http (sid-rsock);
                          if (err!=0) then close socket!
                }
```

And, modify read_http() for include a parameter for select to send the header or not (after first response, no new HTTP headers are send).
What you think?

**Comment by catalinii** [comment]
So when there is data to be read read_http/read_rtsp is called automatically.

You do not need to change stream.c only minisatip.c:493

**Comment by lars18th** [comment]
@catalinii 

Then you say that if I write data (from the client) to the socket, then ALWAYS the function read_rtsp() in minisatip.c is automatically called?

In this case, the change is more simple: only add a var inside this function for checking if it's first call or not, and then when second or succesive requests are received, check correct parameters (identical tuner values or only addpids, or new full pid list) and then update the pid list.

I'm right?

**Comment by catalinii** [comment]
well probably you need to add one inside of Streams structure as this method gets called for all rtsp and http reads...

**Comment by lars18th** [comment]
Ok, I'll try to implement this next week (at time very busy!).

Thank you!

**Comment by lars18th** [comment]
@catalinii 

Related to "resend" multiple HTTP request over same socket for pid filering change... IT WORKS! Great! No changes are needed at all! ;-)

Only the received stream is altered with the HTTP answer, but with a simple "resync" of the TS (search for 0x47) it's easy to cincumvent this problem.

Thank you!!

Also, I hope soon you can implement the RTSP over TCP in client mode for minisatip-2-minisatip over TCP.

**Comment by catalinii** [comment]
Had some time to test today, let me know if this still an issue.

Thanks

**Comment by catalinii** [comment]
sorry wrong issue, I meant #145

**Comment by lars18th** [comment]
Hi @catalinii ,

After several weeks using this, I close this topic. Change the pid list over "persistent http" is working.

However, I suggest to add the enhancement of "RTP over TCP option for minisatip-to-minisatip connection". This is for route minisatip-to-minisatip over open Internet using NAT and no UDP support. I know the problem with retransmissions and TCP, but I suggest to implement it in spare time.
