### ISSUE TITLE
[REQ] Feature request : support for some hardware cam modules

### ISSUE THREAD

**Issue by ovidiu31** [catalinii/minisatip#149]
Hello (Salut) Catalin

Do you think that might possible support for hardware cam modules implementation?
I am able to help you to implement this kind of support by providing you the hardware such as DVB cards with CI slots and hardware cam modules such as : 
- SMIT Irdeto 2 Professional CAM CI Module
- SMIT Viaccess Professional CAM CI Module
- SMIT Conax Professional CAM CI Module
  and dvb cards samples such as : 
- TBS6928SE DVB-S2 TV Tuner CI PCIe Card
- TBS6991SE DVB-S2 Dual Tuner Dual CI PCIe Card
- TBS6290 DVB-T2/T/C Dual Tuner Dual CI PCIe Card
- TBS6680 PCIe DVB-C Dual Tuner Cable TV Card with Dual CI Slot

Please let me know if you are interested into this small project and we can discuss further details.

Best Regards
Ovidiu

**Comment by catalinii** [comment]
Hi Ovidiu,

yes I am interested in making this work, but so far I did not have any hardware available with CI Slot.
You can contact me @ catalinii@yahoo.com to discuss further details about this.

Thanks

**Comment by vdrtuxnet** [comment]
Hi Mates,

do you think that it is possible, that minisatip could take advantage by using a external lib to support
CI+ modules?
There is a source code rotating on the web, to increase the DM7080HD STB sales.
This source compiles without errors on PC Linux, but I have no idea if this is even supposed to work
on non DMM devices.

What did you think?

**Comment by catalinii** [comment]
Hi,

Do you refer to a different library than the one used by ca.c (dvben50221)?

Do you have sources that works?

**Comment by vdrtuxnet** [comment]
Hi catalin,

Yes, I'm referring to a different  than the dvben50221.
Yes, I have the sources and the certs.
Today a friend of mine build this for his DMM7080HD STB and both CI+ interfaces (SKY Germany and HD+ Germany) descrambling the channels, the Sky CI+ module (witch is CI+ 1.2 or 1.3) just one stream and the HD+ CI+ module (witch is 1.4?) four streams simultaneously.

As I'm a lousy coder, I cant make this work on PC Linux.

regards

**Comment by catalinii** [comment]
Hi,

I took a look on the code, you are reffering basically to support for CI+ interfaces using a normal DVB cards, right ?

Thanks

**Comment by vdrtuxnet** [comment]
Hi Catalin,

Yes, you are right, to supporting CI+ on DVB cards.
Do need a link for the sources or do you already found them?

I discovered that there is a non public plug-in for DVBviever, based on that code.

If you need assistance. I have a two DVB-S2 cards with the CI extension on the shelf.

Kind regards

**Comment by 9000h** [comment]
no sure if this is the right forum here for a request like this, as long the hardware CI support is working right (eg cards with CI in the TS path) in minisatip the CI+ daemon may or may not work out of the box and has to run  anyway independent from minisatip

**Comment by vdrtuxnet** [comment]
Hello,

There was no question to interpolate this to minisatip, I knew there is more needed e.g. how to set the youth protection pin and other things.

It is more a question like #103 "Server side decipher", OScam is likewise running independent.

May be minisatip can't take advantage out of this, so the job is on the DVB application side.

To have the possibility, to stay with your favourite DVB application in conjunction with minisatip, would be absolutely great, even with a paired smart card.

Trust me - The Enigma2/OScam Mafia will present a new solution, when the pairing hammer hit us, to fill their money buckets again and again.

Kind regards

**Comment by catalinii** [comment]
Hi vdrtuxnet,

I am not saying no for now, but I need to do some work on minisatip prior to be able to integrate this.

Kindly send me an email and I will let you know if I do it what I need.

My email is in this thread.

Thanks

**Comment by vdrtuxnet** [comment]
Hi Catalin,

thank you for your attention!

It is not a matter of urgency but it would be great to have. 

I'm aboard at the moment, I will contact you , soon as I get back. 

Kind regards

**Comment by sharky1337** [comment]
Any news on this topic ? The pairing hammer hit me :/ @vdrtuxnet . Need to get a pairt card working , but I don't want to stick to engima2.

**Comment by catalinii** [comment]
Send me an email at catalinii@yahoo.com

**Comment by catalinii** [comment]
https://minisatip.org/forum/viewtopic.php?f=5&t=99
