### ISSUE TITLE
versions number issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#15]
if (t->sys == SYS_DVBS || t->sys == SYS_DVBS2)
                sprintf (dad, "ver=1.1;src=%d;tuner=%d,%d,%d,%d,%d,%c,dvbs,,,,%d,;pids=",

DVB-S should have ver=1.0
DVB-T should have ver=1.1
DVB-C should have ver=1.2

**Comment by 9000h** [comment]
the DESCRIBE message is also not complete

Example DESCRIBE Message
Request>
DESCRIBE rtsp://192.168.178.57:554/ RTSP/1.0 CSeq:7
Accept: application/sdp
Connection:close
Response>
RTSP/1.0 200 OK Content-Length:256 Content-Type:application/sdp Content-Base:rtsp://192.168.178.57/ CSeq:7
v=0
o=- 35781181 35781181 IN IP4 192.168.178.57
s=SatIPServer:1 4
t=0 0
m=video 11784 RTP/AVP 33
c=IN IP4 239.0.0.7/1
a=control:stream=16
a=fmtp:33 ver=1.0;src=1;tuner=1,123,1,4,10744.00,h,dvbs,qpsk,off,0.35,22000,56;pids=0,400,401,402 a=sendonly

**Comment by catalinii** [comment]
Done in the last commit
