### ISSUE TITLE
Buffer not flushed properly

### ISSUE THREAD

**Issue by FuNK3Y** [catalinii/minisatip#151]
I started to use minisatip, and it is pretty awesome.

But, when using it with tvheadend (4.0.5) I started to get a lot of ghost channels.

This is most certainly caused by buffer not flushed properly: when changing channel residual data from the previous channel are sometime sent to the client. In my case, the client (tvheadend) detects invalid PID (PIDS from the past channel).

For the reference, I opened a similar case for another SAT>IP server, it seems to be exactly the same issue: http://tvheadend.org/issues/2714, https://github.com/Barracuda09/SATPI/issues/20#issuecomment-80744905 

It has been solved since then.

**Comment by catalinii** [comment]
Thanks for this, I think I noticed it also at some point, will look into it.

**Comment by FuNK3Y** [comment]
I did retest, and it seems to work fine. 

https://github.com/catalinii/minisatip/commit/2d4b7458ff2a99ce1038f81ef4509ab1c97c235f might have solved it
