### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by bergvoll** [catalinii/minisatip#152]
Hi.

I'm trying to compile current master. When I run make, i get this error:
cc  -ggdb -fPIC -DDISABLE_DVBCA -c -o minisatip.o minisatip.c
In file included from minisatip.c:44:0:
dvbapi.h:7:27: fatal error: dvbcsa/dvbcsa.h: No such file or directory
 #include <dvbcsa/dvbcsa.h>
                           ^
compilation terminated.
Makefile:46: recipe for target 'minisatip.o' failed
make: *** [minisatip.o] Error 1

Any suggestions on how to fix this?

**Comment by catalinii** [comment]
Hi,

You need to install libdvbcsa on your system.

Thanks

**Comment by lars18th** [comment]
@bergvoll 

Or best, if you don't need at all the Oscam support, then change this line on Makefile:

```
#DVBCSA?=yes
DVBCSA?=no
```

With this you disable the requirement of the libdvbcsa (not found on all embbeded systems).

Regards!

**Comment by bergvoll** [comment]
Thanks! I thought I had to include dvbsca source files to compile.

For future reference, installing libdvbcsa-dev package in Ubuntu solved it.

**Comment by lars18th** [comment]
@bergvoll 

Sure! install the libdvbcsa-dev is sufficient in any regular PC. But if you don't have access to libdvbcsa, you need to disable it in the Makefile for compiling without support for CSA.

Regards!
