### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by CvH** [catalinii/minisatip#153]
I try to compile the latest minisatip for OpenElec (latest test was with version from 03.03. - compile and works fine). OpenElec provides his own toolchain to build for an specific target

With the recent version it throws errors (most likely my fault) http://pastebin.com/m2jDB59m
```CC?=gcc
DVBCSA?=no
DVBCA?=no
SATIPCLIENT?=no
```

Default Makefile -> http://pastebin.com/6Cc6Am43 (dvbcsa is at toolchain) - I can't bet that this works at all, if this is working it is just a extra
```CC?=gcc
DVBCSA?=yes
DVBCA?=no
SATIPCLIENT?=yes
```

**Comment by catalinii** [comment]
About the first issue, generally after changing the parameters you might want to do a make clean.
Try again with make clean and let me know.

About the second issue in Makefile if DVBCSA is yes there is a line that includes libdvbcsa:
LDFLAGS+=-ldvbcsa


however I do not see in your log that -ldvbcsa is included when it is compiled, this is why you see the error message about the dvbcsa functions.


Thanks

**Comment by CvH** [comment]
Both logs are made with "make clean" ( full log to be sure http://pastebin.com/xezzChCj). 
For the dvbcsa problem I investigate (it also could be the implementation at the oe build system) ...

**Comment by vpeter4** [comment]
If some library is not find automatically you can just set few env variables. As a last reserve.
```javascript
  DIR_TARGET="$(get_build_dir package_name)/.install"
  export CFLAGS="$CFLAGS -I$DIR_TARGET/include"
  export LDFLAGS="$LDFLAGS -L$DIR_TARGET/lib"
  export LIBS="$LIBS -lsome_lib"
```

**Comment by catalinii** [comment]
The other thing I see here is that you don't compile with -DDISABLE_DVBCSA or -DDISABLE_DVBCA but in the command where you generate the minisatip (the one that throws errors) there is no dvbcsa.o and dvbca.o which causes those errors.

I am not sure what create_addon does, but it seems the Makefile is not followed.

**Comment by CvH** [comment]
like expected my fault, tx vpeter for the fix :+1:
