### ISSUE TITLE
multicast test issue

### ISSUE THREAD

**Issue by ovidiu31** [catalinii/minisatip#154]
Hello @catalinii 

Please Help me out
below is an test from the sat>ip certification process , i have some problems runing this test on a new device ... basically picks up same and same multicast ip address 239.255.255.250
( i have added to the device multicast route and still same and same blank result  ... with the certified schwaiger satip device all working fine)

The TEST
[DESCRIPTION: (SEQ014) MS0/P/T fe,port]

[OPTIONS OFF]

SETUP rtsp://<ipaddr>:<port>/?src=1&fe=1&freq=10744&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=0,400,401,402 RTSP/1.0
CSeq:<CSeq>
Transport: RTP/AVP;multicast;port=52876-52877
Connection:close

[EXPECT 200]
[CHECK RTSP RESPONSE]

PLAY rtsp://<ipaddr>:<port>/stream=<Stream> RTSP/1.0
CSeq:<CSeq>
Session:<Session>
Connection:close

[EXPECT 200]
[CHECK RTSP RESPONSE]
[PLAY RTP]
[WAIT 10000ms]

TEARDOWN rtsp://<ipaddr>:<port>/stream=<Stream> RTSP/1.0
CSeq:<CSeq>
Session:<Session>
Connection:close

[EXPECT 200]
[CHECK RTSP RESPONSE]

The Result of the TEST

Request 1
53 45 54 55 50 20 72 74 73 70 3a 2f 2f 31 39 32  SETUP rtsp://192
2e 31 36 38 2e 31 2e 31 30 3a 35 35 34 2f 3f 73  .168.1.10:554/?s
72 63 3d 31 26 66 65 3d 31 26 66 72 65 71 3d 31  rc=1&fe=1&freq=1
30 37 34 34 26 70 6f 6c 3d 68 26 72 6f 3d 30 2e  0744&pol=h&ro=0.
33 35 26 6d 73 79 73 3d 64 76 62 73 26 6d 74 79  35&msys=dvbs&mty
70 65 3d 71 70 73 6b 26 70 6c 74 73 3d 6f 66 66  pe=qpsk&plts=off
26 73 72 3d 32 32 30 30 30 26 66 65 63 3d 35 36  &sr=22000&fec=56
26 70 69 64 73 3d 30 2c 34 30 30 2c 34 30 31 2c  &pids=0,400,401,
34 30 32 20 52 54 53 50 2f 31 2e 30 0d 0a 43 53  402 RTSP/1.0..CS
65 71 3a 31 33 0d 0a 54 72 61 6e 73 70 6f 72 74  eq:13..Transport
3a 20 52 54 50 2f 41 56 50 3b 6d 75 6c 74 69 63  : RTP/AVP;multic
61 73 74 3b 70 6f 72 74 3d 35 32 38 37 36 2d 35  ast;port=52876-5
32 38 37 37 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e  2877..Connection
3a 63 6c 6f 73 65 0d 0a 0d 0a                    :close....
Response in 1 ms
52 54 53 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0d  RTSP/1.0 200 OK.
0a 44 61 74 65 3a 20 53 61 74 2c 20 41 75 67 20  .Date: Sat, Aug 
38 20 31 36 3a 35 37 3a 34 34 20 32 30 31 35 20  8 16:57:44 2015 
47 4d 54 0d 0a 43 73 65 71 3a 20 31 33 0d 0a 54  GMT..Cseq: 13..T
72 61 6e 73 70 6f 72 74 3a 20 52 54 50 2f 41 56  ransport: RTP/AV
50 3b 6d 75 6c 74 69 63 61 73 74 3b 64 65 73 74  P;multicast;dest
69 6e 61 74 69 6f 6e 3d 32 33 39 2e 32 35 35 2e  ination=239.255.
32 35 35 2e 32 35 30 3b 70 6f 72 74 3d 35 32 38  255.250;port=528
37 36 2d 35 32 38 37 37 0d 0a 53 65 73 73 69 6f  76-52877..Sessio
6e 3a 20 31 31 38 39 36 34 31 34 32 31 3b 74 69  n: 1189641421;ti
6d 65 6f 75 74 3d 33 30 0d 0a 63 6f 6d 2e 73 65  meout=30..com.se
73 2e 73 74 72 65 61 6d 49 44 3a 20 31 0d 0a 0d  s.streamID: 1...
0a                                               .

Request 1: SETUP
Response 1: 200 OK
  Session ID OK (1189641421)
  Stream ID OK
Response 1: OK

Request 2
50 4c 41 59 20 72 74 73 70 3a 2f 2f 31 39 32 2e  PLAY rtsp://192.
31 36 38 2e 31 2e 31 30 3a 35 35 34 2f 73 74 72  168.1.10:554/str
65 61 6d 3d 31 20 52 54 53 50 2f 31 2e 30 0d 0a  eam=1 RTSP/1.0..
43 53 65 71 3a 31 34 0d 0a 53 65 73 73 69 6f 6e  CSeq:14..Session
3a 31 31 38 39 36 34 31 34 32 31 0d 0a 43 6f 6e  :1189641421..Con
6e 65 63 74 69 6f 6e 3a 63 6c 6f 73 65 0d 0a 0d  nection:close...
0a                                               .
Response in 1237 ms
52 54 53 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0d  RTSP/1.0 200 OK.
0a 44 61 74 65 3a 20 53 61 74 2c 20 41 75 67 20  .Date: Sat, Aug 
38 20 31 36 3a 35 37 3a 34 36 20 32 30 31 35 20  8 16:57:46 2015 
47 4d 54 0d 0a 53 65 73 73 69 6f 6e 3a 20 31 31  GMT..Session: 11
38 39 36 34 31 34 32 31 0d 0a 43 73 65 71 3a 20  89641421..Cseq: 
31 34 0d 0a 52 54 50 2d 49 6e 66 6f 3a 20 75 72  14..RTP-Info: ur
6c 3d 72 74 73 70 3a 2f 2f 31 39 32 2e 31 36 38  l=rtsp://192.168
2e 31 2e 31 30 3a 35 35 34 2f 73 74 72 65 61 6d  .1.10:554/stream
3d 31 3b 73 65 71 3d 32 31 38 30 36 34 38 3b 72  =1;seq=2180648;r
74 70 74 69 6d 65 3d 31 34 33 39 30 35 33 30 36  tptime=143905306
36 0d 0a 52 61 6e 67 65 3a 20 6e 70 74 3d 30 2e  6..Range: npt=0.
30 30 30 2d 0d 0a 0d 0a                          000-....

Request 2: PLAY
Response 2: 200 OK
  Session ID OK (1189641421)
  RTP-Info OK
Response 2: OK

Response 2
No RTP TS Packets received
No RTCP Packets received

Request 3
54 45 41 52 44 4f 57 4e 20 72 74 73 70 3a 2f 2f  TEARDOWN rtsp://
31 39 32 2e 31 36 38 2e 31 2e 31 30 3a 35 35 34  192.168.1.10:554
2f 73 74 72 65 61 6d 3d 31 20 52 54 53 50 2f 31  /stream=1 RTSP/1
2e 30 0d 0a 43 53 65 71 3a 31 35 0d 0a 53 65 73  .0..CSeq:15..Ses
73 69 6f 6e 3a 31 31 38 39 36 34 31 34 32 31 0d  sion:1189641421.
0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 63 6c 6f 73  .Connection:clos
65 0d 0a 0d 0a                                   e....
Response in 1 ms
52 54 53 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0d  RTSP/1.0 200 OK.
0a 44 61 74 65 3a 20 53 61 74 2c 20 41 75 67 20  .Date: Sat, Aug 
38 20 31 36 3a 35 37 3a 35 36 20 32 30 31 35 20  8 16:57:56 2015 
47 4d 54 0d 0a 43 73 65 71 3a 20 31 35 0d 0a 53  GMT..Cseq: 15..S
65 73 73 69 6f 6e 3a 20 31 31 38 39 36 34 31 34  ession: 11896414
32 31 0d 0a 0d 0a                                21....

Request 3: TEARDOWN
Response 3: 200 OK
  Session ID OK (1189641421)
Response 3: OK

**Comment by 9000h** [comment]
there is  no multicast support implementet atm

**Comment by ovidiu31** [comment]
this was solved by catalinii
