### ISSUE TITLE
multiple audio issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#156]
when I change on my Panasonic the audio language to the second language then there is no audio, if I change it back the the first audio is also dead
this is only on encrypted channels happend

**Comment by catalinii** [comment]
Hi,

Can you post the log please with just one channel from the beginning?

Thanks

**Comment by 9000h** [comment]
which level would you prefer

**Comment by catalinii** [comment]
3 should be fine for now...

**Comment by 9000h** [comment]
3 times -l -l -l did not work for me so I did use 4 and sent the log and pcap

**Comment by catalinii** [comment]
Can you let me know if it works ?

Thanks

**Comment by 9000h** [comment]
excellent, works now as expected
