### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hitam4450** [catalinii/minisatip#157]
After downlaoding the latest master, 

i started to compile ith make and receivers the following messages:

cc  -ggdb -fPIC -DDISABLE_DVBCA -c -o minisatip.o minisatip.c 
In file included from minisatip.c:44:0:
dvbapi.h:7:27: fatal error: dvbcsa/dvbcsa.h: No such file or directory
 #include <dvbcsa/dvbcsa.h>
                           ^
compilation terminated.
Makefile:46: recipe for target 'minisatip.o' failed
make: *** [minisatip.o] Error 1

What went wrong and what  do i have to install additionally ??

list of files in directory:

drwxr-xr-x 2 root root 4,0K Aug 25 15:42 binaries
drwxr-xr-x 2 root root 4,0K Aug 25 15:42 icons
-rw-r--r-- 1 root root 1,4K Aug 25 15:42 Makefile
-rw-r--r-- 1 root root 6,6K Aug 25 15:42 README.txt
-rw-r--r-- 1 root root  25K Aug 25 15:42 adapter.c
-rw-r--r-- 1 root root 3,9K Aug 25 15:42 adapter.h
-rw-r--r-- 1 root root  15K Aug 25 15:42 ca.c
-rw-r--r-- 1 root root  259 Aug 25 15:42 ca.h
-rw-r--r-- 1 root root  30K Aug 25 15:42 dvb.c
-rw-r--r-- 1 root root 2,9K Aug 25 15:42 dvb.h
-rw-r--r-- 1 root root  27K Aug 25 15:42 dvbapi.c
-rw-r--r-- 1 root root 2,5K Aug 25 15:42 dvbapi.h
-rw-r--r-- 1 root root  31K Aug 25 15:42 minisatip.c
-rw-r--r-- 1 root root 1,6K Aug 25 15:42 minisatip.h
-rw-r--r-- 1 root root  17K Aug 25 15:42 satipc.c
-rw-r--r-- 1 root root  113 Aug 25 15:42 satipc.h
-rw-r--r-- 1 root root  19K Aug 25 15:42 socketworks.c
-rw-r--r-- 1 root root 2,2K Aug 25 15:42 socketworks.h
-rw-r--r-- 1 root root  26K Aug 25 15:42 stream.c
-rw-r--r-- 1 root root 1,8K Aug 25 15:42 stream.h
-rw-r--r-- 1 root root  13K Aug 25 15:42 tables.c
-rw-r--r-- 1 root root  388 Aug 25 15:42 tables.h
-rw-r--r-- 1 root root  13K Aug 25 15:42 utils.c
-rw-r--r-- 1 root root 1,5K Aug 25 15:42 utils.h

Hardware: Cubietruck, system armhf!

regards, hitam4450

**Comment by 9000h** [comment]
you are missing libdvbcsa

**Comment by hitam4450** [comment]
Ok and thanks for your reference and help!

After:  apt-get install libdvbcsa1  - I still get the same compile error.
regards, Hitam4450  (DEBIAN Jessie 8.1)

**Comment by 9000h** [comment]
you also need libdvbcsa-dev
