### ISSUE TITLE
[Feature request] Web monitoring

### ISSUE THREAD

**Issue by ViGill** [catalinii/minisatip#158]
Hi,

what about a way to monitor the tuners, connections, etc ?
For instance, it could be a web site like the tvheadend status page or a xml report ?

It would be a  great addition!

Thx

**Comment by 9000h** [comment]
Roadmap proposal #97

**Comment by TheTroll** [comment]
Hi,

here is a quick status page /status.html

http://paste.debian.net/307522/

**Comment by 9000h** [comment]
![screen shot 2015-08-27 at 18 35 28](https://cloud.githubusercontent.com/assets/3009073/9526591/7cb31362-4cea-11e5-8969-e29824b4e1b1.png)

it's a start that could maybe extent with type of source C/T/S/S2 and connected clients

**Comment by TheTroll** [comment]
Ok I'll try to add something like that, don't hesitate if you have other suggestions

**Comment by 9000h** [comment]
perexg did also add some status info for his axe mod 
https://github.com/perexg/minisatip/blob/d8f2c0e7b1ab2ea3d87b05325d1894c180861791/adapter.c#L1002

**Comment by TheTroll** [comment]
What is axe ? a satip client ?

**Comment by 9000h** [comment]
it's a mod of minisatip to run on stapi (Telestar Digibit R1)

**Comment by CvH** [comment]
@TheTroll 
is it a hardware receiver for sat>ip and perexg ported minisatip to this hardware incl some additions

**Comment by TheTroll** [comment]
oki, well this could be reused for sure

**Comment by 9000h** [comment]
btw. if all adapters released by minisatip (60 sec unused ) the status page is empty
![screen shot 2015-08-27 at 18 55 25](https://cloud.githubusercontent.com/assets/3009073/9527173/a205394e-4ced-11e5-9d95-8483dbfe8951.png)

**Comment by TheTroll** [comment]
I saw this, it's more like a bug.
try refreshing the page many times ?

**Comment by 9000h** [comment]
a[i].enabled is only valid if a adatper is in use thats different to a adapter exits

**Comment by TheTroll** [comment]
Are you sure of that ?
For me enabled means it is detected and available at startup...

**Comment by 9000h** [comment]
![screen shot 2015-08-27 at 22 25 09](https://cloud.githubusercontent.com/assets/3009073/9532239/a6ee1da0-4d0a-11e5-952b-66243fb2bac6.png)
looks much more useful now, I hope catalinii like the idea and will integrate this

**Comment by TheTroll** [comment]
I am not really sure about the SNR and LEV parts ... I let catalinii fix that :)

**Comment by 9000h** [comment]
it would may also useful to add some general system info

**Comment by catalinii** [comment]
Hey guys,

about this, I have no problem adding a status page for now, however the long term solution I am thinking of being slightly different.

Probably the best will be to create the files on the disk (in the icons page maybe) or some other directory, and every time the page is requested over the http, the server will fill replace some "strings" from the html with their actual value:

For example: $adapter1_snr$ with 79 .

Then create an html file that will display all those informations in a nice way.

The code will be pretty simple and understandable and requires very small change, while the html files will be in a separate folder and everybody can commit changes.

Html and JS are not my strong suit, but I can add the code for the replacing in minisatip.

About the other 2 commits (first being the status page), first one (regarding adapter close), will break vdr because if you close the adapter when you tune to a new frequency (which can be quite fast after the close of the stream), you need to open all the adapters again.

Think about a box with 8 adapters, the whole process can take more than 1second, which can lead to timeouts.

The third one, we can discuss it in it's own thread.

About the signal status, what are your comments?

**Comment by TheTroll** [comment]
Hey :)

I think it's a good idea yes! (maybe /html is a better subdir name).

Why do you need to reopen all apdaters again ? Why not only reopen the one you need ?

**Comment by catalinii** [comment]
I have renamed from icons to html
The default is status.html (/), in the file there are some examples of variables that are interpreted by the web server when you get the page.

This for now is just experimental so I did not created any documentation for it, but using some java script you can create some web pages.

The idea is:

the variables defined are at the end of adapter.c, stream.c and minisatip.c
$ad_enabledX$ - where X is the adapter number
$st_enabledX$ - where X is the adapter number

At this poitn you can get the following informations:
$st_enabledX$ is the stream active
$st_playX$ is play active
$st_adapterX$ adapter attached to the stream
$st_rhostX$ remote host for the stream
$st_rportX$ remote port for the stream

$ad_freqX$ - frequency
$ad_strengthX$ - strength
$ad_snrX$ - snr
$ad_berX$ - ber
$ad_polX$ - polarity (0,1)
$ad_srX$ - SR (eg 27500)
$ad_enabledX$ - is adapter enabled
$sysX$ - delyvery system
$pidsX$ - list of enabled pids

**Comment by lars18th** [comment]
Hi,

I suggest to improve the status over HTTP with two files (urls):

1) status.html: just the same as now but more readable (user friendly)
2) status.xml: the same info in XML format (for external parsing)

What you think?

**Comment by catalinii** [comment]
I will upload it in the new commit a bit improved.

For xml you are free to create one that suits your needs and we can put it here...

**Comment by lars18th** [comment]
Hi @catalinii 

The new HTML webpage is very useful. Thank you!
When I have sufficient time I'll put an XML file for export the status to a remote program.

However, a simple suggestion: Please, can you add simple "remote commands" over HTTP? Like a REST API... for example:

/cmd/restart
/cmd/reset-tuner0
/cmd/close-stream1
...

What you think about this?

**Comment by catalinii** [comment]
Yes probably in the second phase I will implement the ability to change some startup variables (including some of the variables that can be read) and restart, however we will see at that time what exactly will be included....

**Comment by 9000h** [comment]
what do you think about to catch the user agent for the rtsp sessions also 

[02/10 20:34:42.6828]: read RTSP (from handle 17 sock_id 9, len: 0, sid 0):
PLAY rtsp://192.168.178.133/ RTSP/1.0^M
CSeq: 5^M
User-Agent: LibVLC/2.2.1-libde265 (LIVE555 Streaming Media v2015.06.24)^M
Session: 1804289383^M
Range: npt=0.000-^M
^M

**Comment by catalinii** [comment]
Hi,

is this working in the last commit (UA detection)?

Thanks

**Comment by 9000h** [comment]
var ad_sys =   is double defined in status.html
