### ISSUE TITLE
SNR BER value ...

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#16]
I would like to suggest a small change 
I believe BER is not needed

and propose to change the calc. to

       *strength =  *strength >> 8;
        *snr =  *snr >> 12;

then it looks like this with my card
get_signal took 144 ms for adapter 0 handle 9 (status: 1, ber: 0, strength:189, snr: 12)

**Comment by catalinii** [comment]
Hi,

are the proposed changed based on the code of another products or something that works for your card.

What I have found so far is that the quality and signal level should be between 0..240, however the value returned by the ioctl is 0..65535, this is why I used the multiplier f, however this did not work too good I guess.

Do you have more informations about this ?

**Comment by 9000h** [comment]
the issue is most of the dvb drivers return values completely freestyle :-(

**Comment by catalinii** [comment]
Then I can make it per adapter, find maximum and consider the value being 100 or 240

**Comment by catalinii** [comment]
Actually I see the values are 0..255 and 0..15

**Comment by catalinii** [comment]
I added to the last commit calculation based on max values. My dvb card reports max strength 1450 :)
