### ISSUE TITLE
dvbapi audio issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#164]
Mezzo
HOTBIRD 13D(13.0°E)
11623 V 27500 3/4(DVB-S/MPEG-2) 

this channel has no audio on my Panasonic atm, need to investigate this

**Comment by catalinii** [comment]
Is just this channel or there are another ones with this issue?

**Comment by 9000h** [comment]
it's the only channel I have found atm. and it's encrypted

**Comment by catalinii** [comment]
Can you please upload a log ?
A rescan does not help ?
If you try with VLC is it working ?

Thanks

**Comment by 9000h** [comment]
the url is 
rtsp://192.168.178.133/?src=2&freq=11623&sr=27500&fec=34&pol=v&msys=dvbs&pids=0,115,125,135

strange thing with VLC I get no video, on the Pana I get no audio

**Comment by catalinii** [comment]
Hi,

I will have a fix for this in the next commit.

Thanks

**Comment by 9000h** [comment]
looks like it works, but I need to verify a issue with artefacts on MEZZO on the Panasonic AXW (2014 Series) in version 0.3.60
my Panasonic CXW (2015 Series) plays the MEZZO channel with audio now fine  an with no artefacts

**Comment by 9000h** [comment]
can you please point me to the fix?

**Comment by 9000h** [comment]
was probably a bad signal on one tuner, will close it for now as fixed
