### ISSUE TITLE
No or emty desc.xml with 0.3.61

### ISSUE THREAD

**Issue by vdrtuxnet** [catalinii/minisatip#169]
Hi,

not sure if this is a minisatip or local network issue.

The desc.xml is not showing up, and my vdr clients adding minisatip with 

"SATIP: Adding server '192.168.1.71|DVBS-1|MyBrokenHardware' CI: no Quirks: none"

the output is like:

"XML-Verarbeitungsfehler: Kein Element gefunden
Adresse: http://192.168.1.71:8080/desc.xml
Zeile Nr. 3, Spalte 1:

<parsererror xmlns="http://www.mozilla.org/newlayout/xml/parsererror.xml">XML-Verarbeitungsfehler: Kein Element gefunden
Adresse: http://192.168.1.71:8080/desc.xml
Zeile Nr. 3, Spalte 1:<sourcetext>
^</sourcetext></parsererror>"

I reverted back to 0.3.53, what is very stable for me, the desc.xml is ok and minisatip is added correctly to all clients. 

I can provide logs later this week, if needed. 

Kind regards

**Comment by 9000h** [comment]
I  have seen also issues with the android clients like tivizen satip, but did not dig in deeper.

**Comment by vdrtuxnet** [comment]
I just did a quick test with the HD+ Android app, connecting to minisatip is not possible.

**Comment by catalinii** [comment]
Hi,

in the new version minisatip searches in html directory (from the directory that is run) or /usr/share/minisatip for desc.xml .
Is by any chance this the issue ?

Thanks

**Comment by 9000h** [comment]
should be mentioned in the  README.txt, so that it is clear for everyone

**Comment by vdrtuxnet** [comment]
Thank you!

**Comment by 9000h** [comment]
@catalinii 
are you shure it works this way I also do not have /usr/share/minisatip and my Panasonic get's the xml
```
[15/09 12:10:35.154559069]: read HTTP from 52 sid: -1: GET /desc.xml HTTP/1.1^M
User-Agent: Panasonic MIL DLNA CP UPnP/1.0 DLNADOC/1.50^M
Host: 192.168.178.133:8080^M
X-PANASONIC-Registration: NDNDWDc1MF9TZXJpZXMA^M
X-PANASONIC-DMP-Profile: MPEG_PS_PAL JPEG_SM PV_DIVX_DIV3 PV_DIVX_DIV4 PV_DIVX_DIVX PV_DIVX_DX50 PV_DRM_DIVX_DIV3 PV_DRM_DIVX_DIV4 PV_DRM_DIVX_DIVX PV_DRM_DIVX_DX50^M
^M

[15/09 12:10:35.154559069]: opened html/desc.xml fd 53 at 58747000 - 1242 bytes
[15/09 12:10:35.154559070]: reply -> 52 (192.168.178.138:40113) CL:0 :
HTTP/1.0 200 OK^M
Date: Tue, Sep 15 10:10:35 2015 GMT^M
CACHE-CONTROL: no-cache^M
Content-type: text/xml^M
X-SATIP-RTSP-Port: 554^M
^M

[15/09 12:10:35.154559070]: processing_file 58747000 len 1242:
[15/09 12:10:35.154559070]: <?xml version="1.0"?><root xmlns="urn:schemas-upnp-org:device-1-0" configId="0"><specVersion><major>1</major><minor>1</minor></specVersion><device><deviceType>urn:ses-com:device:SatIPServer:1</deviceType><friendlyName>minisatip</friendlyName><manufacturer>cata</manufacturer><manufacturerURL>http://github.com/catalinii/minisatip</manufacturerURL><modelDescription>minisatip for Linux</modelDescription><modelName>minisatip</modelName><modelNumber>1.1</modelNumber><modelURL></modelURL><serialNumber>1</serialNumber><UDN>uuid:11223344-9999-0000-b7ae-0040caa2c79d</UDN><iconList><icon><mimetype>image/png</mimetype><width>48</width><height>48</height><depth>24</depth><url>/sm.png</url></icon><icon><mimetype>image/png</mimetype><width>120</width><height>120</height><depth>24</depth><url>/lr.png</url></icon><icon><mimetype>image/jpeg</mimetype><width>48</width><height>48</height><depth>24</depth><url>/sm.jpg</url></icon><icon><mimetype>image/jpeg</mimetype><width>120</width><height>120</height><depth>24</depth><url>/lr.jpg</url></icon></iconList><presentationURL>http://192.168.178.133:8080/</presentationURL>^M
<satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBS2-2,DVBT-0,DVBC-1,DVBC2-0,DVBT2-0</satip:X_SATIPCAP></device></root>
[15/09 12:10:35.154559264]: sockets_del: 10 -> handle 52, sid -1
```

**Comment by catalinii** [comment]
It is ./html and /usr/share/minisatip.

I think I will hardcode it and use the hardcoded version if there is none available on the disk and provide a command line for document root.

**Comment by 9000h** [comment]
ok but then the android client issue is something else

**Comment by 9000h** [comment]
probably the old issue  #81 again

**Comment by catalinii** [comment]
I will test this...

**Comment by 9000h** [comment]
I must correct my comment I do have multicast issues after a firmware upgrade on my wireless LAN

**Comment by catalinii** [comment]
Now the desc.xml is still handled inside of minisatip (thanks tivizen) and there is --xml to change the default xml file.

**Comment by 9000h** [comment]
the new status page in the commit from today only works if the response buffer in minisatip.c:1127 is much higher than 5000 bytes, this could be also the issue with the desc.xml outside the code.
Not sure if the response buffer could be changed to dynamic.

**Comment by 9000h** [comment]
a html code cleanup which quiets the browser error log for the status page
```
--- status.html.orig	2015-09-24 16:38:30.589175460 +0200
+++ status.html	2015-09-24 19:17:21.618636948 +0200
@@ -1,8 +1,17 @@
-
+<!DOCTYPE html>
 <html>
+<head>
+<meta charset="utf-8"/>
+</head>
 <title>Minisatip/$version$ on $http_host$</title>
-<body>
-<script language="javascript" type="text/javascript">
+<body onload="JavaScript:timedRefresh(5000);">
+<p>This page will refresh every 5 seconds. This is because we're using the 'onload' event to call our function. We are passing in the value '5000', which equals 5 seconds.</p>
+<script type="text/javascript">
+<!--
+function timedRefresh(timeoutPeriod) {
+	setTimeout("location.reload(true);",timeoutPeriod);
+}
+
 var ad_type = [$ad_type0$, $ad_type1$, $ad_type2$, $ad_type3$, $ad_type4$, $ad_type5$, $ad_type6$, $ad_type7$, $ad_type8$, $ad_type9$, $ad_type10$, $ad_type11$, $ad_type12$, $ad_type13$, $ad_type14$, $ad_type15$ ]
 var ad_enabled = [$ad_enabled0$, $ad_enabled1$, $ad_enabled2$, $ad_enabled3$, $ad_enabled4$, $ad_enabled5$, $ad_enabled6$, $ad_enabled7$, $ad_enabled8$, $ad_enabled9$, $ad_enabled10$, $ad_enabled11$, $ad_enabled12$, $ad_enabled13$, $ad_enabled14$, $ad_enabled15$ ]
 var ad_sys = [$ad_sys0$, $ad_sys1$, $ad_sys2$, $ad_sys3$, $ad_sys4$, $ad_sys5$, $ad_sys6$, $ad_sys7$, $ad_sys8$, $ad_sys9$, $ad_sys10$, $ad_sys11$, $ad_sys12$, $ad_sys13$, $ad_sys14$, $ad_sys15$ ]
@@ -112,4 +121,5 @@
 //-->
 </script> 
 </body>
-</html>
\ No newline at end of file
+</html>
+
```
there is still some garbage at the end of the page,  but this is maybe related to the response buffer
![screen shot 2015-09-24 at 19 18 20](https://cloud.githubusercontent.com/assets/3009073/10080722/927dd278-62f1-11e5-9ea0-44db58b4e3ac.png)

**Comment by connaisseur** [comment]
Options on minisatip seems to be a little bit "out of hands":

We have now (doing a ''minisatip -h''):

    -D --device-id DVC_ID

and

    -D --document-root directory

IMHO that's worse. Some clarification / modification would be helpful.

**Comment by catalinii** [comment]
Hi,

it is a type and it will be fixed in the next commit.

Thanks

**Comment by 9000h** [comment]
missing useragent in status.html
```
--- stream.c.orig	2015-09-28 19:02:16.520342265 +0200
+++ stream.c	2015-09-28 19:50:28.922879829 +0200
@@ -1201,4 +1201,5 @@
 { "st_rhost", VAR_FUNCTION_STRING, (void *) &get_stream_rhost, 0, 0, 0 },
 { "st_rport", VAR_FUNCTION_INT, (void *) &get_stream_rport, 0, 0, 0 },
 { "st_pids", VAR_FUNCTION_STRING, (void *) &get_stream_pids, 0, 0, 0 },
+{ "st_useragent", VAR_ARRAY_STRING, &st[0].useragent, 1, MAX_STREAMS, sizeof(st[0]) },
 { NULL, 0, NULL, 0, 0 } };
```

**Comment by 9000h** [comment]
Hi,
you could also replace document.write( myTable); with:
```
var el = document.createElement('div');
el.innerHTML = myTable;
document.body.appendChild(el);
``

**Comment by catalinii** [comment]
Hi,

I am not very good with html, is there a difference ? :)

**Comment by 9000h** [comment]
there is no much difference only compatibility and performance

**Comment by catalinii** [comment]
Done

**Comment by 9000h** [comment]
@vdrtuxnet can you close it or do you still see issue, for me it's working fine with vdr
