### ISSUE TITLE
No start without html directory

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#170]
Hi,

In last version with mini HTTP status support (great functionality!) when the HTML directory is missing the program has troubles at starting. Please, fix this. I suggest two options:

1) Exit with some error code if the directory is missing.

2) Disable (at runtime) the HTTP status support if the directory is missing.

I detected this when I update to last version and I start (alone) the minisatip binary.

Regards!

**Comment by 9000h** [comment]
it's the same as #169

**Comment by lars18th** [comment]
Then, I close this! ;-)
