### ISSUE TITLE
RFE: question: dvbapi adapter offset

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#173]
do we handle the dvbapi net demux offset right with multiple servers, and whats about a switch like vdr plugin has?
reference: https://github.com/catalinii/minisatip/issues/103

**Comment by catalinii** [comment]
I did not see the need for it until now :)

**Comment by 9000h** [comment]
this is what Manio did in the vdr dvbapi plugin 
https://github.com/manio/vdr-plugin-dvbapi/commit/c7d0e2755cac76c5255e09c0345506cc5bc60124
so it looks not that complicated to implement

there are sometimes issues with multiple connects with the same user to the same dvbapi network demux adapter index on the oscam side like:

```
015/10/02 19:54:02 34F3CF4E c (dvbapi) ERROR: Could not close demuxer socket fd (errno=4 Interrupted system call)
```

**Comment by 9000h** [comment]
btw. would it not make sense to move this error log 
```
--- socketworks.c.orig	2015-10-02 09:26:51.755618057 +0200
+++ socketworks.c	2015-10-02 09:27:15.941235709 +0200
@@ -252,10 +252,10 @@
 
 	if (connect(sock, (struct sockaddr *) serv, sizeof(*serv)) < 0)
 	{
-		LOGL(0, "tcp_connect: failed: connect to %s:%d failed: %s", addr, port,
-				strerror(errno));
 		if (errno != EINPROGRESS)
 		{
+		LOGL(0, "tcp_connect: failed: connect to %s:%d failed: %s", addr, port,
+				strerror(errno));
 			close(sock);
 			return -1;
 		}
```

**Comment by 9000h** [comment]
do you have any plan to move up to dvbapi protocol version 2 ?
https://github.com/manio/vdr-plugin-dvbapi/issues/91#issuecomment-95874618

**Comment by catalinii** [comment]
v2 sounds like a good idea and it will be implemented at some point ... depending on the time

**Comment by 9000h** [comment]
will try the commit from today, what do think about to make the detected pmt pid also available to status.html page

**Comment by catalinii** [comment]
You mean the pmt pid for a key?

**Comment by 9000h** [comment]
I mean the pmt pid which the the client provides in the url or the detected one for the channel which should be the same one at the end.

**Comment by catalinii** [comment]
I just added it...

**Comment by 9000h** [comment]
nice  thanks
```
[07/10 18:18:33.645]: select_and_execute[8]: Connected on socket 15 (sid:-1) from 0.0.0.0:0 - type tcp errno 11
[07/10 18:18:33.647]: dvbapi: server version 2 found, name = OSCam v1.20-unstable_svn, build r10988 (mips-linux-uclibc-ssl-libusb)
```
this would make the log more clear
```
--- socketworks.c.orig  2015-10-02 09:26:51.755618057 +0200
+++ socketworks.c   2015-10-02 09:27:15.941235709 +0200
@@ -252,10 +252,10 @@

    if (connect(sock, (struct sockaddr *) serv, sizeof(*serv)) < 0)
    {
-       LOGL(0, "tcp_connect: failed: connect to %s:%d failed: %s", addr, port,
-               strerror(errno));
        if (errno != EINPROGRESS)
        {
+       LOGL(0, "tcp_connect: failed: connect to %s:%d failed: %s", addr, port,
+               strerror(errno));
            close(sock);
            return -1;
        }
```

**Comment by catalinii** [comment]
This is fixed, right?

**Comment by 9000h** [comment]
dvbapi version 2 is working fine

the log shows still the error on connect which is bit annoying, as EINPROGRESS is no real error
```
[07/10 18:18:33.644]: New TCP socket 15 connected to 192.168.178.1:2000
[07/10 18:18:33.644]: sockets_add: handle 15 (type 1) returning socket index 8 [0.0.0.0:0] read: 0x40887f
[07/10 18:18:33.645]: select_and_execute[8]: Connected on socket 15 (sid:-1) from 0.0.0.0:0 - type tcp errno 11
[07/10 18:18:33.647]: dvbapi: server version 2 found, name = OSCam v1.20-unstable_svn, build r10988 (mips-linux-uclibc-ssl-libusb)
```
the adapter offset is still a wish, as multiple servers get sometimes confused at the oscam side

**Comment by catalinii** [comment]
That message is normal and it should be there as we should find out when  the connection is made...

**Comment by 9000h** [comment]
http://www.streamboard.tv/oscam/changeset/11064 looks also promising, it's may also related to the issue I saw here

**Comment by 9000h** [comment]
today I saw the issue again, after a second dvbapi connect from a different minisatip was connected and then disconnected the first minisatip dvbapi stops descrambling.

**Comment by catalinii** [comment]
Hi,  are you testing with the latest oscam?

**Comment by 9000h** [comment]
last test was with OSCam r11049

**Comment by 3PO** [comment]
>today I saw the issue again, after a second dvbapi connect from a different minisatip was connected >and then disconnected the first minisatip dvbapi stops descrambling. 

Thats the reson why i dont use dvbapi in netmode!

The oscam dvbapi protocoll is not really usefull, if you have more than one Client in your LAN.

The better way is haveing a local oscam on each minisatip Server. ;)

**Comment by catalinii** [comment]
Guys, if you are confident this will fix it, I will implement it... just to get 0.5 a bit stable :)...

**Comment by 9000h** [comment]
I will try again with http://www.streamboard.tv/oscam/changeset/11064 or later as this was a similar issue (VU+ Solo2 mit OpenATV 5.1) with "Twintuner on same Transponder"

**Comment by 9000h** [comment]
looks like it's in 0.7-ca implemented
