### ISSUE TITLE
[info]: MIS Support for Multistream Transponders

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#177]
https://toda.ro/forum/viewtopic.php?t=3&start=10

if someone likes to use or test it 

@ 13 east Hotbird

11373 H DVB-S2/8PSK MPEG-2
Multistream
PLS: Root+8 27500 2/3 Mediaset w HB-13C new
Stream 2
Rete 4 w F 1630 1631 Ita
1632 Org 4004
Canale 5 w F 1610 1611 Ita
1612 Org 4005
Italia 1 w F 1620 1621 Ita
1622 Org 4006
La 5 w 1730 1731 Ita
1732 Org 4013
TgCom24 w F 1810 1811 Ita 4014
Iris w F 1670 1671 Ita
1672 Org 4015

http://www.flysat.com/hotbird.php 

there is also support from the dvb drivers needed

https://bitbucket.org/CrazyCat/linux-tbs-drivers

Omicom S2 PCI.
TBS 5980, 5925, 6925, 6983, 6905, 6908.
Technisat Skystar HD USB, Skystar2 eXpress HD PCI-E.

Digital Devices Cine S2 V6.5, Duoflex S2 - https://bitbucket.org/CrazyCat/dddvb

for tvheadend you can look here
https://tvheadend.org/boards/5/topics/14109?r=16770

**Comment by Yuri666** [comment]
Mediaset left this transponder. For test now you can use 5E, provider Zeonbud.

**Comment by 9000h** [comment]
so the info is more or less useful fro some people only
