### ISSUE TITLE
[RFE] Support for H265/HEVC streaming

### ISSUE THREAD

**Issue by hargut** [catalinii/minisatip#178]
Dear catalinii,

I'd really like to see support for HVEC/H265 streaming in minisatip since there are already some FTA 4k / UHD channels up and running on Astra 19.2E, and most likely on other satellites as well.

0x24 is the pid_type for MPEG4 HEVC video.

Sample Channels on S19.2E (freq=12344;pol=h;srate=30000;coderate=2/3)
* Insight UHD
* PEARL TV 4K UHD

Best Regards,
Harald

**Comment by 9000h** [comment]
it's already in some time, did you try already like Astra 19.2
```
#EXTINF:-1,Astra 19.2E Fashion 4K UHD
rtsp://192.168.178.133/?src=1&freq=11111&sr=22000&fec=23&pol=h&msys=dvbs&pids=0,2815,2816,106
```
UHD1 is HDPLUS crypted btw.

**Comment by hargut** [comment]
Sorry, HVEC/H265 support is already working properly. The issue can be closed.

It seems that I had a wrong frequency in my test setup for the channels.
Above mentioned channels do work properly when streamed with the correct settings:
`#EXTINF:-1,Astra 19.2E PEARL TV 4K UHD 
rtsp://10.0.0.12/?src=1&freq=12344&sr=30000&fec=23&pol=h&msys=dvbs2&pids=106,2815,2816
#EXTINF:-1,Astra 19.2E Insight UHD 
rtsp://10.0.0.12/?src=1&freq=12344&sr=30000&fec=23&pol=h&msys=dvbs2&pids=96,255,256
#EXTINF:-1,Astra 19.2E Fashion 4k Preview 
rtsp://10.0.0.12/?src=1&freq=11112&sr=22000&fec=23&pol=h&msys=dvbs2&pids=97,511,515
#EXTINF:-1,Astra 19.2E Fashion 4k
rtsp://10.0.0.12/?src=1&freq=11112&sr=22000&fec=23&pol=h&msys=dvbs2&pids=106,2815,2816`

Thank you for the support and this great piece of software. :+1: 

Best Regards,
Harald
