### ISSUE TITLE
docu bug: README.txt

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#180]
the REAME.txt suggest a mac value with semicolon
```
-m xx: simulate xx as local mac address, generates UUID based on mac
	-m 00:11:22:33:44:55 
```
but minisatip expects the mac without the semicolon

btw this option is helpful if you have a SAT>IP client like the Panasonic TV which stores the UUID and if you need to change the server to a different hardware(mac) and don't like to rescan all all channels

**Comment by 3PO** [comment]
Here is an other Bug:

>Usage:

>minisatip [-[flzg]] [-r remote_rtp_host] [-d device_id] ....

" [-d device_id]" must be: " [-D device_id]"

**Comment by 9000h** [comment]
rigth
```
-D --device-id DVC_ID: specify the device id (in case there are multiple SAT>IP servers in the network)
 	eg: -d 4 
```

**Comment by catalinii** [comment]
Will fix those in the next commit.

Thanks

**Comment by 9000h** [comment]
thanks
