### ISSUE TITLE
[Feature request] Threads ?

### ISSUE THREAD

**Issue by FuNK3Y** [catalinii/minisatip#181]
I am currently using minisatip on an overclocked pi 1 and it goes pretty well (2 tuners, 2 client - max 2 different streams).

For the sake of testing, I tried to move the oscam part to the raspberry. It worked OK when only 1 client was consuming an encrypted HD stream, but when the second client did connect the poor rasp couldn't handle the load.

I would be interested in testing on a rasp 2; but since minisatip is single threaded I don't expect any benefit. Decoding streams seems like tasks that could be easily parallelized and that would greatly benefit from an increased number of core.

Thanks for the good work !

**Comment by catalinii** [comment]
Hi,

raspberry pi 2 is a ARMv7 which is 2 times more efficient at the same clock frequency,

Having said that, threads is on my TO DO list.

**Comment by FuNK3Y** [comment]
Good to know!

I dis order a pi 2, I will see how it goes!

**Comment by FuNK3Y** [comment]
I did received it and tested, and the pi2 is definitively faster! Without encryption it works smoothly with a low CPU usage. The pi1 sometime missed frames when the 2 tuners were working at the same time.

I will retest once the threads are in place, with the current implementation it is still impossible to have more than 1 encrypted HD.

**Comment by catalinii** [comment]
Hi,

did you managed to test master? how is it working with RPI 2 ?

Thanks

**Comment by FuNK3Y** [comment]
Ho ! I overlooked the new support for thread.

I will test this out this evening for sure

**Comment by FuNK3Y** [comment]
I did test, and it works way better. I get 3-4 encrypted HD stream perfectly now!

Great work, thank you !
