### ISSUE TITLE
bug  PID_FILE

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#183]
the minisatip pid file handling got messed up somehow, under /var/run only %s.pid got written/deleted
minisatip.c:1057
minisatip.c:1002
utils.h:37

see also #182

**Comment by catalinii** [comment]
This should be fixed in 0.5,

can you please test 0.5  and let me know if you have any issues with it ?

**Comment by 9000h** [comment]
the pid file is still written as %s.pid under /var/run
-rw-rw-rw-  1 root  root     4 Oct 30 11:09 %s.pid

**Comment by 9000h** [comment]
fixed in 0.5

**Comment by 9000h** [comment]
the issue is exist also on master

**Comment by catalinii** [comment]
Hi, can we close this ? :)

**Comment by 9000h** [comment]
yes it's fine now
