### ISSUE TITLE
enhancement:  CI/CA mmi socket

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#185]
it would be great to have a mmi socket for accessing the CI from outside like in dvblast or dreambox
https://github.com/gfto/dvblast

**Comment by catalinii** [comment]
I need to look into this and let you know ...

**Comment by 9000h** [comment]
we may find another way to have access to the cam menu, there could be some need if you have to put a pin for parental control in

**Comment by 9000h** [comment]
could this help to get a working MMI interface for minisatip implemented?

https://github.com/aospan/libjokertv/blob/a9a9d5b233389474cff7aa36efa27f8cc78de508/src/joker_en50221_server.c

https://jokersys.com/2018/03/01/common-interface-ci-descrambling-tv/

**Comment by Jalle19** [comment]
AFAICT MMI is nowadays supported, at least for CAM to host communication and PIN parental control.
