### ISSUE TITLE
small issue in last commit 24

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#19]
v=0
o=--1 -1 IN IPV4 192.168.178.133
s=SatIPServer:1 1 1 1
t=0 0

it should be IP4 and not IPV4

**Comment by 9000h** [comment]
and
o=--1 the double -- is probably also a issue

**Comment by 9000h** [comment]
missing cr/lf sendonly\r\n

snprintf(sbuf + slen, size - slen - 1, "m=video %d RTP/AVP 33\r\nc=IN IP4 0.0.0.0\r\na=control:stream=%d\r\na=fmtp:33 %s\r\na=sendonly", ntohs (st[i].sa.sin_port), i, describe_adapter(i, st[i].adapter));
snprintf(sbuf + slen, size - slen - 1, "m=video %d RTP/AVP 33\r\nc=IN IP4 0.0.0.0\r\na=control:stream=%d\r\na=fmtp:33 %s\r\na=sendonly\r\n", ntohs (st[i].sa.sin_port), i, describe_adapter(i, st[i].adapter));

**Comment by 9000h** [comment]
there seem also issues by fill_sockaddr
I made extra LOG in fill_sockaddr before the check if host

[Sun Jan 18 22:39:10.051 2015]: event on socket index 7 handle 16 type 5 (poll fd:16, revents=17)
[Sun Jan 18 22:39:10.051 2015]: select_and_execute[7]: Error on socket 16 (sid:0) from 0.0.0.0:0 - type dvr failure 11:Resource temporarily unavailable
[Sun Jan 18 22:39:10.051 2015]: event on socket index 4 handle 9 type 4 (poll fd:9, revents=25)
[Sun Jan 18 22:39:10.051 2015]: read RTSP (from handle 9 sock_id 4): PLAY rtsp://192.168.178.133:554/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106 RTSP/1.0
Range: npt=0.000-
CSeq: 3


[Sun Jan 18 22:39:10.051 2015]: starting init_hw 1
[Sun Jan 18 22:39:10.051 2015]: detect_dvb_parameters (S)-> freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106
[Sun Jan 18 22:39:10.051 2015]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=338000, sr=6900000, pol=-1, ro=-1, msys=1, mtype=5, pltf=-1, bw=-1, inv=-1, pids=0,100,101,104,102,103,106 - apids=NULL - dpids=NULL
[Sun Jan 18 22:39:10.051 2015]: Setup stream -1 parameters, sock_id 4, handle 9
[Sun Jan 18 22:39:10.051 2015]: fill_sockaddr: gethostbyname(): ?+A
[Sun Jan 18 22:39:10.055 2015]: fill_sockaddr: gethostbyname(): Connection timed out
[Sun Jan 18 22:39:10.055 2015]: New UDP socket 17 connected to 0.0.0.0:0

**Comment by 9000h** [comment]
I did sent you a PM at http://forums.openpli.org please check

**Comment by 9000h** [comment]
socketworks.c missing  htonl  in  function fill_sockaddr 

line 48
        serv->sin_addr.s_addr = htonl(INADDR_ANY);

**Comment by catalinii** [comment]
Comment #1: fixed
Comment #3: http_response will add 2*\r\n
Comment #4: see the issue #18 
comment #5: done

Thanks
