### ISSUE TITLE
info: extended cw (CSA, DES, AES128)

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#191]
not sure if this is of any interest https://github.com/gfto/oscam/commit/be07d0245d13f0d638f24fcf2d55a791c614597c
https://github.com/oscam-emu/OSEmu/blob/master/module-emulator-stream.c

**Comment by catalinii** [comment]
Are there any channels using those systems ?

**Comment by 9000h** [comment]
I suspect PowerVU

**Comment by Yuri666** [comment]
Yes, it's powervu. If want, i can test.

**Comment by vdrtuxnet** [comment]
Hi,

this would be a great feature and a way to get rid of mumudvb.

Quite funny, its working out of the box with a DMM Box, another way to fill their money buckets.

Kind regards

**Comment by Yuri666** [comment]
https://github.com/manio/vdr-plugin-dvbapi/commit/b4cd00a69ca523ef5f76c108f7dd230f5d0c84e5

**Comment by vdrtuxnet** [comment]
Hi Yuri,

THX for the info, is that working for you?
ECMs are fine, but I don't see any EMM in the log.

**Comment by Yuri666** [comment]
Hello!
I can't test now, the wind pushed my satellite dish and I can't receive channels with powervu. :(

**Comment by vdrtuxnet** [comment]
Hello,

Oh poor Yuri, hope you sorted it out.

Some good news, this is perfect working, ECM and EMM side, with minisatip -> vdr-plugin-satip -> vdr -> vdr-plugin-dvbapi -> oscam.

Any chance to got this code added into minisatip?

**Comment by catalinii** [comment]
Hi,
I need a system where to test this...
Thanks 

    On Monday, February 15, 2016 5:19 AM, vdrtuxnet <notifications@github.com> wrote:
 

 Hello,Oh poor Yuri, hope you sorted it out.Some good news, this is perfect working, ECM and EMM side, with minisatip -> vdr-plugin-satip -> vdr -> vdr-plugin-dvbapi -> oscam.Any chance to got this code added into minisatip?—

**Comment by vdrtuxnet** [comment]
Hi Catalin,

and how can we help you?

SSH access?

**Comment by catalinii** [comment]
Hi,

I got access meantime.

Thank you

**Comment by 9000h** [comment]
I believe we can close here

**Comment by catalinii** [comment]
Sorry I will re-open this... I starting working on this and have added most of the code... but was not able to test.
