### ISSUE TITLE
cosmetics: log

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#192]
some log cosmetics master and branch 0.5, would it be better to user the macros
dvb.c:		perror("couldn't set DVR buffer size");
dvb.c:			perror("FE_SET_PROPERTY TUNE failed");
socketworks.c:			perror("select_and_execute: select() error");

**Comment by catalinii** [comment]
Hi,

perror prints to stderr....
or you mean creating another macros that use LoG?

Thanks

**Comment by 9000h** [comment]
this errors get not logged to syslog or file, would it be helpful to have it in the logs

**Comment by 9000h** [comment]
thanks
