### ISSUE TITLE
Adapter pid errs

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#194]
Hi @catalinii ,

Can you explain why these errors:

> [16/11 05:21:59.5131434]: get_active_key: returning key 0 for pid 162, d/c errs 423/0, adapter pid errs 75343
> [16/11 05:21:59.5131434]: get_active_key: returning key 0 for pid 92, d/c errs 31/0, adapter pid errs 75343
> [16/11 05:21:59.5131434]: get_active_key: returning key 0 for pid 93, d/c errs 25/0, adapter pid errs 75343
> ...
> [16/11 05:23:45.5236485]: get_active_key: returning key 0 for pid 162, d/c errs 423/0, adapter pid errs 75343
> [16/11 05:23:45.5236485]: get_active_key: returning key 0 for pid 92, d/c errs 31/0, adapter pid errs 75343
> [16/11 05:23:45.5236485]: get_active_key: returning key 0 for pid 93, d/c errs 25/0, adapter pid errs 75343

I don't know why they appear.

**Comment by catalinii** [comment]
Hi,

if you don't have c errors (whcih are counter continuity errors) everything is fine.
decrypt errors is how many packets have not been decrypted (most likely between tune and the first CW).

Adapter errors are the number of packets for which there is no "filter", it happens mostly in the satipc case...

Anyway those are not getting to the satip clients.

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you for fast respond. My concern is related to "adapter pid errs". Using one HTTP client when the image freezes or have some error, then these messages appear. If you say that this counter is related to pids not found in any filter, then I feel the tuner is receiving garbage. It's correct?

**Comment by catalinii** [comment]
You can give me a log with -l -l -l -l -l  (5 times) and I can look at it, maybe it's something there...

**Comment by lars18th** [comment]
Hi,

With LOG 5 I can't show now the problem... I'm not sure if it's related to the speed of the Oscam server... However, I fount another trouble related to blocking read/writes:

* I start the minisatip with "-l -l -l -l -l" in a SSH remote session (using screen) with PuTTY from my Windows computer.

* Then I start a SAT>IP client in the Windows machine (TransEdit) and I play an encrypted channel. All works right.

* After I close the SAT>IP client and I start VLC using HTTP client mode to play the same channel. All works right.

* Then I "move" the PuTTY window (click left mouse button) and I don't stoping to move the window... this "blocks" the output log of the minisatip, and as consecuence the video frezees after 2 seconds (aprox.). The annoying behaviour is that the stream only blocks when using an HTTP client, with the RTSP client the image don't freeze (only time to time).

Please, can you revise the functions for logging and HTTP streaming and try to make them non-blocking?

**Comment by lars18th** [comment]
Hi @catalinii ,

Compiled the last multithread version (0.5.7), and the same "blocking" behaviour of the LOGs when HTTP client are connected appears.

Please, if you can, put logs or http socket writing functions into a non-blocking thread.

Thank you!

**Comment by catalinii** [comment]
Let me understand this right, Lars.

You want when I want to log something to log in a different thread because LOG (_log function) blocks ?

Thanks

**Comment by lars18th** [comment]
> You want when I want to log something to log in a different thread because LOG (_log function) blocks ?

Yes, I feel something is blocking... and I suspect are logs. Examples:

- You are playing a program with a RTSP client, and you open another client (HTTP) for the same program. Result: one freeze !

- You are playing a program with a HTTP client, and running minisatip in foreground with log enable over a SSH session. You "move" the SSH window (PuTTY) and the log stops updating (you move the window, then the client don't update). Result: one freeze in the video !

So, my opinion is something is blocking. Perhaps log writes?

**Comment by catalinii** [comment]
Hi Lars,


adding a separate thread just for logging is really an overkill, because I need to also allocate memory for buffers... on top of that just an additional thread will require 1M or more of memory (think about the systems with lower memory). The workaround is simple, drop the log level or log to a file.

I believe that it happens because the write to the console is blocking...(yes log writes to the stdout)...
