### ISSUE TITLE
Bug: Oscam reconnection

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#199]
Hi,

I have with last versions (now v0.5.x releases) a very annoying error: When I select one encrypted channel and Oscam triggers "timeout" (aka, this channel can be decrypted) then after that ALL new requests for encrypted channels fails (any FTA channel still works). The reason? The minisatip connection with the Oscam server CLOSES, then the execution of the minisatip continues but disconnected with the Oscam server.

Please, can you add code (or fix it) to reconnect to the Oscam server when the connection disconnects or some other error emerge?
Thank you!

**Comment by catalinii** [comment]
Hi,

Can you upload the log please?

Thanks

**Comment by lars18th** [comment]
This is the same bug as #204 , then I close this!
