### ISSUE TITLE
Log into Syslog?

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#2]
Is it possible to make minisatip able to log into the syslog?

BTW: The Parameter "-l" is not explained in Readme.txt.

**Comment by catalinii** [comment]
Do you think there is a point adding logging to syslog ?

In general without -l it should not write anything to the logs (unless there is something seriously wrong) and searching in syslogs in this case might be more of a hassle.

When -l is enabled (when you actually need the log) getting the data from there might be again a hassle.

If you feel strong about having it log to syslog I can add it.

**Comment by catalinii** [comment]
Created an enhancement in the new system:
https://toda.ro/issues/5
