### ISSUE TITLE
ca_mask should have 32bit

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#200]
can we sync up here with oscam 
http://www.streamboard.tv/oscam/changeset/11173

**Comment by catalinii** [comment]
I was looking into this but I think is related to AU...

**Comment by catalinii** [comment]
Did u tested AU with the latest commit?

**Comment by 9000h** [comment]
yes, it's still not working
one of the streampid's is detected as "Datastream (DSM CC)" if I remember right
