### ISSUE TITLE
Disable unused tuners

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#201]
Hi,

This is my current config:

$ mumudvb -l

MuMuDVB Version 1.7.1
 -- Build information --

Built with CAM support.
Built without transcoding support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.
-- -- -- ---
Originally based on dvbstream 0.6 by (C) Dave Chapman 2001-2004
Released under the GPL.
Latest version available from http://mumudvb.braice.net/
Project from the cr@ns (http://www.crans.org)
by Brice DUBOST (mumudvb@braice.net)

Info:  DVB:  ==================================
Info:  DVB:          DVB CARDS LISTING
Info:  DVB:  ==================================

Info:  DVB:  =========== Card 0 - Tuner 0 ===========
Info:  DVB:   Frontend : Afatech AF9013 DVB-T
Info:  DVB:   Terrestrial (DVB-T) card
Info:  DVB:   Frequency: 174000 kHz to 860000 kHz
Info:  DVB:

Info:  DVB:  =========== Card 1 - Tuner 0 ===========
Info:  DVB:   Frontend : Afatech AF9013 DVB-T
Info:  DVB:   Terrestrial (DVB-T) card
Info:  DVB:   Frequency: 174000 kHz to 860000 kHz
Info:  DVB:

Info:  DVB:  =========== Card 2 - Tuner 0 ===========
Info:  DVB:   Frontend : vTuner proxyFE DVB-S2
Info:  DVB:   Satellite (DVB-S) card
Info:  DVB:   Frequency: 950000 kHz to 2150000 kHz
Info:  DVB:   Symbol rate: 1000 k symbols/s to 45000 k symbols/s
Info:  DVB:

And this is the command line when I start minisatip:

$  ./minisatip -f -i -14 -e 2 -a 1:0:0 -ll

But the file /desc.xml includes this:

>  satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBS2-1,DVBT-2</satip:X_SATIPCAP>

Also in the LOG are messages related to DVB-T tuners and in the Web interface I show three tuners.

So I suggest to change the tractament of the tuner parameters to completly disable tuners.

**Comment by catalinii** [comment]
Hi,

Yes this will be fixed in the commit.

Thanks for reporting this

**Comment by lars18th** [comment]
Hi @catalinii ,

> Yes this will be fixed in the commit.
Thank you!

I hope next version also includes support for ALi SAT>IP servers (faulty servers!).

**Comment by lars18th** [comment]
Thank you! Bug fixed.
