### ISSUE TITLE
enhancement: dedicate delivery systems to dvb-c or dvb-t tuner based

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#202]
this more related to cards with DVB-C/C2/T/T2, in case of cards like the one from Digital devices which have 2 tuners on the same cable. If on stream is requested from DVB-C the DVB-T will not work on the second tuner except you can combine the DVB-C and DVB-T antenna signals which is not possible here. The best way to get around this is to dedicate the card/tunes to a one delivery system DVB-C or DVB-T.

here are a good list of all DD cards http://www.argus-tv.com/wiki/index.php?title=Digital_Devices, mine is a DuoFlex CT v2 (signal-input-connector and one output, signal is looped through)

**Comment by catalinii** [comment]
So you mean to link the system of one card to the other cards ?

If one is DVB-C all others are DVB-C and the other way around ?

I am guessing this happens if you have multiple cards some DVB-C some DVB-T, get_free_adapter will bind to one that has the wrong cable attached?

**Comment by 9000h** [comment]
I may was vague here. Linking the delivery system of one tuner card0 to the other card0 tuner would fix the issue for this card but not if you have a mix of cards and one has no signal for a specific delivery system.

**Comment by catalinii** [comment]
What do you propose?

**Comment by 9000h** [comment]
I like to have

1 card 2 x DVB-S2
1 card 2 x DVB-C/T   signal is only DVB-C
1 stick 1 x DVB-C/T/T2 singnal is only DVB-T/T2

so if a request comes for DVB-T/T2 is has to go to the stick only

**Comment by catalinii** [comment]
Maybe I can add some code to force specific delivery system for specific adapters.

So the DVB-C channels goes just to the DVB-C/T card.

What do you think ?

**Comment by 9000h** [comment]
that would be nice

**Comment by 9000h** [comment]
-Y is now implemented, thanks!
