### ISSUE TITLE
ECM key re-ask when NULL

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#203]
Hi,

With some SLOW cam server, I have this problem: sometimes the Oscam server return "timeout" for key request.

Then in the minisatip code this line manages this case (
http://github.com/catalinii/minisatip/blob/d8cb1ead4f51cc19228df8212e29a7d83045b352/dvbapi.c#L435)
`
    LOGL(1, "get_active_key: returning NULL for pid %d, starting key %d",
            p->pid, key);
    return NULL;
`

Then no action when no key. Please, can you add some "re-ask" for the key? I like to configure Oscam for "short" timeout and leave minisatip to retry for the key.
Is this a good idea?

**Comment by catalinii** [comment]
I think is a good idea.... I will include this in the next commit..

**Comment by lars18th** [comment]
Perfect! ;)

**Comment by lars18th** [comment]
Hi @catalinii ,

After try last commit (v.0.5.10) I feel this change in #759-761 of dvbpai.c improves a bit:

```
+	if((getTick() - k->last_ecm > 1000) && !k->key_ok[0] && !k->key_ok[1])
+		p->ecm_parity = -1;
+
```

However, it don't resolves the full problem, some freezes continue. Any suggestion?

**Comment by lars18th** [comment]
Hi @catalinii ,

I feel that last commit don't implement what you think. I do this patch with current version:

```
dvbapi.c:
@957:         return 0;
     +
     +        if((getTick() - k->last_ecm > 100) && !k->key_ok[0] && !k->key_ok[1])
     +        {
     +                 p->ecm_parity = -1;
     +                 LOG("dvbapi: Re-ask ECM key");
     +        }
     +
@762:        if ((b[0] & 1) == p->ecm_parity);
```

Then in the Oscam server I set "1500" for the timeout of the client. With this config when I start to show a program, when Oscam starts to decrypt then the message "re-ask ECM" is shown in the log. Then when the program starts to decrypt after some time the NULL decoding message appears... but never is found the "re-ask ECM" message. Also the images freezes regularly as the timeout in the Oscam is low and requests to slow servers expires.

Please, say if I lost something.
Thank you!

**Comment by catalinii** [comment]
Is this still needed after fixing the SID?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> Is this still needed after fixing the SID?

Yes! They are different issues. As pointed here with my code change, your current code only "re-ask" at the start of the channel tune. Mainly the code does this: when you tune a new channel, if first call to the Oscam sever, and when it returns a NULL key because the reader is not initialized (or it's finding something else), then after "1000" msec (you have fixed this value) then you re-ask for the key. This is great, and it starts the decoding process in a more robust way.

However, my request is different: when you're whatching a program, sometimes you can receive a NULL key. This is because the reader has triggered a timeout. If the Oscam server sets a small value for timeout and the reader is slow, then this occurs often. In this case, my request is for "re-ask" each time you receive a NULL key when processing the channel decoding.

My patch demonstrates that the re-ask function is only called in the initialization process of the channel tune. Please, add this log to the code (I feel useful to know when re-ask is triggered); and try to implement the "re-ask" at any time.

You agree? ;)

**Comment by lars18th** [comment]
Hi @catalinii ,

I like to found the code where the NULL key is processed *after* the initialization of the program. I need to log (with level 1) this case, to search for a solution. Please, can you include some debug info about this?

In addition, another question: When minisatip has a NULL key and one encrypted packet arrives to the buffer, what is the behaviour? You discard the packet (until a valid key arrives) or you copy it to the output buffer without decrypting?

Regards!

**Comment by lars18th** [comment]
Hi @catalinii ,

I discovered the part of the code that creates the trouble. I explain it:

* The constant MAX_KEY_TIME defined in "dvbapi.h" defines 25 sec. for a max time of a key.

* The line "390@dvbapi.c" invalidates the key when time out:
http://github.com/catalinii/minisatip/blob/a5c6903886fc1cdeb08cf5e17ca54a57d7448594/dvbapi.c#L390

Then I commented this like, and the errors disapears! :)

The main problem seems to be the cache of Oscam. If this timeout is less that the maximum time of cache, when you invalidate a key and re-ask for them to the Oscam server, it don't have it in the cache... so the problem appears.

Please, review this line of code. I'm not sure if it's has sense, as if the key is valid... why invalidate it?
Regards!

**Comment by lars18th** [comment]
I respond to me:

> In addition, another question: When minisatip has a NULL key and one encrypted packet arrives to 
> the buffer, what is the behaviour? You discard the packet (until a valid key arrives) or you copy it 
> to the output buffer without decrypting?

After review the function decrypt_stream() in dvbapi.c, I feel it is working right: they don't discard packets when it can decode them.

http://github.com/catalinii/minisatip/blob/a5c6903886fc1cdeb08cf5e17ca54a57d7448594/dvbapi.c#L524

The only remaining problem here is then the value MAX_KEY_TIME. The need to be changed? If it's really needed?

Regards!

**Comment by catalinii** [comment]
Well MAX_KEY_TIME is a mechanism to detect when a key expires...except parity changes...
The approach might not work when a channel uses constant CW...

Other than that it should be ok...

**Comment by lars18th** [comment]
Hi @catalinii ,

> Well MAX_KEY_TIME is a mechanism to detect when a key expires

But a key expiration isn't defined in the standard... any key can be valid until the parity change!
At time, I commented the lines that checks this value, and I don't have any problem. I recommend to disable this code, as I never see it in another implementations.

You agree?

**Comment by catalinii** [comment]
Lars,

there are 2 situations which are kinda of hard to separate.

A key arrives from dvbapi server on a parity that is active... how do u distinguish if it is the active key or is the key that will be active after 2 parity changes ?

Before MAX_KEY_TIME was not used, but it did fix the situation that I am explaining (and I agree that this could also break things)....

**Comment by lars18th** [comment]
Hi @catalinii ,

I need to say first that I continue commenting this line:
http://github.com/catalinii/minisatip/blob/master/dvbapi.c#L388
And I continue to see log messages of "get_active_key: Invalidating key %d, parity %d, as the CW expired, pid %d". And the server works well with this line commented out.

Related to your comment:

>there are 2 situations which are kinda of hard to separate.
>A key arrives from dvbapi server on a parity that is active... 
>how do u distinguish if it is the active key or is the key that will be active after 2 parity changes ?

I feel the response is simple:

- When you ask for key0 and key1, if some of them are NULL, then the received is the good key.
- If not, then you need to campare current keyX with received keyX; if they are identical, then the received key is the current one, if not then is the one that will be valid after 2 partiry changes.

I feel is easy to distinguish beetwen current valid key and the next key. Rigth?

**Comment by catalinii** [comment]
Are you getting this in non-constant CW channels?

Theoretically sounds easy. Practically feel free to implement it and test it and let me know how ut goes....

**Comment by lars18th** [comment]
Hi @catalinii ,

> Are you getting this in non-constant CW channels?

Yes, in regular CA channels.

> Practically feel free to implement it and test it and let me know how ut goes

Sorry! I'm not an specialist with DVBAPI. At time I'm working on supporting other "external" tuner protocols. So, I can't fix this problem, except to comment this line. Please, I suggest to comment out it in the current master tree until you can fix. You agree?

**Comment by catalinii** [comment]
I dont see any log can u send me one?

**Comment by lars18th** [comment]
> I dont see any log can u send me one?

I'll prepare one...

**Comment by lars18th** [comment]
Hi @catalinii ,

I need your help, as I'm still having troubles with this problem.
I discovered with logs that when the freeze appears, the log always shows like this:

```
[17/11 11:45:07.761 AD2]: Parity change for key 0, new parity 1 pid 116 [47 00 74 D4], last_parity_change 1816842
[17/11 11:45:07.761 AD2]: get_active_key: searching key for pid 166, starting key 0 parity 1 ok 1 1
[17/11 11:45:07.761 AD2]: get_active_key: Invalidating key 0, parity 1, as the CW expired, pid 166
[17/11 11:45:07.762 AD2]: get_active_key: trying next key for pid 166, key -1 parity -1 ok -1 -1
[17/11 11:45:07.762 AD2]: get_active_key: returning NULL for pid 166, starting key 0
[17/11 11:45:07.762 AD2]: get_active_key: searching key for pid 117, starting key 0 parity 1 ok 1 0
[17/11 11:45:07.762 AD2]: get_active_key: trying next key for pid 117, key -1 parity -1 ok -1 -1
[17/11 11:45:07.762 AD2]: get_active_key: returning NULL for pid 117, starting key 0
[17/11 11:45:07.762 AD2]: get_active_key: searching key for pid 116, starting key 0 parity 1 ok 1 0
[17/11 11:45:07.762 AD2]: get_active_key: trying next key for pid 116, key -1 parity -1 ok -1 -1
[17/11 11:45:07.763 AD2]: get_active_key: returning NULL for pid 116, starting key 0
```

Then my question is: What is the sense of the key "-1". I understand the values "1" and "0", but not the value "-1".

Please, can you explain it?
Thank you!

**Comment by catalinii** [comment]
Hi Lars,

will close this. We can discuss in #337 

Thanks
