### ISSUE TITLE
DVB-API freezes

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#204]
Hi,

This is a very annoying bug! I'm trying to found the origin, but I need your help.

Description of the issue:

- You use minisatip with "-t" and Oscam server. You select some channel, and do some channel surfing. When you select one channel that Oscam can't decrypt (by any reason), then any change to another encrypted channel... never will use the DVB-API.

I discover this problem, and I can confirm that the Oscam don't receive any further ECM o command from the client (=minisatip). Also, in the LOG of the minisatip no new "key" messages appears. Also, if you change to another channel that before you can decrypt. The only solution in this case is restart the minisatip process.

Please, can you instruct me where to search for this bug?
My feel is that the code that uses the "-t" command has some bug. In any case I suggest to add some tag (for example "OSCAM:") to log lines that implies messages to/from the Oscam server. Perhaps with this will be more easy to discover and fix errors related to decrypting.

What is your feeling?

**Comment by catalinii** [comment]
Hi,

Please attach a log with -l 5 times.

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

The log is HUGE. Any idea where to search first?

**Comment by catalinii** [comment]
Better send it to me I am not excluding some lock problems.

**Comment by lars18th** [comment]
Hi @catalinii ,

I do extensive testing, and logs are large. But I have the info for reproducing the error, and info about where is the problem.

First my results: Please, see this partial log:

```
[28/12 09:25:01.58179 AD2]: returning new key 0 for adapter 2, pmt pid 1024 sid 4C41
[28/12 09:25:01.58179 AD2]: Sending pmt to dvbapi server for pid 1024, Channel ID 4C41, key 0, using socket 12


[28/12 09:33:24.460646 AD2]: returning new key 0 for adapter 2, pmt pid 1044 sid 0000
[28/12 09:33:24.460646 AD2]: Sending pmt to dvbapi server for pid 1044, Channel ID 0000, key 0, using socket 12


[28/12 09:34:12.508340 AD2]: returning new key 1 for adapter 2, pmt pid 1030 sid 4C41
[28/12 09:34:12.508340 AD2]: Sending pmt to dvbapi server for pid 1030, Channel ID 4C41, key 1, using socket 12
```

You can see here the tunning of a crypted channel and the command sended to Oscam. Then a change to a channel that "freezes". And last the return to the first channel. Where is the problem? You request the ChannelID=0000 to the Oscam server... and after that, any new requests to the Oscam server from minisatip don't work.

Then how to reproduce this error:

1) Start new minisatip instance with the parameter "-t".
2) Tune the channel SID=30800 in Astra 19.2 10729V (first crypted channel in first transponder).
3) Wait until you show the channel.
4) Change to channel SID=30820 in the same transponder (last channel in this transponder, only active time to time but visible in the PAT table).
5) Retune the first channel.

You can check that after the step "4" any new request from minisatip fails if the channel is encrypted (you can tune any FTA channel without problems). The only solution after this "freeze" is restart the minisatip.

I hope you can fix this (not request ChannelID=0000).
Regards!

**Comment by lars18th** [comment]
Hi @catalinii ,

Here my patch for a workaround of this bug:

```
dvbapi.c:
@929:         int key, pid = spmt->pid;
     +        if ((spmt->sid < 1) || (spmt->sid > 65535))
     +                 return;
@930:         p = find_pid(ad->id, pid);
```

I hope you agree!

**Comment by lars18th** [comment]
Hi @catalinii ,

You agree to incorporate my patch?

Regards!

**Comment by lars18th** [comment]
Hi @catalinii ,

Please, don't think that this issue is related to #199. It's really a different one! The re-ask after NULL is one thing, and this bug is related to ask incompatible sid value (0 is out of range) to the Oscam server. Please, add my workaround to your code, or review it for not selecting 0 as sid value.

Regards!

**Comment by catalinii** [comment]
So the issue was that the SID detection was broken for PMTs that are bigger than 1 packet.
I have also added the test with a log message in tables.c.

Thank you :)

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you for fix this issue! Is working like a charm. I close it.
