### ISSUE TITLE
xml missing crlf

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#22]
beteen modelName and modelName

**Comment by catalinii** [comment]
Done,

btw, how is for you vdr ?

**Comment by 9000h** [comment]
I use VDR http://www.tvdr.de since the beginning in 2000 with the http://www.vdr-wiki.de/wiki/index.php/DVB-S_full-featured-Karten at this time now Digital-Devices DVBS2 cards with "yavdr" distri.
