### ISSUE TITLE
RFE: Compile without LINUX DVBAPI (external tuners only)

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#227]
Hi,

At time it's possible to use minisatip without any tuner device, as it can manage external tuners. Current implementation suports SAT>IP servers and REEL Netceivers (soon more!).

Then, why not include support for external tuners only? In this form, minisatip will don't have any kernel dependencies... you can compile static and for any platform.

Hopefully, I'm developed a patch for this. See:
http://github.com/lars18th/minisatip/commit/a2cf560613fab98f6ef10dd5dbc3f71ad0d51f9f

I hope Catalin likes to merge this patch. As a general description:

* A new environment var DISABLE_LINUXDVB controls if you like to compile without Linux DVBAPI.

* When you disable the DVBAPI in the logs the version is 0000 (relevant for checking that internal tuners are disabled).

* The code mainly disables all unused functions for internal adapters. However, I need to maintain the file "dvb.c" when compiling without Linux DVBAPI as some tool functions are used on other parts of the code. I suggest to do some code refactoring for move these functions to "utils.c".

* If you develop support for any external tuner, or are doing some testing with external devices, I suggest to compile without Linux DVBAPI. Why? Because you can check if this implementation works right (I need testers). Also the unused code can't create interferences with your external tuners. And more interesting, you can assert that no kernel dependent code is used in your code (take note about the included DVB declarations, as they correspond to API 5.4... mainly code as you have DVBAPI 5.0).

I hope you like it! :)

**Comment by catalinii** [comment]
The patch sounds good and I have accepted as I think is a good idea...

**Comment by lars18th** [comment]
Ok. Now we need that some other people checks it on several devices... Please!

**Comment by catalinii** [comment]
Closing this as no issues reported.

Thanks
