### ISSUE TITLE
RFE: Reconnect to OSCAM server when rebooted

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#228]
Hi,

I do this test:

* Open some encrypted channel using a SAT>IP client through minisatip.
* Wait until the channel is played, then using the Oscam GUI I select "reboot".

After that, minisatip don't reconnect to the Oscam server. Please, can you try to reconnect when the server fails?

Thank you!

**Comment by lars18th** [comment]
Hi @catalinii ,

Please, can you do something about this? I suggest to try it: execute minisatip and when running, restart the oscam server (using the gui command). When you done it, minisatip reconnects?

Regards!

**Comment by catalinii** [comment]
Hi Lars,

try now.

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you! Trouble fixed: now when Oscam reboots, minisatip try to reconnect and reask for the current key! Then, you can continue viewing the same channel (with the logical time in black while restart) without need to do any channel change.

Great! ;)
