### ISSUE TITLE
Drop explicit frontend selection ("fe=x") in satipc.c

### ISSUE THREAD

**Issue by HellGL** [catalinii/minisatip#234]
Hi @catalinii,
great work! I already posted this comment in the comments to issue [#109](https://github.com/catalinii/minisatip/issues/109) but I think it is better to open a new one.
I am trying to run minisatip on a Atom based NAS (Synology DS-710+) together with an oscam server in order avoid decryption on my Raspberry Pi2. However it did not work from the start and I think I found out why:
According to the SAT>IP specs the frontend parameter "fe=x" is optional or even not recommended: 

>In normal operation SAT>IP clients should not specify a particular frontend in their requests.

The problem is if minisatip is one of several clients of another SAT>IP server selecting a specific frontend starting with 1 often fails. If I comment line 410

`satipc.c:410: // FILL("&fe=%d", ad->satip_fe, 0, ad->satip_fe);`

the frontend is automatically chosen by the SAT>IP server and everything works fine. Is there a good reason to specify a frontend?

While thinking about it: Maybe it would make sense to specify the frontend as optinal parameter to the "-s" or and additional option: This would make it possible to set up a fully managed system where each tuner receives a fixed transponder (so also the other tuning parameter like frequency, source and polarity must be specified) and minisatip could serve these transponders to many clients.

**Comment by catalinii** [comment]
Hi,

I think a parameter should be added as the needs of different people are different.

What setup do you have ?

Thanks

**Comment by HellGL** [comment]
Hi,
I have a GSS Box DSI 400 and various clients (iPad, iPhone, RPi2 with vtuner). In a simple setup the "fe=x" should not be needed but I agree that there might be situations where a user should be able to select a specific frontend, but if none is specified the parameter should be left out and the frontend will be selected automatically by the server.

**Comment by catalinii** [comment]
Check now...
