### ISSUE TITLE
RFE: Help with "Build information"

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#242]
Hi,

I suggest to put a simple enhancement in minisatip. See here the output of the mumudvb tool:

```
MuMuDVB Version 1.7.1
 --- Build information ---
Built with CAM support.
Built without transcoding support.
Built with ATSC support.
Built with ATSC long channel names support.
Built with support for DVB API Version 5.
---------
```

As more and more minisatip will implement optional compilation options (satip client, netceiver, static, dvbcsa, etc.) why not put this info inside the help header?

Perhaps a cosmetic enhancement, but interesting, or not?

Also, please, when run minisatip without any parameter, please, print the help output and not run the tool. This is more user-friendly.

**Comment by catalinii** [comment]
I think it sounds good, and I need to add a configure script soon as depending on the setup there could be different configuration, so when I will do that, I will add this  too...

Thanks

**Comment by catalinii** [comment]
Done in the last commit...

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you! Working like a charm. ;)

Before close this issue, one suggestion:

- Please, split "help" in two parts like:

HEADER
```
minisatip version 0.5.43, compiled with s2api version: 0504
[30/03 04:08:06.195 main]: Built with dvbcsa
[30/03 04:08:06.195 main]: Built with dvbapi
[30/03 04:08:06.195 main]: Built with AES (OpenSSL)
[30/03 04:08:06.195 main]: Built with tables processing
[30/03 04:08:06.195 main]: Built with satip client
[30/03 04:08:06.195 main]: Built with linux dvb client
[30/03 04:08:06.195 main]: Built with backtrace
[30/03 04:08:06.195 main]: Built without netceiver

./minisatip [-[fgltz]] [-a x:y:z] [-b X:Y] [-c X] [-d A:C-U ] [-D device_id] [-e X-Y,Z] [-i prio]
            [-[uj] A1:S1-F1[-PIN]] [-m mac][-o oscam_host:dvbapi_port] [-p public_host] [-r remote_rtp_host]
            [-R document_root] [-s [DELSYS:]host[:port] [-u A1:S1-F1[-PIN]] [-w http_server[:port]]
            [-x http_port] [-X xml_path] [-y rtsp_port]
```

and the HELP BODY

```
Help
-------
...
```

Also, then add the option if you execute it with an unkown parameter (like '-?') to print the first part of the help. That is, only print the FULL help when you request it (with '-h').

You agree?

Note: Also, why not print the first part (header help) when you run it wihtout parameters?

**Comment by catalinii** [comment]
Hi ...

I think the behaviour wothout parameters is just to run....not request reading the help if there is no need to.

Please reopen or open a new one if you have any suggestions.

Thanks
