### ISSUE TITLE
dvbapi issue unknown operation

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#244]
with the todays git 0.5.24 and oscam r11211 some error get logged
 dvbapi: unknown operation: 40 0C 6F 88 00 00 00 00 00 00 00

**Comment by catalinii** [comment]
Hi,

It seems is CA_SET_DESCR_MODE.

We can link this to #191.

Thanks

**Comment by catalinii** [comment]
Hi,

I will close this once I will start working on #191 I will include this too (which hopefully will be soon).

Thanks
