### ISSUE TITLE
recipe for target 'utils.o' failed

### ISSUE THREAD

**Issue by pbriesch** [catalinii/minisatip#247]
Hi, there is a compile error:

----
cc -ggdb -fPIC  -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -c -o adapter.o adapter.c
cc -ggdb -fPIC  -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -c -o utils.o utils.c
utils.c:633:3: error: ‘dvbapi_sym’ undeclared here (not in a function)
   dvbapi_sym,
   ^
Makefile:105: recipe for target 'utils.o' failed
make: *** [utils.o] Error 1

**Comment by catalinii** [comment]
Thanks Paul, try now.

**Comment by pbriesch** [comment]
:+1:
