### ISSUE TITLE
Status page not accessible

### ISSUE THREAD

**Issue by pbriesch** [catalinii/minisatip#254]
Hi,

I cannot access the status page at  http://IP:8080

Regards, Paul

**Comment by catalinii** [comment]
Hi Paul,

can you provide a log please?

Thanks

**Comment by 3PO** [comment]
same here:

...
Feb 20 10:33:26 [minisatip] read HTTP from 8 sid: -1:
Feb 20 10:33:26 [minisatip] Could not open file html//status.html
....

**Comment by catalinii** [comment]
Can you confirm you are in the directory with the sources?

minisatip is trying to open html/status.html.

**Comment by pbriesch** [comment]
Well, I couldn't look into the log, yet.
However I found out, that Safari on the Mac cannot open the status page. Firefox and Chrome do not have this problem.

**Comment by 3PO** [comment]
I can find the Status.hlml here:

```
vdr01_64 ~ # curl http://192.168.177.11/minisatip/status.html
<html>
<title>Test</title>
<body>Freq $ad_freq0$, SR $ad_sr0$, Strength $ad_strength0$ SNR $ad_snr0$ pids=$pids0$ <br>
Freq $ad_freq1$, SR $ad_sr1$, Strength $ad_strength1$ SNR $ad_snr1$ pids=$pids1$ <br>
Stream 0 enabled $st_enabled0$ rhost: $st_rhost0$:$st_rport0$ <br>
Stream 1 enabled $st_enabled1$ rhost: $st_rhost1$:$st_rport1$ <br>
</body>
</html>
vdr01_64 ~ #
``` 

The path on the Server is:

```
server02 ~ # ll /var/www/localhost/htdocs/minisatip
insgesamt 76
drwxr-xr-x 2 root root  4096 11. Sep 21:56 .
drwxr-xr-x 5 root root  4096 11. Sep 21:56 ..
-rw-r--r-- 1 root root  1242 11. Sep 21:56 desc.xml
-rw-r--r-- 1 root root 10268 11. Sep 21:56 lr.jpg
-rw-r--r-- 1 root root 36793 11. Sep 21:56 lr.png
-rw-r--r-- 1 root root  2601 11. Sep 21:56 sm.jpg
-rw-r--r-- 1 root root  6694 11. Sep 21:56 sm.png
-rw-r--r-- 1 root root   355 11. Sep 21:56 status.html
server02 ~ #
```

Is this correct?

**Comment by 3PO** [comment]
i have installed the minisatip binary to /usr/bin.
Is there a way to configure minisatip, where to find the html directory?

**Comment by catalinii** [comment]
-R path.

**Comment by 3PO** [comment]
THX, now it's working.

![2016-02-20_135253](https://cloud.githubusercontent.com/assets/945108/13196838/891274f6-d7da-11e5-91a3-59527b980a0f.png)

But sometimes, i get issuses like this:

![2016-02-20_135200](https://cloud.githubusercontent.com/assets/945108/13196839/904b1a0c-d7da-11e5-94cc-80e51fb68179.png)

**Comment by catalinii** [comment]
Yeah, some other users reported the same issue... I will look into it...

Thanks

**Comment by pbriesch** [comment]
Works now on Safari.

Thank you!

**Comment by pbriesch** [comment]
The status page doesn't load with Safari on the Mac (OS X El Capitan Public Beta 7).
Chrome and Firefox work fine.
On iOS 9.3 Safari works fine as well.

**Comment by vdrtuxnet** [comment]
Hi,

I can not confirm this, on my Mac the status load without issues.
[OS X El Capitan - 10.11.3 / Safari - 9.0.3 (11601.4.4)]

**Comment by REELcoder** [comment]
Hi,
Safari 10 is not anymore able to show the statuspage. The JS seems to be blocked. In the Inspector of Safari, I have the following error:

[Error] Blocked script execution in 'http://core:8080/#0' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. (core, line 6, x2)

Any ideas? 

Cheers

**Comment by 9000h** [comment]
not sure what happen here, on macos sierra I do not have any issue with safari
do you have any plugins like AdBlock Plus, if yes try to deactivate it

**Comment by REELcoder** [comment]
Yes Sierra here as well... AdBlock is deactivated, no success. No problem with el capitain. Firefox and others work fine.

**Comment by 9000h** [comment]
did you check also the preferences if JavaScript is enabled or disabled  in Safari

**Comment by REELcoder** [comment]
Yes, JavaScript is enabled. This seems to be a very rare problem. Before updating to Sierra there was no problem.

**Comment by REELcoder** [comment]
shame on me... Safari restarted, now it works...

**Comment by 9000h** [comment]
could it be closed?

**Comment by catalinii** [comment]
Yes
