### ISSUE TITLE
oscam get's wrong pid after some time

### ISSUE THREAD

**Issue by holli73** [catalinii/minisatip#259]
hello,

after some time some channels are not de-crypted anymore because minisatip is sending wrong caid for de-crypt ?

```
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 PMT update for decoding of SRVID 132F!
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 continue decoding of SRVID 132F
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 0 CAID: 0648 ECM_PID: 0078 PROVID: 000000
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 1 CAID: 0650 ECM_PID: 007A PROVID: 000000
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 2 CAID: 0D95 ECM_PID: 010E PROVID: 000000
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 3 CAID: 0D98 ECM_PID: 0110 PROVID: 000000
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 4 CAID: 0500 ECM_PID: 01CD PROVID: 051900
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 5 CAID: 09C4 ECM_PID: 01E0 PROVID: 000000
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 6 CAID: 098C ECM_PID: 01EA PROVID: 000000
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 stream Reserved(type: 8c pid: 01ea length: 0)
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 found 7 ECMpids and 1 STREAMpids in caPMT
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 serving srvid 132F (0648@000000:132F unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 PMT update for decoding of SRVID 132F!
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 continue decoding of SRVID 132F
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 0 CAID: 0648 ECM_PID: 0078 PROVID: 000000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 1 CAID: 0650 ECM_PID: 007A PROVID: 000000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 2 CAID: 0D95 ECM_PID: 010E PROVID: 000000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 3 CAID: 0D98 ECM_PID: 0110 PROVID: 000000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 4 CAID: 0500 ECM_PID: 01CD PROVID: 051900
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 5 CAID: 09C4 ECM_PID: 01E0 PROVID: 000000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 ecmpid 6 CAID: 098C ECM_PID: 01EA PROVID: 000000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 stream Reserved(type: 8c pid: 01ea length: 0)
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 found 7 ECMpids and 1 STREAMpids in caPMT
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 serving srvid 132F (0648@000000:132F unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0000

```

 ok case after restart minisatip:

```

2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0648 ECM_PID: 0078 PROVID: 000000 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0650 ECM_PID: 007A PROVID: 000000 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0D95 ECM_PID: 010E PROVID: 000000 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0D98 ECM_PID: 0110 PROVID: 000000 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 4 CAID: 0500 ECM_PID: 01CD PROVID: 051900 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 5 CAID: 09C4 ECM_PID: 01E0 PROVID: 000000 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 ecmpid 6 CAID: 098C ECM_PID: 01EA PROVID: 000000 
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 stream Reserved(type: 8c pid: 01ea length: 0)
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 found 7 ECMpids and 1 STREAMpids in caPMT
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 serving srvid 132F (0648@000000:132F unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0000
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 trying to descramble PID 2 CAID 0D95 PROVID 000000 ECMPID 010E ANY CHID PMTPID 0000 VPID 0000
2016/02/22 21:11:33 093CA5B0 c      (ecm) anonymous (0D95@000004/0000/132F/B8:F9DA2F87259694FFBA3E5034B9AB2C36): found (126 ms) by orficecard-2 (P/2/2/2) - ORF1 HD
```

**Comment by catalinii** [comment]
Hi holli73,

can you highlight where the wrong pid in the log or what do you see wrong with the log?

Thanks

**Comment by holli73** [comment]
hello,

i'm not sure what is wrong - but i have a DVBAPI definition with:

```
P: 0D95 1 # ORF ICE
P: 1843 1 # HD plus
P: 09C4 1 # Sky HD V13

I: 0
```

all my old sat boxes (coolstream) are connecting to the same server and are always asking for the CAID only defined - for a reason i don't know oscam can not descramble anymore 

in a good case 0648 gets matched to

```
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 serving srvid 132F (0648@000000:132F unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0000
2016/02/22 21:11:33 093CA5B0 c   (dvbapi) Demuxer 0 trying to descramble PID 2 CAID 0D95 PROVID 000000 ECMPID 010E ANY CHID PMTPID 0000 VPID 0000
2016/02/22 21:11:33 093CA5B0 c      (ecm) anonymous (0D95@000004/0000/132F/B8:F9DA2F87259694FFBA3E5034B9AB2C36): found (126 ms) by orficecard-2 (P/2/2/2) - ORF1 HD
```

and all is OK -> all my other oscam clients will initiate already the request with 0D95 and not 0648...

and in the bad case i get

```
2016/02/22 21:07:12 093CA5B0 c   (dvbapi) Demuxer 1 serving srvid 132F (0648@000000:132F unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0000
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 PMT update for decoding of SRVID 132F!
2016/02/22 21:07:14 093CA5B0 c   (dvbapi) Demuxer 1 continue decoding of SRVID 132F
```

but no descramble - once i restart minisatip - all works fine again (apx. after 2-3 day's this occurs).

hope this makes sense

best regards
holli

**Comment by 3PO** [comment]
CAID 0D95 is NOT(!) ORF ICE, 0648 is ORF ICE!

**Comment by holli73** [comment]
hello,

my cards are green and have ICE on it - on card init i get:

```
2016/02/26 22:38:59 66C80765 r   (reader) orficecard-2 [mouse] card detected
2016/02/26 22:38:59 66C80765 r   (reader) orficecard-2 [mouse] type: CryptoWorks
2016/02/26 22:38:59 66C80765 r   (reader) orficecard-2 [mouse] type: CryptoWorks, caid: 0D95, ascii serial: #########, hex serial: ##########
2016/02/26 22:39:00 66C80765 r   (reader) orficecard-2 [mouse] issuer: CryptoWorks, id: 04, bios: v3, pin: unknown, mfid: 3F00
2016/02/26 22:39:00 66C80765 r   (reader) orficecard-2 [mouse] providers: 4 (04,08,0C,10)
2016/02/26 22:39:00 66C80765 r   (reader) orficecard-2 [mouse] found card system cryptoworks
2016

```
sorry - but this works since years that way - before i had 0D05 cards and those were changed to the once i have now...

best regards
holli

**Comment by 3PO** [comment]
0D05 is Cryptoworks, not ICE!

**Comment by holli73** [comment]
hello,

but this cards i have now have ICE on it and in oscam they are found as:

type: CryptoWorks, caid: 0D95

the 0D05 are not working anymore and got replaced by the ICE ones i have now with 0D95 - if they are not ICE but something else i don't know - but this is just a label in the config file i could just write ORF if this is better - but for a reason i don't know minisatip provided CAID is not descrambled anymore see above and all my other oscam clients on native sat boxes are all sending 0D95 and not 0648 because i don't have a 0648 card...

best regards
holli

**Comment by akawi** [comment]
it's oscam problem , use old version better , or try to restart your box/pc/oscam until it's fixed
if you see a lot of 
(dvbapi) Demuxer ......
(dvbapi) Demuxer ......

 , so restart again 

until you see
found (126 ms)
found (126 ms)
found (126 ms)


and please can you help here 
https://github.com/catalinii/minisatip/issues/270

**Comment by catalinii** [comment]
try to see if the latest commit makes any difference.

Thanks

**Comment by holli73** [comment]
hello,

i updated today - so i will let you know

thanks
holli

**Comment by holli73** [comment]
hello,

i looks a bit better but i still have issues f.ex.

```
2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0D98 ECM_PID: 09C5 PROVID: 000000 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 0650 ECM_PID: 09C6 PROVID: 000000 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0D95 ECM_PID: 09C7 PROVID: 000000 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0648 ECM_PID: 09C8 PROVID: 000000 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 4 CAID: 098C ECM_PID: 0A30 PROVID: 000000 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 5 CAID: 09C4 ECM_PID: 0A3A PROVID: 000000 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 ecmpid 6 CAID: 0500 ECM_PID: 0A47 PROVID: 051900 
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 stream Datastream (MPEG-2 tabled data)(type: 05 pid: 1900 length: 0)
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 found 7 ECMpids and 1 STREAMpids in caPMT
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 serving srvid 33FD (0D98@000000:33FD unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0000
2016/03/04 20:03:37 2AFFA33D c   (dvbapi) Demuxer 0 trying to descramble PID 2 CAID 0D95 PROVID 000000 ECMPID 09C7 ANY CHID PMTPID 0000 VPID 0000
2016/03/04 20:03:37 2AFFA33D c      (ecm) anonymous (1843@000000/0000/2E9B/89:672662C659283CDB249250B7048E906E): found (381 ms) by hdplus - Super RTL HD
** 2016/03/04 20:03:37 2AFFA33D c      (ecm) anonymous (0D95@000004/0000/33FD/B8:606911B0A9AB86C0D17994A732FF42A0): cache1 (0 ms) by orficecard-2 (cw count 2)
2016/03/04 20:03:40 2AFFA33D c      (ecm) anonymous 
2016/03/04 20:03:44 2347398A c      (ecm) mbclark (0D95@000004/0000/33A5/B8:51DF4D93859ABC7DFCE58C421ECF2AFB): found (127 ms) by orficecard-2 (P/2/2/2) - ORF Sport +

```
so here you can see that ORF sport + is served on my other clients at od95 with 33a5 but minisatip comes in with 0648 and 33FD - oscam still is able to match this to pid2 and decrypt see line with ** but not picture/video on tv is streamed...

maybe the dvbapi client should have a oscam.dvbapi config as well where all available CAID's are specified so the minisatip implementation already send the correct caid?

i'm not familiar with the protocol here but i do not get all channels working - f.ex. in tvh i can define a default CAID for channels if the wrong one is choosen...

best regads
holli

**Comment by akawi** [comment]
Hi,
can you add a user name in oscam.conf  [dvbapi]
user                          = holli

and in oscam.user 

put same user

[account]
user                          = user
group                         = 1

so the oscam can read correctly the oscam.dvbapi file

PS: i still not understand how you activate satip with tvh , because i find adapter in tvh from minisatip
Regards

**Comment by holli73** [comment]
hello,

configuration/general/sat-ip server...


<img width="451" alt="tvh-satip" src="https://cloud.githubusercontent.com/assets/1434090/13550478/e0a19efa-e31e-11e5-85a4-328959be1eb4.png">

**Comment by catalinii** [comment]
Uncomment dvbapi.c line 681 and compile it and see if it makes any difference.

This will disconnect from oscam once no channel is active and reconnect when there are active channels.

Thanks

**Comment by holli73** [comment]
hello,

i enabled the code line -> rebuild it - and let you know the result

thanks
holli

**Comment by holli73** [comment]
hello,

with the latest pull minisatip is not working anymore on crypted channels (regardless if the line 681 is enabled or not) further i have a job which checks the webinterface every minute and if no response within 5 second - it kill's minisatip and restarts - with the latest pull the webinterface is not responding at all... (even in chrome)

i had to go back to a515474cf8501f0f967d226f704c2bb39eb4254b commit - all looks ok again but with the latest i can not get it to work.

best regards
holli

**Comment by catalinii** [comment]
Test with the line uncommented on a515474... 

About the latest commit can u upload a log?

Thanks

**Comment by holli73** [comment]
hello,

with how many -l ?

best regards
holli

**Comment by catalinii** [comment]
3 is ok

**Comment by holli73** [comment]
hello,

i did zap on crypted channels - no video - and one channel with no need for crypt - worked fine - but the webinterface did not show up and was the last thing before ctrl-c.

best regards
holli
[mlatest.txt](https://github.com/catalinii/minisatip/files/160332/mlatest.txt)

**Comment by catalinii** [comment]
Hi,

I don't see any dvbapi message in the log... are you sure is compiled with DVBCSA=yes and you run it with -o ?

Thanks

**Comment by holli73** [comment]
hello,

yes - i did not change something withing my makefile:

```
hts@fernsehen:~/minisatip$ cat Makefile
CC?=gcc
EMBEDDED?=no
DVBCSA?=yes
DVBCA?=no
SATIPCLIENT?=yes
NETCVCLIENT?=no
STATIC?=no
LINUXDVB?=yes
```
and the start command is:

`root     25749     1  1 Mar06 ?        00:41:46 /home/hts/minisatip/minisatipx --dvbapi 192.168.250.55 1234 -e 4-7
`

so i'm not using the -o instead --dvbapi
if i use the git reset the same files/start command works...

thanks
holli

**Comment by catalinii** [comment]
Try 
make clean;make 

You should see some messages with dvbapi.

I tried both -o and --dvbapi and works for me.

Thanks

**Comment by holli73** [comment]
hello,

since the last pull it works as expected - never mind - but i still have an issue with not getting all channels available:

i have a dvbapi on my oscam for this 3 cards:

```
P: 0D95 1 # ORF ICE
P: 1843 1 # HD plus
P: 09C4 1 # Sky HD V13
I: 0
```
but with minisatip i get some channels not to decode - f.ex:

```
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 09C4 ECM_PID: 1BC6 PROVID: 000000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 1 CAID: 098C ECM_PID: 1AC6 PROVID: 000000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 2 CAID: 0D95 ECM_PID: 1FC7 PROVID: 000000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 3 CAID: 0648 ECM_PID: 1FC8 PROVID: 000000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 4 CAID: 0D98 ECM_PID: 1FC9 PROVID: 000000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 5 CAID: 0650 ECM_PID: 1FCA PROVID: 000000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 ecmpid 6 CAID: 0500 ECM_PID: 1DC6 PROVID: 051900
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 stream Datastream (MPEG-2 tabled data)(type: 05 pid: 1900 length: 0)
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 found 7 ECMpids and 1 STREAMpids in caPMT
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 serving srvid 4462 (Kabel1 Classics) on adapter 0000 camask 0001 index 0000 pmtpid 0000
2016/03/25 14:43:44 1657E19F c   (dvbapi) Demuxer 0 impossible to descramble PID 2 CAID 0D95 PROVID 000000 ECMPID 1FC7 PMTPID 0000 (NO MATCHING READER)
```

if i change the order and put 09C4 on top - this channel is working but the ORF (0D95) not anymore!!
on my tvh server i could define prefered CAID for channels but how would i do this with minisatip?

any idea?

thanks
holli

**Comment by catalinii** [comment]
Hi,

I saw tvh sends the caids and providers stored internally as opposed  to minisatip which sends the all the CA information from the PMT.

Just out of curiosity does it work with vdr-plugin-dvbapi?

Thanks

**Comment by holli73** [comment]
hello,

sorry i can not try - i use the tvh mainly for my iphone/ipad's and on my panasonic tv's (satip) before minisatip - i would like to use minisatip instead of tvh-satip server (because tvh - crashes too often) .
so i don't have a xbmc running at the moment - but i could try to use kodi on my macbook with this plugin?

or where should i use the vdr-plugin-dvbapi?

i have physical satboxes (coolstream's) where i use the oscam just as client an connecting to the same oscam server but this are sending the correct CAID's as well without need for a prefered CAID...

hope this makes sense

best regards
holli

**Comment by catalinii** [comment]
Hi hollli,

I think the best way forward is to check http://www.streamboard.tv/wiki/OSCam/en/Config/oscam.dvbapi to prioritize your provider id.

From minisatip without duplicating oscam the functionality I cannot do too much.

Thanks

**Comment by holli73** [comment]
hello,

i modified my dvbapi file on my oscam server - leave it here if someone else needs this information as well - how to force special service on a CAID

```
P: 09C4::4462 1 #kabel1 classics on sky v13
P: 0D95 1 # ORF ICE
P: 1843 1 # HD plus
P: 09C4 1 # Sky HD V13
I: 0
```

best regards
holli
