### ISSUE TITLE
[New] Statupage Next Generation

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#265]
A friend of of mine has made the statuspage a litle bit prettier:

![2016-02-28_084934](https://cloud.githubusercontent.com/assets/945108/13378814/bf260b28-de12-11e5-84d5-11244fe1b21c.png)

https://github.com/NemoN/minisatip

**Comment by NemoN** [comment]
WIP Version...

**Comment by catalinii** [comment]
Thanks .... It looks better :)

**Comment by 9000h** [comment]
looks good but with some glitches
var ad_allsys	= ["dvbc2,dvbc", "dvbc2,dvbc", "dvbc", "dvbc", "dvbs,dvbs2,dss", "dvbs,dvbs2,dss", "dvbs,dvbs2,dss", "dvbs,dvbs2,dss", "dvbt", "", "", "", "", "", "", "" ];
the icons may got not selected right
![screen shot 2016-02-28 at 13 25 19](https://cloud.githubusercontent.com/assets/3009073/13379175/12cc943e-de1f-11e5-8589-ddfca8a7a1dd.png)

**Comment by NemoN** [comment]
thanks for the report, currently its a beta version.
please report issues at https://github.com/NemoN/minisatip/issues
(please include html source of status.html - for debugging purposes)

**Comment by 3PO** [comment]
Is it possible, to add Parameters for showing CAID, Channelname, Provider and orbital Position?

**Comment by 9000h** [comment]
for the Orbital position the NIT needs to be filtered and for the channel name the SDT, not sure if this is really needed but it's possible.

**Comment by jmendeth** [comment]
That looks great! I recently created [another one](http://codepen.io/jmendeth/full/RabOXy), for special cases where there is only one tuner:

![Test screenshot](https://cloud.githubusercontent.com/assets/1177304/13392634/3bb14864-dedc-11e5-8358-13ba949e10f8.png)

https://github.com/jmendeth/dm500-satip/tree/master/data/html

It also uses XHR to update the data without having to refresh the page.

**Comment by catalinii** [comment]
jmendeth, you can create a push request with status2.html which to contain your code, maybe I can make a command line parameter to switch between pages....

**Comment by NemoN** [comment]
new version online https://github.com/catalinii/minisatip/pull/278

**Comment by catalinii** [comment]
Thanks

**Comment by 3PO** [comment]
>Is it possible, to add Parameters for showing CAID, Channelname, Provider and orbital Position?

Any News?

**Comment by catalinii** [comment]
Hi,

it is possible to see CAID, Provider ID (with the current implementation) if the channel is encrypted.

Channel Name, Provider Name can be obtained by parsing the  SDT (which is not implemented). 
I am not really sure how to get the orbital position at this point...as I don't think is part of the SDT information...

**Comment by 3PO** [comment]
> I am not really sure how to get the orbital position at this point...as I don't think is part of the SDT >information...

You can find this in the "Satellite delivery system descriptor"

See: --> http://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.03.01_60/en_300468v010301p.pdf
Site 38


>**orbital_position: **The orbital_position is a 16-bit field giving the 4-bit BCD values specifying 4 
>characters of the orbital position in degrees where the decimal point occurs after the third 
>character (e.g. 019,2 degrees).

**Comment by 3PO** [comment]
Hi,
are there any News about Channel Name, Provider Name and CAID?

**Comment by catalinii** [comment]
Hi 3PO,

I will do this one with #291. Prior to this I need to do some changes in tables.c and adapter.c
Thanks

**Comment by Jalle19** [comment]
Closing this since the changes suggested here have long since been upstreamed.
