### ISSUE TITLE
how to compile it on ubuntu ?

### ISSUE THREAD

**Issue by akawi** [catalinii/minisatip#270]
Hi,
Please how to compile it on ubuntu ?
Regards

**Comment by holli73** [comment]
hello,

i just run this script:

```
#!/bin/bash

cd minisatip
info=$(git pull)
nixtodo="Already up-to-date."

if [ "$info" = "$nixtodo" ]; then
	echo "***** $info *****"
else
	make clean
	git pull
	make
fi

ps -ef|grep minisatipx
```

and i'm on ubuntu

> 
Linux fernsehen 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

what error do you get?

best regards
holli

**Comment by akawi** [comment]
i get this 
***** Already up-to-date. *****
root     24964 24930  0 22:39 pts/1    00:00:00 grep minisatipx

**Comment by holli73** [comment]
hello,

this ok - that just means that your checkout/code is already the latest - so you need to run:

within your minisatip directory:

make clean
make

and what error do you get on the make?

i use this script for my automated update (every day pull the latest stuff...) and if no changes i do not need to build...

just run the 2 command above - what error do you get?

best regards
holli

**Comment by akawi** [comment]
Thank you 

the error

~/minisatip# make
cc -ggdb -fPIC  -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -c -o minisatip.o minisatip.c
cc -ggdb -fPIC  -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -c -o socketworks.o socketworks.c
cc -ggdb -fPIC  -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -c -o stream.o stream.c
cc -ggdb -fPIC  -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -c -o adapter.o adapter.c
In file included from adapter.c:34:0:
dvbapi.h:7:27: fatal error: dvbcsa/dvbcsa.h: No such file or directory
 #include <dvbcsa/dvbcsa.h>
                           ^
compilation terminated.
make: *** [adapter.o] Error 1

**Comment by holli73** [comment]
hello,

you are missing the decryp libraries:

`sudo  apt-get install libdvbcsa-dev`

should do the trick

best regards
holli

**Comment by akawi** [comment]
Thank you 
it's ok now 
compile OK
but no idea how i can add sat>ip server , and the page web not working ip:8080

i want stream channels with minisatip + oscam for the crypted channles , is that can be done with minisatip ?

**Comment by akawi** [comment]
any help please ?

**Comment by 3PO** [comment]
"page web" <-- WTF???

**Comment by akawi** [comment]
sorry about that 
with page web i mean ( ip:8080 )
all working now 
rtsp:// Ok
http:// Ok

just the channels freeze because it's need transcode ,
you mean tvheadend can connected to minisatip and i can transcode channels in  tvheadend ?

**Comment by holli73** [comment]
hello,

> 
you mean tvheadend can connected to minisatip and i can transcode channels in tvheadend ?

yes - but if you just need it for streaming no need for minisatip - this can all be done through tvh  even tvh has now an build in satipserver...

best regards
holli

**Comment by catalinii** [comment]
Yes, there are couple of ways of doing transcoding outside of minisatip.

If you are still interested in seeing it in minisatip, please comment on #238 .
