### ISSUE TITLE
getTick() - uint32_t - wrapping discussion

### ISSUE THREAD

**Issue by perexg** [catalinii/minisatip#272]
It's just a discussion that getTick() returns 32-bit unsigned value (milliseconds). If my calculation is right, it wraps after 49 hours. If the return value is extended to 64-bit unsigned value, the wrapping is 584942417 years.

I see that the code substract the new value with old ones (time diff), so it's probably not an issue, but all code using getTick() values should be reviewed (if the checks are using values updated in less than 49 hours).

**Comment by catalinii** [comment]
Hi,

there is no good reason for which it should remain 32 bit, we can bump it to 64. I think maybe is better to keep substracting from the initial value as it will make reading internal variables easier.

Thanks
