### ISSUE TITLE
bug now

### ISSUE THREAD

**Issue by akawi** [catalinii/minisatip#274]
links working but on the status page i can't see nothing 

`0	()	undefined undefined	NaNMHZ	LEV 

SNR 

1	()	undefined undefined	NaNMHZ	LEV 

SNR 

2	()	undefined undefined	NaNMHZ	LEV 

SNR 

3	()	undefined undefined	NaNMHZ	LEV 

SNR 

4	()	undefined undefined	NaNMHZ	LEV 

SNR 

5	()	undefined undefined	NaNMHZ	LEV 

SNR 

6	()	undefined undefined	NaNMHZ	LEV 

SNR 

7	()	undefined undefined	NaNMHZ	LEV 

SNR 

8	()	undefined undefined	NaNMHZ	LEV 

SNR 

9	()	undefined undefined	NaNMHZ	LEV 

SNR 

10	()	undefined undefined	NaNMHZ	LEV 

SNR 

11	()	undefined undefined	NaNMHZ	LEV 

SNR 

12	()	undefined undefined	NaNMHZ	LEV 

SNR 

13	()	undefined undefined	NaNMHZ	LEV 

SNR 

14	()	undefined undefined	NaNMHZ	LEV 

SNR 

15	()	undefined undefined	NaNMHZ	LEV 

SNR 
`

**Comment by catalinii** [comment]
Will look into it.
Thx

**Comment by catalinii** [comment]
Try now...
Thanks

**Comment by akawi** [comment]
Fixed and now i see for each stream the source crypt
