### ISSUE TITLE
Multiple USB DVB-C adapters not working anymore

### ISSUE THREAD

**Issue by MastaG** [catalinii/minisatip#276]
Hi there,

This commit: https://github.com/catalinii/minisatip/commit/49f1bbcd533adf51d90129b418b5ac36cb73b879

Breaks multiple USB DVB-C adapters for me.
I have 3 of them and with this commit only the first one is working.
I'm starting it with:

minisatip -e 0,1,2 -x 8875 -w myserver:8875 -g --threads

And I use TVHeadend to connect with my XML.

If I revert to the previous commit, then all 3 of them work :)

**Comment by catalinii** [comment]
Hi,

Can you provide a log with -l -l -l when you try to watch a channel?

Thanks

**Comment by catalinii** [comment]
I will fix this in the next commit...

Thanks

**Comment by MastaG** [comment]
Hi there my friend,

My apologies for the late response, sundays we usually go out with the
family.
I've tried the latest master rev. and it appears to be working again :)


Do you still need a log file of it running on 3 DVB-C tuners?

2016-03-07 1:25 GMT+01:00 catalinii <notifications@github.com>:

**Comment by catalinii** [comment]
IHi,

I think I have all I need for now...

Thanks

**Comment by MastaG** [comment]
Alright, drop a message anytime you'd need some info.
Thanks a lot for the quick response and actions :)

2016-03-07 11:07 GMT+01:00 catalinii <notifications@github.com>:

**Comment by catalinii** [comment]
Hi,

let me know how is it now.

Thanks
