### ISSUE TITLE
BUG: Malformed SSDP messages

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#277]
Hi @catalinii ,

Two of the SSDP messages have wrong end, and some tools discard these messages.
I found the messages, and I suggest the fix. See these two lines:

http://github.com/catalinii/minisatip/blob/master/minisatip.c#L1035
http://github.com/catalinii/minisatip/blob/master/minisatip.c#L1041

Both messages are ended with a simple '\r\n'. But the standard enforces to use double ended (like the rest of SSDP messages, for example in minisatip.c#L984).

So, please, can you fix the code with using '\r\n\r\n' ?
Thank you! ;)

**Comment by catalinii** [comment]
Done,

thanks

**Comment by lars18th** [comment]
Thank you!
