### ISSUE TITLE
info: client app

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#280]
there is a new Android SAT>IP App that work also with minisatip "Auroa TV"

**Comment by lars18th** [comment]
Hi @9000h ,

"Aurora TV" is still ALPHA software. It only works with HTTP transport, and not using RTP.

I hope some other developers like to develop a good Android SAT>IP client App. The best at time is the one from Elgato, but it lacks HD support (only MPEG-2 SD).

**Comment by 9000h** [comment]
alt least German FTA HD Channels do work with "Aurora TV" actually

**Comment by lars18th** [comment]
Thank you, @9000h !

I discovered the last (and improved) version today. I'm testing it now, as I have SAT>IP & HDHomeRun in my home, so it seems to be perfect. However, at time, it has some troubles.

Regards!

**Comment by catalinii** [comment]
Hey guys,

I will close this as well, if you have any issues with Aurora TV let me know.

Thanks
