### ISSUE TITLE
compile error since netceiver support

### ISSUE THREAD

**Issue by rucati** [catalinii/minisatip#282]
Hi,
Since netceiver-support, I cannot compile minisatip for openelec. 
NETCVCLIENT=no is added in the makefile.

Anyway who can point out what I'm doing wrong? I don't get the meaning of the output.
http://pastebin.com/aRRNjhXe
Thanks

**Comment by catalinii** [comment]
try now:

./configure --disable-netcv

If it does not work, please provide full configure log and make output.
Thanks
