### ISSUE TITLE
Segfault in process_dmx

### ISSUE THREAD

**Issue by srehm** [catalinii/minisatip#287]
Hello,

I am running minisatip from git version 9610663 and I am ocassionally getting the attached segfault. The first thing that comes to mind is to add a
 null check for 'sid' but I am not sure if this is the correct approach or whether there is something wrong somewhere else.

[gdb.txt](https://github.com/catalinii/minisatip/files/180869/gdb.txt)

Regards,
Stefan

**Comment by catalinii** [comment]
Hi,

Thanks for the report I will fix this in the new commit.
