### ISSUE TITLE
With parameter -s only 7 devices found

### ISSUE THREAD

**Issue by FrodoVDR** [catalinii/minisatip#288]
I have 3 SAT>IP server's and want to lead them via minisatip together.
If I configure with -s more than 7 devices only 7 found.

Example:
-a 0:0:0 -s 192.168.6.237 -s 192.168.6.237 -s 192.168.6.237 -s 192.168.6.237 -s 192.168.6.236 -s 192.168.6.236 -s 192.168.6.236 -s 192.168.6.236

The last was not found.

If I change the parameter to:
-a 0:0:0 -s dvbs2:192.168.6.237 -s dvbs2:192.168.6.237 -s dvbs2:192.168.6.237 -s dvbs2:192.168.6.237 -s dvbs2:192.168.6.236 -s dvbs2:192.168.6.236 -s dvbs2:192.168.6.236 -s dvbs2:192.168.6.236

minisatip found only 5 devices.

Why you can define no more than 7 remote SAT>IP server?

**Comment by catalinii** [comment]
Hi,

will fix this in the next commit.

I increased the size of an array that stores the satip servers....

Thanks
