### ISSUE TITLE
enhancement: dvb adpater 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#29]
I would be nice to have a cli option to specify the adapter number or a list of adapters which should be used by minisatip. If you may have some other applications running on the same machine then this is a issue.

**Comment by catalinii** [comment]
When there are no active streams, minisatip releases all the devices.
When someone asks for a device, minisatip will try to open all of them (ofc it will fail for the used ones).

I think it should play nice with other applications.

Do you have a scenario in which this does not happen ?

**Comment by 9000h** [comment]
I run VDR which allocated the adapters permanently, so maybe adapter 0 and 1 are in uses by VDR but adapter 2,3 ... are free.

**Comment by catalinii** [comment]
And do you have some issues with minisatip if you start first vdr?

**Comment by catalinii** [comment]
The thing is that minisatip locks all the adapters it could find the first 60s if u want everything to be used by minisatip

**Comment by 9000h** [comment]
here are a log with VDR running on adapter 0 and 1, 2  was free.
so it works as designed

root@yavdr:/home/yavdr/satip/minisatip-master# ./minisatip -l -l -l -f
Starting minisatip version 0.1.13, dvbapi version: 0504
[Tue Jan 20 17:35:18.000 2015]: New UDP socket 3 bound to 0.0.0.0:1900
[Tue Jan 20 17:35:18.000 2015]: setting multicast for 239.255.255.250
[Tue Jan 20 17:35:18.000 2015]: New UDP socket 4 bound to 239.255.255.250:1900
[Tue Jan 20 17:35:18.000 2015]: New UDP socket 7 bound to 0.0.0.0:5500
[Tue Jan 20 17:35:18.000 2015]: New UDP socket 8 bound to 0.0.0.0:5501
[Tue Jan 20 17:35:18.000 2015]: sockets_add: handle 3 (type 0) returning socket index 0 [0.0.0.0:0]
[Tue Jan 20 17:35:18.000 2015]: sockets_add: handle 4 (type 0) returning socket index 1 [0.0.0.0:0]
[Tue Jan 20 17:35:18.000 2015]: sockets_add: handle 5 (type 2) returning socket index 2 [0.0.0.0:0]
[Tue Jan 20 17:35:18.000 2015]: sockets_add: handle 6 (type 2) returning socket index 3 [0.0.0.0:0]
[Tue Jan 20 17:35:18.000 2015]: starting init_hw 0
[Tue Jan 20 17:35:18.000 2015]: trying to open [0] adapter 0 and frontend 0
Could not open /dev/dvb/adapter0/dvr0 in RW mode
[Tue Jan 20 17:35:18.001 2015]: trying to open [1] adapter 0 and frontend 1
Could not open /dev/dvb/adapter0/dvr1 in RW mode
[Tue Jan 20 17:35:18.001 2015]: trying to open [2] adapter 1 and frontend 0
adapter.c:103 allocation_wrapper malloc allocated 9222 bytes at 0x106ecb0
[Tue Jan 20 17:35:18.001 2015]: opened DVB adapter 2 fe:9 dvr:10
[Tue Jan 20 17:35:18.001 2015]: Done setting DVR buffer to 5775360 bytes
[Tue Jan 20 17:35:18.001 2015]: deleting pids on adapter 2, sid -1, pids=NULL
[Tue Jan 20 17:35:19.532 2015]: sockets_add: handle 10 (type 5) returning socket index 4 [0.0.0.0:0]
[Tue Jan 20 17:35:19.532 2015]: done opening adapter 2 fe_sys 1
[Tue Jan 20 17:35:19.532 2015]: done init_hw 1
Initializing with 1 devices
[Tue Jan 20 17:35:19.733 2015]: ssdp_discovery fd: 3 -> NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=1800
LOCATION: http://192.168.178.101:8080/desc.xml
NT: upnp:rootdevice
NTS: ssdp:alive 
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.13
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::upnp:rootdevice
BOOTID.UPNP.ORG: 1
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

**Comment by 9000h** [comment]
so there is only on case where is causes issues, in my test machine I have a broken dual tuner card where the dvb-s tuner is half dead.
it's a DVBSky T9580 DVB-T2/T/C and DVB-S2/S Dual PCIe

the only chance to avoid issues is to delete the device file atm

but maybe someone has similar issue with multiple cards where some adapter has simply no signal
