### ISSUE TITLE
Problem with request header

### ISSUE THREAD

**Issue by clausmuus** [catalinii/minisatip#292]
The minisatip web frontend do not answer if there is a "/?" inside the request header, e.g.:
`wget "http://minisatipserver:8080" --header="Referrer: http://minisatipserver/?" -O -`

**Comment by catalinii** [comment]
I will close this, please reopen it if it;s still an issue...

thanks

**Comment by clausmuus** [comment]
Now I have the opposite problem. If there is no "/?" in the header, the minisatip web frontend do not answer.
