### ISSUE TITLE
RFE: Change LOG of SSDP messages

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#297]
Hi,

As my suggestion in #205 has unaccepted, I suggest another similar change:

- Move all SSDP log messages to level 5 (-lllll).

At time, is impossible to make a debug in level 3 because the verbosity of the SSDP messages (mainly async messages for auto-discovering unrelated to the work of the RTSP server).

Please, @catalinii , can you accept this change? ;)

**Comment by catalinii** [comment]
Hi,

I'll move SSDP to 5 ...

Thanks

**Comment by lars18th** [comment]
Good news!
Thank you, @catalinii .

**Comment by lars18th** [comment]
Thank you @catalinii for the commit:
http://github.com/catalinii/minisatip/commit/05900ca105e5d09cb288e61cfcbec94d9170297b

I close this! :)
