### ISSUE TITLE
[REF] RESTful for minisatip

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#299]
I it posssible, to implant RESTful to minisatip?

**Comment by lars18th** [comment]
Hi,

This is already commented in #273 . Also, related to #291.
I suggest to close this entry and continue in the #273.

For sure, +1 for add some HTTP functions for controlling an stream received using "other" transport (mainly by http, but why not also rtp).

**Comment by catalinii** [comment]
Yes it is possible and it will be done, but probably later...

**Comment by Jalle19** [comment]
"RESTful" is IMO too vague here. I understand you mean some sort of API to control minisatip, but it would be better to focus on concrete use cases like the PID control mentioned in #273 

Also we've gone 5 years without this so perhaps we're doing fine without it :shrug:
