### ISSUE TITLE
Could not set pid filter : Too many open files

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#3]
When i run minisatip, i get after a while tis issue in the logfile:

>Could not set pid filter : Too many open files

Logfile:  http://dreipo.cc/logs/log.tgz

**Comment by catalinii** [comment]
Hi,

can you try now the latest commit ?

Thanks

**Comment by catalinii** [comment]
Hi,

please let me know if this is still an issue.

Thanks

**Comment by 3PO** [comment]
Hi,

it seems, this Problem is solved. :)
