### ISSUE TITLE
Clients requesting the same tp - server uses different tuners

### ISSUE THREAD

**Issue by JV16Bar** [catalinii/minisatip#300]
I don't know, if this behaviour is normal: if I connect 2 (or more) clients to my minisatip server requesting the same channel (same source, tp, etc), minisatip provides them using separate phisycal tuner for each. 
Doesn't matter if the clients are vdr instances, or vlcs.
Here is a screenshot, i slightly modified the web ui to show a column with current src:

https://s30.postimg.org/i5jdfyngh/minisatip.jpg

**Comment by catalinii** [comment]
Hi,

I know about the issue, a configuration option might be suited in order to have different behavior on this issue...

**Comment by catalinii** [comment]
HI,

try now with the latest commit.

Thanks

**Comment by JV16Bar** [comment]
Currently I have only 2 tuners available, but first test are looking good. If i select one channel, and try another channel from the same tp, minisatip always uses the same tuner.
