### ISSUE TITLE
minisatip crash

### ISSUE THREAD

**Issue by HellGL** [catalinii/minisatip#301]
Hi,
I tried to run the latest version of minisatip today and it crashes with a "RECEIVED SIGNAL 11 - SP=0 IP=0". If I run it with gdb it gives me the following output (textfile attached).
[minisatip_gdb.txt](https://github.com/catalinii/minisatip/files/231904/minisatip_gdb.txt)

If I can do more to debut, please let me know. Thank you.

**Comment by catalinii** [comment]
Hi,

If you can reproduce can you give me the output of 
bt
thread apply all bt

Thanks

**Comment by HellGL** [comment]
Yes, I can reproduce it. Unfortunately it does not give much more:

`[22/04 17:33:01.289 AD0]: satipc: Received signal status from the server for adapter 0, stength=255 status=1 snr=15
[22/04 17:33:01.291 AD0]: satipc: Received signal status from the server for adapter 0, stength=0 status=0 snr=0
[22/04 17:33:01.291 AD0]: satipc: Received signal status from the server for adapter 0, stength=255 status=1 snr=15

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5df9700 (LWP 1601)]
select_and_execute (arg=<error reading variable: Cannot access memory at address 0xfffffffffffff418>, arg@entry=<error reading variable: Cannot access memory at address 0x8>) at socketworks.c:646
646                                             sockets_unlock(ss);
(gdb) bt
#0  select_and_execute (arg=<error reading variable: Cannot access memory at address 0xfffffffffffff418>, arg@entry=<error reading variable: Cannot access memory at address 0x8>) at socketworks.c:646
Cannot access memory at address 0x8
(gdb) thread apply all bt

Thread 5 (Thread 0x7ffff5df9700 (LWP 1601)):
#0  select_and_execute (arg=<error reading variable: Cannot access memory at address 0xfffffffffffff418>, arg@entry=<error reading variable: Cannot access memory at address 0x8>) at socketworks.c:646
Cannot access memory at address 0x8
(gdb) `

**Comment by HellGL** [comment]
Maybe I should mention that I run it on a Synology NAS in a docker container. But on the other hand all other software I compiled in the container works fine including kernel modules (vtuner) and DVB applications (vdr).

**Comment by catalinii** [comment]
Hi,
Can you do in gdb:
print i
print *s[i]
up
print i
print *s[i]


Thanks

**Comment by catalinii** [comment]
Is this still reproducible ?

Thanks
