### ISSUE TITLE
crash with git from today 27.04.2016

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#303]
try to reproduce it, but no luck up to now

Apr 27 21:09:17 satip minisatip[20466]: print_trace at /usr/src/satip/minisatip/utils.c:401
Apr 27 21:09:17 satip minisatip[20466]: posix_signal_handler at /usr/src/satip/minisatip/utils.c:435
Apr 27 21:09:17 satip minisatip[20466]: ?? ??:0
Apr 27 21:09:17 satip minisatip[20466]: set_algo at /usr/src/satip/minisatip/dvbapi.c:857
Apr 27 21:09:17 satip minisatip[20466]: dvbapi_reply at /usr/src/satip/minisatip/dvbapi.c:376
Apr 27 21:09:17 satip minisatip[20466]: select_and_execute at /usr/src/satip/minisatip/socketworks.c:646
Apr 27 21:09:17 satip minisatip[20466]: main at /usr/src/satip/minisatip/minisatip.c:1308
Apr 27 21:09:17 satip minisatip[20466]: ?? ??:0
Apr 27 21:09:17 satip minisatip[20466]: _start at ??:?
Apr 27 21:09:17 satip minisatip[20466]: RECEIVED SIGNAL 11 - SP=0 IP=0
Apr 27 21:09:17 satip minisatip[20466]: Obtained 9 stack frames.
Apr 27 21:09:17 satip minisatip[20466]: 0x416c30 : 0x416d21 : 0x7fee1eb9cd10 : 0x41d9c5 : 0x41b85d : 0x40999b : 0x40708f : 0x7fee1d956a40 : 0x403479 :
Apr 27 21:09:17 satip systemd[1]: minisatip.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 21:09:17 satip systemd[1]: minisatip.service: Unit entered failed state.
Apr 27 21:09:17 satip systemd[1]: minisatip.service: Failed with result 'exit-code'.

**Comment by catalinii** [comment]
Hi, can you test now ?

Thanks

**Comment by 9000h** [comment]
ok will try it out tonight

**Comment by 9000h** [comment]
looks like it's fixed

**Comment by catalinii** [comment]
thanks
