### ISSUE TITLE
RFE: Continous streaming when decoding errors

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#307]
Hi @catalinii ,

I like to suggest to add this functionality, as some clients has troubles maintaining the sync when a decoding glitch appears.

Let me to explain the suggestion:
- During the time as one decoding key is invalid (for any reason, don't care about this), the packets to be decoded can be:
  - Option 1: Discarded when the buffer is full.
  - Option 2: Sended to the stream out.

I feel that at time, the option 1 is the one used by minisatip (please, confirm it!).
Then I suggest to change this behaviour. This is my proposal:
- When one undecoded packet needs to be go out of the buffer, and the current key is invalid then:
  - Set the "Transport Error Indicator (TEI)" and clear the "Scrambling control" bits.
    (See: http://en.wikipedia.org/wiki/MPEG_transport_stream#Packet)
  - Flush the packet from the buffer to the stream.

The result of applying this algorithm is that the client continues receiving the Transport Stream with all data in sync, but with "tunning errors"... that is in fact equal to "decoding errors". So the TS structure isn't altered in any sense.

What you think about this? It's a good idea?

**Comment by lars18th** [comment]
Hi @catalinii ,

As no response to this topic after several time... Please, can you answer those questions?

- When the current key is invalid, you discard the encrypted packet or you send it intact to the output buffer? Or you do another action?

- Can you please point me to the code where is done this action? I like to try review the code to understand the current behaviour.

Thank you for your effort!

**Comment by lars18th** [comment]
Hi @catalinii ,

After review your code I discovered this:

* minisatip.c#365: opts.drop_encrypted = 1;

This just controls the functionality I request. Si, I disable and after recompile... and it works!
I suggest to add the command-line for enable/disable this option (default "drop encrypted").

However, I discovered more:

* dvbapi.c#561: decrypt_stream()

This functions has two calls to mark_decryption_failed() inside the loop that process the buffer. But I have two problems:

1. At the start of tunning a program, when the PSI data for CA is cleared, it's good to not send the encrypted packets. But disabling this option of "drop encrypted" then this behaviour is lost. I prefer to allways drop at starting. It's this is possible?

2. When a client receive some encrypted packets inside the stream the behaviour is undefined. So, I prefer to send "erroneous packets" than "encrypted packets". I described this in my first post (set TEI and clear Scrambling bits).

What you think?

**Comment by lars18th** [comment]
Hi @catalinii ,

I have done this simple patch:

dvbapi.c#L554
```
        if (opts.drop_encrypted)
        {
                //b[1] |= 0x1F;
                //b[2] |= 0xFF;
                b[1] |= 0x80; // set the Transport Error Indicator (TEI)
                b[3] &= 0x3F; // clear the encrypted flags
        }
```

This solves the problem (2) when setting "opts.drop_encrypted = 0".

I hope you agree to incorporate this patch, and add the parameter for setting "opts.drop_encrypted" (I suggest "-C" as the parameter with "default=1").

Finally, what you think about the problem (1) ?
Regards.

**Comment by catalinii** [comment]
I know what you mean about problem 1, and maybe that is the way to go (will implement it when the time will permit)...

I am not sure I understand why clearing the encrypted flag and marking it as error would make a difference over changing the PID to 8191 .... I believe that some clients might get confused by the error   indicator (which some clients might not check for) and the decrypted stream which is actually encrypted.

About not sending encrypted traffic in the beginning even if the option is there...you need to think that at the beginning of playing a channel you do not know if a CW will arrive ... also you don't know when... if you drop everything you don't give the opportunity to the client (let's say vdr or tvh) to do something about it...

You are saying: " as some clients has troubles maintaining the sync when a decoding glitch appears."

what time of sync, AV sync (pts,dts)?
More specifically what problem are you trying to resolve?

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you for your response! I comment on parts:

> I am not sure I understand why clearing the encrypted flag and marking 
> it as error would make a difference over changing the PID to 8191 .... 
> I believe that some clients might get confused by the error indicator (which 
> some clients might not check for) and the decrypted stream which is actually encrypted.

When you use "transparent decrypting" (presenting the program as FTA), and you can't decode... what data you need to send to the client? At time, with flag "opts.drop_encrypted=1" you are sending nothing (when you change the PID to NULL 8192 the packets are in fact removed, as you filter all padding!). But this ins't consistent with broadcasting transmissions. When an error ocurrs then the stream is typically corrupted... and only when sync is lost, no data is present in the tuner. Then my idea is quite simple: when you can't decode, send data as is with errors... This is very easy: clear the encrypted flags, and this "converts" the packet to garbagge. Additionally, as you know the data is corrupted, you can set the TEI flag. With this flag the decoder can discard the packet instead of passing it to the input buffer. This more or less mimics the behaviour of real transmissions.

> About not sending encrypted traffic in the beginning even if the option is there...
> you need to think that at the beginning of playing a channel you do not know 
> if a CW will arrive ... also you don't know when... if you drop everything you don't 
> give the opportunity to the client (let's say vdr or tvh) to do something about it...

Sure! This is my concern. With my current patch some clients refuse to play if the key is not available in short time. Then my suggestion is add a simple flag that it's set to 0 when a new program is selected and set to 1 when first packet is decoded. So you only need to check this flag for discarding the packet or for sendding it as corrupted. More or less like:

```
	   if (opts.drop_encrypted)
		{
			if (_starting_flag_)
			{
				// discard the packet (convert to NULL packet!)
				b[1] |= 0x1F;
				b[2] |= 0xFF;
			} else {
				b[1] |= 0x80; // set the Transport Error Indicator (TEI)
				b[3] &= 0x3F; // clear the encrypted flags
			}
		}
```

> You are saying: " as some clients has troubles maintaining the sync 
> when a decoding glitch appears."
> what time of sync, AV sync (pts,dts)?
> More specifically what problem are you trying to resolve?

With several clients, specially with HTTP transport, but also with RTP transport; when you "remove" undecoded packets, the timming packets (PCR) are received out-of-sync. As you don't recreate timer counts these errors breaks the timer sync in the client. The perceived effect is that the client then needs to discard more packets until it resynchronizes, although some good packets are comming. So the good way is send padding... or in my oppinion "corrupted" packets. This don't breaks the continuity of the streams, and the decoder can maintain the sync.

If you like to make a test, try this: include random errors in the decoding function (for example, discarding to call to the decode function each N encrypted packets with a random length). Then try to visualize this with some client: Your client stops, freezes, shows errors... or it tries to resync?

I really think that is important to implement this consistent way for streaming undecoded packets.
You think the same?

**Comment by catalinii** [comment]
When you say that some clients are not syncing properly, do you mean you have Audio / Video Sync issues ?
Because mpegts specifies the PTS/DTS in the header, so, the vpid and apid should be sufficient for syncing the sound and video.

If you are talking about a specific client which does not work, which one is it ?

I do not have any problem with implementing certain changes, however I want to make sure that the existing clients are not disrupted and that more clients can connect to the app....In this case, I am really afraid that by implementing this, I can break certain clients that do not check for TEI.

That's why I want to see examples of things that does not work in real life...

thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

First of all, my first request is "enable with a command parameter the setting of opts.drop_encrypted", as this is at time unimplemented. Why you say that this can disrupt some clients? If some user likes to use the *current* behaviour, he don't ned to do anything: the default is the current "drop encrypted" packets.

However, after disable this mode with the commandline (I suggest "-C" for disable dropping unencrupted packets), my suggestion only changes from the current behaviour in that point: at time you copy the encrypted packet, and my suggestion os copy garbagge and indicate that the packet contains errors. Which option is more close to physical tuners?

Related to your questions:

1) Unencrypted packets don't produce A/V sync problems, but Timer troubles. As several (~1K) packets ar lost, the decoder is confused and needs to resynchronize. During this process any valid packets are discard. For example, in some cases it happens that when the key fails then audio packets can be decrypted and video be undecrypted. So the result is a trouble in sync.

2) I can't point to specific clients. Sorry! But several software decoder fails when receive the stream from minisatip (when the decoding process fails intermittently because timeout in the key recovery).

Finally, a simple comment: if some client doesn't checks the TEI flag the final result is quite simple... the decoder can ingress corrupted data. Nothing more, nothing less. Don't worry about this... for this reason you will have the command line!

**Comment by catalinii** [comment]
Hi Lars, I agree with adding an option for drop encrypted but I dont agree with marking TEI and clearing the unencrypted flag.

Reasons 
1) don't fix it if it's not broken
2) hardware decoders ingesting garbage data when they expect a frame is no so simple as the data will not have tags... you could potentially have a frame 188 x 1k or more...buffers overflows ..think about extreme cases.
3) when the correct CW is sent, the decrypted stream will have mpegts tags containg the a/v pts....which are already syncronized ... so it can start playing them right away. What happens is that the client buffers the frames before displaying them.

The real problem here is the correct CW appearing later which can be corrected by buffering undecrypted data. Any other "fix" will not make a difference...


But as I said I will try to do this...when the time permits.


Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> 1) don't fix it if it's not broken

Yes, but between discarding unencrypted data or sending it, the best is offer to the user the option of select the behaviour.

> 2) hardware decoders ingesting garbage data

All hardware decoders are resilent to errors in the stream! Errors in the stream only produce glitches in the image and the TEI flag is defined for this specific case: when the tuner knows that the packet has errors.

> The real problem here is the correct CW appearing later which can be 
> corrected by buffering undecrypted data

Yes. And I also agree that improving the robustness to "slow key recovery" and "re-ask when key timeout appears" are relevant points for work on it. However, the use of a consistent mode for process "unencrypted" packets I feel is a good question.

I hope you can include these changes soon.
Thank you for your good job!

**Comment by lars18th** [comment]
Hi @catalinii ,

After more tests, I agree with you that is not necessary to set the TEI flag and clear the encrypted flags. However, enable the option for "remove" unencrypted packets or resend at is, is really useful.
So, please, can you commit the patch?

Also, it will be useful if you can always remove the unencrypted packets at the setup of the channel (first tunning). I hope you can implement it when you have free time! ;)

Regards.

**Comment by catalinii** [comment]
I am not sure I understand what you mean by:
"Also, it will be useful if you can always remove the unencrypted packets at the setup of the channel (first tunning). "

The option for drop_encrypted will be -E (will be enabled in the next commit).

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> I am not sure I understand what you mean by:
> "Also, it will be useful if you can always remove the unencrypted packets at the setup of the channel (first tunning). "
>
> The option for drop_encrypted will be -E (will be enabled in the next commit).

OK, I try to explain...

- With "-E" enabled, all encrypted packets will be removed: OK.
- Without "-E" (default behaviour), all encrypted packets will be passed:
 - This is ok during the playback, as if some packet can't be decoded the stream isn't modified (it maintains the same number of 188-length packets).
 - But, at starting of the playback, when you use the option "-t" if you send some encypted packet, then several clients interpret that the channel is encrypted (whatever the PSI table says). Then, in this specific case (without "-E" and with "-t") it's best to not send any encrypted packet... until the decoding process has started.

I hope this helps.

**Comment by catalinii** [comment]
Hi,

so you are saying you do not want for the encrypted packets to not be sent until the decoding starts ?

if yes, can I ask what is the side effect (what's not working)?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> so you are saying you do not want for the encrypted packets to not be sent until the decoding starts ?

Yes!

> if yes, can I ask what is the side effect (what's not working)?

If you use the option "-t" and send the encrypted packets, some clients refuses to play, as they think: "the PSI table has invalid CA information, the channel is encrypted". So, they don't to play the channel, altrough after sometime new unencrypted packets start to comming.

I do several tests, and the best option is: "send encrypted packets for not disturbing the player, but not send any invalid (=undecrypted) audio/video packet until the decrypting process is started".

I hope you can evalute it, and agree to implement in this way!

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you! Last commit supports "-E" parameter and it works right.

However, before close this issue: You will implement the option for not sending the encrypted packets at start with using "-E" and "-t" ?

**Comment by lars18th** [comment]
Hi @catalinii ,

After years of this issue, I made a PR that solves this problem: PR #445.
If you accept and merge it, then I'll close this issue.

Let me to explain the problem:

- When using the "-t" parameter for transparent descrambling, _some_ clients have troubles. The reason is because when you don't use the "-E" parameter the behaviour is to discard all encrypted packets. However this generates a problem with the PCR. Typically the pid with the PCR is the video stream, that is encrypted. Then when you discard these packets because you can't decrypt them for some reason, in this particular case the client doesn't receives packets with PCR. And even when the number of "lost" packets are low, the PCR is missing and several clients have troubles with the stream. In these cases the regular behaviour of the client is stop for 1-2 seconds and resync. But if the "lost time" continues longer then the client tries to "re-play". And this implies a lot of time; more than the "lost time". So, in these cases passing the encrypted packets are a better option: The client receives the correct PCR, and discard the encrypted data. However, doing this behaviour all the time generates another problem. The problem is with the _initial_ encrypted stream. This patch solves this issue filtering all encrypted packets until the initial decryption. After this phase the behaviour changes to pass all encrypted packets. So this is the preferable behaviour when using "-t" and "-E" at the same time.

In fact, I recomend to use all the time the "-E" parameter! This solves incompatibilities with a lot of clients.

I hope you merge soon this PR.
Regards!

**Comment by Jalle19** [comment]
Is this still something that remains undone?

**Comment by lars18th** [comment]
Hi @Jalle19 ,

> Is this still something that remains undone?

Absolutly YES! I'm using for months an "internal" patch that implements a new way to output the non-decrypted packets. It's quite complex (but lightweight) and I've planned to do a refinement. However, I'm very busy for these weeks, and I'll work on it and I'll publish it perhaps in some months. So please, leave this open.

Regards.
