### ISSUE TITLE
BUG: SSDP bad udp cksum

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#309]
Hi @catalinii ,

I discovered using tcpdump that SSDP messages from minisatip has incorrect udp checksums:

```
$ tcpdump -vv -X -i eth0 -n udp dst port 1900

05:15:15.241715 IP (tos 0x0, ttl 1, id 63505, offset 0, flags [DF], proto UDP (17), length 404)
    192.168.1.31.1900 > 239.255.255.250.1900: [bad udp cksum 0x8446 -> 0xb459!] UDP, length 376
```

I don't know why, as messages from other sources have correct checksums.

Please, take into account that this is related to udp checksum, and not with the ip header checksum. If you like to disable udp checksums, then the field needs to be zeroed.

Regards!

**Comment by catalinii** [comment]
Hi,
The system should fill the checksum as required, as I am not using RAW sockets... I have added the IIPPROTO_UDP at socket creation,now sure will make any difference.

**Comment by lars18th** [comment]
Hi @catalinii ,

Problem fixed! ;)
