### ISSUE TITLE
PATCH: Add support for Windows (Cygwin)

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#310]
Hi @catalinii ,

As the current version supports SAT>IP client mode AND disable the Linux DVB-API, I compiled a version using the Cygwin layer... It's impresive, with a few changes it works!

So, I have prepared a patch. This patch is fully compatible with Linux, as maintains the compatibility of the headers. So, I suggest to merge it with the current branch of minisatip. This patch also includes my suggestion commented on #302.

Please, try it! :)

```
diff -rupN original/adapter.c temppatch/adapter.c
--- minisatip-master/adapter.c  2016-05-27 08:52:06.000000000 -0400
+++ minisatip-master/adapter.c  2016-05-27 08:54:39.000000000 -0400
@@ -26,7 +26,8 @@
 #include <unistd.h>
 #include <fcntl.h>
 #include <poll.h>
-#include <linux/ioctl.h>
+//#include <linux/ioctl.h>
+#include <sys/ioctl.h>

 #include "socketworks.h"
 #include "dvb.h"
diff -rupN original/dvb.h temppatch/dvb.h
--- minisatip-master/dvb.h  2016-05-27 08:44:20.000000000 -0400
+++ minisatip-master/dvb.h  2016-05-27 08:45:08.000000000 -0400
@@ -2,7 +2,8 @@
 #define DVB_H

 #ifdef DISABLE_LINUXDVB
-#include <linux/types.h>
+//#include <linux/types.h>
+#include <stdint.h>
 #include <time.h>
 #define DVBAPIVERSION 0x0500
 #define LOGDVBAPIVERSION 0x0000
diff -rupN original/utils.c temppatch/utils.c
--- minisatip-master/utils.c    2016-05-27 08:57:27.000000000 -0400
+++ minisatip-master/utils.c    2016-05-27 08:58:14.000000000 -0400
@@ -853,7 +853,8 @@ char *readfile(char *fn, char *ctype, in
        return 0;
    snprintf(ffn, sizeof(ffn), "%s/%s", opts.document_root, fn);
    ffn[sizeof(ffn) - 1] = 0;
-   if ((fd = open(ffn, O_RDONLY | O_LARGEFILE)) < 0)
+// if ((fd = open(ffn, O_RDONLY | O_LARGEFILE)) < 0)
+   if ((fd = open(ffn, O_RDONLY)) < 0)
        LOG_AND_RETURN(NULL, "Could not open file %s", ffn);
    if ((fstat(fd, &sb) == -1) || !S_ISREG(sb.st_mode))
    {
diff -rupN original/socketworks.c temppatch/socketworks.c
--- minisatip-master/socketworks.c  2016-05-27 09:07:09.000000000 -0400
+++ minisatip-master/socketworks.c  2016-05-27 09:20:10.000000000 -0400
@@ -115,13 +115,28 @@ int udp_bind(char *addr, int port)

    if (!fill_sockaddr(&serv, addr, port))
        return -1;
-   sock = socket(AF_INET, SOCK_DGRAM, 0);
+   serv.sin_addr.s_addr = htonl(INADDR_ANY);
+// sock = socket(AF_INET, SOCK_DGRAM, 0);
+   sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (sock < 0)
    {
        LOGL(0, "udp_bind failed: socket(): %s", strerror(errno));
        return -1;
    }

+   if (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval)) < 0)
+   {
+       LOGL(0, "udp_bind failed: setsockopt(SO_REUSEADDR): %s",
+               strerror(errno));
+       return -1;
+   }
+   if (bind(sock, (struct sockaddr *) &serv, sizeof(serv)) < 0)
+   {
+       LOGL(0, "udp_bind: failed: bind() on host %s port %d: error %s", addr,
+               port, strerror(errno));
+       return -1;
+   }
+
    if (addr && atoi(addr) >= 239)
    {
        struct ip_mreq mreq;
@@ -135,19 +150,6 @@ int udp_bind(char *addr, int port)
            LOGL(0, "membership error: %s", strerror(errno));
        }
    }
-   if (setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval)) < 0)
-   {
-       LOGL(0, "udp_bind failed: setsockopt(SO_REUSEADDR): %s",
-               strerror(errno));
-       return -1;
-   }
-
-   if (bind(sock, (struct sockaddr *) &serv, sizeof(serv)) < 0)
-   {
-       LOGL(0, "udp_bind: failed: bind() on host %s port %d: error %s", addr,
-               port, strerror(errno));
-       return -1;
-   }

    set_linux_socket_timeout(sock);
```

Regards!

**Comment by lars18th** [comment]
Hi @catalinii ,

You agree to incorporate the changes in to the main stream? ;)

Regards!

**Comment by catalinii** [comment]
Hi,

I have added in the alst commit, please test it now.
ABout the ssdp issue let's discuss there...

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

Two comments:

* First: I missing in the original patch one modification. Wihtout it the last commit don't compile in Cygwin. Here a simple overview:

"socketworks.c"
```
void set_socket_send_buffer(int sock, int len)
{
	int sl;
	int rv;
	if (len <= 0)
		return;
+#ifdef SO_SNDBUFFORCE
	if ((rv = setsockopt(sock, SOL_SOCKET, SO_SNDBUFFORCE, &len, sizeof(len))))
		LOGL(3, "unable to set output socket buffer (force) size to %d", len);
+#endif
	if (rv && setsockopt(sock, SOL_SOCKET, SO_SNDBUF, &len, sizeof(len)))
		LOGL(3, "unable to set output socket buffer size to %d", len);
	sl = sizeof(int);
	if (!getsockopt(sock, SOL_SOCKET, SO_SNDBUF, &len, (socklen_t *) &sl))
		LOG("output socket buffer size for socket %d is %d bytes", sock, len);

}

void set_socket_receive_buffer(int sock, int len)
{
	socklen_t sl;
	int rv;
	if (len <= 0)
		return;
+#ifdef SO_SNDBUFFORCE
	if ((rv = setsockopt(sock, SOL_SOCKET, SO_RCVBUFFORCE, &len, sizeof(len))))
		LOGL(3, "unable to set receive socket buffer (force) size to %d", len);
+#endif
	if (rv && setsockopt(sock, SOL_SOCKET, SO_RCVBUF, &len, sizeof(len)))
		LOGL(3, "unable to set receive socket buffer size to %d", len);
	sl = sizeof(int);
	if (!getsockopt(sock, SOL_SOCKET, SO_RCVBUF, &len, &sl))
		LOG("receive socket buffer size is %d bytes", len);

}
```

As you can imagine, a simple mistake! ;)

* Second: Wihtout the reordering discussed in #302 the binary in Windows don't work. Here the output at start:

```
./minisatip.exe -f -s 192.168.1.35:554 -l
[01/06 12:17:00.764]: minisatip version 0.5.51, compiled with s2api version: 0000
[01/06 12:17:00.764]: Built without dvbcsa
[01/06 12:17:00.765]: Built without CI
[01/06 12:17:00.765]: Built without dvbapi
[01/06 12:17:00.765]: Built without AES (OpenSSL)
[01/06 12:17:00.765]: Built without tables processing
[01/06 12:17:00.765]: Built with satip client
[01/06 12:17:00.765]: Built without linux dvb client
[01/06 12:17:00.766]: Built without backtrace
[01/06 12:17:00.766]: Built without netceiver
[01/06 12:17:00.767]: New UDP socket 3 bound to 0.0.0.0:1900
[01/06 12:17:00.767]: setting multicast for 239.255.255.250
[01/06 12:17:00.768]: udp_bind: failed: bind() on host 239.255.255.250 port 1900: error Cannot assign requested address
[01/06 12:17:00.769]: SSDP: Could not bind on 239.255.255.250 udp port 1900
```

In fact, I discovered your fault in the order of settings the socket calls trying to compile for Windows. And with my proposed reordering it works in Windows without any problem!
Please, commit the reordering...

**Comment by lars18th** [comment]
Hi @catalinii ,

Please, can you accept the missed patch of "#ifdef SO_SNDBUFFORCE" (transparent for all platforms)?

Also, can you consider my proposal for listening in a local address instead of the multicast address? With these two mods, the Cygwin version will compile and executes without troubles. My idea is prepare a binary package and, if you accept it, publish it in the "releases" section.

You agree?

**Comment by catalinii** [comment]
Hi,

It's a good idea but I will look next week and see what needs to be done.

Thanks

**Comment by lars18th** [comment]
OK. Great! ;)

**Comment by catalinii** [comment]
Sorry for late reply, still in vacation... can you try now ?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

With last commit it compiles. Thank you!

However:

1) If you don't execute minisatip with elevated privileges (as Administrator), then the SSDP Auto Discovering don't works!

2) Even, if you execute with or without elevated privileges, always an error related to bind to 1900 is raised:

```
[18/07 12:25:09.646]: New UDP socket 3 bound to 0.0.0.0:1900
[18/07 12:25:09.647]: setting multicast for 239.255.255.250
[18/07 12:25:09.654]: udp_bind: failed: bind() on host 239.255.255.250 port 1900: error Cannot assign requested address
[18/07 12:25:09.655]: New UDP socket 4 bound to 239.255.255.250:1900
```

Only, my previous patch related to the order of the bind can overcome this problem (see #302).
Why you think is this behaviour?

3) I suggest that you remove the conditional compilation (#ifndef __CYGWIN__) at 
http://github.com/catalinii/minisatip/blob/master/utils.c#L856
as it's completly useless! Why you force to use O_LARGEFILE ? This is only for read/write >2GB files in Linux. Several other UNIXes don't have this defined. If you really like to use it, I suggest to check if "O_LARGEFILE" is defined, not if "__CYGWIN__" is defined. Conditional compilation difficults the portability of the code! Also, I compile it in Linux without O_LARGEFILE and all works as expecte (nothing changes!).

When all troubles are fixed, I'll create a BAT file for launch it, and I prepare a ZIP with binaries. If you like then you can publish it in the "Release" space of the GitHub repository.
You agree?

**Comment by lars18th** [comment]
Hi Catalin,

Regarding this support for CYGWIN, please can you apply the point (3)?
I'm convinced that you don't need to use O_LARGEFILE (>2GB) option for read texts, images, playlists, etc.
Or if you prefer:

```
#ifdef O_LARGEFILE
   	if ((fd = open(ffn, O_RDONLY | O_LARGEFILE)) < 0)
#else
	if ((fd = open(ffn, O_RDONLY)) < 0)
#endif
```

In reference to points (1) and (2), any idea?
Regards.

**Comment by catalinii** [comment]
Hi,

in utils.c is:
#ifndef __CYGWIN__
        if ((fd = open(ffn, O_RDONLY | O_LARGEFILE)) < 0)
#else
        if ((fd = open(ffn, O_RDONLY)) < 0)
#endif

Is this not working ?

About 2, 3, see: https://github.com/catalinii/minisatip/blob/master/socketworks.c#L156

Is this working now ?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> in utils.c is:
> ...
> Is this not working ?

Yes, it's working! I know.
But I suggest change "#ifndef __ CYGWIN __" by "#ifdef O_LARGEFILE" because the O_LARGEFILE isn't available in all systems (not only in Cygwin, as it's a GNU extension.).
Moreover, I repeat: why you need to open >2GB files?
I say this because I prefer "clean & portable" code if possible.

Regarding the listening SSDP socket trouble, I'll check!
Thank you!

**Comment by catalinii** [comment]
the #ifdef O_LARGEFILE will be implemented in the next commit.

Why is it needed ... because allows minisatip to serve files larger than 2G... why limit it ?

I have added it because personally I needed it.. so I guess sooner or later someone might need it as well.

thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

Nothing to say for the use of O_LARGEFILE... it's your code. Thank you for clarify it!

> the #ifdef O_LARGEFILE will be implemented in the next commit.

Again, thanks! I prefer portable code... ;)

**Comment by ant-thomas** [comment]
This may seem like a stupid question, but using cygwin and Windows does this allow minisatip to access Windows DVB devices? Or is this only for client mode? 

I'd really like a version of minisatip to run on Windows using available DVB devices as I'm having issues with a specific DVB-C tuner under Linux, it works fine on windows.

**Comment by catalinii** [comment]
Hi,

by compiling it under Windows, it cannot access the windows devices (at least not now).

Maybe it's worth filling an enhancement, maybe another users are interested in it.

Thanks

**Comment by lars18th** [comment]
Hi @ant-thomas ,

Yes, only "client mode". This is mainly for testing pourpose.

However, if minisatip will have someday access to udp multicast input, then will be possible to implement some kind of "scripting input" (like tuner controlled by scripts). So, using an external tool running in Windows to "control" your BDA tuner, then it would be possible to achieve your goal.

I hope Catalin will agree. ;)

**Comment by catalinii** [comment]
I think in general that whatever a user needs is best to fill an ER. If multiple users needs it, it will get prioritized.

It also allows me to plan ahead and to think how a change can allow more ERs to be implemented.

**Comment by lars18th** [comment]
Hi @catalinii ,

I hope not be the only who wants to have this functionality.
I'm sure that it will be great for all IPTV users!

What can I do to increase the priority of this ER?

**Comment by catalinii** [comment]
Hi Lars, just create the ER

If more users wants it, maybe I can give it a go at some point.
