### ISSUE TITLE
Loglevels?

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#314]
Hi,

what is the difference between "-l", "-l -l", and "-l -l -l"?

On my System, there is no difference, if i use "-l", "-l -l", or "-l -l -l".

I use gentoo with metalog.

**Comment by lars18th** [comment]
Hi @3PO ,

Try "-ll" and "-lll" instead of repeat the parameter!
If you like to see the difference try "-lllll" and your log will go full in a short time.

**Comment by 3PO** [comment]
it makes no difference if i use "-l", or "-lll", or something else.

**Comment by lars18th** [comment]
Hi @3PO ,

And "-llll" (5 times)?
It's very annoying.
Please, post your command line.

**Comment by 3PO** [comment]
>And "-llll" (5 times)? ...

Same as i wrote above




>[...] Please, post your command line.

```
server02 ~ # ps -aux |grep minisatip |grep -v grep
root      8972  1.3  0.0 1059996 3020 ?        Sl   12:25   0:00 /usr/bin/minisatip -g -lllll -o localhost 4444 -R /etc/minisatip/html/
server02 ~ #

```

**Comment by lars18th** [comment]
Hi @3PO ,

Ok, I know. I use in my system "-f" instead of "-g" (running inside screen tool). Try to execute without "-g" and with "-f" in the foreground. In this case, you see the difference?

Perhaps the problem is in your SYSLOG daemon.

**Comment by 3PO** [comment]
In foreground it seems workig. But this means there is a Bug in minisatip.

BTW: would it not easyer to make the loglevels like this:

-l 1, -l 2, ....

0 = off
1 = info
2 = error
3 = debug

**Comment by lars18th** [comment]
Hi @3PO ,

off = ""
info = "-l"
error = "-ll"
debug = "-lll"
...

It's like that! Using the regular "getopt_long()" C function this is common syntax. However, it's more common to use "-v" (verbose) than "-l" (log).

Please, first check your SYSLOG daemon, and if the trouble continues then ask @catalinii for fix the problem.

**Comment by 3PO** [comment]
At the Moment it is:

"-l" = debug
"-ll" = more debig
"-lll" = anymore debug
"-llll" = very verbose debug

"info" and "error" is stll missing!

BTW: My SYSLOG Daemon is woking fine since 10 years ago on all my Systems.

**Comment by catalinii** [comment]
I have implemented log levels for specific modules, please take a look and let me know if it's better.
 
Thanks
