### ISSUE TITLE
missing space

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#32]
strream.c:57 there is a space missing after o=- and I'm not sure if negative values here are a issue

from the spec

v=0
o=- 5678901234 7890123456 IN IP4 192.168.128.5
s=SatIPServer:1 4
t=0 0

“o=” gives the originator of the session “-“ <session-id> <session-version> IN for internet and the IP address of the
server. The session-id and session-version values shall be present but are not used currently.

**Comment by catalinii** [comment]
Done in the next commit
