### ISSUE TITLE
No Servers found if minisatip is started via systemd

### ISSUE THREAD

**Issue by henfri** [catalinii/minisatip#320]
Hello,

I am using minisatip successfully on debian jessie.
But it works only, if I start minisatip manually, as root from the shell.
If I let systemd start minisatip it does run, but clients do not find it.

Here's my script:
[Unit]
Description=Multi-threaded SAT>IP server
After=network.target

[Service]
#User=root
#Group=root
WorkingDirectory=/var/lib/minisatip
Type=simple
EnvironmentFile=/etc/default/minisatip
ExecStart=/usr/bin/minisatip -f $SERVER_ARGS

[Install]
WantedBy=multi-user.target

What could be the reason?

Greetings,
Hendrik

**Comment by henfri** [comment]
(uncommenting User=root and Group=root does not help aswell)

**Comment by srehm** [comment]
Hello henfri,

my systemd unit looks similar to yours except that I use "Type=forking" and omit die "-f" parameter to minisatip. But as far as I understood the documentation of the types, that should not be the reason (but you could try nevertheless).
Do your clients find the server if you disable automatic start up of the minisatip service at boot, let the system boot up completely and then call

systemctl start minisatip.service

from the shell (replace minisatip.service with whatever your unit is called)?

**Comment by 9000h** [comment]
can you try with:

[Unit]
Description=Multi-threaded SAT>IP server
After=network-online.target

**Comment by henfri** [comment]
Thanks for your hints
@9000h: that did not help
@srhem: what I did try now was do stop and start the service:
root@homeserver:~# service minisatip stop
root@homeserver:~# service minisatip start

After that, clients can access sat->ip.

Before stopping minisatip I do see minisatip in the running processes. So, minisatip DOES run.

Any further ideas?

**Comment by srehm** [comment]
Looks like the network interface isn`t up yet when minisatip starts. I dont know how that is possible if you really used the "network-online.target".  If you are using Network manager or systemd-networkd to manage your interfaces than this might help:

http://stackoverflow.com/questions/32873571/debian-systemd-service-starts-before-network-is-ready

**Comment by henfri** [comment]
Thanks.
this did the trick (from your link):
 systemctl enable systemd-networkd-wait-online.service

Greetings and Thanks!
