### ISSUE TITLE
RFE: UDP client port rage

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#323]
Hi,

In order to improve the minisatip->minisatip interopeartibility, I give a suggestion:
- Add the option for selecting the UDP port range used for receiving the RTP stream.

At time, two options are available for minisatip->minisatip comunication:
1. Using stadard UDP transport.
2. Over TCP (using "-O --satip-tcp Use RTSP over TCP instead of UDP for data transport").

The first is great over LAN, the second over WIFI or routed networks. However, over NAT networks only TCP is working at time. Then, if I can select the listening UDP port range, and set some port forwarding rules, then UDP can also work.

You like to add this option?
Regards.

**Comment by catalinii** [comment]
Hi,

currently it depends on start_rtp (which I see is not configurable via command line).

sip->listen_rtp = opts.start_rtp + 1000 + ad->id * 2;

So basically it starts at 6500 and uses 2 ports for each adapter.

I can just probably add a configurable option for start_rtp, but I am thinking more about a configuration file as there are many options that could be configured manually...

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

Yes, please, add the command line option for configure the "start_rtp" port (I recommend to use the option "-P").

Futhermore, remember to print at start
- "Base UDP client port: " (=start_rtp) 
- "End UDP client port: " (=start+rtp+(adapters*2))

That info will be useful for know the used port range.

Thank you!

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you for the commit!

However, before close this issue, two questions:

1) Why use for the parameter a value substracting 1000? It's a little annoying to set the parameter for port 10000, and the program uses 11002 and 11003. I suggest to use: port = ("-P value" + 2*(A-1)), if the adapter starts in 1 (and not 0).

2) The number of the adapter... is related to the "sat-ip client" adapter, or to the full list of mixed adapters? I want to guarantee that a specific port is always used. If the "A" only applies to "sat-ip client adapters" then it's easy...

In any case, thank you for improve this good software!

**Comment by catalinii** [comment]
there are 2 values, 1 for the server (-P) the other one for satip>client.

Thinking of it, I think is better to add the satip part to the adapter configuration, which I might add to a config file later on.

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> there are 2 values, 1 for the server (-P) the other one for satip>client.

OK. Now I understand. My request has only for the "client" part. However, current implementation is then right.

> I might add to a config file later on.

OK. I hope soon you can support a config file.

**Comment by lars18th** [comment]
Hi, @catalinii ,

Thank you for implement it! I see the new parameter in the last commit:
http://github.com/catalinii/minisatip/commit/c3f69cf19ed25b039bdf8d7cc0616d1d2bf3e2f6

**Comment by catalinii** [comment]
Hi,

over WAN is highly recommended to use tcp mode which is in a much better state (no existing issues in 0.7).

Closing this issue.
