### ISSUE TITLE
Minisatip accessible only from local machine until Restart

### ISSUE THREAD

**Issue by henfri** [catalinii/minisatip#324]
Hello,

I still have the problems that I thought I had solved in https://github.com/catalinii/minisatip/issues/320

What I found now is, that a docker-container running on the machine that is running minisatip (minisatip DIRECTLY running on the machine) CAN access minisatip.
It is only other Clients (Android, Windows) that cannot.

Any ideas, what could be the reason?

I am running Debian Jessie.

Greetings,
Hendrik

**Comment by henfri** [comment]
Hello,

some more info:
`root@homeserver:~# lsof | grep mini |grep TCP
minisatip  981                       root    5u     IPv4              17482        0t0        TCP *:rtsp (LISTEN)
minisatip  981                       root    6u     IPv4              17483        0t0        TCP *:tproxy (LISTEN)
minisatip  981                       root    9u     IPv4              41412        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39050 (ESTABLISHED)
minisatip  981                       root   13u     IPv4              41426        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39052 (ESTABLISHED)
minisatip  981                       root   18u     IPv4              41430        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39054 (ESTABLISHED)
minisatip  981                       root   22u     IPv4              41433        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39056 (ESTABLISHED)
minisatip  981 1026                  root    5u     IPv4              17482        0t0        TCP *:rtsp (LISTEN)
minisatip  981 1026                  root    6u     IPv4              17483        0t0        TCP *:tproxy (LISTEN)
minisatip  981 1026                  root    9u     IPv4              41412        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39050 (ESTABLISHED)
minisatip  981 1026                  root   13u     IPv4              41426        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39052 (ESTABLISHED)
minisatip  981 1026                  root   18u     IPv4              41430        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39054 (ESTABLISHED)
minisatip  981 1026                  root   22u     IPv4              41433        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39056 (ESTABLISHED)
minisatip  981 1073                  root    5u     IPv4              17482        0t0        TCP *:rtsp (LISTEN)
minisatip  981 1073                  root    6u     IPv4              17483        0t0        TCP *:tproxy (LISTEN)
minisatip  981 1073                  root    9u     IPv4              41412        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39050 (ESTABLISHED)
minisatip  981 1073                  root   13u     IPv4              41426        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39052 (ESTABLISHED)
minisatip  981 1073                  root   18u     IPv4              41430        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39054 (ESTABLISHED)
minisatip  981 1073                  root   22u     IPv4              41433        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39056 (ESTABLISHED)
minisatip  981 4323                  root    5u     IPv4              17482        0t0        TCP *:rtsp (LISTEN)
minisatip  981 4323                  root    6u     IPv4              17483        0t0        TCP *:tproxy (LISTEN)
minisatip  981 4323                  root    9u     IPv4              41412        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39050 (ESTABLISHED)
minisatip  981 4323                  root   13u     IPv4              41426        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39052 (ESTABLISHED)
minisatip  981 4323                  root   18u     IPv4              41430        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39054 (ESTABLISHED)
minisatip  981 4323                  root   22u     IPv4              41433        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39056 (ESTABLISHED)
minisatip  981 4325                  root    5u     IPv4              17482        0t0        TCP *:rtsp (LISTEN)
minisatip  981 4325                  root    6u     IPv4              17483        0t0        TCP *:tproxy (LISTEN)
minisatip  981 4325                  root    9u     IPv4              41412        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39050 (ESTABLISHED)
minisatip  981 4325                  root   13u     IPv4              41426        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39052 (ESTABLISHED)
minisatip  981 4325                  root   18u     IPv4              41430        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39054 (ESTABLISHED)
minisatip  981 4325                  root   22u     IPv4              41433        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39056 (ESTABLISHED)
minisatip  981 4327                  root    5u     IPv4              17482        0t0        TCP *:rtsp (LISTEN)
minisatip  981 4327                  root    6u     IPv4              17483        0t0        TCP *:tproxy (LISTEN)
minisatip  981 4327                  root    9u     IPv4              41412        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39050 (ESTABLISHED)
minisatip  981 4327                  root   13u     IPv4              41426        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39052 (ESTABLISHED)
minisatip  981 4327                  root   18u     IPv4              41430        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39054 (ESTABLISHED)
minisatip  981 4327                  root   22u     IPv4              41433        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39056 (ESTABLISHED)
`

This is directly after boot. 
172.17.0.7 is a VDR that is running inside a Docker-Container on the same machine.

After restarting minisatip, it looks very similar:
`root@homeserver:~# lsof | grep mini |grep TCP
minisatip 10424                        root    5u     IPv4              80629        0t0        TCP *:rtsp (LISTEN)
minisatip 10424                        root    6u     IPv4              80630        0t0        TCP *:tproxy (LISTEN)
minisatip 10424                        root   16u     IPv4              81792        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39406 (ESTABLISHED)
minisatip 10424                        root   25u     IPv4              80765        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39408 (ESTABLISHED)
minisatip 10424                        root   26u     IPv4              80766        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39410 (ESTABLISHED)
minisatip 10424                        root   27u     IPv4              80767        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39412 (ESTABLISHED)
minisatip 10424 10425                  root    5u     IPv4              80629        0t0        TCP *:rtsp (LISTEN)
minisatip 10424 10425                  root    6u     IPv4              80630        0t0        TCP *:tproxy (LISTEN)
minisatip 10424 10425                  root   16u     IPv4              81792        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39406 (ESTABLISHED)
minisatip 10424 10425                  root   25u     IPv4              80765        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39408 (ESTABLISHED)
minisatip 10424 10425                  root   26u     IPv4              80766        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39410 (ESTABLISHED)
minisatip 10424 10425                  root   27u     IPv4              80767        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39412 (ESTABLISHED)
minisatip 10424 10427                  root    5u     IPv4              80629        0t0        TCP *:rtsp (LISTEN)
minisatip 10424 10427                  root    6u     IPv4              80630        0t0        TCP *:tproxy (LISTEN)
minisatip 10424 10427                  root   16u     IPv4              81792        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39406 (ESTABLISHED)
minisatip 10424 10427                  root   25u     IPv4              80765        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39408 (ESTABLISHED)
minisatip 10424 10427                  root   26u     IPv4              80766        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39410 (ESTABLISHED)
minisatip 10424 10427                  root   27u     IPv4              80767        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39412 (ESTABLISHED)
minisatip 10424 10429                  root    5u     IPv4              80629        0t0        TCP *:rtsp (LISTEN)
minisatip 10424 10429                  root    6u     IPv4              80630        0t0        TCP *:tproxy (LISTEN)
minisatip 10424 10429                  root   16u     IPv4              81792        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39406 (ESTABLISHED)
minisatip 10424 10429                  root   25u     IPv4              80765        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39408 (ESTABLISHED)
minisatip 10424 10429                  root   26u     IPv4              80766        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39410 (ESTABLISHED)
minisatip 10424 10429                  root   27u     IPv4              80767        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39412 (ESTABLISHED)
minisatip 10424 10431                  root    5u     IPv4              80629        0t0        TCP *:rtsp (LISTEN)
minisatip 10424 10431                  root    6u     IPv4              80630        0t0        TCP *:tproxy (LISTEN)
minisatip 10424 10431                  root   16u     IPv4              81792        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39406 (ESTABLISHED)
minisatip 10424 10431                  root   25u     IPv4              80765        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39408 (ESTABLISHED)
minisatip 10424 10431                  root   26u     IPv4              80766        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39410 (ESTABLISHED)
minisatip 10424 10431                  root   27u     IPv4              80767        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39412 (ESTABLISHED)
minisatip 10424 10433                  root    5u     IPv4              80629        0t0        TCP *:rtsp (LISTEN)
minisatip 10424 10433                  root    6u     IPv4              80630        0t0        TCP *:tproxy (LISTEN)
minisatip 10424 10433                  root   16u     IPv4              81792        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39406 (ESTABLISHED)
minisatip 10424 10433                  root   25u     IPv4              80765        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39408 (ESTABLISHED)
minisatip 10424 10433                  root   26u     IPv4              80766        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39410 (ESTABLISHED)
minisatip 10424 10433                  root   27u     IPv4              80767        0t0        TCP dns.fritz.box:rtsp->172.17.0.7:39412 (ESTABLISHED)
`
But now other devices can also see minisatip. Before restart of minisatip, this was not the case.

Greetings,
Hendrik

**Comment by catalinii** [comment]
Hi,

can this problem be reproduced outside of container ?

I see it listens on all interfaces (which is expected).

Thanks

**Comment by henfri** [comment]
Hello,

thanks for your reply.
In fact, minisatip does *not* run in a container. Only vdr does. And VDR does work with minisatip.
Only devices on other machines cannot detect minisatip until it is restarted.

Greetings,
Hendrik

**Comment by catalinii** [comment]
Hi,

Can you upload logs indicating the period where it stops replying to clients?

Thanks

**Comment by henfri** [comment]
Hello,

I fear, we still have a mis-understanding of what happens:
1) I boot the server. Minisatip is started automatically with the script below. It runs natively on this debian jessie machine with no virtualization or docker.
2) Just after boot, with no further interaction:
    -minisatip is visible to a vdr which is hosted by the same machine as minisatip and I can watch&record TV
    -http://server:8081/ is accessible and shows the minisatip http server
    -minisatip is not visible to a windows client (DVB-Viewer)
    -stopping the docker container does not make a difference
3) re-starting the service with "service minisatip restart" solves this issue. Minisatip becomes visible to DVBViewer immediately. It is also visible and usable still in vdr.

Note, that the Problem is not, that no DVB-Devices are available to minisatip because they are all used by VDR. Minisatip is not at all visible to DVB-Viewer.

netstat says:
tcp        0      0 0.0.0.0:554             0.0.0.0:*               LISTEN      985/minisatip
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      985/minisatip
udp        0      0 239.255.255.250:1900    0.0.0.0:*                           985/minisatip
udp        0      0 0.0.0.0:1900            0.0.0.0:*                           985/minisatip
this is the unchanged  after re-starting the service


the log shows:
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.227 main]: Built with tables processing
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.227 main]: Built with satip client
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.227 main]: Built with linux dvb client
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.227 main]: Built with backtrace
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.227 main]: Built without netceiver
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.227 main]: membership error: No such device
Sep 17 10:51:42 homeserver minisatip[985]: [17/09 10:51:42.426 main]: Initializing with 4 devices
Sep 17 11:48:06 homeserver minisatip[985]: [17/09 11:48:06.431 AD1]: Connection REFUSED on stream 1, closing the stream, remote 172.17.0.6:4010
Sep 17 11:48:06 homeserver minisatip[985]: [17/09 11:48:06.934 AD2]: Connection REFUSED on stream 3, closing the stream, remote 172.17.0.6:4014
Sep 17 11:48:07 homeserver minisatip[985]: [17/09 11:48:07.158 AD0]: Connection REFUSED on stream 0, closing the stream, remote 172.17.0.6:4012
(172.17.0.6 is the vdr in the docker container)
The Connection REFUSED does not appear after restarting the minisatip service


more /etc/systemd/system/minisatip.service
[Unit]
Description=Multi-threaded SAT>IP server
After=network-online.target
Wants=network-online.target

[Service]
User=root
Group=root
WorkingDirectory=/var/lib/minisatip
Type=simple
EnvironmentFile=/etc/default/minisatip
ExecStart=/usr/bin/minisatip -f $SERVER_ARGS

[Install]
WantedBy=multi-user.target

Greetings,
Hendrik

**Comment by tmn505** [comment]
Run
`systemctl list-units`
and search for Your network device minisatip should listen on, for example
`sys-subsystem-net-devices-enp0s25.device`
Add something like this to Your minisatip.service
```
Requires=sys-subsystem-net-devices-enp0s25.device
After=sys-subsystem-net-devices-enp0s25.device
```
Also would be good if this interface has static IP.

**Comment by henfri** [comment]
Hello,

thanks for your help.
Unfortunately, I still did not succeed:
```
[Unit]
Description=Multi-threaded SAT>IP server
After=network-online.target sys-devices-pci0000:00-0000:00:19.0-net-eth0.device
Wants=network-online.target
Requires=sys-devices-pci0000:00-0000:00:19.0-net-eth0.device

[Service]
User=root
Group=root
WorkingDirectory=/var/lib/minisatip
Type=simple
EnvironmentFile=/etc/default/minisatip
ExecStart=/usr/bin/minisatip -f $SERVER_ARGS

[Install]
WantedBy=multi-user.target

```

I then did a systemctl daemon-reload and a reboot.
No change compared to before :-(

Did I do something wrong?
The IP is static.

Greetings,
Hendrik

**Comment by tmn505** [comment]
You can delete previous additions. If You're using networkd, enable wait online service `systemd-networkd-wait-online.service` and ad this to minisatip.service:
```
Wants=systemd-networkd-wait-online.service
After=systemd-networkd-wait-online.service
```
Let's hope it wont introduce any race conditions.
Another hack (agnostic of used network configuration method) is to ad `ExecStartPre=/usr/bin/sleep 10`, or more seconds if the interface has no IP yet or is still not up.
If You're using `/etc/network/interface` maybe this http://unix.stackexchange.com/questions/209832/debian-systemd-network-online-target-not-working, can help You.
@catalinii How exactly minisatip  starts listening on network interface? Does it tries to listen on every interface, even if it's not up? Maybe binding to specified IP address would be better, for example 0.0.0.0?

**Comment by henfri** [comment]
Hello,

thanks, the sleep 10 does seem to work.
I wonder though, whether this feature shouldn't be impemented in minisatip itself?

Greetings,
Hendrik

**Comment by catalinii** [comment]
I think at this point there are too many dependencies of network being up.

I will close this.

Thank you
