### ISSUE TITLE
PID Update Errors

### ISSUE THREAD

**Issue by Quantomax** [catalinii/minisatip#327]
There seems to be a problem in minisatip, in updating pids during client EIT scan, if it reaches a channel, already tuned by another receiver:

Client 1 (RPI with vdr-satip) views channel A
Client 2 (vdr with vtuner/satip (and idlepowerdown patch)) on localhost does EIT scan:

If C2 tunes to C1's channel, it erases all PIDS (as seen in Web-IF):

**Streams**
**192.168.1.8:45758**
_Client: vdr-satip/2.2.3-GIT-4c45787_
127.0.0.1:34578
Pids:
Pids:

Afterwards C1 needs to switch channel to clear condition.

Bye.

**Comment by catalinii** [comment]
Hi,

Can you send me logs for this issue ?

Thanks

**Comment by Quantomax** [comment]
Hi,

> Can you send me logs for this issue ?

Yes, shure. The issue is reproducible and will need about 30 mins to
happen. What -v count should I use, so that you ca see something useful?

Regards,
Stefan Hachmann

**Comment by catalinii** [comment]
Hi,

use 
-l -l -l 

Thanks

**Comment by Quantomax** [comment]
Hi,

as requested:
192.168.1.8 VDR with satip-plugin  -> wakes server 192.168.1.9 -> minisatip
192.168.1.9 VDR with vtuner/satip ->127.0.0.1 -> minisatip
If 127.0.0.1 reaches 192.168.1.8's (master) channel while EPG-Scanning, 192.168.1.8 gets black picture

minisatip.log -> .xz -> .zip:
[minisatip.log.zip](https://github.com/catalinii/minisatip/files/560189/minisatip.log.zip)

**Comment by catalinii** [comment]
Hi,

can you tell me the exact time stamp where this happens ?

Thanks

**Comment by Quantomax** [comment]
Hi,
I think, you should monitor PID 4920 in my Log.

-> 29/10 19:30:41.364 PID 4920 packets rise normal
-> 29/10 19:30:43.633 PID 4920 gets deleted by closing stream 2. 

After that PID 4920 and picture with it are gone.

Hth,
Quantomax

**Comment by catalinii** [comment]
Hi,

I was wondering if you can reproduce this on 0.7-ca.

Thank you

**Comment by catalinii** [comment]
I think I fixed this, let me know if you can test...
