### ISSUE TITLE
Tuner management

### ISSUE THREAD

**Issue by m4r2** [catalinii/minisatip#329]
I have a pc with one dvb-s2 tuner. If two different clients (tested with SatIP DvbViewer and Aurora TV) requesting the same tb, the second shows a black screen. With two SatIP DvbViewer it works.
I think if I would have a second tuner, the second tuner would be occupied too.

**Comment by catalinii** [comment]
Hi,

Can you upload logs?

Thanks

**Comment by alc120** [comment]
Hi!
Here is the log file.
[minisatip.txt](https://github.com/catalinii/minisatip/files/560354/minisatip.txt)
Thanks

**Comment by catalinii** [comment]
Hi,

you need the same transponder frequency:

[30/10 09:28:08.928 main]: no adapter found for f:12421500 pol:2 msys:5
[30/10 09:28:08.928 main]: Dumping adapters:
[30/10 09:28:08.928 main]: 0|f: 12422000 sid_cnt:1 master_sid:0 del_sys: dvbs undefined undefined

One client has 12421.5, the other 12422.

Thanks
