### ISSUE TITLE
offtopic: future use 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#33]
serverside encryption is missing in the spec but implemted by DD octonet and dvbviewer RS
 
if we get a x_pmt parameter which is not in the spec but introduced by DD, we can adopt this also

x_pmt parameter with PMT pid=x  should be used  for the TuningDetail selection

clients recognise the if the feature is there or not  on the <modelName>OctopusNet</modelName> so we can emulate this if needed.

in debviewer RS
  UseTCP =

    0 = No CI,

    1 = Any CI (x_pmt  Session-Start and encrypted channel)

    2 = CI #1 (x_pmt for encrypted channel Sendern, x_ci=1)

    3 = CI #2 (x_pmt for encrypted channel Sendern, x_ci=2)

?src=1&freq=11303&pol=h&msys=dvbs&sr=22000&pids=0,107,1920,1925,1921,1922,1923&x_pmt=107

**Comment by vdrtuxnet** [comment]
Quite good idea 9000h!

vdr-plugin-satip as well as tvheadend (as perexg told me) are able to handle this feature

**Comment by catalinii** [comment]
Hi,

I am not sure I understand,

you mean DVBCSA decrypting ?

if I get the pmt pid, what happens next ? (how do we get the keys, who does the actual decrypting) ?

**Comment by 9000h** [comment]
no, we should only discuss the use of real CI Hardware here, all other options which may against any local law not

**Comment by 9000h** [comment]
Here is simple prog to show how to use CI's
http://fimml.at/projects/dvbdescramble

**Comment by CReimer** [comment]
I'd like to see support for OSCAM.

tvheadend and vdr (vdr-plugin-dvbapi) are using a protocol called dvbapi to handle ECM and EMM data.

**Comment by vdrtuxnet** [comment]
I think that shouldn't be the job of minisatip, a 2nd party app could do it. Solution are already available, or Manio could convert vdr-plugin-dvbapi to a stand-alone dvb-app-dvbapi or so.

I run some tests tomorrow and call back.

**Comment by catalinii** [comment]
In my opinion  the purpose of minisatip is to be used *WITH* software like tvheadend or vdr,  .. and not to replace them.

Indeed at one point I will start studying software that is using the hardware CI that is attached to the system and use that, but I would like first minisatip to be stable (and compatible with as many products on the market) and compliant with the satip standard.

Once that is done, we can go ahead and try to add another features.

**Comment by vdrtuxnet** [comment]
full ack catalini, 
minisatip have to stay lightweight and should not reinvent the wheel.

**Comment by catalinii** [comment]
I guess I will close this as we have an enhancement in the new system
