### ISSUE TITLE
PAT/PMT version issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#330]
https://github.com/catalinii/minisatip/blob/feb3f1bb45654198f541bd3621825b46786b5902/tables.c#L344
should the PMT version not calculated like 
ver = (b[5] & 0x3E) >>1;

https://github.com/catalinii/minisatip/blob/feb3f1bb45654198f541bd3621825b46786b5902/tables.c#L205 
should the PAT version not calculated like 
ver = (b[5] & 0x3E) >>1;

this are probably not the only locations in the code

**Comment by catalinii** [comment]
Hi,
see this:

https://github.com/catalinii/minisatip/blob/feb3f1bb45654198f541bd3621825b46786b5902/tables.c#L487
basically in assemble_packet b+10 becomes b+5.

Thanks
