### ISSUE TITLE
crash if logging into syslog during decrypting

### ISSUE THREAD

**Issue by michaelarlt** [catalinii/minisatip#332]
I found a strange behavior which i can reproduce every time.
If im starting minisatip within init script using parameter -g it will crash after few seconds when i'm switching to decrypted channel for whatever reason. It doesnt matter if demuxing is successfull or not.
This is reproducable with the latest git and even packaged yavdr version in xenial

yavdr version - crashing
`/usr/bin/minisatip -gllltE -x 8089 -y 554 -e 0-1,6,7 -o 192.168.7.1:2000 -s dvbc:192.168.7.5:9983 -s dvbc:192.168.7.5:9983 -a 0:0:0 -R /var/lib/minisatip -w 192.168.7.5:8070`

yavdr version - working
`/usr/bin/minisatip -fllltE -x 8089 -y 554 -e 0-1,6,7 -o 192.168.7.1:2000 -s dvbc:192.168.7.5:9983 -s dvbc:192.168.7.5:9983 -a 0:0:0 -R /var/lib/minisatip -w 192.168.7.5:8070`

similar, if im running directly from the git source
i was also testing with self built init script for the git version with the cmdline
`/sbin/start-stop-daemon --start --quiet --exe /usr/src/minisatip/minisatip --startas /usr/src/minisatip/minisatip -- -l -l -l -E -x 8089 -y 554 -e 0-1,6,7 -o 192.168.7.1:2000 -s dvbc:192.168.7.5:9983 -s dvbc:192.168.7.5:9983 -a 0:0:0 -R /usr/src/minisatip/html`
and
`/sbin/start-stop-daemon --start --quiet --exe /usr/src/minisatip/minisatip --startas /usr/src/minisatip/minisatip -- -g -l -l -l -E -x 8089 -y 554 -e 0-1,6,7 -o 192.168.7.1:2000 -s dvbc:192.168.7.5:9983 -s dvbc:192.168.7.5:9983 -a 0:0:0 -R /usr/src/minisatip/html`

same behavior. if you need me to test some constellations just let me know.
uname -a: `4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`ll /dev/dvb/*/front*
crw-rw-rw-+ 1 root video 212,  3 Nov  6 17:29 /dev/dvb/adapter0/frontend0
crw-rw-rw-+ 1 root video 212,  7 Nov  6 17:29 /dev/dvb/adapter1/frontend0
crw-rw-rw-+ 1 root video 212, 11 Nov  6 17:29 /dev/dvb/adapter2/frontend0
crw-rw-rw-+ 1 root video 212, 15 Nov  6 17:29 /dev/dvb/adapter3/frontend0`

**Comment by catalinii** [comment]
Hi,

can you upload logs.

Also run:
gdb --args /usr/src/minisatip <PARAMETERS>

and when it crashes do:
bt

and get me the output.

Thanks

**Comment by catalinii** [comment]
Hi,
this should be fixed in 0.7-ca.
If you have any more issues let me know.

Thanks
