### ISSUE TITLE
process_pmt can't find CA pid

### ISSUE THREAD

**Issue by Yuri666** [catalinii/minisatip#333]
I have few channels what not decoded by CAM.  PMT CA pid not found:

>[15/11 16:34:56.452 AD1]: PMT pid: 0032 (50), pmt_len 105, pi_len 76, sid 012D (301)
>[15/11 16:34:56.453 AD1]: PI pos 0 caid 2710 => pid 0029 (41)
>[15/11 16:34:56.453 AD1]: PI pos 12 caid 4AE1 => pid 0031 (49)
>[15/11 16:34:56.454 AD1]: PI pos 22 caid 2710 => pid 0025 (37)
>[15/11 16:34:56.454 AD1]: PI pos 32 caid 2710 => pid 002E (46)
>[15/11 16:34:56.454 AD1]: PI pos 42 caid 4AE1 => pid 0028 (40)
>[15/11 16:34:56.455 AD1]: PMT pid 50 - stream pid 0033 (51), type 27, es_len 0, pos 0, pi_len 52 old pmt -1, old pmt for this pid 0
>[15/11 16:34:56.455 AD1]: PMT pid 50 - stream pid 0034 (52), type 4, es_len 6, pos 5, pi_len 52 old pmt -1, old pmt for this pid 0
>[15/11 16:34:57.543 signal]: BW 78KB/s, Total BW: 1 MB, ns/read 5491, r: 35, tt: 192 ms, n: 0 (s: 0 ms, s_cnt 0)

After changing process_pmt functions in tables.c to decrease minimal spid:
>if (stype != 2 && stype != 3 && stype != 4 && stype != 6 && stype != 27
  -&& stype != 36 || spid < 64)
 +&& stype != 36 || spid < 50)
>continue;

CA pid was founded and decoding worked:
>[15/11 16:36:40.059 AD1]: PMT pid: 0032 (50), pmt_len 105, pi_len 76, sid 012D (301)
>[15/11 16:36:40.060 AD1]: PI pos 0 caid 2710 => pid 0029 (41)
>[15/11 16:36:40.060 AD1]: PI pos 12 caid 4AE1 => pid 0031 (49)
>[15/11 16:36:40.060 AD1]: PI pos 22 caid 2710 => pid 0025 (37)
>[15/11 16:36:40.061 AD1]: PI pos 32 caid 2710 => pid 002E (46)
>[15/11 16:36:40.061 AD1]: PI pos 42 caid 4AE1 => pid 0028 (40)
>[15/11 16:36:40.061 AD1]: PMT pid 50 - stream pid 0033 (51), type 27, es_len 0, pos 0, pi_len 52 old pmt -1, old pmt for this pid 50
>[15/11 16:36:40.062 AD1]: PMT pid 50 - stream pid 0034 (52), type 4, es_len 6, pos 5, pi_len 52 old pmt -1, old pmt for this pid 50
>[15/11 16:36:40.062 AD1]: PMT CA pid 50 len 105 ver 2 sid 301 (12d)
>[15/11 16:36:40.353 signal]: BW 199KB/s, Total BW: 4 MB, ns/read 4728, r: 9, tt: 42 ms, n: 0 (s: 0 ms, s_cnt 0)

btw, on the HB 13E, tp81 there is channel with PMT pid=40.

**Comment by catalinii** [comment]
Hi,

I will rewrite a good part of the PMT handling, this behavior will definitely changed.

Thanks

**Comment by catalinii** [comment]
Hi.

try now.

Thanks

**Comment by Yuri666** [comment]
All works ok, thanks!
