### ISSUE TITLE
Suggestion: Change LOG level 3 to 4 of some lines.

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#334]
Hi @catalinii ,

Similar to my suggestion #297 and my comments in #314, I have this suggestion:

Please, move these logs from level 3 to level 4 in "minisatip.c":
http://github.com/catalinii/minisatip/blob/1acc614b953fafabe3175646b37d8c2ee531e38b/minisatip.c#L766
http://github.com/catalinii/minisatip/blob/1acc614b953fafabe3175646b37d8c2ee531e38b/minisatip.c#L1035
http://github.com/catalinii/minisatip/blob/1acc614b953fafabe3175646b37d8c2ee531e38b/minisatip.c#L1164
http://github.com/catalinii/minisatip/blob/1acc614b953fafabe3175646b37d8c2ee531e38b/minisatip.c#L1488

The reason is quite simple: when running ministip in a environment with multiple devices, not only the client to debug connects to the server, but also other UPNP clients. Then, I prefer to move these logs related to XML gets and SSID to the next level. Then it's more easy to debug the relevant info in a real environment (using the log level 3).

You agree?

**Comment by catalinii** [comment]
Hi,

Log level >=4 has too much garbage, and are used only if something really bad happened. Those lines (and ll 3)  are generally for me to be able to understand what is going on if there is an issue.

You can use levels lower than 3 if you mind them.
Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

I'm doing also some debug, and I really need the level 3. So, please think you on this:

- The minisatip source code has very few "LOGL(4,..." messages. Then you can take this way: Level>=5 is very large garbage; and Level=4 is only a lot more that level 3.
- Why you need to show the content of SSDP responses of other clients when you're debugging a connected client?

At minimum move lines 1164 & 1488 to level 4.
I hope you accept it!
Regards.

**Comment by catalinii** [comment]
I have implemented log levels for specific modules, please take a look and let me know if it's better.

Thanks
