### ISSUE TITLE
RFE: Add cmd option for correct ad_strength & ad_snr values

### ISSUE THREAD

**Issue by tunip** [catalinii/minisatip#335]
In status.html I can edit this values to my needs.

![signal_msip](https://cloud.githubusercontent.com/assets/11404472/20385906/a26162d2-acb9-11e6-96f9-962fa2a2fbc8.jpg)
```
var s1 = parseInt(ad_strength[i] / 1.55);
         signal = "<div class='level'>STR <div class='pBar' data-from='"+ s1 + "' data-to='" + s1 + "'></div> " + s1 + "%</div><br />";
         if (ad_type[i] == 1 || ad_type[i] == 3)
                 var s2 = parseInt(ad_snr[i] / 0.80);
```

But in Tvheadend the values are complete wrong.
![signal_tvh](https://cloud.githubusercontent.com/assets/11404472/20385918/af72b1e2-acb9-11e6-9cfb-b7340cb0abb7.jpg)

It would be nice to add a cmd option like this `--strength 1.55 --snr 0.80`, where you can set what fit your needs.

Then all clients have the correct STR an SNR values.

Thx

**Comment by lars18th** [comment]
+1

Several devices/drivers have different STR & SNR ranges. I suggest to use specific values for each adapter for tweak them.

Regards.

**Comment by catalinii** [comment]
Hi,

if the issue is that the signal and snr provided by the driver are off, I cannot do too much about it, as it should be fixed in the driver.
Here is the new dvbapi specs: 
http://webcache.googleusercontent.com/search?q=cache%3Awww.linuxtv.org%2Fdownloads%2Fv4l-dvb-apis%2Ffrontend-properties.html&rlz=1C1CHFX_enAU683AU683&oq=cache%3Awww.linuxtv.org%2Fdownloads%2Fv4l-dvb-apis%2Ffrontend-properties.html&aqs=chrome..69i57j69i58.1537j0j4&sourceid=chrome&ie=UTF-8

search for DTV_STAT_SIGNAL_STRENGTH 

If the values from minisatip as they are, are different from the ones shown in tvh for example, then let me know and I can look what is different.

**Comment by tunip** [comment]
Hi catalinii,

I am with you. But DigitalDevices are very resistant about changes user would have in their drivers.

Made a few tests with Tvheadend using the adapters directly and with minisatip.

Tvheadend standalone:
![tvh_direct](https://cloud.githubusercontent.com/assets/11404472/20595086/dfdc645c-b238-11e6-877c-16fc1ee00bdc.jpg)

Tvheadend standalone (old status):
![tvh_direct_oldstatus](https://cloud.githubusercontent.com/assets/11404472/20595097/ef8ee712-b238-11e6-841a-c4e511a03ee1.jpg)


In Tvheadend you can only tune signalstrength but not SNR if we use satip. 

Tvheadend with minisatip (signalrange 240):
![tvh_minisatip_240](https://cloud.githubusercontent.com/assets/11404472/20595138/16ddf4de-b239-11e6-9928-e572076aac3a.jpg)

Tvheadend with minisatip (signalrange 100):
![tvh_minisatip_100](https://cloud.githubusercontent.com/assets/11404472/20595153/2029ecbe-b239-11e6-8608-f5fb5d358727.jpg)

minisatip would be the central software/distributor in my environment, which will have access to the local dvb-adapters and other satip-servers. Thats the idea behind this request, let the user tune some values in minisatip if the driver or satip-server gives you wrong/bad numbers.
I used this device (http://www.durasat.de/messgeraete/dur-line-sf-4000-bt-satfinder.html) to adjust my dish. Now I have more or less trusted SNR and STRENGTH values. If I could adjust/tune SNR and STRENGTH in minisatip to the same values from that sat-finder device, then they would more "real" and comparable.
I also have a unused DD Octopus Net V1 here. If I want to use this device with minisatip, then all values are mixed and wrong.

Thx

**Comment by catalinii** [comment]
Hi,

I will keep this in mind for future versions, but 2 parameters does not require too much work,

Thanks

**Comment by lars18th** [comment]
Hi,

+1 for more tweaks.

And remember to improve the SAT>IP client mode!

**Comment by 3PO** [comment]
Maybe it is better to show real values in "dbm" instead "%"?

This is the issue from the Webinterface:

![2017-01-24_222813](https://cloud.githubusercontent.com/assets/945108/22268396/b50e5cc4-e287-11e6-955b-514bd6b5943e.png)

and this is the issue form "dvb-fe-tool":

**DVB-S(2):**

```
server02 ~ # dvb-fe-tool -a0 -f0 -m -c1
       (0x00) Signal= -29,89dBm C/N= 0,00dB postBER= 31,5x10^-6 
```

```
server02 ~ # dvb-fe-tool -a0 -f1 -m -c1
Lock   (0x1f) Signal= -26,61dBm C/N= 12,37dB postBER= 0 preBER= 0
```

```
server02 ~ # dvb-fe-tool -a0 -f2 -m -c1
       (0x00) Signal= -37,69dBm C/N= 10,84dB postBER= 1,78x10^-6 preBER= 0

```
```
server02 ~ # dvb-fe-tool -a0 -f3 -m -c1
       (0x00) Signal= -28,38dBm C/N= 12,85dB postBER= 0 preBER= 0

```
```
server02 ~ # dvb-fe-tool -a0 -f4 -m -c1
Lock   (0x1f) Signal= -27,76dBm C/N= 13,65dB postBER= 4,27x10^-6 preBER= 0

```
```
server02 ~ # dvb-fe-tool -a0 -f5 -m -c1
       (0x00) Signal= 0,00dBm

```

**DVB-T:**

```
server02 ~ # dvb-fe-tool -a2 -f0 -m
Lock   (0x1f) Signal= 71,51% C/N= 23,30dB preBER= 0
server02 ~ #
```

**Comment by catalinii** [comment]
I have added -M to be able to specify multiplier for strength and snr.

As the the value of the Strength is negative, 100 is added. ( -40 dbM => 60 %).

**Comment by tunip** [comment]
Hi,

thx for the implementation. Th strength value could be changed successfully. But snr does not change on different values.

Right I use:
`-M 0-3:1.3-1.6`

**Comment by catalinii** [comment]
Hi,

sorry for the late reply, are you checking the web interface ?

Thanks

**Comment by tunip** [comment]
Hi, 

yes, I am using the webinterface.

**Comment by tunip** [comment]
Latest master works fine now. I can set it to the my needed values (-M *:1.3-6).

minisatip:
![image](https://user-images.githubusercontent.com/11404472/31671512-693a7a0e-b35a-11e7-847e-f10d4a5ba012.png)

Tvheadend:
![image](https://user-images.githubusercontent.com/11404472/31671555-82458926-b35a-11e7-8806-9aac558fdf44.png)

Many Thanks!

I close here.
