### ISSUE TITLE
Possible fix for glitches when OSCAM timeout

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#337]
Hi @catalinii ,

After much debug of my troubles described in #203 I think I found the problem and how to solve it:

* The problem appears as "freezes" or "glitches" when you have one "slow card server".

* One way to reproduce the problem is set a ridiculous low "client timeout" value in Oscam, like 150ms or less. See: http://www.streamboard.tv/wiki/OSCam/en/Config/oscam.conf#clienttimeout

* As the current DVBAPI protocol is async (see:  http://github.com/trevd/android_external_oscam/blob/master/README.dvbapi_protocol )
then when the "client tiemout" expires you don't receive any "ERROR" or similar response.

* Instead of the previous, when the Oscam server triggers the "client timeout" the response received is "DMX_STOP" related to the ECM pid corresponding to the program to decrypt.

* After that, minisatip correctly resends the ECM key request. And this is right.

However, the problem is when the minisatip receives the DMX_STOP command.
In this case, it always invalidates de current key! See: http://github.com/catalinii/minisatip/blob/a5c6903886fc1cdeb08cf5e17ca54a57d7448594/dvbapi.c#L212

But this has a problem: When you ask for the **next** key (i.e. "1" is valid and you request for "0"), and you receive a DMX_STOP because the timeout for the **next** key... why you need to invalidate the **current** key (i.e. "1")? I suggest to maintain the **current** key validity and not interrupt the decryption. Only resend the next key request.

I feel that the value MAX_KEY_TIME is introduced in minisatip to be in synch with the "client timeout" value in the Oscam server? It's my assumption right? In this case I suggest to document this behaviour in the README. Also I suggest to add the option to tweak this value... for example, in my current configuration I need to have a value around 3.5 seconds in Oscam, instead of the 15s. default in minisatip.

What you think, Catalinii?

**Comment by lars18th** [comment]
Hi @catalinii ,

What you think about maintain the validity of "current_key" when you receive DMX_STOP after requesting for the "next key"? It will possible that you overcome this problem? I think is not a good idea to discard the current key when it's valid. The message DMX_STOP is related to the upcoming key, not the current one.

Regards.

**Comment by lars18th** [comment]
Hi @catalinii ,

I have some channels that when I tune them the DMX_STOP response is triggered. But after this, the decrypt code never re-tryies to ask for the key. Then the channel is never opened.

Please, can you link a re-try key when DMX_STOP is received?
Thank you!

**Comment by catalinii** [comment]
Hi,

I will keep this in mind for 0.7. That part will most likely be rewritten.

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

Thank you! With the current implementation the most annoying trouble is when the decryption stops... it takes several seconds to recover or never recovers (needs a manual program change). I hope you can implement some code for solving timeouts.

Regards.

**Comment by catalinii** [comment]
Hi,

give this a try on 0.7-ca.
It is still rough, but let me know what works, what doesn't.

Thanks

**Comment by catalinii** [comment]
Hi,

can you check if this is still an issue ?

Thanks
