### ISSUE TITLE
Bug: "-t --cleanpsi" parameter don't work

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#340]
Hi @catalinii ,

In current releases the parameter "-t --cleanpsi" doesn't work!

I check it in this way:

- I open one client using the http interface (more simple to check the parameters). For example with pids "0,17,18" & PMT, Video/Audio, EMM of the channel. This starts to decrypt and play it.

- I open a second client that shows the PAT/PMT tables (TSReader, TransEdit, etc.) over the same frequency and/or the same program. The result is: The program continues to be signalized as encrypted.

Please, can you review the code?
Thank you!

**Comment by catalinii** [comment]
Hi,

are you saying for one channel the PMT is cleaned for one is not ?
or is cleaned for both (or none ) ?

Thanks

**Comment by marian3** [comment]
Hi, I don't know, but it also seems to me that the switch doesn't work. I have a sat / ip client vu + zero (VTi 13), which will snap the image every time dcw changes. Decodes a decoded program.
Of course, the freeze shouldn't be there (I'll try to find out the cause).
But if I told the client that it was a decoded channel, it would no longer try to decode it.

**Comment by catalinii** [comment]
Does it work if you do not use the switch? Generally the switch lets the client know the channel is free (instead of encrypted). But in both cases the stream is decrypted by minisatip. If you see glitches during CW changes may noy be related to this switch.

**Comment by marian3** [comment]
Hi, I'm not saying the problem is with this switch. I thought this switch could solve the problem, albeit unsystematically.

**Comment by lars18th** [comment]
Hi @catalinii ,

After years I've identified the bug. Please commit the PR #915 that fixes it! 😉
