### ISSUE TITLE
RFE: DVB-S2X test channel Astra 19.2

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#341]
is someone out there with a TBS6522 to test?

Digital Devices Cine S2 version 7 or Max-S8 are not able to handle DVB-S2X

http://www.sat-universe.com/showthread.php?p=2036712222
http://www.isatdb.com/de/channel-frequency/ses-uhd-demo-channel-dolby-labs-test-stream--lqyl
http://www.areadvd.de/news/ses-ultra-hd-tests-mit-dvb-s2x-auf-astra
reference to the standard
https://www.dvb.org/resources/public/standards/a83-2_dvb-s2x_den302307-2.pdf

https://rickcaylor.websitetoolbox.com/post/about-new-tbs-cards-dvbs2x-8171928
http://www.tbsdtv.com/forum/viewtopic.php?f=195&t=10021

another one at Eutelsat 33C 33E New DVB-S2X Mux 12621V SR 10058 FEC 25/36 

https://sourceforge.net/p/crazyscan/code/141/

**Comment by tunip** [comment]
I use a Max-S8 with latest drivers. How can I test this?

**Comment by 9000h** [comment]
you may can test with ffplay,vlc etc. and you need to create a valid url from the info
http://www.isatdb.com/de/channel-frequency/ses-uhd-demo-channel-dolby-labs-test-stream--lqyl

**Comment by 9000h** [comment]
but it's probably not working right now, the Max-S8 hardware should work (not sure if there are a major difference between v1 and v2 in regards to the demod)
not sure if the DD drivers ready right now, and in minisatip there are also changes needed

**Comment by catalinii** [comment]
Hi,
It does not seem that the dd drivers supports dvb-s2x  yet.

When they will let me know and I can get it implemented.

Thanks

**Comment by 9000h** [comment]
Digital Devices Cine S2 version 7 or Max-S8 are not able to handle DVB-S2X

**Comment by catalinii** [comment]
When someone have HW available I can try to integrate code into minisatip...

Please let me know here.

**Comment by 9000h** [comment]
looks like there is something going on
https://github.com/DigitalDevices/dddvb/commit/f7e8b25e020f7bf0e9f161c3ce3e48442702b83b

**Comment by 9000h** [comment]
I do have a TBS5520SE here will try if I can get it to work on a DVB-S2X transponder

**Comment by catalinii** [comment]
If it is all about a modulation it should be a simple change.

Thanks

**Comment by 9000h** [comment]
will try it out in the next days an report here

**Comment by catalinii** [comment]
You might need to add the modulation string here:
https://github.com/catalinii/minisatip/blob/master/src/dvb.c#91 except
defining the values  in front end.h

**Comment by 9000h** [comment]
maybe not as the kernel/driver support for S2X is unclear 
https://tvheadend.org/issues/4075#note-6

**Comment by 9000h** [comment]
as there is no transponder to test anymore on 19.2E or 13.0E I will close it
