### ISSUE TITLE
Info: 0.7 issues

### ISSUE THREAD

**Issue by catalinii** [catalinii/minisatip#343]
Hi,

I am adding a new branch which will incorporate new features around handling of PMTs to facilitate adding new CA modules.

If you see any issues, regarding dvbapi, CI, ... please feel free to open an issue, and include 0.7 in the title.

Thanks

**Comment by catalinii** [comment]
MOstly the work will be on the CA side:
- dvbapi changes 
- moving CSA/AES implementation to the pmt module
- store information like channel name for PMT, CAIDs, ...
- adding support for another CA hardware/ CI modules

thanks

**Comment by catalinii** [comment]
including DD CI implementation

**Comment by lars18th** [comment]
Thank you!

Good information! Then the decryption part will be the most rewrited. Any other new?

**Comment by lars18th** [comment]
Hi @catalinii,

I started to test the branch 0.7 (last commit):

1) The web UI doesn't work: it shows an empty page with only the "reload buttons".

2) Continues the problem with interruptions in decoding when a timeout in the Oscam server appears (see issue #337 ). I hope you can include some code for "re-send" ECMs when a timeout is triggered.

For the reset, it seems to work right.
Good job!

**Comment by tunip** [comment]
@lars18th  web UI works fine here on branch 0.7.  Maybe browser cache?

**Comment by lars18th** [comment]
Hi @tunip ,

I feel you don't updated the subdirectory "html" where you run the minisatip executable.
In my server, using the last commit of the branch "0.7" the UI is boggus! Tested with Chrome and Explorer.
Also, the Chrome debug indicates:

`Uncaught SyntaxError: Invalid or unexpected token                        (index:87)
`

**Comment by lars18th** [comment]
Hi @catalinii ,

Please, review the quotes ( " ) in this file... you lost some of them:
http://github.com/catalinii/minisatip/blob/0.7/html/status.html#L87

Regards!

**Comment by lars18th** [comment]
Hi @catalinii ,

This line also needs to use quotes:
http://github.com/catalinii/minisatip/blob/0.7/html/status.html#L113

I changed it to

`var has_axe     = "$has_axe$";
`

Now, my UI works (after add quotes in 87,88 and 89 lines).
However, I have a problem: I see my three tuners (0,1,2) and some undefined from 16-31.

Please, can you fix the WEB interface?
Thank you!

**Comment by catalinii** [comment]
The page should be fixed now. Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> The page should be fixed now. Thanks

Thank you!
However, I can't test it. It doesn't compile! See #348

**Comment by 9000h** [comment]
Close?

**Comment by lars18th** [comment]
> Close?

Yes, please!

**Comment by lars18th** [comment]
Please @catalinii , close this old issue!
