### ISSUE TITLE
0.7 online handling CAM errors

### ISSUE THREAD

**Issue by Yuri666** [catalinii/minisatip#345]
I have several CAM modules. In some of these, sometimes errors EN50221ERR_CAWRITE and EN50221ERR_TIMEOUT occur during operation.
I think it depends on the timing settings in the DVB-Apps, but it would be nice if minisatip can handle these errors.
That's when the error occurred:
> [05/12 07:09:20.907 signal]: BW 1631KB/s, Total BW: 4451 MB, ns/read 1793, r: 66, tt: 118 ms, n: 0 (s: 0 ms, s_cnt 0)
>[05/12 07:09:21.789 AD1]: no data sent for more than 1s sid: 0 for 192.168.1.2:48375
>Message repeated 8 times
>[05/12 07:09:30.738 CA1]: Error reported by stack slot:0 error:-3
>[05/12 07:09:31.215 AD1]: no data sent for more than 1s sid: 0 for 192.168.1.2:48375
>Message repeated 2 times
>[05/12 07:09:33.422 main]: read RTSP (from handle 8 sock_id 7, len: 0, sid 0):
>[05/12 07:09:33.423 main]: reply -> 8 (192.168.1.2:48375) CL:0 [sock_id 7]:
>[05/12 07:09:34.423 AD1]: no data sent for more than 1s sid: 0 for 192.168.1.2:48375
>Message repeated 11 times

Channel switching is not helping.
But if switch from the channel and wait for the closing of the adapter, after the next switching channel starts:
>[10/12 19:22:27.022 AD1]: Requested adapter 1 close due to timeout, result 1 max_rtime 0
>[10/12 19:22:27.023 AD1]: sockets_del: 9 -> handle 11, sid 1, overflow 0
>[10/12 19:22:27.023 AD1]: closing DVR socket -1 pos 9 aid 1
>[10/12 19:22:27.023 AD1]: closing adapter 1  -> fe:9 dvr:11
>[10/12 19:22:27.023 AD1]: adapter.c:814: get_adapter returns NULL for adapter_id 1
>[10/12 19:22:27.023 AD1]: adapter.c:612: get_adapter returns NULL for adapter_id 1
>[10/12 19:22:27.023 AD1]: closing CA device 1, fd 12

It would be fine, as a workaround, if minisatip doing re-open adapter if there were errors -2 and -3 appears. (Maybe enough re-open CA device, need tests)

**Comment by catalinii** [comment]
Hi, I need to improve this part on 0.7.

Will keep this open to handle better such cases.

Thanks

**Comment by catalinii** [comment]
If someone can reproduce this please let me know.
I can try fixing it on 0.7-ca
