### ISSUE TITLE
SAT>IP server app for Android ?

### ISSUE THREAD

**Issue by bluepuma77** [catalinii/minisatip#346]
Hi, have you thought about creating a DVB2IP Android app using SAT>IP protocol on the basis of this project? It seems more and more Android TV-boxes with DVB-Tuner(s) show up, but a good Android app for TV networking like SAT>IP server or tvheadend server is still missing. And if using SAT>IP, you even have a standard that some TVs already implement.

Some Andoid box examples:
WeTek Play TV
Videostrong K1 Plus T2 S2
VideoStrong KII Pro Android Set-top Box with DVB-T2 & DVB-S2 Tuners
Xtreamer mxV Plus DVB-T2 and mvX Pro DVB-T2/DVB-S2 Combo TV Boxes
Geniatech ATV1960 Octa-core Android TV Box Comes with a Dual TV Tuner
http://www.cnx-software.com/tag/dvb/

**Comment by CvH** [comment]
WeTek Play 1/2 have support for Linux (LibreELEC) where Tvh and VDR runs very well (just for info).

An android app would be nice for the other boxes but I guess the horrible drivers will prevent this.

**Comment by catalinii** [comment]
Hi,

if those devices that you've mentioned have /dev/dvb/adapter0/{demux0,frontend0,dvr0} is just a matter of compiling minisatip on android.

If they do let me know and I can try to get an android version out for test.

Thanks

**Comment by lars18th** [comment]
Hi,

> if those devices that you've mentioned have /dev/dvb/adapter0/{demux0,frontend0,dvr0} 
> is just a matter of compiling minisatip on android.

In Android devices the Linux DVB API is a pain. I suggest to compile minisatip with a "dynamic" path for "devices". Just say: with the option for setting the main path for these devices...

for example:

```
$ minisatip \
-demux-path "/local/device/dvb/ad/dmx" \
-frontend-path "/local/device/dvb/ad/fe" \
-dvr-path "none"
```

I think this is the only way for include some support for Android devices.

**Comment by catalinii** [comment]
If you do not have DVR device is still possible but the current implementation needs to be changed.

**Comment by lars18th** [comment]
Hi @catalinii ,

I don't say that DVR device doesn't exist! I say that some implementations dont have it. So, for a wide support, it's preferable to support only the minimum: DEMUX and FRONTEND. I'm not sure, but I feel DVR is only for hardware filtering, right?

In any case, if you need DEMUX, FRONTEND and DVR devices, the first trial is add support for map them. From my experience, a lot, if not all, Android devices with DVB tuners doesn't use regular pathes for dvb. So, my suggestion is quite simple: add support for alternative pathes. In any case, the ioctrl calls are the same (or very close).

If you can provide this support, we can test it on some devices.
You agree?
Regards!

**Comment by catalinii** [comment]
hi

i tried removing the dvr code and use just the demux but it created some issues with detecting maxim number of pid filters.

So anyway both implementations are needed.

But in android there is the linux kernel so dvr device should be there

**Comment by lars18th** [comment]
Hi @catalinii ,

> i tried removing the dvr code and use just the demux but it created 
> some issues with detecting maxim number of pid filters.

Other projects, like TVHeadend, have the option for setting the MAX_PIDS for each tuner/device. So, why not use this approach?

- Let the user to disable DVR device and set the max pids (by default 24 or 32, as you prefer).
- In any other case, the DVR device is used.

What you think?

> But in android there is the linux kernel so dvr device should be there

The Android kernel is a mix of Linux kernel and a lot of patches. At time, Google refusese to include full support for DVB inside the Android kernel. Then most manufacturers are using alternative approaches for boxes with Tuners: A few of them are patcheing the kernel and using standard DVB devices; A lot use alternative pathes (like /usr/local/dvb/) for custom kernel drivers; and some other use user-level drivers (with also alternative pathes).

So, my suggestion is very simple: at time only add support for alternative device pathes.

You agree?

**Comment by catalinii** [comment]
Hi Lars,

I think if someone is interested in this and can give access to a device then we can analyse if we can offer a solution for all the devices.

Otherwise, probably LibreELEC or something similar is the best way forward.

Thanks

**Comment by catalinii** [comment]
To make it easier for the application to be ported on Android, I did some changes:

1) https://github.com/catalinii/minisatip/blob/0.7-ca/dvb.c#L47

The DVB devices can be changed from here, no need to replace in all the source

2) https://github.com/catalinii/minisatip/blob/0.7-ca/minisatip.c#L510
opts.use_demux_device: if set to 1, the dvr device will not be used

3) To compile in android, edit the following in Makefile (once you have the Android NDK):

CC=<path_to_NDK>/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
CFLAGS?=-fPIE --sysroot=<path_to_NDK>/ndk-bundle/platforms/android-16/arch-arm/ -Wall -Wno-switch -ggdb -fPIC $(EXTRA_CFLAGS)
LDFLAGS?=-pie

You can give it a try and let me know if someone is still interested in this.

Thanks

**Comment by mazafra1** [comment]
GCC is not included in Android NDK anymore. Any alternative?

Thanks.

**Comment by catalinii** [comment]
Check src/Makefile and let me know if you encounter any issues

**Comment by mazafra1** [comment]
When I perform `./configure --host=armv7a-linux-androideabi16 --enable-static` _src/Makefile_  gets overwritten and I lost the changes you suggested. I'm attaching my [config.log](https://github.com/catalinii/minisatip/files/4487394/config.log) file.

If I modify manually my _src/Makefile_ before launching `make` instruction, it couldn't find then some headers files (e.g. errno.h). 

So I modified the _CFLAGS_ variable, based on [Android documentation](https://developer.android.com/ndk/guides/standalone_toolchain#selecting_your_sysroot), to:
`CFLAGS?=-fPIE --sysroot=<path_to_NDK>/android-ndk-r21/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/ -Wall -Wno-switch -ggdb -fPIC $(EXTRA_CFLAGS)`

Now I don't have anymore the _errno.h_ file not found error but stuck on:
`utils.c:57:10: fatal error: 'execinfo.h' file not found
#include <execinfo.h>`
I couldn't find that file in the Android NDK. It seems [it does not exist](https://stackoverflow.com/questions/8115192/android-ndk-getting-the-backtrace). Same error using the parameter suggested in the Stackoverflow article: `-funwind-tables`.

Sorry my inexperience but it's my first time compiling for Android.
Thanks!

**Comment by catalinii** [comment]
Hi,

edit src/Makefile and change EMBEDDED=1
Thanks

**Comment by mazafra1** [comment]
OK. That did the trick!! We passed over that point. Now it seems Android NDK lacks of a _sendmmsg_ implementation:
`socketworks.c:0: error: undefined reference to 'sendmmsg'`

Besides flag -lrt does not exist on my mac os version, so I commented it out.

Thanks.

**Comment by lars18th** [comment]
Hi @mazafra1 ,

> OK. That did the trick!! We passed over that point. Now it seems Android NDK lacks of a _sendmmsg_ implementation:
> `socketworks.c:0: error: undefined reference to 'sendmmsg'`

If you see the code https://github.com/catalinii/minisatip/blob/49290afdaf48e39766e04ed459f1594bfa47d425/src/socketworks.c#L1296
then you can check that the APPLE implementation lacks it too.

So, I recommend to try this: change this line https://github.com/catalinii/minisatip/blob/49290afdaf48e39766e04ed459f1594bfa47d425/src/socketworks.c#L1289
to `#if defined(__APPLE__) || defined(__ANDROID__)`

**Comment by mazafra1** [comment]
That made the compilation work completely. Thanks!!!

Now I’m trying to execute the program but it requires root permissions, right? Is that mandatory? Since some Android boxes may not have been rooted this could be a show stopper. Can we overcome this in any way?

Thanks.

**Comment by lars18th** [comment]
> That made the compilation work completely. Thanks!!!

:wink: 

 
> Now I’m trying to execute the program but it requires root permissions, right? Is that mandatory? Since some Android boxes may not have been rooted, this could be a show stopper. Can we overcome this in any way?

To overcome the root requirement, you need to:
- Not use IP ports below 1024. So you need to configure, almost to listen in a non default :554 for the RTSP.
- Not use real tuners. If your Android device has internal tuners, then you need to check if the filesystem devices are accessible (readable) from the console. Some manufacturers use non-standard paths to overcome this limitation.

So, please check first with the `satipc` module using remote SAT>IP servers.

Regards.

**Comment by lars18th** [comment]
Hi @catalinii ,

https://github.com/catalinii/minisatip/blob/49290afdaf48e39766e04ed459f1594bfa47d425/src/socketworks.c#L1289
> 
> 
> to `#if defined(__APPLE__) || defined(__ANDROID__)`

Why not commit/merge this change?

**Comment by mazafra1** [comment]
Thanks for your support @lars18th !!

Going forward you mentioned:
>  To overcome the root requirement, you need to:
>
>     * Not use IP ports below 1024. So you need to configure, almost to listen in a non default :554 for the RTSP.
So, from documentation, the right parameter to use would be `-y --rtsp-port rtsp_port: port for listening for rtsp requests [default: 554]`, right?


>     * Not use real tuners. If your Android device has internal tuners, then you need to check if the filesystem devices are accessible (readable) from the console. Some manufacturers use non-standard paths to overcome this limitation.
Doing a 'ls -l /dev' gives me these 2 devices as "suspicious" to be my 2 tuners (Dvb-S2 and Dvb-T2), am I correct?
`crw------- 1 root      root         251,   0 2015-01-01 01:00 0:0:0:0`  
`crw------- 1 root      root         251,   1 2015-01-01 01:00 0:0:0:1`

> So, please check first with the `satipc` module using remote SAT>IP servers.
I don't know what this exactly mean.

Besides, my device has a read-only file system. I believe this may be a problem.

**Comment by mazafra1** [comment]
Some of my findings:

HTTP server starts well on port 8080. Though it does NOT serve some webpages (e.g. status.html) but serves other well (desc.xml):
![imagen](https://user-images.githubusercontent.com/31898896/79687113-52b26a00-8245-11ea-8153-91ae3a1b639a.png)



But I think main thing for now  is that it's not finding any tuner (should I indicate somehow what tuners the minisatip server should use?):
![imagen](https://user-images.githubusercontent.com/31898896/79687109-4d551f80-8245-11ea-8e50-e833e73fddae.png)

**Comment by lars18th** [comment]
Hi @mazafra1 ,

First, I have some experience with STBs, and related to STB based on Android, it's **very hard** to found a model with Linux DVB API support. So, regarding minisatip and your device **by default** it's very difficult that it can found _any_ tuner. So, you need first to search for the tuners devices. Perhaps you want to try other Linux tools like "mumudvb", for example, to search/try/use Linux DVB tuners. Search for "demux" and "dvb" devices. When you found them, then you can try with the parameters `--dmx-source` and `--demux-dev` when run minisatip.

My initial suggestion about the use the "satipc" module, it's because the lack of internal tuners. So, using an external SAT>IP server in you network (it can be another minisatip running in a regular Linux box), you can test the minisatip in Android using this external tuner.

So, if it's your objective to use minisatip to export the tuners in an Android STB, then my response is: you're far to achive that at this moment. The biggest problem is the Linux DVB API. Regular Android boxes with DVB tuners *don't have* this API implemented. So it's imposible to use these devices until some public API is published and minisatip will implement this support. What device are you using?

But if your objective is only to run minisatip inside the Android platform, using network tuners... then this can be done. The current code can be compiled with minimal changes.

Regards.

**Comment by mazafra1** [comment]
Thanks @lars18th !

Yes, my objective would be to use minisatip to export the tuners in an Android STB. My STB model is Viark droi. Specs here: [Hi3798MV200.pdf](https://github.com/catalinii/minisatip/files/4499069/Hi3798MV200.pdf)

I'd give a try to [mumudvb](https://github.com/braice/MuMuDVB) and let you know.

**Comment by retrofan1979** [comment]
> But if your objective is only to run minisatip inside the Android platform, using network tuners... then this can be done. The current code can be compiled with minimal changes.
> 

Hi, how can I compile it for Android so I will get an APK file? I would like to test with these SAT>IP servers:

Fritz!WLAN Repeater DVB-C
Geniatech EyeTV Netstream 4C

Thanks!

**Comment by Jalle19** [comment]
@mazafra1 did you ever get mumudvb to work on your Android STB?

**Comment by mazafra1** [comment]
> @mazafra1 did you ever get mumudvb to work on your Android STB?

No

**Comment by Jalle19** [comment]
Okay, do you remember what the problem was?

**Comment by mazafra1** [comment]
> Okay, do you remember what the problem was?

Sorry, I do not really recall. This was a long time ago and I abandoned the investigation. Looking at the thread history, from @lars18th reply, I believe that "_Regular Android boxes with DVB tuners don't have the Linux DVB API implemented_" may be the show stopper here.

**Comment by lars18th** [comment]
Hi,

Over many years what I have seen is that it is very uncommon for an Android box having support for the Linux DVB API. So don't waste your time triying this. Only if using ad-hoc APIs for DVB on these boxes you can handle the tuner.

**Comment by Jalle19** [comment]
Alright
