### ISSUE TITLE
Unicable/ JESS does not apply to Netceiver

### ISSUE THREAD

**Issue by 22101** [catalinii/minisatip#347]
Perhaps you could apply it in next versions.

**Comment by catalinii** [comment]
@REELcoder do you have any input how unicable/jess can be set on netceiver?

Thanks

**Comment by 9000h** [comment]
as far as I know Jess is not supported by the Netceiver, and a valid config may has to downloaded to get it work.
like 
netcvupdate -A -U netceiver.conf

**Comment by 22101** [comment]
I will try to download the working unicable conf with a reelbox

**Comment by REELcoder** [comment]
@catalinii I have no further information. At some point REEL introduced Unicable as per standard EN50494 but JESS as per standard EN50607 is not supported. Using a Reelbox is for sure the most convenient way to configure the netceiver.

**Comment by 22101** [comment]
Please have a look...
[netceiver.conf_normal.txt](https://github.com/catalinii/minisatip/files/717276/netceiver.conf_normal.txt)
[netceiver.conf_unicable.txt](https://github.com/catalinii/minisatip/files/717277/netceiver.conf_unicable.txt)

**Comment by 9000h** [comment]
@22101 please close as this is not a minisatip issue

**Comment by 22101** [comment]
Can you explain it to me? In support forum cata wrote that i have to open an issue here? I understand, that JESS wouldn´t be supported by Netceiver itself but the older Unicable should work?

**Comment by 9000h** [comment]
I can not test here but Unicable may work, Jess is not supported by the Netceiver.

**Comment by 22101** [comment]
The question is, how does minisatip manage the classic configuration (without unicable)? Is a new netceiver.conf generated and uploaded to netceiver, when i changed parameter "/u"? I hope you understand my confusion.

**Comment by catalinii** [comment]
As the issue cannot fixed in minisatip code, I will close this.
The forum link:
https://minisatip.org/forum/viewtopic.php?f=5&t=404

Thanks
