### ISSUE TITLE
RFE: AVM FRITZ!WLAN Repeater DVB-C tuner bind source ip address

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#349]
Hi,

would be great if we can add a this feature to the client support, AVM did limit it to one tuner per ip.
please see also the TVH support for this kind of satip server
https://tvheadend.org/boards/4/topics/18013?r=22619#message-22619

the local network needs to be prepared with additional local ip's for eth0:1 eth0:2 eth0:3 eth0:4 
the affected AVM devices are:
AVM FRITZ!WLAN Repeater DVB-C (2 tuners)
AVM FRITZ!BOX 6490 (DVB-C 4 tuners)

CU
9000h

**Comment by catalinii** [comment]
Hi,

I'll keep this in my mind.

Thanks

**Comment by 9000h** [comment]
the implementation looks like https://github.com/rofafor/vdr-plugin-satip/commit/3a9dc9a6348b50995ed39ad274e1c47eae670051

**Comment by catalinii** [comment]
Hi,

does it support RTSP over tcp ? or just over UDP ?
You can test with minisatip -O -s dvbc:xxx

Thanks

**Comment by 9000h** [comment]
from the history (2014) they did not support rtsp over tcp but will check if the actual firmware supports it

**Comment by catalinii** [comment]
Hi,

I don't think it actually matters. The tcp connection comes from a different IP now with:

-s dvbc:source_ip/repeater 

Thanks

**Comment by 9000h** [comment]
will try it out to night

**Comment by 9000h** [comment]
rtsp over tcp is not working with the Fritz!Box 6490 Cable / Fritz!Box 6490 Repeater DVB-C but udp is working, maybe we can add a note to the readme

**Comment by catalinii** [comment]
You were not able to have it work ?

**Comment by 9000h** [comment]
looks like a udp bind ip is also needed, I could only get one stream to work

**Comment by catalinii** [comment]
Interesting because udp bind is on 0.0.0.0 by default so it listens on all
interfaces.

tcpdump shows the tcp packets going grom different ips?

**Comment by 9000h** [comment]
not sure what I had done wrong but with the git from today it works 
![grafik](https://user-images.githubusercontent.com/3009073/28767071-96c1fa1c-75d2-11e7-9e1b-ccf6233935b8.png)
![grafik](https://user-images.githubusercontent.com/3009073/28767092-a725ed14-75d2-11e7-93fe-90abdb4cbce8.png)

**Comment by 9000h** [comment]
there is one limitation I have found:
2 different channels on different freq is ok
2 times the same channel on the same freq is ok
2 different channels on the freq is not working  with the Fritz!Box as the box may do not support it

**Comment by 9000h** [comment]
upps got a crash with today git
```
Aug  1 16:58:48 satip minisatip[26399]: [01/08 16:58:48.757 main]: Mutex init 0x95715e4
Aug  1 16:58:48 satip minisatip[26399]: [01/08 16:58:48.757 main]: sockets_add: handle 15 (type 1) returning socket index 16 [192.168.178.104:59025] read: 0x8050659
Aug  1 16:58:48 satip minisatip[26399]: [01/08 16:58:48.758 main]: read HTTP from 15 sid: -1:
Aug  1 16:58:48 satip minisatip[26399]: [01/08 16:58:48.758 main]: POST /state.json HTTP/1.1
Aug  1 16:58:48 satip minisatip[26399]: Host: 192.168.178.129:8080
Aug  1 16:58:48 satip minisatip[26399]: Connection: keep-alive
Aug  1 16:58:48 satip minisatip[26399]: Content-Length: 0
Aug  1 16:58:48 satip minisatip[26399]: Accept: */*
Aug  1 16:58:48 satip minisatip[26399]: Origin: http://192.168.178.129:8080
Aug  1 16:58:48 satip minisatip[26399]: X-Requested-With: XMLHttpRequest
Aug  1 16:58:48 satip minisatip[26399]: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
Aug  1 16:58:48 satip minisatip[26399]: DNT: 1
Aug  1 16:58:48 satip minisatip[26399]: Referer: http://192.168.178.129:8080/
Aug  1 16:58:48 satip minisatip[26399]: Accept-Encoding: gzip, deflate
Aug  1 16:58:48 satip minisatip[26399]: Accept-Language: en-US,en;q=0.8,de;q=0.6
Aug  1 16:58:48 satip minisatip[26399]: #015
Aug  1 16:58:48 satip minisatip[26399]: *** stack smashing detected ***: /usr/bin/minisatip terminated
Aug  1 16:58:48 satip minisatip[26399]: print_trace at /usr/src/satip/minisatip-0.7-ca/utils.c:454
Aug  1 16:58:48 satip minisatip[26399]: posix_signal_handler at /usr/src/satip/minisatip-0.7-ca/utils.c:492
Aug  1 16:58:48 satip minisatip[26399]: ?? ??:0
Aug  1 16:58:48 satip minisatip[26399]: message repeated 6 times: [ ?? ??:0]
Aug  1 16:58:48 satip minisatip[26399]: _fini at ??:?
Aug  1 16:58:48 satip minisatip[26399]: RECEIVED SIGNAL 6 - SP=0 IP=0
Aug  1 16:58:48 satip minisatip[26399]: Obtained 10 stack frames.
Aug  1 16:58:48 satip minisatip[26399]: 0x8060bd4 : 0x8060cc1 : 0xb77cacfc : 0xb77cace5 : 0xb73a0ea9 : 0xb73a2407 : 0xb73dc37c : 0xb746c6b8 : 0xb746c648 : 0x80802e4 :
Aug  1 16:58:48 satip systemd[1]: minisatip.service: Main process exited, code=exited, status=1/FAILURE
````

**Comment by catalinii** [comment]
Hi,

can you reproduce this at will ?

Can you run on the binary that crashed: 
addr2line -e  minisatip 0x8060bd4
addr2line -e  minisatip 0x8060cc1 
addr2line -e minisatip 0xb77cacfc
..........................

Thank you

**Comment by catalinii** [comment]
Hi,

can you provide a log for: "2 different channels on the freq is not working with the Fritz!Box as the box may do not support it"

Thanks

**Comment by catalinii** [comment]
Is this still an issue ?

Thanks

**Comment by 9000h** [comment]
need to check again but I believe so, the AVM devices do support only one stream per tuner from one source IP

**Comment by 9000h** [comment]
multiple streams with the same channel form minisatip seem to work and as there is only one channel to the satipc
![screen shot 2017-10-12 at 21 51 14](https://user-images.githubusercontent.com/3009073/31516183-f0f875b6-af97-11e7-9387-f343cd74d3fe.png)
 
please look at the log I sent you where I try to open a second channel which did not work

**Comment by 9000h** [comment]
seems to work now
