### ISSUE TITLE
no issue oftopic

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#35]
only to collect info here
there is a slightly different implementation on the server side out called Big2Small by Ali STB's 

http://www.satelliteguys.us/xen/threads/trying-to-stream-video-from-amiko-mini-hd-se-to-windows.344995/

Big2Small is using port 554 and 'GET' style request parameters to specify what I requested to watch. In this case it was NBC West on C-Band.

rtsp://192.168.2.101:554/?alisatid=16&freq=3780&pol=v&msys=dvbs2&mtype=8psk&ro=0.35&plts=on&sr=29999&fec=0&camode=0&vpid=520&apid=781,782,783,784&ttxpid=8191&subtpid=8191&pmt=267&prognumber=12&pids=520,781,782,783,784,8191,8191,520,267

Finally, Big2Small starts playing the stream by sending this:

rtsp://192.168.2.101:554/stream=1

**Comment by catalinii** [comment]
You mean to implement this protocol as well ?

**Comment by 9000h** [comment]
I have no need for it, there are some clients under android out for this servers.

**Comment by catalinii** [comment]
For this there minisatip supports GET on port 8080

**Comment by mfat** [comment]
Hi @catalinii 
I have a satellite STB with a similar ALi chipset that uses this protocol. I want minisatip to work with this as a client, and then use minisatip in tvheadend as a dvb frontend. Is it possible?
