### ISSUE TITLE
web server problem

### ISSUE THREAD

**Issue by stailus** [catalinii/minisatip#352]
Hi,

I use minisatip 0.5.68 whitout any problem. Now when I try 0.7.4 web server don't work

I get this error in Google Chrome. I try with IE, Firefox but same problem

Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
jquery.dataTables.min.js:5 Uncaught ReferenceError: jQuery is not defined
    at jquery.dataTables.min.js:5
    at jquery.dataTables.min.js:5
jquery.pBar.min.js:5 Uncaught ReferenceError: jQuery is not defined
    at jquery.pBar.min.js:5
(index):277 Uncaught ReferenceError: $ is not defined
    at (index):277

I try to start with -R option but the same problem.

![jquery](https://cloud.githubusercontent.com/assets/19729347/25651283/ebf800d6-2fea-11e7-90a7-74a7e7c403a8.jpg)

What is wrong?

**Comment by catalinii** [comment]
Hi,

can you check now please?
If not working please upload the log with -l -l -l.
Thanks

**Comment by stailus** [comment]
Hi,

I try, no jquery error, but the same result. I attach log file

[log.txt](https://github.com/catalinii/minisatip/files/973013/log.txt)

**Comment by haarm** [comment]
Hi,
I have been having the same problem .
Greets
haarm

**Comment by 9000h** [comment]
I do have also issues to get the status page, you can replicate the issue with wget, it never got completed.
```
wget http://192.168.178.129:8080/status.html
--2017-05-03 20:03:32--  http://192.168.178.129:8080/status.html
Connecting to 192.168.178.129:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘status.html’

status.html             [ <=>               ]  11.35K  --.-KB/s 
```

**Comment by 9000h** [comment]
here the fix
```
--- minisatip.c.orig	2017-05-03 20:27:18.671839397 +0200
+++ minisatip.c	2017-05-03 20:27:34.632782391 +0200
@@ -1217,6 +1217,7 @@
 		if(strstr(ctype, "html"))
 		{
 			process_file(s, f, nl, ctype);
+			flush_socket(s);
 			closefile(f, nl);
 		}
 		return 0;
```

**Comment by haarm** [comment]
It works !!!!
Thank you

**Comment by stailus** [comment]
Is ok now. Thank you !
