### ISSUE TITLE
Segfault when using syslog

### ISSUE THREAD

**Issue by fe31nz** [catalinii/minisatip#353]
minisatip 0.7.4

When I tried using -g to output to syslog, I got a segfault.  Debugging the code in utils.c:_log() where the segfault occurred, I discovered that since opts.file_line is unused and always 0, when opts.slog is set by using the -g option, the len1 variable is uninitialised when it is used here:

	len = len1 =
			len1 < (int) sizeof(output[0]) ? len1 : (int) sizeof(output[0]) - 1;

When the random uninitialised value of len1 happens to be the wrong value (eg a large negative number in my case), that results in len being set to len1's bad value, and then a segfault happens in this code:

       len += vsnprintf(output[idx] + len, sizeof(output[0]) - len, fmt, arg);

What also happened when I added debug code to try to find this problem is that often just adding some debug code would cause the uninitialised value len1 was getting to become something that would not cause a segfault.  It appears that most of the time, that is what was happening when -g has been used in the past.  So random bits of memory may have been being overwritten by this bug, and it may have been the source of some difficult to track problems.

I have not traced out what all the logic in _log() is trying to do - I have just hacked a fix for myself.  So I will leave it to you to do a proper fix.

**Comment by catalinii** [comment]
Hi,

if you replace:

int len, len1, both;

to 

int len = 0, len1 = 0, both = 0;

Does it work for you ?

Thanks for reporting this.

**Comment by fe31nz** [comment]
Yes, that fixes it.

**Comment by catalinii** [comment]
Thanks for debuggimg this
