### ISSUE TITLE
satip-client fails after initial SETUP

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#356]
Hi @catalinii ,

I do some testing with the client mode (minisatip as client of one SAT>IP hardware server) using the last snapshot. It works, but I see one miss-implementation. Please check this:

- **Behaviour:** Using minisatip in satip-client mode, when one client first requests one program, the client doesn't receive any data. However, if the client cancels the request and retune the same program, then the stream is received.

- **LOG**: This is the simplified log of the previous described behaviour

```
OPTIONS
SETUP pids=...
 no data sent for more than... (the client receives nothing)
PLAY pids=none
DESCRIBE
PLAY addpids=... (the client receives the program)
DESCRIBE
PLAY addpids=...
DESCRIBE
PLAY addpids=...
DESCRIBE
PLAY delpids=...
DESCRIBE
PLAY delpids=...
DESCRIBE
PLAY delpids=...
DESCRIBE
PLAY delpids=...
TEARDOWN
```

It's possible that minisatip uses the SETUP request as the sense of "setup+play"?
If this is true, I feel is needed to make one PLAY after receive the response of the initial SETUP.
You agree?

Regards!

**Comment by catalinii** [comment]
Hi Lars,

yes it's possible, please send me the log.

There are couple of changes in the 0.7.4, but should be also more reliable.

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

In wich level you need the log?

In any case, the simplified log attached includes **all** calls to the hardware SAT>IP server. So, the behaviour is very clear: after the SETUP command the current code doesn't sends the PLAY command, and it assumes that the server is sending the stream.

I wait for your reply!
Thank you for this good piece of code.

**Comment by catalinii** [comment]
Hi Lars,

as always  3 -l :)

Thanks

**Comment by catalinii** [comment]
Hi,
in 0.7-ca with
-l satipc,http

Thanks

**Comment by catalinii** [comment]
Please reopen if this is still an issue.

Thanks
