### ISSUE TITLE
RTSP CSeq mismatch or invalid CSeq (85)

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#357]
Since i switched from the 0.7 branch to master, i have the following issues in the syslog:

    May 07 09:53:45 [vdr] [1496] SATIP: Idle timeout - releasing [device 2]
    May 07 09:53:45 [vdr] [1496] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
    May 07 09:53:45 [vdr] [1496] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 2]
    May 07 09:53:45 [vdr] [1501] SATIP: Idle timeout - releasing [device 3]
    May 07 09:53:45 [vdr] [1501] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
    May 07 09:53:45 [vdr] [1501] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 3]
    May 07 09:53:45 [vdr] [2004] DDCI-Dbg: DdCiTsSend for /dev/dvb/adapter0/sec0 CAM buff rd(-> CAM):26514, wr:26519
    May 07 09:53:45 [vdr] [1491] SATIP: Idle timeout - releasing [device 1]
    May 07 09:53:45 [vdr] [1491] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
    May 07 09:53:45 [vdr] [1491] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 1]

Mainly it seems that all is working, but what this issues mean and where do they comme from?

**Comment by 3PO** [comment]
I asked the maintainer of the vdr-satip-plugin and he answerd me:

> There's an auto-incremented packet sequence number (CSeq) in RTSP communication. When an mismatch is detected, either the server is malfunctioning or some packet has been dropped during the transport. In your case, the server is clearly malfunctioning as it's returning also an invalid HTTP status code 0.

**Comment by catalinii** [comment]
Hi,

can you upload the minisatip log (-l -l -l) and the vdr log at the time of
this message?

Thanks

**Comment by 3PO** [comment]
VDR Log:
```
May 07 11:18:00 [vdr] [1488] SATIP: Idle timeout - releasing [device 0]
May 07 11:18:00 [vdr] [1488] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 11:18:00 [vdr] [1488] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
May 07 11:18:01 [vdr] [14732] CAM 1: decrypts channel S19.2E-133-11-113
May 07 11:18:01 [vdr] [1496] SATIP: Idle timeout - releasing [device 2]
May 07 11:18:01 [vdr] [1501] SATIP: Idle timeout - releasing [device 3]
May 07 11:18:01 [vdr] [1501] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 11:18:01 [vdr] [1501] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 3]
May 07 11:18:01 [vdr] [1496] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 11:18:01 [vdr] [1496] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 2]
May 07 11:18:01 [vdr] [1491] SATIP: Idle timeout - releasing [device 1]
May 07 11:18:01 [vdr] [1491] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 11:18:01 [vdr] [1491] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 1]
May 07 11:18:03 [vdr] [2005] DDCI-Dbg: DdCiTsRecv for /dev/dvb/adapter0/sec0 CAM buff wr(CAM ->):77900, rd:77952
May 07 11:18:05 [vdr] [2004] DDCI-Dbg: DdCiTsSend for /dev/dvb/adapter0/sec0 CAM buff rd(-> CAM):86693, wr:86765
May 07 11:18:13 [vdr] [2005] DDCI-Dbg: DdCiTsRecv for /dev/dvb/adapter0/sec0 CAM buff wr(CAM ->):122894, rd:122976
```

minisatip Log: https://bpaste.net/show/17fd518c9557

**Comment by catalinii** [comment]
Hi,

I see the timeout is configured to 15ms ... can you upload the minisatip log without using syslog ?
I assume is timeout at this point, so the answer takes more than 15ms
Thank you

**Comment by 3PO** [comment]
VDR Log:

```
May 07 14:07:14 [vdr] [27155] DDCI-Dbg: DdCiTsSend for /dev/dvb/adapter0/sec0 CAM buff rd(-> CAM):43787, wr:43814
May 07 14:07:16 [vdr] [27134] [plex] Server updated via GDM: 192.168.177.10
May 07 14:07:24 [vdr] [27156] DDCI-Dbg: DdCiTsRecv for /dev/dvb/adapter0/sec0 CAM buff wr(CAM ->):83272, rd:83328
May 07 14:07:24 [vdr] [27155] DDCI-Dbg: DdCiTsSend for /dev/dvb/adapter0/sec0 CAM buff rd(-> CAM):83854, wr:83854
May 07 14:07:25 [vdr] [27128] SATIP: Idle timeout - releasing [device 3]
May 07 14:07:25 [vdr] [27128] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 14:07:25 [vdr] [27128] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 3]
May 07 14:07:25 [vdr] [27125] SATIP: Idle timeout - releasing [device 2]
May 07 14:07:25 [vdr] [27122] SATIP: Idle timeout - releasing [device 1]
May 07 14:07:25 [vdr] [27119] SATIP: Idle timeout - releasing [device 0]
May 07 14:07:25 [vdr] [27125] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 14:07:25 [vdr] [27125] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 2]
May 07 14:07:25 [vdr] [27119] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 14:07:25 [vdr] [27119] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
May 07 14:07:25 [vdr] [27122] curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
May 07 14:07:25 [vdr] [27122] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 1]
May 07 14:07:34 [vdr] [27156] DDCI-Dbg: DdCiTsRecv for /dev/dvb/adapter0/sec0 CAM buff wr(CAM ->):121551, rd:121632
May 07 14:07:34 [vdr] [27155] DDCI-Dbg: DdCiTsSend for /dev/dvb/adapter0/sec0 CAM buff rd(-> CAM):122095, wr:122095
```

minisatip Log:
[minisatip.zip](https://github.com/catalinii/minisatip/files/981567/minisatip.zip)

**Comment by catalinii** [comment]
Hi,

could you please check if this works with 0.5 again ?
In the rtsp traffic I did not see anything unusual.

Thanks

**Comment by 3PO** [comment]
With the 0.5 branch i get no issues. 
With the former 0.7 branch (-> not 0.7-ca!) i got also no issues.

BTW: The maintainer of the vdr-satip-plugin also wrote:

> Well, even if a client misbehaves, the server should never return the zero status code, so there are at least some missing features or bugs in the server. But that doesn't mean, that the client is working according to specs. You'll need to analyze the network traffic in order to make any conclusions.

**Comment by catalinii** [comment]
Hi, so I assume 0.7-ca does not work also?

Btw could u upload satip-plugin logs with the highest debug level?

**Comment by 3PO** [comment]
>Hi, so I assume 0.7-ca does not work also?

I'll check it. ;)


>Btw could u upload satip-plugin logs with the highest debug level?

There is no possibility for switching to an other debug level in the satip plugin. :(

**Comment by 3PO** [comment]
I cannot compile minisatip 0.7-ca.

Buildlog: https://bpaste.net/show/221ebeda2d9e

**Comment by catalinii** [comment]
HI,
compile it with:

make clean;make DVBAPI=0 DVBCSA=0 DVBAES=0  DVBCA=0  -j 12

Thanks

**Comment by ecdlguy** [comment]
Hi guys,

I'm facing the very same problem as 3PO:
```
> tail /var/log/messages
curl_easy_perform() [rtsp.c,365] failed: RTSP CSeq mismatch or invalid CSeq (85)
SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.2.30/ [device 0]
```
This is the minisatip-Version I'm using:
```
> minisatip7 -help | head -1
minisatip version 0.7.4-axe205, compiled with s2api version: 0501
```
Since this issue has been closed, is there a workaround?

cheers,
Thorsten
