### ISSUE TITLE
check: RTP port

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#36]
only for verify  

One for RTP; one for RTCP. By convention, the RTP port is should be even.

**Comment by catalinii** [comment]
if the RTP port is not even, what to do ? (considering the client is already listening there ?)

**Comment by 9000h** [comment]
I'm also unsure but the RFC's suggest it, hmm

**Comment by catalinii** [comment]
I guess it is better just to leave it as it is :)
