### ISSUE TITLE
[0.7-ca] configure does not work correctly

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#360]
If i use configure with the following parms,

`./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --enable-linuxdvb --disable-dvbca --disable-dvbaes --enable-dvbcsa --disable-dvbapi --enable-satipc --disable-static`

i see in the summary:

```
minisatip configuration

Linux DVB:                                disabled
Common Interface (needs DVBEN50221):      disabled
OpenSSL (AES as part of DVBAPI):          disabled
Embedded system:                          disabled
DVBCSA (needs libdvbcsa):                 disabled
Netceiver support:                        disabled
SatIP Client:                             disabled
Static:                                   enabled
dvbapi:                                   disabled
axe:                                      disabled
```

 Complete build Log: https://bpaste.net/show/da32fd8b421d

**Comment by 3PO** [comment]
Am i really the only one with this problem??

**Comment by 3PO** [comment]
It's working now.

Thanks!

**Comment by 3PO** [comment]
Just for information:

In "master" the problem still exists.

**Comment by catalinii** [comment]
Hi,

I will move the master to 0.7-ca when it is ready.

Thanks
