### ISSUE TITLE
[0.7-ca] CAM decrypting fails

### ISSUE THREAD

**Issue by emilsvennesson** [catalinii/minisatip#362]
Hi! Thank you for this great piece of software. :-)

I am attempting to run tvheadend along with minisatip with two CAM adapters, but haven't managed to get the decryption to work successfully.

minisatip.log: https://paste.ee/p/1ly2Q
ls -l /dev/dvb/adapter*: https://paste.ee/p/vGW93
dmesg | grep DDBridge: https://paste.ee/p/mpg5j

I am running ddbridge with adapter_alloc=3 so that all cards display under one adapter. I have also verified that it works fine under VDR.

Please let me know if you're in need of more information! I can also provide remote access to the VM if that makes the troubleshooting easier.

-- Emil

**Comment by catalinii** [comment]
Hi Emil,

thank you for the report.

Please check with the new version and let me know if it is better.

Thank you

**Comment by emilsvennesson** [comment]
Hi @catalinii - thanks a lot for looking into this!

I've tried with the latest commit but it's still behaving the same way unfortunately. 
Here's the log: https://paste.ee/p/02Ubp

One thing I've noticed it that it doesn't detect both CA adapters ('No CA device detected on adapter 1').

-- Emil

**Comment by catalinii** [comment]
Hi,

do you still have this issue ?

Thank you

**Comment by emilsvennesson** [comment]
@catalinii Unfortunately, yes. Here's a debug log from the latest commit:

https://paste.ee/p/UwYYN

I still see "[04/07 17:30:40.501 main]: No CA device detected on adapter 1" in the log.

**Comment by 9000h** [comment]
looks like Digital Devices Cine C2T2 V7 an a DD CI, at the moment you can only get it to work if you use the kernel redirect workaround on a single tuner.
https://www.linuxtv.org/wiki/index.php/Digital_Devices_DuoFlex_C%26T

**Comment by emilsvennesson** [comment]
@9000h That's what I'm doing on both adapters. I've also verified that it works using VDR.

**Comment by 9000h** [comment]
and you load the module with the right option
0: adapter0, adapter1 and adapter2
 1: adapter0 with both frontends, adapter1 with CI
 2: adapter0 with both frontends, adapter2 with CI
 3: single adapter0 directory with both frontends and CI

options ddbridge adapter_alloc=3

**Comment by catalinii** [comment]
Hi,

is this still an issue ?

Thanks
