### ISSUE TITLE
Unicable not works with REEL Netceiver

### ISSUE THREAD

**Issue by fadidar** [catalinii/minisatip#363]
Dear all,

I will use the netceiver and minisatip, but it not works. I have an unicable system with two wideband lnbs and one Durline Wideband switch (DUR-line DWB-32 K). The netceiver is direct connect on the second Ethernet port on my server. My standard VDR system with 2 PCIe DVB cards works fine with the unicable system.

> --> minisatip -f -n eth1:1 -e 0-1 -u 0:4-984-48,1:5-1020-23 -l -l -l
> 
> ### [13/06 11:59:28.067 main]: Setting unicable adapter 0 slot 4 freq 984
> [13/06 11:59:28.067 main]: Setting unicable adapter 1 slot 5 freq 1020
> [13/06 11:59:28.067 main]: minisatip version 0.7.4, compiled with s2api version: 050A
> [13/06 11:59:28.068 main]: Built without dvbcsa
> [13/06 11:59:28.068 main]: Built with CI
> [13/06 11:59:28.068 main]: Built without dvbapi
> [13/06 11:59:28.068 main]: Built without AES (OpenSSL)
> [13/06 11:59:28.068 main]: Built with tables processing
> [13/06 11:59:28.068 main]: Built with satip client
> [13/06 11:59:28.068 main]: Built with linux dvb client
> [13/06 11:59:28.068 main]: Built with backtrace
> [13/06 11:59:28.068 main]: Built with netceiver
> [13/06 11:59:29.844 main]: REEL: Search for 1 Netceiver on eth1... ##############
> Found NetCeiver: fxxx::xxx:xxxx:xxxx:xxxx
> 	Tuner: Conexant CX24116 DVB-S2, Type 4
> 	Tuner: Conexant CX24116 DVB-S2, Type 4
> 	Tuner: Conexant CX24116 DVB-S2, Type 4
> 	Tuner: Conexant CX24116 DVB-S2, Type 4
> 	Tuner: Conexant CX24116 DVB-S2, Type 4
> 	Tuner: Conexant CX24116 DVB-S2, Type 4
> 
> [13/06 11:59:29.844 main]: netceiver: adding [AD0 DVB-S2] [AD1 DVB-S2] 
> [13/06 11:59:29.844 main]: Initializing with 2 devices
> [13/06 11:59:29.910 main]: netceiver: adapter 0 tuning to 11302 @ 19.2E pol:h sr:22000 fec:23 delsys:dvbs2 mod:8psk
> ......
> ....
> <?xml version="1.0"?><root xmlns="urn:schemas-upnp-org:device-1-0" configId="0"><specVersion><major>1</major><minor>1</minor></specVersion><device><deviceType>urn:ses-com:device:SatIPServer:1</deviceType><friendlyName>minisatip</friendlyName><manufacturer>cata</manufacturer><manufacturerURL>http://github.com/catalinii/minisatip</manufacturerURL><modelDescription>minisatip for Linux</modelDescription><modelName>minisatip</modelName><modelNumber>1.1</modelNumber><modelURL></modelURL><serialNumber>1</serialNumber><UDN>uuid:11223344-9999-0000-b7ae-4c0289009de8</UDN><iconList><icon><mimetype>image/png</mimetype><width>48</width><height>48</height><depth>24</depth><url>/sm.png</url></icon><icon><mimetype>image/png</mimetype><width>120</width><height>120</height><depth>24</depth><url>/lr.png</url></icon><icon><mimetype>image/jpeg</mimetype><width>48</width><height>48</height><depth>24</depth><url>/sm.jpg</url></icon><icon><mimetype>image/jpeg</mimetype><width>120</width><height>120</height><depth>24</depth><url>/lr.jpg</url></icon></iconList><presentationURL>http://192.168.0.125:8016/</presentationURL>
> <satip:X_SATIPCAP xmlns:satip="urn:ses-com:satip">DVBS2-2</satip:X_SATIPCAP></device></root>
> [13/06 12:05:35.906 main]: select_and_execute[10]: Close on socket 29 (sid:-1) from 192.168.0.23:50838 - type http errno 0
> [13/06 12:05:35.906 main]: sockets_del: 10 -> handle 29, sid -1, overflow 0, allocated 0, used 0
> [13/06 12:05:35.906 main]: minisatip.c:1232 get_sid returns NULL for s_id = -1
> [13/06 12:05:35.906 main]: Requested stream close -1 timeout -1 type -1
> [13/06 12:05:35.906 main]: closing stream -1
> [13/06 12:05:35.906 main]: sockets_del: 10 Last open socket is at index 12 current_handle 29
> [13/06 12:05:35.906 main]: Delete socket 10 done: sid -1
> [13/06 12:05:36.034 signal]: BW 178KB/s, Total BW: 1 MB, ns/read 34, r: 87, w: 142 fw: 0, tt: 3 ms
> [13/06 12:05:37.044 signal]: BW 166KB/s, Total BW: 1 MB, ns/read 33, r: 84, w: 132 fw: 0, tt: 2 ms
> [13/06 12:05:38.054 signal]: BW 178KB/s, Total BW: 1 MB, ns/read 34, r: 90, w: 142 fw: 0, tt: 3 ms
> [13/06 12:05:39.063 signal]: BW 173KB/s, Total BW: 1 MB, ns/read 34, r: 87, w: 138 fw: 0, tt: 2 ms
> [13/06 12:05:40.073 signal]: BW 161KB/s, Total BW: 1 MB, ns/read 63, r: 38, w: 129 fw: 0, tt: 2 ms
> [13/06 12:05:41.083 signal]: BW 173KB/s, Total BW: 2 MB, ns/read 85, r: 29, w: 138 fw: 0, tt: 2 ms
> [13/06 12:05:41.499 AD1]: Requested adapter 1 close due to timeout, result 1 max_rtime 0
> [13/06 12:05:41.499 AD1]: sockets_del: 7 -> handle 11, sid 1, overflow 0, allocated 0, used 0
> [13/06 12:05:41.499 AD1]: closing DVR socket -1 pos 7 aid 1
> [13/06 12:05:41.499 AD1]: closing adapter 1  -> fe:0 dvr:11
> [13/06 12:05:41.499 AD1]: netceiver: delete receiver instance for adapter 1
> [13/06 12:05:41.499 AD1]: adapter.c:829: get_adapter returns NULL for adapter_id 1
> [13/06 12:05:41.499 AD1]: adapter.c:627: get_adapter returns NULL for adapter_id 1
> [13/06 12:05:41.499 AD1]: done closing adapter 1
> [13/06 12:05:41.499 AD1]: sockets_del: 7 Last open socket is at index 12 current_handle 11
> [13/06 12:05:41.600 AD1]: No enabled sockets for Thread ID b24ffb40 name AD1 ... exiting 
> [13/06 12:05:41.600 AD1]: Mutex init 0x800d6be0
> [13/06 12:05:41.600 AD1]: add_join_thread: pthread b24ffb40
> [13/06 12:05:42.093 signal]: BW 178KB/s, Total BW: 2 MB, ns/read 84, r: 30, w: 142 fw: 0, tt: 2 ms
> [13/06 12:05:42.093 signal]: Joining thread b24ffb40
> [13/06 12:05:43.103 signal]: BW 166KB/s, Total BW: 2 MB, ns/read 83, r: 28, w: 132 fw: 0, tt: 2 ms
> [13/06 12:05:44.113 signal]: BW 172KB/s, Total BW: 2 MB, ns/read 82, r: 29, w: 137 fw: 0, tt: 2 ms
> [13/06 12:05:45.122 signal]: BW 173KB/s, Total BW: 2 MB, ns/read 83, r: 29, w: 138 fw: 0, tt: 2 ms
> [13/06 12:05:46.132 signal]: BW 173KB/s, Total BW: 2 MB, ns/read 82, r: 29, w: 138 fw: 0, tt: 2 ms
> [13/06 12:05:47.142 signal]: BW 172KB/s, Total BW: 3 MB, ns/read 82, r: 29, w: 137 fw: 0, tt: 2 ms
> [13/06 12:05:48.152 signal]: BW 173KB/s, Total BW: 3 MB, ns/read 84, r: 29, w: 137 fw: 0, tt: 2 ms
> [13/06 12:05:49.162 signal]: BW 172KB/s, Total BW: 3 MB, ns/read 82, r: 29, w: 137 fw: 0, tt: 2 ms
> [13/06 12:05:50.172 signal]: BW 173KB/s, Total BW: 3 MB, ns/read 83, r: 29, w: 138 fw: 0, tt: 2 ms
> Message repeated 1 times
> [13/06 12:05:52.191 signal]: BW 172KB/s, Total BW: 3 MB, ns/read 83, r: 29, w: 137 fw: 0, tt: 2 ms
> [13/06 12:05:52.544 main]: select_and_execute[8]: Close on socket 13 (sid:1) from 192.168.0.68:41049 - type rtsp errno 0
> [13/06 12:05:52.544 main]: sockets_del: 8 -> handle 13, sid 1, overflow 0, allocated 0, used 0
> [13/06 12:05:52.544 main]: Requested stream close 1 timeout 30000 type 2
> [13/06 12:05:52.544 main]: sockets_del: 8 Last open socket is at index 12 current_handle 13
> [13/06 12:05:52.544 main]: Delete socket 8 done: sid -1
> [13/06 12:05:52.550 main]: Mutex init 0x800e0f64
> [13/06 12:05:52.550 main]: sockets_add: handle 11 (type 1) returning socket index 7 [192.168.0.68:41050] read: 0x800a79b1
> [13/06 12:05:52.550 main]: minisatip.c:834 get_sid returns NULL for s_id = -1
> [13/06 12:05:52.550 main]: read RTSP (from handle 11 sock_id 7, len: 0, sid -1):
> [13/06 12:05:52.550 main]: OPTIONS rtsp://192.168.0.125/ RTSP/1.0
> Connection:Close
> CSeq:1016
> Session:1681692777

If I connect the Netceiver on the legacy output of the wideband switch, then I got successful a video stream. (commandline: minisatip -f -n eth1:1 -e 0-1)

BR,

Fadi

**Comment by catalinii** [comment]
Hi,

The unicable/jess settings in minisatip apply to dvb adapters.

Netceiver needs to be configured separately. 

For more details see: https://github.com/catalinii/minisatip/issues/347

Thanks

**Comment by fadidar** [comment]
Hi catalinii,
thanks for your quick response. 
Ok. I will configure the Netceiver separately.

BR,

Fadi
