### ISSUE TITLE
[0.7-ca] Webinterface is not working

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#365]
Hi, it seems, that the Webif in the 0.7-ca branch is not working.

All i can is is this:

![2017-06-16_182225](https://user-images.githubusercontent.com/945108/27235468-3ff69c44-52c1-11e7-9424-d3029b156690.png)

**Comment by catalinii** [comment]
Hi,

the status.html is changed between 0.7-ca and 0.7.4. It seems that you are using the previous one. The new title should be "Minisatip status".

Thanks

**Comment by 3PO** [comment]
Yes, that was the problem. :)

Sorry for the noise.
