### ISSUE TITLE
 [0.7-ca] minisatip is not working reliable

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#367]
Hi,

After a couple of hours,  i get the following in the VDR Log:

```
Jun 25 12:32:32 [vdr] [16351] SATIP: Idle timeout - releasing [device 0]
Jun 25 12:34:27 [vdr] epg2vdr: Update info.epg2vdr recordings
Jun 25 12:34:27 [vdr] epg2vdr: Updated 0 info.epg2vdr files
Jun 25 12:40:01 [cron] (root) CMD (test -x /usr/sbin/run-crons && /usr/sbin/run-crons)
Jun 25 12:40:27 [vdr] epg2vdr: Update info.epg2vdr recordings
Jun 25 12:40:27 [vdr] epg2vdr: Updated 0 info.epg2vdr files
Jun 25 12:42:26 [vdr] [16725] epg data writer thread started (pid=16342, tid=16725, prio=low)
Jun 25 12:42:28 [vdr] [16725] epg data writer thread ended (pid=16342, tid=16725)
Jun 25 12:46:27 [vdr] epg2vdr: Update info.epg2vdr recordings
Jun 25 12:46:27 [vdr] epg2vdr: Updated 0 info.epg2vdr files
Jun 25 12:48:52 [vdr] [16353] changing name of channel 3402 from 'PPV HD: POLSAT BOXING NIGHT 7,;' to 'TEST,;'
Jun 25 12:49:03 [vdr] [16351] SATIP-ERROR: Connection timeout - retuning [device 0]
Jun 25 12:49:05 [vdr] [16351] curl_easy_perform() [rtsp.c,334] failed: Timeout was reached (28)
Jun 25 12:49:05 [vdr] [16351] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jun 25 12:49:05 [vdr] [16351] SATIP-ERROR: Connect failed [device 0]
Jun 25 12:49:06 [vdr] [16351] curl_easy_perform() [rtsp.c,209] failed: Timeout was reached (28)
Jun 25 12:49:06 [vdr] [16351] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jun 25 12:49:06 [vdr] [16351] SATIP-ERROR: Connect failed [device 0]
Jun 25 12:49:08 [vdr] [16351] curl_easy_perform() [rtsp.c,209] failed: Timeout was reached (28)
```

Here is the Log from the minisatip Server at the same time:

https://paste.pound-python.org/show/xB3U3DNyUq767i4ipg46/

When i restart minisatip, the VDR reconnect immediately:

```
Jun 25 16:12:05 [vdr] [16351] curl_easy_perform() [rtsp.c,209] failed: Couldn't connect to server (7)
Jun 25 16:12:05 [vdr] [16351] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jun 25 16:12:05 [vdr] [16351] SATIP-ERROR: Connect failed [device 0]
Jun 25 16:12:07 [vdr] [16349] SATIP: Detected 1 RTP packet errors [device 0]
Jun 25 16:12:07 [vdr] [16353] creating new channel '!mwl3a 3lik,;Eutelsat' on S13.0E transponder 211200 with id 318-13400-4774-0
Jun 25 16:12:07 [vdr] [16353] creating new channel 'nar elhob,;Eutelsat' on S13.0E transponder 211200 with id 318-13400-4775-0
Jun 25 16:12:07 [vdr] [16353] creating new channel 'anta 7iate,;Eutelsat' on S13.0E transponder 211200 with id 318-13400-4776-0
Jun 25 16:12:07 [vdr] [16353] creating new channel 'lo3b whob,;Eutelsat' on S13.0E transponder 211200 with id 318-13400-4777-0
Jun 25 16:12:07 [vdr] [16353] creating new channel 'Arab Fun 2,;Eutelsat' on S13.0E transponder 211200 with id 318-13400-4778-0
Jun 25 16:12:25 [vdr] [16350] SATIP: Adding server '192.168.177.11|DVBS2-8,DVBC-8,DVBT2-8|minisatip' Filters: none CI: yes Quirks: RtpOverTcp,CiXpmt
Jun 25 16:12:36 [vdr] [16351] SATIP: Idle timeout - releasing [device 0]
Jun 25 16:13:38 [vdr] epg2vdr: Update info.epg2vdr recordings
Jun 25 16:13:38 [vdr] epg2vdr: Updated 0 info.epg2vdr files
```

**Comment by catalinii** [comment]
Hi,

could you try the latest commit ?

Also please use output to a file (using -F file_path ) and -l http and without syslog output.
Thank you

**Comment by 3PO** [comment]
This is the issue form the VDR after restarting minisatip:

```
Jun 26 20:02:35 [vdr] [9588] SATIP: Adding server '192.168.177.11|DVBS2-8,DVBC-8,DVBT2-8|minisatip' Filters: none CI: yes Quirks: RtpOverTcp,CiXpmt
Jun 26 20:02:49 [vdr] [9589] SATIP: Idle timeout - releasing [device 0]
Jun 26 20:03:14 [vdr] epg2vdr: Update info.epg2vdr recordings
Jun 26 20:03:14 [vdr] epg2vdr: Updated 0 info.epg2vdr files
Jun 26 20:05:30 [vdr] [9597] SVDRP < 192.168.177.10:43146 client connection accepted
Jun 26 20:05:30 [vdr] [9597] SVDRP < 192.168.177.10:43146 server created
Jun 26 20:05:30 [vdr] epg2vdr: Got epgd state 'busy (match)' (4)
Jun 26 20:05:30 [vdr] epg2vdr: Change handler state to 'standby'
Jun 26 20:05:30 [vdr] [9597] SVDRP < 192.168.177.10:43146 lost connection to client
Jun 26 20:05:30 [vdr] [9597] SVDRP < 192.168.177.10:43146 connection closed
Jun 26 20:05:30 [vdr] [9597] SVDRP < 192.168.177.10:43146 server destroyed
Jun 26 20:05:43 [vdr] [9597] SVDRP < 192.168.177.10:44954 client connection accepted
Jun 26 20:05:43 [vdr] [9597] SVDRP < 192.168.177.10:44954 server created
Jun 26 20:05:43 [vdr] epg2vdr: Got epgd state 'standby' (1)
Jun 26 20:05:43 [vdr] epg2vdr: Change handler state to 'active'
Jun 26 20:05:43 [vdr] [9597] SVDRP < 192.168.177.10:44954 lost connection to client
Jun 26 20:05:43 [vdr] [9597] SVDRP < 192.168.177.10:44954 connection closed
Jun 26 20:05:43 [vdr] [9597] SVDRP < 192.168.177.10:44954 server destroyed
Jun 26 20:05:49 [vdr] epg2vdr: Updated changes since '26.06.2017 19:30:10'; 237 channels, 2606 events (18 deletions) in 5.840 seconds
Jun 26 20:05:49 [vdr] [23595] epg data writer thread started (pid=9580, tid=23595, prio=low)
Jun 26 20:05:54 [vdr] [23595] epg data writer thread ended (pid=9580, tid=23595)
Jun 26 20:08:47 [vdr] [9589] curl_easy_perform() [rtsp.c,334] failed: Couldn't connect to server (7)
Jun 26 20:08:47 [vdr] [9589] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jun 26 20:08:47 [vdr] [9589] SATIP-ERROR: Pid update failed - retuning [device 0]
Jun 26 20:08:47 [vdr] [9589] curl_easy_perform() [rtsp.c,334] failed: Couldn't connect to server (7)
```

And here is the corresponding Log from minisatip:

http://dreipo.cc/logs/minisatip.log.tgz

**Comment by 9000h** [comment]
I also did notice some issues by watching different crypted channels from different transponders, only the first works with 0.7-ca. If the second one is FTA then it works.

**Comment by tunip** [comment]
Same here. Only first ECM is good on some transponders. The second ECM freeze minisatip.

**Comment by 9000h** [comment]
the issue I did had was a oscam compiled with WITH_EXTENDED_CW enabled, without all look fine with the latest commit from today

**Comment by tunip** [comment]
Makes no differents if OSCAM is compiled with or without WITH_EXTENDED_CW.

caid 0648 works fine with 0.7-ca. But caid 09c4 has dropouts. After every new CW stream hangs a few seconds. The minisatip webinterface is showing only "Loading.."

**Comment by 9000h** [comment]
and you did use commit 535?

**Comment by tunip** [comment]
Yes, I use last commit 527ecf9. Which caids are you using?

**Comment by 9000h** [comment]
0x648,0x1843,0x500,0x9c7

**Comment by catalinii** [comment]
tunip can you upload your logs?

**Comment by tunip** [comment]
minisatip log:
[minisatip.zip](https://github.com/catalinii/minisatip/files/1115001/minisatip.zip)

minisatip webinterface:
![minisatip_1a](https://user-images.githubusercontent.com/11404472/27734724-7b9b1672-5d9c-11e7-80db-3f07e8bd44b8.jpg)

After manually reload the page it show this:
![minisatip_1](https://user-images.githubusercontent.com/11404472/27734726-7dcdd22c-5d9c-11e7-9cf4-e4e32eaa042a.jpg)

After a few minutes it comes back.

Tvheadend log:
2017-06-30 13:46:16.346 satip: SAT>IP DVB-S Tuner #1 (10.10.10.66) - RTSP error -5 (I/O error) [9874-200]
2017-06-30 13:46:16.706 subscription: 0014: service instance is bad, reason: Tuning failed

**Comment by 3PO** [comment]
Same behavior of the Webinterface as tunip told, on my minisatip server.

**Comment by catalinii** [comment]
Hi,

I see the log does not include the 13:46.

Can you create a new log by adding:
-v socket -l lock,http

Also when the page is not loading, please open the chrome developer tools and see what error is reported there about getting /stats.json.

Another question, are the numbers after BW changing when this happens ?

The extended CW issue is different than this, we can open a new issue.
Thank you

**Comment by tunip** [comment]
Here are the logs with socket, lock & http enabled:
[minisatip.log.zip](https://github.com/catalinii/minisatip/files/1117062/minisatip.log.zip)

Yes all the stats are still updated if this happens.

Chrome Developer console druing streaming a channel:
<img width="978" alt="dev_console" src="https://user-images.githubusercontent.com/11404472/27762143-e770f45a-5e6b-11e7-878b-7cbea5b418dc.png">

I reactivated card with caid 1843 (nagra) and it works also fine with 0.7-ca. Only 09c4 (videoguard2) has the issues with streaming. The Webinterface issue is with FTA and encrypted channels.

Thx

**Comment by 3PO** [comment]
Here is an other Log:

Log from VDR after restarting minisatip on the server:

`
Jul 01 16:20:29 [vdr] [10642] curl_easy_perform() [rtsp.c,209] failed: Couldn't connect to server (7)
Jul 01 16:20:29 [vdr] [10642] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jul 01 16:20:29 [vdr] [10642] SATIP-ERROR: Connect failed [device 0]
Jul 01 16:20:30 [vdr] [10640] SATIP: Detected 1 RTP packet errors [device 0]
Jul 01 16:20:33 [vdr] epg2vdr: Handler: Toggle vps flag for 'Moskau, Mythen, Mauerfall' at 'S19.2E-1-1051-28725' from 01.07.2017 15:44:00 to 01.07.2017 14:43:00
Jul 01 16:20:37 [vdr] [10641] SATIP: Adding server '192.168.177.11|DVBS2-8,DVBC-8,DVBT2-8|minisatip' Filters: none CI: yes Quirks: RtpOverTcp,CiXpmt
Jul 01 16:20:54 [vdr] [10649] SVDRP < 192.168.177.10:46998 client connection accepted
Jul 01 16:20:54 [vdr] [10649] SVDRP < 192.168.177.10:46998 server created
Jul 01 16:20:54 [vdr] epg2vdr: Got epgd state 'busy (match)' (4)
Jul 01 16:20:54 [vdr] epg2vdr: Change handler state to 'standby'
`

This is the Point at minisatip is stopping to work:

`
Jul 01 17:37:04 [vdr] epg2vdr: Change handler state to 'active'
Jul 01 17:37:04 [vdr] [10649] SVDRP < 192.168.177.10:52588 lost connection to client
Jul 01 17:37:04 [vdr] [10649] SVDRP < 192.168.177.10:52588 connection closed
Jul 01 17:37:04 [vdr] [10649] SVDRP < 192.168.177.10:52588 server destroyed
Jul 01 17:37:16 [vdr] [10642] SATIP: Idle timeout - releasing [device 0]
Jul 01 17:37:16 [vdr] epg2vdr: Updated changes since '01.07.2017 17:36:14'; 237 channels, 2027 events (62 deletions) in 12.383 seconds
Jul 01 17:37:17 [vdr] [15180] epg data writer thread started (pid=10632, tid=15180, prio=low)
Jul 01 17:37:22 [vdr] [15180] epg data writer thread ended (pid=10632, tid=15180)
Jul 01 17:38:54 [vdr] [10642] curl_easy_perform() [rtsp.c,334] failed: Timeout was reached (28)
Jul 01 17:38:54 [vdr] [10642] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jul 01 17:38:54 [vdr] [10642] SATIP-ERROR: Pid update failed - retuning [device 0]
Jul 01 17:38:55 [vdr] [10642] curl_easy_perform() [rtsp.c,334] failed: Timeout was reached (28)
Jul 01 17:38:55 [vdr] [10642] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jul 01 17:38:55 [vdr] [10642] SATIP-ERROR: Connect failed [device 0]
Jul 01 17:38:57 [vdr] [10642] curl_easy_perform() [rtsp.c,209] failed: Timeout was reached (28)
Jul 01 17:38:57 [vdr] [10642] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jul 01 17:38:57 [vdr] [10642] SATIP-ERROR: Connect failed [device 0]
Jul 01 17:38:59 [vdr] [10642] curl_easy_perform() [rtsp.c,209] failed: Timeout was reached (28)
Jul 01 17:38:59 [vdr] [10642] SATIP-ERROR: Detected invalid status code 0: rtsp://192.168.177.11/ [device 0]
Jul 01 17:38:59 [vdr] [10642] SATIP-ERROR: Connect failed [device 0]
Jul 01 17:39:01 [vdr] [10642] curl_easy_perform() [rtsp.c,209] failed: Timeout was reached (28)
`

minisatip log with "-v socket -l lock,http": 
--> http://dreipo.cc/logs/minisatip2.log.tgz

**Comment by catalinii** [comment]
I think there are 2 issues here:

1) minisatip crashes. Please use the latest commit because some of them are fixed.

The issue here I think is more complicated.

If the timeout is reported, it means that minisatip does not respond in 1.5 seconds which is not the case. Here I see all the answers are < 10ms.

Could you also do a tcpdump -ni any port 554 -w xx.pcap -s 0

try to reproduce and upload xx.pcap.

Also please let me know if you can enable full debug on vdr-plugin-satip

Thanks

**Comment by tunip** [comment]
Short test with the new commit results in the same behaviour with caid 09C4.
Stream restarts every few seconds. This is maybe different den 3POs issue with his VDR setup (third issue?).

tcpdump during webinterface issue:
[minisatip.zip](https://github.com/catalinii/minisatip/files/1119365/minisatip.zip)

**Comment by catalinii** [comment]
Hi,

I am aware of issue 2.

You can open a new issue for issue 3.

Could you please provide what I have requested earlier to continue looking into this issue ?

Basically, tcpdump, minisatip logs and vdr plugin satip debug logs (higher debug level possible).

Thanks

**Comment by catalinii** [comment]
Hi @3PO 

do you play something when it fails or just leave it scan in the background and you get that error ?

Thank you

**Comment by 3PO** [comment]
only scan in the background.

**Comment by 9000h** [comment]
the web interface issue is still there and looks like:
![screen shot 2017-07-14 at 23 00 42](https://user-images.githubusercontent.com/3009073/28230763-9b965854-68e8-11e7-84c4-2065f9475037.png)

**Comment by catalinii** [comment]
Hi 3PO,

can you check with the latest commit ?
If it does not work, please upload -v socket -l lock,http

Thanks

**Comment by 3PO** [comment]
>Hi 3PO,
>
>can you check with the latest commit ? ...

The Webinterface still does not work:

https://paste.pound-python.org/show/lf6DsmvgTdL1Ue0IANzr/

**Comment by catalinii** [comment]
Hi,

check if this https://github.com/catalinii/minisatip/commit/ee07b9d5596f7786abc6a1c8faf431aa70a3d481 is ok.

If no, please show me what is in the console.

Thanks

**Comment by catalinii** [comment]
Hi,

There is another issue open for the interface problem.

Can you test vdr?

Thanks

**Comment by tunip** [comment]
With latest commit ac84a70 the webinterface works fine since 30min.

**Comment by 9000h** [comment]
the status page has still issues with the commit from today
the state.jason seem to be working but there is still an error
![mini](https://user-images.githubusercontent.com/3009073/28531942-9bc0cb7c-7098-11e7-8dea-1a388dd19c34.png)

https://pastebin.com/0MFA086v

**Comment by tunip** [comment]
Issue 2 (webinterface):
To early... "Loading..." not only on "�UHD1 by ASTRA / HD+". Same message in Chrome dev console as 9000h.

**Comment by catalinii** [comment]
Hi,

please let me know if you still have issue with the latest commit.

If you do, please open a new issue.

3PO, any luck testing ?

Thank you

**Comment by 3PO** [comment]
>3PO, any luck testing ?

It seems, that minisatip is running stable now, but the Webinterface still doesn't work.

**Comment by 9000h** [comment]
it's still an issue here
https://pastebin.com/N5TEgBDy
![mini](https://user-images.githubusercontent.com/3009073/28631129-7b71587e-722c-11e7-9fb6-1ef620ea8505.png)

**Comment by tunip** [comment]
The webinterface runs since a few hours fine. Also the special chars are gone in channel names.

**Comment by catalinii** [comment]
Hi 9000h,

could you please upload a log for 12188 with:  -l http,pmt -v pmt

Thanks

**Comment by 9000h** [comment]
hope its's sufficent as I had to do this remote
https://pastebin.com/xECQCbN4

**Comment by Yuri666** [comment]
I think it's a wrong way to ignore some characters in provider and channel name. In my case (cyrillic), I lost letters in some channels name in web interface. I think need just convert from iso8859 to utf8.

**Comment by catalinii** [comment]
Hi Yuri,

no character is ignored, just that 1 or 3 bytes can be the charset. 

What issue do u have with cyrillic charset ?

9000h,
you are missing pid 17.

Thanks

**Comment by 9000h** [comment]
right with pid 17 the names come up
http://192.168.178.129:8080/?src=1&freq=12188&sr=27500&pol=h&msys=dvbs&pids=0,17,44,163,104,106

**Comment by Yuri666** [comment]
Hi,
now, if i set codepage in web browser to iso8859-5, i can see cyrillic channels name properly, but lost cyrillic symbols "p" and "T".
After i remark in pmt.c in function copy_en300568_string lines:
//              case 0xE0:
//              case 0xC2:
//                      continue;
symbols is appear in web intrface.

**Comment by catalinii** [comment]
Hi,

The code was written based on the  specs.

on which frequency and which channel do you have issues?

Thanks

**Comment by Yuri666** [comment]
For example:
12398 (R), Pids: 324,18,404,17,1,0,3304,16 : looks "МАЧ! АРЕНА HD", should be "МАТЧ! АРЕНА HD"
11842 (L), Pids: 18,100,101,102,0,1,16,17 : looks: "Экан 2. Кинозалы", should be "Экран 2. Кинозалы"

**Comment by 3PO** [comment]
It seems, its still not working reliable. :(
Minisatip stops running after a undetermined time. 

Startparms:
`/usr/bin/minisatip -F /log/minisatip.log -v socket -l lock,http -o localhost 4444 -R /etc/minisatip/html/`

Log: http://dreipo.cc/logs/minisatip3.log.tgz

**Comment by catalinii** [comment]
Hi 3PO,

please run gdb --args ./minisatip -f -l http -o localhost:4444 -R /etc/minisatip/html/ | tee /log/minisatip.log 

When it breaks, run:

bt
thread apply all bt

and provide minisatip.log

**Comment by catalinii** [comment]
Yuri, please test the latest commit, if it is not right, please open a new issue.

**Comment by Yuri666** [comment]
Ok, now looks fine, thanks!

**Comment by 3PO** [comment]
The Webinterface dont show VDR Clients (-> satip Plugin) anymore, others e.g. DVBViewer are shown.

**Comment by catalinii** [comment]
Hi,

can you provide screenshot and log (only -l http)

Thanks
