### ISSUE TITLE
cosmetic: missing Status code 455 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#37]
Status code 455 – Method Not Valid in This State

it's probably not needed at the moment, there is no multicast atm :-)

there are probably more missing

Spec
3.5.14 Status Code Definitions

**Comment by catalinii** [comment]
Do you have some suggestion where to change to return it ?

**Comment by 9000h** [comment]
if you have a look at the octonet implementation it may help, but may need a additional option or config file to specify the unicable frequency's

http://download.digital-devices.de/download/linux/octonet.source/octoserve.tar.xz

the implementation for normal diseqc is equal to minisat

they have 
static int diseqc(int fd, int sat, int hor, int band)
static int set_unicable(int fd, uint32_t freq, uint32_t sr,
                        int sat, int hor, int band,
                        uint32_t slot, uint32_t ubfreq)
static int set_jess(int fd, uint32_t freq, uint32_t sr,
                    int sat, int hor, int band,
                    uint32_t slot, uint32_t ubfreq)

www/scif.html

**Comment by catalinii** [comment]
I will close this until I have somewhere to add the status 455
