### ISSUE TITLE
[0.7-ca] channel names sometimes not shown in the webinterface

### ISSUE THREAD

**Issue by tunip** [catalinii/minisatip#373]
a) Sometimes the channel name would not be shown in the webinterface.
b) And sometimes you see 2 channel names in the webinterface.
c) On some HD+ channels you see always 2 channel names.

### Channel ORF1 HD
case 1: The channel name is shown:
![msatip_1](https://user-images.githubusercontent.com/11404472/28659730-ca7a6cba-72b0-11e7-9f88-9333b104fdb7.jpg)
[minisatip_1.log.zip](https://github.com/catalinii/minisatip/files/1179199/minisatip_1.log.zip) (-l http,pmt -v pmt)

case 2: The channel name is not shown: 
![msatip_2](https://user-images.githubusercontent.com/11404472/28659734-cc4094de-72b0-11e7-8575-b91cce4031c1.jpg)
[minisatip_2.log.zip](https://github.com/catalinii/minisatip/files/1179200/minisatip_2.log.zip) (-l http,pmt -v pmt)

case 3: Two channel names are shown (very rare on this channel):
![msatip_3](https://user-images.githubusercontent.com/11404472/28661292-7cffaaee-72b6-11e7-8cae-501d821710cd.jpg)
*after a few seconds*
![msatip_4](https://user-images.githubusercontent.com/11404472/28661294-7e83e768-72b6-11e7-8bce-39b5e39a6451.jpg)

### Channels from HD+ package
case 4: On different channels from HD+ I see always two channel names like this:
![msatip_5](https://user-images.githubusercontent.com/11404472/28665676-bb36b038-72c4-11e7-963f-3a4a97addef0.jpg)
(provide logs later)

If 2 channel names or no channel name (case 2, 3 and 4) is shown in the webinterface, OSCAM shows this in the logs:
```
2017/07/27 10:31:15 08BC87C1 c   (dvbapi) Demuxer 1 no enabled matching ecmpids -> decoding is waiting for matching readers!
2017/07/27 10:31:24 08BC87C1 c        (-) -- Skipped 1 duplicated log lines --
2017/07/27 10:31:24 08BC87C1 c      (ecm) jk (0648@000000/0001/132F/4CD277E287459791D9f5B5A622AD809E54): found (122 ms) by orf - ORF eins HD
```
It looks like minisatip it trying then to decrypt more then one channel, although only one channel is streamed.

If one channel name (case 1) is shown in the webinterface, OSCAM log has not this messages "Demuxer 1 no enabled matching ecmpids...", because only one channel is decrpyted in OSCAM (demuxer 0).

**Comment by catalinii** [comment]
Hi,

2) please let me know if "no channel" is still an issue.
3) this is an issue let me know if you can reproduce and send me logs.

When you see multiple channels it means that you are playing multiple channels. The other possibility is that you have multiple channels (like Disney and Disney Austria) sharing the same video pids or audio pids.

This causes minisatip to detect that both channels are running and send both PMTs to oscam. If either of them can be decrypted, minisatip will use the key to decrypt the channel. This is not an unusual occurence.

Thanks

**Comment by 9000h** [comment]
still happen also on a single channel

**Comment by tunip** [comment]
Hi,

thx for your fast response!

2. Will report if this is still an issue. The first ~30 channels changes are looksing fine.
3. If I start minisatip with "-l http,pmt -v pmt" the tuners staying online and would not go into offline state.
In this state I can not reproduce the issue.
If I start minisat without debug/logging options I am able to reproduce the issue after a lot of tries:
![msatip_6](https://user-images.githubusercontent.com/11404472/28669190-72fb9c16-72d3-11e7-9148-deebdf902454.jpg)
Here I play a single channel ORF1 HD like in my first post. But now the second channels is not ORF2N HD. It is now Servus TV HD Deutschland which is a FTA channel. But minisatip also tries to decrypt it.
OSCAM log: `Demuxer 1 no enabled matching ecmpids -> decoding is waiting for matching readers!` :-).

4. I play always a single channel if I am testing. And yes, they have the same video and audio pids. In my case I stream only the channel "Disney Channel HD" (PMT 96).
Disney Channel HD
![disn_1](https://user-images.githubusercontent.com/11404472/28669081-f41e2ecc-72d2-11e7-9fc3-1cd82a06549e.jpg)
Disney Channel HD Austria
![disn_2](https://user-images.githubusercontent.com/11404472/28669082-f5945236-72d2-11e7-88eb-24907400a624.jpg)

**Comment by tunip** [comment]
@9000h yes for "RTL Television" I can reproduce it (not in my channel list, but I used your URL for testing). No channel name in the webinterface. Will profide the logs later...

**Comment by catalinii** [comment]
For the channel name to work, you need also pid 17 added by the client. Minisatip does not add pid 17 automatically, that's why is possible to not have the channel name.

About issue 3, please provdei the log when you can reproduce and also the state.json (wget http://minisatip:8080/state.json)

Thanks

**Comment by catalinii** [comment]
Hi,

let me know if you had time to reproduce.

Thank you

**Comment by tunip** [comment]
Hi,

I was not able to reproduce it.

Thx
