### ISSUE TITLE
[0.7-ca] No third content delivered from webserver

### ISSUE THREAD

**Issue by tunip** [catalinii/minisatip#375]
Hello,

I use the minisatip webserver to deliver some third content do other apps.
This worked fine in version 0.5.

In version 0.7.6 it does not work anymore:
`curl -v -I http://10.10.10.66:8080/satip.xml` (also with /html/satip.xml it does not work)
```
*   Trying 10.10.10.66...
* TCP_NODELAY set
* Connected to 10.10.10.66 (10.10.10.66) port 8080 (#0)
> HEAD /satip.xml HTTP/1.1
> Host: 10.10.10.66:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 503 Service Unavailable
HTTP/1.0 503 Service Unavailable
< Date: Tue, Aug 8 12:17:31 2017 GMT
Date: Tue, Aug 8 12:17:31 2017 GMT
< Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN
< Server: minisatip/0.7.6
Server: minisatip/0.7.6
```
`curl --trace-ascii --url http://10.10.10.66:8080/satip.xml`
``` 
 curl: (52) Empty reply from server
```
Thx

**Comment by catalinii** [comment]
Hi,

can you check now ?

Thanks

**Comment by tunip** [comment]
Thx for you answer. Unfortunately still no success from loading content directly from the webserver.

Chrome debug console:
<img width="443" alt="net_error" src="https://user-images.githubusercontent.com/11404472/29320312-0c40a2ec-81d7-11e7-8814-8e4c8b22b201.png">

Curl test:
```
$ curl -o satip.xml http://10.10.10.66:8080/satip.xml
curl: (52) Empty reply from server
```

**Comment by Ntemis** [comment]
Confirm here
demetris@demetris-mate:~$ curl -v -I http://192.168.1.212:8080/satip.xml
*   Trying 192.168.1.212...
* Connected to 192.168.1.212 (192.168.1.212) port 8080 (#0)
> HEAD /satip.xml HTTP/1.1
> Host: 192.168.1.212:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
HTTP/1.0 200 OK
< Date: Tue, Aug 15 19:47:34 2017 GMT
Date: Tue, Aug 15 19:47:34 2017 GMT
< Cache-Control: no-cache
Cache-Control: no-cache
< Content-type: text/xml
Content-type: text/xml
< Server: minisatip/0.7.6
Server: minisatip/0.7.6

< 
* Closing connection 0
demetris@demetris-mate:~$ curl -o satip.xml http://192.168.1.212:8080/satip.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server

**Comment by Ntemis** [comment]
http://192.168.1.212:8080/ webpage is empty

**Comment by tunip** [comment]
The minisatip status page works fine here. Only third content like satip.xml or other files are not able to load.

**Comment by Ntemis** [comment]
This issue is now fixed for me, kuddos.

**Comment by tunip** [comment]
Fixed for me too. Many thanks!
