### ISSUE TITLE
Scanning on enigma 2 box(duo2) returns (0)/zero channels

### ISSUE THREAD

**Issue by Ntemis** [catalinii/minisatip#377]
SAT>IP client on enigma 2(DUO2) sees the DVB-T X2 tuners but when you try to scan for new channels finds nothing.
P.s, Signal is not an issue.

**Comment by catalinii** [comment]
Where is minisatip running?

Can you upload logs?

**Comment by Ntemis** [comment]
Of cource i can. Its running on armbian xenial 16.04.3 with an orange pi pc.
How i take logs?


Στις 16 Αυγ 2017 08:40, ο χρήστης "catalinii" <notifications@github.com>
έγραψε:

**Comment by catalinii** [comment]
Hi,

run ./minisatip -l http

then capture /tmp/minisatip.log and upload it here.

Take a note of frequency that you cannot scan.

Thanks

**Comment by Ntemis** [comment]
Will upload log asap

Στις 17 Αυγ 2017 8:46 π.μ., ο χρήστης "catalinii" <notifications@github.com>
έγραψε:

**Comment by Ntemis** [comment]
Here you go
http://dpaste.com/3P4XATB
[minisatip.log.zip](https://github.com/catalinii/minisatip/files/1232331/minisatip.log.zip)

**Comment by catalinii** [comment]
I don't see any connection from some other IP to minisatip requesting data. 
I use myself also enigma and minisatip and have no issue with it.

Maybe you should try manual scan with network detection.

**Comment by Ntemis** [comment]
Looks like Official Blackhole image was the fault.
I switch to openvix and works, closing down
