### ISSUE TITLE
minisatip doesnt run after reboot of the server

### ISSUE THREAD

**Issue by Ntemis** [catalinii/minisatip#378]
minisatip configuration

Linux DVB:				  enabled
Common Interface (needs DVBEN50221):	  disabled
OpenSSL (AES as part of DVBAPI):	  enabled
Embedded system:			  disabled
DVBCSA (needs libdvbcsa):		  disabled
Netceiver support:			  disabled
SatIP Client:				  enabled
Static:					  disabled
dvbapi:					  enabled
axe:					  disabled
enigma:					  disabled

minisatip: error while loading shared libraries: libdvben50221.so: cannot open shared object file: No such file or directory
I have to make clean then configure again and build(make) then it works until i reboot again

**Comment by catalinii** [comment]
Your issue happened because you've compiled with DVBCA and then for some reason the library was not in LD_LIBRARY_PATH.

I will close this as it is an environmental problem.
