### ISSUE TITLE
feature request: unicable for dvb-s

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#38]
would be nice to have unicable EN50494 and maybe also EN50607/JESS support like the octonet in minisatip, this would help people without legacy SAT plugs

**Comment by catalinii** [comment]
This sounds interesting, do you have where to test this ?

**Comment by 9000h** [comment]
I have a TechniSat: TechniRouter Mini 2/1x2 here

**Comment by 9000h** [comment]
f you have a look at the octonet implementation it may help, but may need a additional option or config file to specify the unicable frequency's

http://download.digital-devices.de/download/linux/octonet.source/octoserve.tar.xz

the implementation for normal diseqc is equal to minisat

they have
static int diseqc(int fd, int sat, int hor, int band)
static int set_unicable(int fd, uint32_t freq, uint32_t sr,
int sat, int hor, int band,
uint32_t slot, uint32_t ubfreq)
static int set_jess(int fd, uint32_t freq, uint32_t sr,
int sat, int hor, int band,
uint32_t slot, uint32_t ubfreq)

www/scif.html

**Comment by 9000h** [comment]
unicable EN50494 is now working also with a least disqec A and B
in my case adapter 2 scr 0 freq 1284 
minisatip -l - -e2 -f -u2:0-1284

the needed patch:

--- dvb.c.orig	2015-02-17 09:33:47.000000000 +0100
+++ dvb.c	2015-02-17 13:11:21.578081620 +0100
@@ -257,11 +257,14 @@
 	LOGL(3, "send_unicable fd %d, freq %d, ufreq %d, pos = %d, pol = %d, hiband = %d, slot %d, diseqc => %02x %02x %02x %02x %02x",
                   fd, freq, ufreq, pos, pol, hiband, slot, cmd.msg[0], cmd.msg[1], cmd.msg[2], cmd.msg[3], cmd.msg[4]);
 
+	if (ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_13) == -1)
+		LOG("send_unicable: pre voltage  SEC_VOLTAGE_13 failed for fd %d: %s", fd, strerror(errno));
+	msleep(35);
 	if (ioctl(fd, FE_SET_TONE, SEC_TONE_OFF) == -1)
 		LOG("send_unicable: FE_SET_TONE failed for fd %d: %s", fd, strerror(errno));
+	msleep(15);
 	if (ioctl(fd, FE_SET_VOLTAGE, SEC_VOLTAGE_18) == -1)
 		LOG("send_unicable: FE_SET_VOLTAGE failed for fd %d: %s", fd, strerror(errno));
-	msleep(15);
 	if (ioctl(fd, FE_DISEQC_SEND_MASTER_CMD, &cmd) == -1)
 		LOG("send_unicable: FE_DISEQC_SEND_MASTER_CMD failed for fd %d: %s", fd, strerror(errno));
 	msleep(15);

**Comment by 9000h** [comment]
the jess part needs also the "pre voltage" but I do not have the hardware atm to test

**Comment by catalinii** [comment]
Thanks :)
will add those in the next commit

**Comment by 9000h** [comment]
we should also think about a mutex lock when tune unicable/jess to avoid issues on the "bus"

**Comment by catalinii** [comment]
Hi, now minisatip is single threaded so nobody is touching the bus while we are in send_*, so for now I am trying to avoid locks....

If the design will change, locks will be needed in alot of places...

**Comment by 9000h** [comment]
that's fine with the single threaded server atm
one addition for unicable is still missing 
it's the "PIN" support, but I have unfortunately nothing where I can test that it's a minor change and low prio

**Comment by catalinii** [comment]
In the next commit there will be support for this (untested)....

**Comment by catalinii** [comment]
Hi,

Please reopen this when you can test it if there are any issues.

Thanks

**Comment by 9000h** [comment]
will do so
