### ISSUE TITLE
Slave configuration in minisatip 0.7-ca

### ISSUE THREAD

**Issue by kaffeekanne** [catalinii/minisatip#382]
Is configuring slave devices disabled 0.7-ca branch? When trying to use it, minisatip starts saying "module -S/--slave not found" and starts normally. In branch 0.5 everything works as documented. I can understand if this quirk is removed, but liked the feature.

**Comment by catalinii** [comment]
Hi,

can you provide the command line and the logs (first few lines) ?

Thanks

**Comment by catalinii** [comment]
If you have the logs please reopen this.

Thank you
