### ISSUE TITLE
dvbapi issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#385]
since 02.09 dvbapi fixes I do have unusual results

**Comment by 9000h** [comment]
lastest commit from today seems to fix ist

**Comment by 9000h** [comment]
works when fresh started but after some channel switches to different delivery systems dvbs dvbc satipc I got freezer on ever cw switch

**Comment by 9000h** [comment]
the issue starts with commit
"coverity fixes and increase the satip agressivity into getting the signal"

**Comment by 9000h** [comment]
it only happens here with -l http,dvbapi (and did crash), without any log it seems to work

**Comment by catalinii** [comment]
Hi,

can you test ?

Thank you

**Comment by 9000h** [comment]
one warning at compile time
```
/include/libxml2 -DDISABLE_DDCI  -c utils.c -o ../build/utils.o
utils.c: In function ‘get_current_timestamp_log’:
utils.c:648:6: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  if (gettimeofday(&tv, NULL))
      ^
```

**Comment by 9000h** [comment]
still crashes but could not reproduce it when I run it with gdb
```
[24/09 13:25:46.793 AD4]: clearing filter on PID 397 FD 58
[24/09 13:25:46.794 AD4]: dvbapi: sending ECM key 0 for pid 0096 (150), current ecm_parity = 0, previous parity 0, demux = 0, filter = 6, len = 183 [88 70 B4 00]
[24/09 13:25:46.834 signal]: Mutex init 0x8096d20
[24/09 13:25:46.834 signal]: BW 143KB/s, Total BW: 0 MB, ns/read 7935, r: 24, w: 126 fw: 0, tt: 190 ms
[24/09 13:25:46.844 AD4]: dvbapi: sending ECM key 0 for pid 0096 (150), current ecm_parity = 0, previous parity 0, demux = 0, filter = 6, len = 183 [88 70 B4 00]
RECEIVED SIGNAL 11 - SP=0 IP=0
Obtained 10 stack frames.
map_intd at /usr/src/satip/minisatip-0.7-ca/src/utils.c:347
map_intd at /usr/src/satip/minisatip-0.7-ca/src/utils.c:358
?? ??:0
?? ??:0
?? ??:0
print_trace at /usr/src/satip/minisatip-0.7-ca/src/utils.c:481
dvb_demux_set_pid at /usr/src/satip/minisatip-0.7-ca/src/dvb.c:942
dvb_demux_set_pid at /usr/src/satip/minisatip-0.7-ca/src/dvb.c:955
set_adapter_dmxsource at /usr/src/satip/minisatip-0.7-ca/src/adapter.c:1736 (discriminator 3)
select_and_execute at /usr/src/satip/minisatip-0.7-ca/src/socketworks.c:803
0x8060d28 : 0x8060e15 : 0xb77c8cfc : 0xb73b7383 : 0xb73d93df : 0x80614c3 : 0x80807c1 : 0x808087e : 0x805f11b : 0x805220c : 
```

**Comment by catalinii** [comment]
Hi,

You can comment line 1539 (set_signal_handler) in utils.c.

Then run: ulimitc -c unlimited

And start minisatip.

When it crashes u should have a core file then run

gdb ./minisatip core

Then bt
Thread apply all bt

Thanks

**Comment by 9000h** [comment]
I did try but I'm unable to get a core 
```
[24/09 15:16:43.556 AD4]: dvbapi: sending ECM key 0 for pid 0096 (150), current ecm_parity = 0, previous parity 0, demux = 0, filter = 6, len = 183 [88 70 B4 00]
RECEIVED SIGNAL 11 - SP=0 IP=0
Obtained 10 stack frames.
map_intd at /usr/src/satip/minisatip-0.7-ca/src/utils.c:347
map_intd at /usr/src/satip/minisatip-0.7-ca/src/utils.c:358
?? ??:0
?? ??:0
?? ??:0
print_trace at /usr/src/satip/minisatip-0.7-ca/src/utils.c:481
dvb_demux_set_pid at /usr/src/satip/minisatip-0.7-ca/src/dvb.c:943
dvb_demux_set_pid at /usr/src/satip/minisatip-0.7-ca/src/dvb.c:955 (discriminator 1)
set_adapter_dmxsource at /usr/src/satip/minisatip-0.7-ca/src/adapter.c:1736 (discriminator 3)
select_and_execute at /usr/src/satip/minisatip-0.7-ca/src/socketworks.c:803
0x8060d28 : 0x8060e15 : 0xb7768cfc : 0xb7357383 : 0xb73793df : 0x80614c3 : 0x80807c1 : 0x808087e : 0x805f11b : 0x805220c :
```

**Comment by catalinii** [comment]
Hi

Could you try to delete the entire minisatip dir and clone from github
again?

Thanks

**Comment by 9000h** [comment]
did clone it fresh from git
git clone -b 0.7-ca https://github.com/catalinii/minisatip.git
If I start it with -l http,dvbapi from cli then it still crashes with SIGNAL 11
````
minisatip -o 192.168.178.129:2000  -Y 0:dvbt2,1:dvbt2,2:dvbt2,3:dvbt2  -u 4:4-984[-48],5:5-1020[-23],6:6-1056[-88],7:7-1092[-204] -m 0040caa2c79d  -s 
dvbc:192.168.178.129/192.168.178.1 -s dvbc:192.168.178.130/192.168.178.1 -lhttp,dvbapi -f
````
If I run it with gdb it did not crash.
````
gdb --args ./minisatip  -o 192.168.178.129:2000 -Y 0:dvbt2,1:dvbt2,2:dvbt2,3:dvbt2 -u 4:4-984[-48],5:5-1020[-23],6:6-1056[-88],7:7-1092[-204] -m 0040caa2c79d -s dvbc:192.168.178.129/192.168.178.1 -s dvbc:192.168.178.130/192.168.178.1 -l http,dvbapi -f
````
very strange

**Comment by catalinii** [comment]
Which channel you have issues with?

**Comment by 9000h** [comment]
the channel is on Hotbird 13 East
#EXTINF:-1,Hotbird 13.0E MEZZO
rtsp://192.168.178.129/?src=2&freq=11623&sr=27500&fec=34&pol=v&msys=dvbs&pids=0,115,125,135

**Comment by catalinii** [comment]
Just starting minisatip and playing mezzo ? Nothing else?

**Comment by 9000h** [comment]
yes starting minisatip from a terminal cli and playing mezzo via vlc

**Comment by catalinii** [comment]
What OS are you using? x86_64?

**Comment by 9000h** [comment]
no this one is i386

 file minisatip
minisatip: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=879fdf391d05d9d5d46c7092d7aaaa14fd68c68c, not stripped

"Ubuntu 16.04.3 LTS"
Linux satip 4.8.0-30-lowlatency #32~16.04.1-Ubuntu SMP PREEMPT Fri Dec 2 04:48:29 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by catalinii** [comment]
Hi,

Tried it in a docker container but no luck reproducing.

Could you try valgring ./minisatip .... 2>log.txt 1>log.txt


Thanks

**Comment by 9000h** [comment]
Hi,
 not much time atm, but sent you the valgrind log.
CU

**Comment by catalinii** [comment]
It appears again a crash from dvb.c that should be fixed already ( the LOG line is reported at 1171, in the latest commit from Master there is no LOG at that line).

There is no info about the dvbapi issue.

Thanks

**Comment by 9000h** [comment]
unfortunately it still crashes here
valgrind log sent

**Comment by haarm** [comment]
It's not stable here either.
Channels are no longer decoded after X time.

**Comment by catalinii** [comment]
Hi

If it is not crashing please open a new issue and upload logs (with -l
dvbapi,pmt,http)

Thanks

**Comment by 9000h** [comment]
did a quick test and the issue is probably also fixed with the commit from today, will test again later today

**Comment by 9000h** [comment]
when testing in the same environment it still crashes, very strange

**Comment by haarm** [comment]
Minisat does not support, it simply does not decrypt after X time.
Free to Air always goes

**Comment by 9000h** [comment]
@haarm your issue is probably a different one, in my environment it crashes only with with -l
dvbapi under defined use, if I use it without -l dvbapi the there is no issue with decrypting or fta channels

**Comment by haarm** [comment]
-l only gives to the logfile that is written to... right? This has nothing to do with decoding.

**Comment by catalinii** [comment]
Probably some LOG line is wrong. But if your does not crash please open a
new issue.

**Comment by 9000h** [comment]
I finally found the issue, it was my fault here as I had by accident a binary in /usr/sbin and it was a difference between ./minisatip and minisatip. 

Sorry to to cause inconvenience.
