### ISSUE TITLE
ddci - multiple declaration of dvbca_del_pmt

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [catalinii/minisatip#386]
Hey,
when i try to compile latest 0.7-ca branch i got following : 

ddci.c:98: Multiple Declaration of `dvbca_del_pmt'

**Comment by catalinii** [comment]
Hi

Ddci code is disabled and still in development.  Until ready will be
disabled by default. I will let everyone jnow when is ready for testing.

Thanks

**Comment by c-o-m-m-a-n-d-e-r** [comment]
great glad to hear that ... do you have a timeline for that? round about? :-)

**Comment by catalinii** [comment]
Not really as I do not have much time, but I am working on it.

Please feel free to use #126 for comments.

I will close this
