### ISSUE TITLE
Plex - Live TV & DVR channel scan did not find channels

### ISSUE THREAD

**Issue by tunip** [catalinii/minisatip#388]
Hello,

if i try to scan for channels in Plex via SATIP protocol, zero channels are found. With another SATIP device (Digital Devices Octopus Net) channels are found.

minisatip log (-l http):
[minisatip.log.zip](https://github.com/catalinii/minisatip/files/1356871/minisatip.log.zip)

Plex Tuner Service log:
[plex_tuner_service.log.zip](https://github.com/catalinii/minisatip/files/1356890/plex_tuner_service.log.zip)

Thx

**Comment by NightHammer1000** [comment]
Yep. Same Issue here. Tried out almost everything.
I can see via the Status Page that the Frequencys are being polled but it seems that Plex just cant find anything.

**Comment by catalinii** [comment]
Hi,
I am in contact with some people from dvblink about this.

Will let you know once I have more details.

Thanks

**Comment by NightHammer1000** [comment]
If we can help in any way let me know. I can Provide Logs if needed

**Comment by NightHammer1000** [comment]
News on that?

**Comment by catalinii** [comment]
Hi, I am still waiting on an answer from dvnlogic.

Thanks

**Comment by HazCod** [comment]
@catalinii did you hear about this?

**Comment by catalinii** [comment]
Hi, I am still waiting for an update about this.

Thanks

**Comment by NightHammer1000** [comment]
Still nothing on this?

**Comment by catalinii** [comment]
Check the latest commits.

Thank you

**Comment by hanzoh** [comment]
As this fix is now included in the latest satip-axe build, I just tried this out and it working correctly!

**Comment by tunip** [comment]
Thanks the fix.
