### ISSUE TITLE
enhancement: ATSC support

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#39]
for people outside Europe like US this is a must

**Comment by catalinii** [comment]
This sounds interesting, however how do we integrate this in SATIP protocol, as I would not want to break the compatibility with existing satip clients.

I am not sure if there is some client out there that can use this.
+ There have HDHomeRun as protocol I guess (which is for ATSC)

**Comment by 9000h** [comment]
it's low priority I think and should no that complicated as it is very similar to normal DVB, the bigger issue would be to find someone who can test/help

**Comment by catalinii** [comment]
Lets see maybe satip will add support in the standard too

**Comment by 9000h** [comment]
a adapter looks like this and the default could be 8VSB

Info: using DVB adapter auto detection.
   /dev/dvb/adapter0/frontend0 -> TERRCABLE_ATSC "HDHomeRun ATSC": good :-)
   /dev/dvb/adapter1/frontend0 -> TERRCABLE_ATSC "HDHomeRun ATSC": good :-)
Using TERRCABLE_ATSC frontend (adapter /dev/dvb/adapter0/frontend0)
-_-_-_-_ Getting frontend capabilities-_-_-_-_
Using DVB API 5.10
frontend 'HDHomeRun ATSC' supports
INVERSION_AUTO
8VSB
16VSB
QAM_64
QAM_256
FREQ (54.00MHz ... 858.00MHz)
...
...

**Comment by catalinii** [comment]
I saw the api for ATSC (both sat and cable) and is not much different or much work to add support for it ...
As I said one problem is how we control the DVB card (rtsp request) and which clients will accept it...
The another problem will be the XML, more specifically in X_SATIPCAP how do we report atsc hardware without breaking compatibility with existing software ?

And if someone here have the hardware and willing to test I guess we can try to make it work.

Thanks

**Comment by 9000h** [comment]
catalinii, thats the way to go

**Comment by catalinii** [comment]
Done as well.

closing this, if there are any issues with this, please let me know
