### ISSUE TITLE
Crash with "stack smashing detected"

### ISSUE THREAD

**Issue by localhosthack0r** [catalinii/minisatip#394]
Hi,

I have sometimes crashes of minisatip, tried to keep logging active (just -l), that produced a huge log (141 MB), but I think I recorded the crash.

Here a snipped:
`[21/11 22:34:48.271 main]: read HTTP from 23 sid: -1: 
*** stack smashing detected ***: /home/andre/minisatip/minisatip terminated
RECEIVED SIGNAL 6 - SP=0 IP=0
RECEIVED SIGNAL 11 - SP=0 IP=0
Obtained 10 stack frames.
print_trace bei /home/andre/minisatip/src/utils.c:475
posix_signal_handler bei /home/andre/minisatip/src/utils.c:513
?? ??:0
?? ??:0
?? ??:0
?? ??:0
print_trace bei /home/andre/minisatip/src/utils.c:475
posix_signal_handler bei /home/andre/minisatip/src/utils.c:513
?? ??:0
?? ??:0
0x41b6e0 : 0x41b7cf : 0x7f0db239a390 : 0x7f0da9a61ccb : 0x7f0da9a63668 : 0x7f0db1875b0f : 0x41b6e0 : 0x41b7cf : 0x7f0db239a390 : 0x7f0db1795428 : [21/11 22:35:01.828 main]: Initializing with 4 devices`

Complete log at 
https://www.file-upload.net/download-12827497/minisatip.StackSmash.log.html

**Comment by catalinii** [comment]
Hi,

could you comment at line 1539 in utils.c the line:
// set_signal_handler(arg0);

The run: ulimit -c unlimited; ./minisatip ....

When minisatip crashes a core file will be generated, the run:

gdb ./minisatip core
> thread apply all bt
and upload the logs and output here.

Thank you

**Comment by localhosthack0r** [comment]
Hmm,... did what you recommended, but that does not look very helpful to me, maybe I did something wrong?


GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
./minisatip: Erfolg.
[New LWP 10354]
[New LWP 10355]
[New LWP 10356]
[New LWP 10358]
[New LWP 10357]
Core was generated by `/home/andre/minisatip/minisatip -l dvbapi,pmt,tables,http -H 1:5 -b 4042752 -B'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f69662fa428 in ?? ()
[Current thread is 1 (LWP 10354)]
(gdb) thread apply all bt

Thread 5 (LWP 10357):
#0  0x00007f69663c070d in ?? ()
#1  0x0000000000000000 in ?? ()

Thread 4 (LWP 10358):
#0  0x00007f69663c070d in ?? ()
#1  0x0000000000000000 in ?? ()

Thread 3 (LWP 10356):
#0  0x00007f69663c070d in ?? ()
#1  0x0000000000000000 in ?? ()

Thread 2 (LWP 10355):
#0  0x00007f69663c070d in ?? ()
#1  0x0000000000000000 in ?? ()

Thread 1 (LWP 10354):
---Type <return> to continue, or q <return> to quit---
#0  0x00007f69662fa428 in ?? ()
#1  0x00007f69662fc02a in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb)

**Comment by catalinii** [comment]
Hi,

can you reproduce this?

Thanks

**Comment by localhosthack0r** [comment]
Changed my hardware setup, and with this it is not reproducible, currently.
