### ISSUE TITLE
Web-GUI did not work, if started with absolute path

### ISSUE THREAD

**Issue by sumulu** [catalinii/minisatip#396]
If you are inside the folder with the minisatip binary and execute it here, Web-GUI is working.

If you start it from outside of this folder, like:

root@raspberrypi:~# ./minisatip/minisatip -f --delsys 1:dvbc2 -p /pl.m3u

Web-GUI shows error 404 in Google Chome.
If this is not a bug, you should get a warning message.

**Comment by catalinii** [comment]
Hi,

there is -R option where you can specify the path to the html document root.
Generally minisatip tests for the presence of html folder in the local dir.

Thanks
