### ISSUE TITLE
Web-GUI: Loading bar in signal column stops working

### ISSUE THREAD

**Issue by sumulu** [catalinii/minisatip#397]
If I start the server and open in my satip app one channel seconds later, I see in column "signal" real values of STR and SNR strength. After 5 minutes, I see only zero percent for every channel.

My system is:
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
Adapter: Hauppauge WinTV-soloHD

**Comment by catalinii** [comment]
Hi.

can you upload log and screenshot ?

Thanks

**Comment by 3PO** [comment]
Same problem here:

minisatip version: https://github.com/catalinii/minisatip/commit/04ab04bd6271231de7287b38cc0a85c07a73e3c2


![2018-01-06_174720](https://user-images.githubusercontent.com/945108/34641815-142f13c2-f30a-11e7-931d-992407e7ae8f.png)

**Comment by catalinii** [comment]
Hi,

can you please upload the log AND the screenshots ?

-l http,dvb,adapter

Thanks

**Comment by sumulu** [comment]
First run, some seconds after server start:
![first_run_of_client_after_start](https://user-images.githubusercontent.com/26624688/36219123-b0d7a32c-11b6-11e8-9d00-38a2782037b1.PNG)

Second run of SAT-IP app, one minute later:
![second_run_of_client_after_waiting](https://user-images.githubusercontent.com/26624688/36219142-baba6e6a-11b6-11e8-9f12-fa501deda823.PNG)

[LOGFILE.txt](https://github.com/catalinii/minisatip/files/1725080/LOGFILE.txt)

[14/02 18:25:24.251 signal]: ioctl fd 10 FE_READ_BER failed, error 95 (Operation not supported)
[14/02 18:25:24.251 signal]: ioctl fd 10 FE_READ_SIGNAL_STRENGTH failed, error 95 (Operation not supported)
[14/02 18:25:24.251 signal]: ioctl fd 10 FE_READ_SNR failed, error 95 (Operation not supported)

**Comment by sumulu** [comment]
Here is second LOGFILE with "http,dvb,adapter"

[LOGFILE2.txt](https://github.com/catalinii/minisatip/files/1725099/LOGFILE2.txt)

**Comment by lars18th** [comment]
Hi @sumulu ,

It's the problem fixed with latest version?
If yes then close this issue.

Thank you!

**Comment by Jalle19** [comment]
Closing this since there's been much work done on the signal strength reporting lately. Please re-open if this exact issue persists, preferably with new screenshots and logs.
