### ISSUE TITLE
cannot build minisatip (‘DMX_SET_SOURCE’ undeclared)

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#402]
cannot build minisatip  commit  81e10bd

https://paste.pound-python.org/show/uCtvhgMp7tFBMwhyc8K3/

**Comment by 9000h** [comment]
no issue here

**Comment by catalinii** [comment]
@3PO, did you change the OS, or some kinda of libraries?

I did not change the code around DMX_SET_SOURCE, but this ioctl is used mostly on boxes running enigma.

Thanks

**Comment by 3PO** [comment]
i use 

`server02 ~ # uname -a
Linux server02 4.14.8-gentoo-r1 #1 SMP Fri Dec 29 18:46:52 CET 2017 x86_64 Intel(R) Pentium(R) CPU N3700 @ 1.60GHz GenuineIntel GNU/Linux
server02 ~ #
`

But it seems since kernel 4.14 DMX_SET_SOURCE does not exists anymore.

https://paste.pound-python.org/show/FhDBbsuCtBwKypvyffzo/

**Comment by catalinii** [comment]
I will put an ifdef around those lines of code, is anyway not needed in Linux

**Comment by 3PO** [comment]
FYI:
--> https://patchwork.kernel.org/patch/9938909/

**Comment by 9000h** [comment]
or as workaround like OpenPLi did fix it
https://github.com/OpenPLi/enigma2/commit/7996dbb88a72603a3cacf0609195a822eee1a1da

**Comment by catalinii** [comment]
I saw this commit before, but did not pay attention to it.

Now I have defined DMX_SET_SOURCE just for enigma boxes as is not needed in Linux.

**Comment by 3PO** [comment]
Now i can build minisatip without any issuses again. :)

--> https://paste.pound-python.org/show/tbf0l0sMWndUZHNMQ7eD/

Thanks!
