### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#405]
Sometimes minisatip stops woking with to message, "stack smashing detected".

Log: https://paste.pound-python.org/show/ANgsPxlQ6IRlzuKQqtXE/

**Comment by catalinii** [comment]
hi,

can you reproduce this at will?

thanks

**Comment by 3PO** [comment]
Yes We Can! :)

Steps to reproduce:

On my satip Server i start minisatip with this parms:

`/usr/bin/minisatip --delsys 8:dvbt,9:dvbt,10:dvbt,11:dvbt,12:dvbt,13:dvbt,14:dvbt,15:dvbt -F /log/minisatip.log -o localhost 4444 -R /etc/minisatip/html/`

The client is a VDR (2.3.8) with the satip Plugin, started with this parms:

`--plugin='satip --devices=4'`

minisatip and the satip plugin are the newest from git.

I zap the channels up and down, an after a few minutes, minisatip stops working with the above error message.

**Comment by 3PO** [comment]
No further suggestions?

**Comment by 9000h** [comment]
do you see something like this in dmeg or syslog?

Dec 20 16:21:43 localhost kernel: vmap allocation for size 16781312 failed: use vmalloc= to increase size.

**Comment by catalinii** [comment]
Sorry guys, just busy those days, did not have time to look into this yet

**Comment by 9000h** [comment]
try to run it in gdb
ulimit -c unlimited to get a core
gdb --args /usr/bin/minisatip  -f --delsys 8:dvbt,9:dvbt,10:dvbt,11:dvbt,12:dvbt,13:dvbt,14:dvbt,15:dvbt

when it crashes apply:

set filename-display absolute
thread apply all bt
handle SIGPIPE nostop noprint pass
bt

**Comment by 3PO** [comment]
All i can see, is this:

    server02 ~ # ulimit -c unlimited
    server02 ~ # gdb --args /usr/bin/minisatip --delsys 8:dvbt,9:dvbt,10:dvbt,11:dvbt,12:dvbt,13:dvbt,14:dvbt,15:dvbt -F /log/minisatip.log -o localhost 4444 -R /etc/minisatip/html/
    GNU gdb (Gentoo 7.12.1 vanilla) 7.12.1
    Copyright (C) 2017 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-pc-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <https://bugs.gentoo.org/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from /usr/bin/minisatip...(no debugging symbols found)...done.
    (gdb)

**Comment by 9000h** [comment]
and then type in 
set filename-display absolute
thread apply all bt
handle SIGPIPE nostop noprint pass
run

an let it run until it crashes
then type
bt

**Comment by 3PO** [comment]
server02 ~ # gdb --args /usr/bin/minisatip --delsys 8:dvbt,9:dvbt,10:dvbt,11:dvbt,12:dvbt,13:dvbt,14:dvbt,15:dvbt -F /log/minisatip.log -o localhost 4444 -R /etc/minisatip/html/                                                            GNU gdb (Gentoo 7.12.1 vanilla) 7.12.1
    Copyright (C) 2017 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-pc-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <https://bugs.gentoo.org/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from /usr/bin/minisatip...(no debugging symbols found)...done.
    (gdb) set filename-display absolute
    (gdb) thread apply all bt
    (gdb) handle SIGPIPE nostop noprint pass
    Signal        Stop      Print   Pass to program Description
    SIGPIPE       No        No      Yes             Broken pipe
    (gdb) run
    Starting program: /usr/bin/minisatip --delsys 8:dvbt,9:dvbt,10:dvbt,11:dvbt,12:dvbt,13:dvbt,14:dvbt,15:dvbt -F /log/minisatip.log -o localhost 4444 -R /etc/minisatip/html/
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    [27/01 00:58:40.513 main]: Setting delivery system for adapter 8 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 9 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 10 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 11 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 12 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 13 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 14 to dvbt and undefined
    [27/01 00:58:40.514 main]: Setting delivery system for adapter 15 to dvbt and undefined
    [Inferior 1 (process 3063) exited normally]
    (gdb) bt
    No stack.
    (gdb)

**Comment by 9000h** [comment]
no to need add minisatip -f option  to run it in foreground

**Comment by 3PO** [comment]
I don't know way, but i seems the problem is gone.
I'm not able to reproduce it anymore.

Maybe voodoo? :)

**Comment by catalinii** [comment]
If it happens again, do:

make clean;make EXTRA_CFLAGS=-fsanitize=address

and run minisatip and see if u can reproduce. This option will slow down minisatip (so it should not be an issue if your CPU is fast)

**Comment by 3PO** [comment]
No, it seems not, so this issue can be closed.
