### ISSUE TITLE
Sound absent issues.

### ISSUE THREAD

**Issue by Yuri666** [catalinii/minisatip#407]
Hi,
i have minisatip and tvheadend as client.
One 4k channel have no sound, minisatip and tvheadend don't see sound pid.
I found that channel have ac3 sound with stream type = user private stream (0x81).
After i changing pmt.c the issue is gone:
```
@@ -1501,6 +1501,8 @@
                isAC3 = 0;
                if (stype == 6)
                        isAC3 = is_ac3_es(pmt_b + i + 5, es_len);
+               else if(stype == 129)
+                       isAC3 = 1;

                if (pmt->all_pids < MAX_PMT_PIDS - 1)
```
Second channel (Rai 4K at 13e) have two sound streams (aac adts) and not have sound at tvheadend, becouse minisatip can't found sound streams. 
I have gcc version 4.9.2 (Raspbian 4.9.2-10) and don't know C syntax, but after changing pmt.c i have sound:
```
@@ -1514,7 +1516,7 @@
                        LOGM("pmt processing complete, es_len + i %d, len %d, es_len %d", es_len + i, pmt_len, es_len);
                        break;
                }
-               if (stype != 2 && stype != 3 && stype != 4 && !isAC3 && stype != 27 && stype != 36 && stype != 15)
+               if ((stype != 2) && (stype != 3) && (stype != 4) && !isAC3 && (stype != 27) && (stype != 36) && (stype != 15))
                        continue;

```

**Comment by catalinii** [comment]
Hi,

can you create a PR ?

Thank you
