### ISSUE TITLE
simplify code

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#416]
to simplify the could we not replace the map_intd function with strtol, the only drawback I could see is in some places the usage of NULL and this could have some impact

**Comment by catalinii** [comment]
Hi,

yes that is the point of map_intd was created, to check for NULL (as strtol will crash).
Currently, there are plenty of places where the map_intd is called with NULL argument, checking for NULLs in all those places will make the code harder to read, except the time required to add the extra code.

Thanks

**Comment by 9000h** [comment]
understood
