### ISSUE TITLE
 No RTCP packet type 204

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#42]
This relates maybe to the missing signal quality, lock status on the client side like the android signal meter tool

The SAT>IP specification specifies the delivery of RTCP packets together with the RTP packets. Those RTCP packets of type 204 contain the status information of the associated stream.
Exampe: ver1.2;src=1; tuner1,240,1,7,112,,dvbc,,,,6900,34;pids=0,16,17,18,20
This also includes the status information (e.g. signal quality, lock status, etc.) of the tuner. 

this is the client side:
https://code.google.com/p/satip/source/browse/satip/satip_rtp.c?r=a72d5083b2a54c2611bb2039cda0a076500442f5#52

**Comment by catalinii** [comment]
in send_rtcp, stream.c: CC is 204, did u managed to reproduce this error ?

**Comment by 9000h** [comment]
no not jet

**Comment by catalinii** [comment]
Can you please do it and I hope to be able to try the Android app (did not have too much luck since here I have just a DVB-T card, my DVB-S card is remote)

**Comment by 9000h** [comment]
will do so, i need to sniff the traffic between the app and my digibit where it works fine.

**Comment by catalinii** [comment]
Tried to test today rtcp, found some issues but the app is still not working...
I am waiting for your capture to see what is different between minisatip and digibit.

**Comment by catalinii** [comment]
Close .. Same as issue #58
