### ISSUE TITLE
Remote SAT-IP server connection check and special ports problem

### ISSUE THREAD

**Issue by sumulu** [catalinii/minisatip#424]
I tested to connect a remote SAT>IP server.

It would be helpful, if connection is checked while start and show you a server connection error on failure in the status page. I mean check for a answer on this port or check, if it is really a rtsp stream.

![example_of_faked_server](https://user-images.githubusercontent.com/26624688/36174794-b357fec0-110d-11e8-90d5-6943f5dd7ff1.PNG)

I got it only to work, if minisatip connects to remote server on port 554 or 8554.
I used another port forward on the router in the external network instead of 8554.

I tested different SAT>IP Clients, but no stream starts.
Status page show me that something is connected while the test.
If you look in the column "streams" ... there is no channel name, but PIDs.

![status_page_on_exotic_port](https://user-images.githubusercontent.com/26624688/36175228-0b2736ba-110f-11e8-9505-30c3ec7744a4.PNG)

**Comment by catalinii** [comment]
If minisatip did not work on another port than 554 or 8554, please upload a log. (./minisatip -f -l http )

Thanks

**Comment by sumulu** [comment]
After server start, I switched two times the channel. Status bar was working 3 times.
I closed SAT-IP app and waited until I saw tuner offline message on status page.
I started SAT-IP app again and channel status bar did not work anymore.

![status_page_on_exotic_port](https://user-images.githubusercontent.com/26624688/36218641-5dd2e16a-11b5-11e8-9db4-7547dc3999d7.PNG)

![second_run_of_client_after_waiting](https://user-images.githubusercontent.com/26624688/36218650-628adbc2-11b5-11e8-8a46-6a1e049ad698.PNG)

[14/02 18:25:24.251 signal]: ioctl fd 10 FE_READ_BER failed, error 95 (Operation not supported)
[14/02 18:25:24.251 signal]: ioctl fd 10 FE_READ_SIGNAL_STRENGTH failed, error 95 (Operation not supported)
[14/02 18:25:24.251 signal]: ioctl fd 10 FE_READ_SNR failed, error 95 (Operation not supported)

Attached the complete LOGFILE.

[LOGFILE.txt](https://github.com/catalinii/minisatip/files/1725045/LOGFILE.txt)

**Comment by sumulu** [comment]
Sorry first screenshot is wrong... because it is DVB-C.

![first_run_of_client_after_start](https://user-images.githubusercontent.com/26624688/36218839-f0cdb062-11b5-11e8-932a-35f2d727ad4a.PNG)

**Comment by sumulu** [comment]
LOG file with port 8554 ... this version works.

[LOGFILEOK_port8554.txt](https://github.com/catalinii/minisatip/files/1725191/LOGFILEOK_port8554.txt)

LOG file with port 8555 ... this version did not work.

[LOGFAILED_port8555.txt](https://github.com/catalinii/minisatip/files/1725193/LOGFAILED_port8555.txt)

Port forward is working, because I see in the WebGUI of my external Selfsat-IP-Server a rtsp connection.
This means, I see my WAN-IP in the client list. Stream goes to my local minisatip server, because I see a channel connection, but stream does not start on SAT>IP clients.

![selfsat-webgui](https://user-images.githubusercontent.com/26624688/36221628-fbca4710-11be-11e8-931f-6e8a64dfd4cc.PNG)

**Comment by catalinii** [comment]
I do not see any error on minisatip side (or coming from the server), just that the stream does not arrive. I see also minisatip receiving the report with signal, but no actual stream is received from the server (ALL PIDS have counter  = 0)

**Comment by sumulu** [comment]
Confirmed, it's not a problem of minisatip. I tested with DVDViewer 6.0.4 and connected direct to the WAN-IP of external router. Same situation .... only 554 and 8554 port forward is working. I think the problem is the firmware on the SAT-IP-Server, because connection is established, but I got no video stream. closed.
