### ISSUE TITLE
priority of adapters and m3u url parameters

### ISSUE THREAD

**Issue by sumulu** [catalinii/minisatip#432]
I have two usb dvbc adapters. One adapter is with CI slot. Is there a start option available to setup the adapter with CI always as the first tuner?

On my tablet I use a m3u list. I think the parameter "src" should select the tuner. Maybe this is wrong, but I saw this in a example. The parameter has no effect. It selects always the next free tuner. I tried src=1 and src=2 ...

**Comment by 9000h** [comment]
src= is the signal source
fe= is the frontend
http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf

**Comment by sumulu** [comment]
Thanks, this works

**Comment by catalinii** [comment]
You could also try to control how the drivers are loaded (if they are not the same model). But is much easier with fe= ...
