### ISSUE TITLE
IOS/Android sat ip alignment tool no signal issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#433]
after long time I did try these apps but there is no signal any more

**Comment by 9000h** [comment]
PR is done, but I'm not sure if it brakes something

**Comment by catalinii** [comment]
Hi, does the PR fixes something ?

**Comment by 9000h** [comment]
the IOS App is not working on IOS 9 or higher so the IOS App is dead beef atm
the Android App is working
