### ISSUE TITLE
Cannot tune with sub-MHz precision

### ISSUE THREAD

**Issue by madmanxxx** [catalinii/minisatip#438]
In my country, there are some channels broadcast on 191.5MHz (DVB-T). Unfortunately, minisatip does not parse frequencies with numbers after decimal separator (neither dot nor comma work).

Note: There is a driver bug / feature that is tuner-dependent. I have two USB DVB-T tuners on the same machine. When I tune them to 191 MHz (half a MHz short), one of them locks successfully (IT9135), while another (DIB0700) doesn't.

**Comment by catalinii** [comment]
Hi,

Can you upload logs (- http,dvb ) ?

Thanks

**Comment by madmanxxx** [comment]
OK, now I have successfully tuned both of my tuners using comma as a decimal separator. Sorry for confusion.

PS: I could have sworn this didn't work. Was it implemented between 10.2017 and 03.2018? Because I did a lot of testing in the beginning of 2018, but then updated minisatip on March and didn't do any further tests...

**Comment by madmanxxx** [comment]
PS2: Although the tuner tunes successfully to 191.5MHz, status page (http://localhost:8080) shows 191MHz. Nothing important, but technically it's incorrect.
