### ISSUE TITLE
BUG: VideoLAN receives RTP packets "out of order"

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#439]
Hi,

The last version of VLC (3.0.0) has _some_ SAT>IP support (in fact, it's a RTSP input adapted to the SAT>IP dialect; plus a simple UPNP discovery and a list of programs downloaded from external server). See the how to from here:
http://www.satip.info/sites/satip/files/files/Microsoft%20Word%20-%20mini-howto_satip_with_vlc_v2.pdf

Doing some testing, I found a very strange behaviour with minisatip: Time to time the RTP received packets are **out-of-order**!

See the debug of the VLC in the < CTL >+< M > Window in "Verbose=1":

```
satip warning: Gap in seq_nr (11256 > 11250), probably lost a packet
ts warning: discontinuity received 0x5 instead of 0x4 (pid=256)
satip warning: Received out of order packet (seq_nr=11250 
satip warning: Received out of order packet (seq_nr=11251 
satip warning: Received out of order packet (seq_nr=11252 
satip warning: Received out of order packet (seq_nr=11253 
satip warning: Received out of order packet (seq_nr=11254 
satip warning: Received out of order packet (seq_nr=11255 
ts warning: discontinuity received 0xb instead of 0xd (pid=255)
ts warning: discontinuity received 0xd instead of 0x4 (pid=18)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 13, expected 4) for PID 18
ts warning: discontinuity received 0xa instead of 0x8 (pid=32)
satip warning: Gap in seq_nr (11315 > 11310), probably lost a packet
satip warning: Received out of order packet (seq_nr=11310 
ts warning: discontinuity received 0x3 instead of 0xc (pid=18)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 3, expected 12) for PID 18
satip warning: Received out of order packet (seq_nr=11311 
ts warning: discontinuity received 0x5 instead of 0xc (pid=255)
satip warning: Received out of order packet (seq_nr=11312 
satip warning: Received out of order packet (seq_nr=11313 
satip warning: Received out of order packet (seq_nr=11314 
ts warning: discontinuity received 0xf instead of 0xe (pid=256)
ts warning: discontinuity received 0x7 instead of 0x5 (pid=32)
main warning: playback way too early (-217837): playing silence
main warning: playback too early (-110626): down-sampling
main warning: picture is too late to be displayed (missing 232 ms)
satip warning: Gap in seq_nr (14174 > 14171), probably lost a packet
ts warning: discontinuity received 0xf instead of 0xb (pid=255)
satip warning: Received out of order packet (seq_nr=14171 
satip warning: Received out of order packet (seq_nr=14172 
satip warning: Received out of order packet (seq_nr=14173 
ts warning: discontinuity received 0xd instead of 0xc (pid=256)
main warning: playback way too early (-198351): playing silence
main warning: playback too early (-102001): down-sampling
main warning: picture is too late to be displayed (missing 110 ms)
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 9, expected 0) for PID 18
ts error: libdvbpsi error (PSI decoder): TS discontinuity (received 4, expected 11) for PID 18
```

I do this test with the RTSP **and** the HTTP output of the minisatip, but with the HTTP I don't see _any_ error. I use for testing the "Sat.1" in Astra 19.2:

- VLC 3.0.0 (Windows), minisatip (Linux) P'n'P input "4. Sat.1" ---> Out of order packets received
- VLC 3.0.0 (Windows), minisatip (Linux) HTTP input  of "Sat.1" ---> clean input

(Note: for the SAT>IP "Sat.1" channel the URL for HTTP is:
 `http://minisatip:8080/?src=1&freq=12545&pol=h&ro=0.35&msys=dvbs&mtype=qpsk&plts=off&sr=22000&fec=56&pids=0,17,18,255,256,96,32`
This is exact the same query used by the VLC SAT>IP input)

So the conclusion is: something is wrong in the RTP output stream.
Please, can you check it?

Thank you!

**Comment by lars18th** [comment]
Hi,

One more thing: Using my hardware SAT>IP server with VLC I don't see any RTP error!
So the error, appears only with the minisatip software source.

Regards.

**Comment by catalinii** [comment]
Hi Lars,

are you using wireless by any chance ?

Thank you

**Comment by lars18th** [comment]
> are you using wireless by any chance ?

NO. Fully gigabit cable network.

> please check your network looks like you have issues with UDP.

Checked! The trouble is *only* with minisatip... other software generates RTP (UDP) packets in order and are received in order.

Please, belive me: do a test (very easy to do it), and check results!

**Comment by SuNNjek** [comment]
I am having the same issue. It only pops up when I select a channel from the UPnP playlist though. When I manually enter the URL AND replace the "sat.ip" in the URL with the host of my minisatip server, everything works fine.

**Comment by lars18th** [comment]
Hi,

@SuNNjek ,

> I am having the same issue. It only pops up when I select a channel from the UPnP playlist though. When I manually enter the URL AND replace the "sat.ip" in the URL with the host of my minisatip server, everything works fine.

When using the UPnP option, the "input driver" used is "sat.ip" (also when you use it explicitly in the command line). However, when you use the URL option the "input driver" used is "rtsp" (not the same as "sat.ip"; so the code is _different_. I feel the RTSP implementation inside the SAT.IP driver doesn't support packet reordering, instead of the more complex implementation of the regular RTSP driver.

@catalinii ,

> Can you upload logs (-l http) and tcpdump pcap file (on the minisatip host) + vlc log?

Honestly, I prefer you do the test (it's just a simple VLC client in a Windows machine, and the minisatip in a Linux machine, both in the same wired network). Why? Because is the best method to convince that the trouble is not in the network but in the sender.

You will do it? :smile:

**Comment by lars18th** [comment]
Hi @catalinii ,

Have you test it?

**Comment by catalinii** [comment]
Hi,

I do not have a DVB-* in my land, that's why I was asking for the files above. It is expected for the tcp to work good, but I do not want to exclude environmental issues for now.
Please upload the files so I can take a look
Thank you

**Comment by lars18th** [comment]
>  I do not want to exclude environmental issues for now.

Hi @catalinii ,

I do a test using a different platform, and the problem doesn't appears. I'll do more testing.

Regards.

**Comment by lars18th** [comment]
Hi @catalinii ,

After testing in different platforms, I can see that the minisatip code is right. The problem appears only on some devices when the TCP/IP stack decides to reorder UDP packets.

So, don't worry!
In any case, the VLC implementation needs to be improved for right processing of reordered UDP packets.
Regards.
