### ISSUE TITLE
compile with -Wall

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#44]
dvb.c:579:5: warning: implicit declaration of function 'toupper' [-Wimplicit-function-declaration]

\#include \<ctype.h\> will fix it
----
dvb.c:555:2: warning: enumeration value 'SYS_UNDEFINED' not handled in switch [-Wswitch]
dvb.c:555:2: warning: enumeration value 'SYS_DVBC_ANNEX_B' not handled in switch [-Wswitch]

     switch (tp->sys)
missing default: adding that will make compiler happy

dvb.c:521:9: warning: unused variable 'tt' [-Wunused-variable]
dvb.c:444:28: warning: unused variable 'event' [-Wunused-variable]
dvb.c:439:11: warning: unused variable 'bandwidth_hz' [-Wunused-variable]
dvb.c:436:14: warning: unused variable 's' [-Wunused-variable]
dvb.c:435:6: warning: unused variable 'i' [-Wunused-variable]
dvb.c:434:6: warning: unused variable 'rc' [-Wunused-variable]
dvb.c: In function 'dvb_delsys':
dvb.c:713:6: warning: unused variable 'ds' [-Wunused-variable]
dvb.c: In function 'detect_dvb_parameters':
dvb.c:794:2: warning: value computed is not used [-Wunused-value]
dvb.c:872:4: warning: implicit declaration of function 'map_float' [-Wimplicit-function-declaration]
dvb.c: In function 'get_signal':
dvb.c:1028:28: warning: unused variable 'ev' [-Wunused-variable]
dvb.c: At top level:
dvb.c:138:20: warning: 'fe_bandwidth_tab' defined but not used [-Wunused-variable]
dvb.c:161:20: warning: 'fe_hierarchy_tab' defined but not used [-Wunused-variable]

**Comment by catalinii** [comment]
I have fixed what I think I don't need anymore.
Thanks

**Comment by 9000h** [comment]
low prio but could me make -Wall the standard and try to get the compile clean
