### ISSUE TITLE
BUG: UDP bind for listening UPnP requests fails

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#440]
Hi,

See this log:

```
[08/06 18:05:43.816 main]: New UDP socket 3 bound to 0.0.0.0:1900
[08/06 18:05:43.823 main]: setting multicast for 239.255.255.250
[08/06 18:05:43.835 main]: udp_bind: failed: bind() on host 239.255.255.250 port 1900: error Cannot assign requested address
[08/06 18:05:43.839 main]: New UDP socket 4 bound to 0.0.0.0:1900
```

This appears in a machine that has already running a service listening in UDP/1900.

I recomend to add a command line option for passing the listening address where bind, instead of use "0.0.0.0:1900"

You agree?

**Comment by lars18th** [comment]
Hi,

Futhermore in this position it's required to insert an `else return -1`
https://github.com/catalinii/minisatip/blob/66985bbbd5abe7dedd17ba97a5417fb9ce752b15/src/socketworks.c#L164

So, if the bind fails and not multicast, in this case you need to return false (-1).

**Comment by lars18th** [comment]
Hi @catalinii ,

I creted a PR for resolve the problem: #441 .
Futhermore, it improves the log when multicast is used.

I hope you merge it! :smile:

**Comment by catalinii** [comment]
Hi,

Thank you for the PR, I've just merged it.
Can we close the issue ?

Thank you
