### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#442]
Hi,

I like to comment that the current branch can be compiled and it runs in the WSL (_Windows Subsystem for Linux_).

In order to compile I recomend:

```
./configure --disable-linuxdvb --disable-dvbca --disable-dvbaes --disable-dvbcsa --disable-netcv --enable-satipc --disable-dvbapi --enable-static
```

And then you can use it with a "remote" tuner (SAT>IP server). For sure, you can't use BDA tuners. But it's useful if you like to use, for example, one remote (no LAN, but Internet) SAT>IP server with RTP-over-TCP and serve this server in your local network... using your Windows laptop. :laughing: 

I suggest to comment it in the README.
You agree? :smile:

**Comment by catalinii** [comment]
Hi,

Does it work if you run just ./configure?

Which options are enabled and should not be?

Thanks

**Comment by lars18th** [comment]
Hi @catalinii ,

> Does it work if you run just ./configure?

I explain more:

1. In any Windows 10, install "Debian" from the Windows Store.
2. After install it, create your user, and install the build environment: `sudo apt-get update; sudo apt-get install build-essential`. Plus, install git client: `sudo apt-get install git`.
3. Then you can download with: `git clone https://github.com/catalinii/minisatip.git`.
4. `cd minisatip`, `./configure ...` (add here my previous parameters).
5. You can run it with `./minisatip -f -i -10 -s remote_satip_server_ip -a 1:0:0 -l`

But, I forget to mention that you need to **disable the firewall**, or almost add the corresponding rules in you machine.

> Which options are enabled and should not be?

I do not do an exhaustive test of the options. It compiles as far afer apply my patch #441 .
Regards!

**Comment by catalinii** [comment]
Hi Lars,

I meant if you run just ./configure (with no arguments), does it work ?

This should be the expected behavior.

Thanks

**Comment by lars18th** [comment]
> I meant if you run just ./configure (with no arguments), does it work ?
> This should be the expected behavior.

I'll try in next few days. I'm not sure... but I feel some changes will be necesary (for example, the `linuxdvb` is not available at all!).

Regards.

**Comment by lars18th** [comment]
Hi @catalinii ,

When executing a plain `./configure` in the Debian WSL, the result is:

```
Linux DVB:                                enabled
Common Interface (needs DVBEN50221):      disabled
OpenSSL (AES as part of DVBAPI):          disabled
Embedded system:                          disabled
DVBCSA (needs libdvbcsa):                 disabled
Netceiver support:                        disabled
SatIP Client:                             enabled
Static:                                   disabled
dvbapi:                                   enabled
axe:                                      disabled
enigma:                                   disabled
```

I feel it doesn't have sense to enable `Linux DVB` in this environment. However, the package compiles fine with `make` and it executes and works with: `sudo ./minisatip -s sat_ip_address -f -ll`.

So, I feel you can write in the README about the supported platforms and add Windows WSL as device less supported platform (like MacOSX and others).

You agree?

**Comment by 9000h** [comment]
still something open?

**Comment by lars18th** [comment]
Hi,

> still something open?

I don't have time to test this now. However, I recommend to write something in the README about compatibility with WSL and Cygwin.

**Comment by Jalle19** [comment]
Personally I think WSL and Cygwin are such niche environments to be running this in (especially since it would be radically limited in functionality) that I don't think it's a good idea to mention in the README that it's technically supported. Same thing with macOS.

**Comment by lars18th** [comment]
Hi @Jalle19 ,

I don't agree with you at 100%, but in part only.

Advantages of compiling minisatip with Cygwin and WSL are that you can found more bugs because the warnings printed. I used this technique recently. However, more interesting are to run minisatip as "satipc" module. In this case you don't need at all DVB drivers. So it's entirely multiplatform. It can be used for example to run it as proxy for real SAT>IP servers (that perhaps have an incosistent or faulty implementation of the standard). And for sure, you can run minisatip in a container. In this case is not mandatory to support other platforms, but in any case, it can help.

As a summary: IMHO it will be interesting to support compiling it for Cygwin (almost), MacOS (perhaps) and Windows native (with msys2 tools).

**Comment by lars18th** [comment]
Hi,

With current versions of WSL, I can compile (and debug) minisatip correctly. So I close this issue.
