### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by danielkucera** [catalinii/minisatip#446]
Hi @catalinii ,

can you please create tag or branch with current version? I created a package for openwrt https://github.com/openwrt/packages/pull/6325 and want to build from more recent code.

**Comment by catalinii** [comment]
Hi,

Could you try using git as here: https://github.com/openwrt/packages/blob/master/multimedia/tvheadend/Makefile

Thank you

**Comment by danielkucera** [comment]
I'd like to but the difference is that tvh has correctly defined version tags: 
![screenshot from 2018-06-21 17-26-42](https://user-images.githubusercontent.com/1734256/41728994-71de1fae-7578-11e8-8b22-58e987bb7267.png)

**Comment by tmn505** [comment]
There is no need to branch or create a tag, You can do it in similar fashion as I did here:
https://github.com/tmn505/openwrt-dvb/blob/master/minisatip/Makefile
The version number is taken from `minisatip/src/minisatip.h` in line 12 and 10.

**Comment by danielkucera** [comment]
@tmn505 , why don't you pull this back to original openwrt?

**Comment by danielkucera** [comment]
@catalinii , I see you started using tags. :+1:
