### ISSUE TITLE
SAT>IP client mode: support for servers without "pids=all"

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#448]
Hi,

I have different SAT>IP servers. Regarding the "pids=all" support I see three different behaviours:

1. It works! The server sends the full transport stream without problems.
2. It's accepted, but dosen't work. The server not filters the stream, but the bandwith is limited. Then you receive a lot of CC errors, but you can still read the PSI tables.
3. It isn't accepted. The server refuses the request or internally replaces it with "pids=none". So, you can't receive any packet.

In order to improve the support for servers in the third group I suggest to include support for "hacking" the "pids=all" calls. For example, you can provide this command line parameter: `-s --satip-servers [DELSYS:][FE_ID@][source_ip/]host[:port][#no-all]`.

This parameter should work at _server_ level (so you can mix different servers with different support); and it instructs to **replace** the request "pids=all" with "pids=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20" (that's all PSI tables).

With this hack you can use for example:

```
minisatip -s 192.168.1.100:554#no-all -s 192.168.1.101
```

In this example the first server will use the hack and the second no. And the minisatip can serve "pids=all" to any SAT>IP client.

You agree?

**Comment by catalinii** [comment]
Hi Lars,

this is fine to be implemented, if you want you can make a patch for that.

Thank you

**Comment by lars18th** [comment]
Hi @catalinii ,

Now I'm a quite busy. Sorry!

So, I request if you can add it, as you know the code very well.
If not then I'll try in the future.

Regards.

**Comment by lars18th** [comment]
> Hi Lars,
> 
> this is fine to be implemented, if you want you can make a patch for that.
> 
> Thank you

Done #549 !
I hope you like to merge it. :wink:

**Comment by lars18th** [comment]
I close it as it's resolved!
