### ISSUE TITLE
[Feature Request] ablte to specify --satip-tcp for each satip source independently

### ISSUE THREAD

**Issue by ErAzOr2k** [catalinii/minisatip#449]
Hi,

i have two SATIP servers as sources. I'm now in the situation, where I need to enable --satip-tcp (-O) for one SATIP server, but for the other server the option need to be disabled.

This should be valid for SATIP server, which are inported with --satip-servers or --satip-xml.

Regards

**Comment by catalinii** [comment]
Hi,

I think it is a good point, will try to implement it.

Thanks

**Comment by 9000h** [comment]
@ErAzOr2k close ?
