### ISSUE TITLE
minisatip is too verbose in Syslog

### ISSUE THREAD

**Issue by henfri** [catalinii/minisatip#452]
Hello,

I am running minisatip with this command:
/usr/bin/minisatip -f -x 8081 -p http://homeserver:8081/playlist.m3u -F /tmp/minisatip.log

Nevertheless, I see lots of entries like this one in the syslog:
```

Sep  2 19:57:05 homeserver minisatip[2452]: [02/09 19:57:05.760 main]: tuning to 11836000(1236000) pol: h (2) sr:27500000 fec:34 delsys:dvbs
Sep  2 19:57:06 homeserver minisatip[2452]: [02/09 19:57:06.249 main]: tuning to 12109000(1509000) pol: h (2) sr:27500000 fec:34 delsys:dvbs
Sep  2 19:57:06 homeserver minisatip[2452]: [02/09 19:57:06.860 main]: tuning to 12187000(1587000) pol: h (2) sr:27500000 fec:34 delsys:dvbs
```

How can I reconfigure minisatipy to avoid these verbose messages?

Regards,
Hendrik

**Comment by catalinii** [comment]
Hi,

What exactly would you expect to see?

Thank you

**Comment by henfri** [comment]
Hi, 
thanks for your quick reply.

Nothing. 
Except if there is something I *need* to know. I.e. Errors.
But with the current settings, I get hundrets of messages a day.

Greetings,
Hendrik

**Comment by henfri** [comment]
Hello,

is it possible to achieve this with the current options availalbe in the commandline parameters?

Greetings,
Hendrik

**Comment by 9000h** [comment]
This should be fixed since some time.
