### ISSUE TITLE
How to  enable-adapters

### ISSUE THREAD

**Issue by MrOnyx** [catalinii/minisatip#453]
What is the command to enable-adapters DVB-S?
I only see DVB-C
![screenshot_2018-09-16 minisatip 0 7 16 on 192 168 178 25 8080](https://user-images.githubusercontent.com/2565966/45599650-9270fa00-b9ef-11e8-9e18-5013ae76101f.png)

**Comment by 9000h** [comment]
Hi,
what type of dvb hardware do you have?
can you provide some more info like "lsdvb"?
CU
9000h

**Comment by MrOnyx** [comment]
> root@ZBOX-ID91:~# lsdvb

                lsdvb: Simple utility to list PCI/PCIe DVB devices
                Version: 0.0.4
                Copyright (C) Manu Abraham

em28xx (-1:-1 -1:255) on PCI Domain:1112099911 Bus:1380998979 Device:1413568073 Function:69
        DEVICE:0 ADAPTER:0 ERROR: Open frontend0 failed
root@ZBOX-ID91:~#

hostname = ZBOX-ID91
uname -m = x86_64
uname -r = 4.15.0-34-generic
uname -s = Linux
uname -v = #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018

root@ZBOX-ID91:~# dmesg | grep DVB
[    6.796092] em28xx 3-4:1.0: DVB interface 0 found: isoc
[    7.188375] em28xx 3-4:1.0: Identified as PCTV DVB-S2 Stick (461e) (card=92)
[    7.196073] em28xx 3-4:1.0: Binding DVB extension
[    7.264862] dvbdev: DVB: registering new adapter (3-4:1.0)
[    7.264866] em28xx 3-4:1.0: DVB: registering adapter 0 frontend 0 (Montage Te                                  chnology M88DS3103)...
[    7.265217] em28xx 3-4:1.0: DVB extension successfully initialized
[    9.210906] em28xx 3-4:1.0: DVB: adapter 0 frontend 0 frequency 0 out of rang                                  e (950000..2150000)
root@ZBOX-ID91:~#

**Comment by 9000h** [comment]
Hi,
if you may run thv and minisatip on the same machine it could be tvh has it in use already.
DEVICE:0 ADAPTER:0 ERROR: Open frontend0 failed
CU
9000h

**Comment by MrOnyx** [comment]
I use on same machine tvh and minisatip 
Sundtek DVB-C is also in the same mchine and works

**Comment by 9000h** [comment]
did you try to stop tvh before you start minisatip?

**Comment by MrOnyx** [comment]
root@ZBOX-ID91:~# lsdvb

                lsdvb: Simple utility to list PCI/PCIe DVB devices
                Version: 0.0.4
                Copyright (C) Manu Abraham

em28xx (1112099911:1380998979 1413568073:69) on PCI Domain:3027502 Bus:0 Device:0 Function:0
        DEVICE:0 ADAPTER:0 ERROR: Open frontend0 failed
root@ZBOX-ID91:~# systemctl stop tvheadend
root@ZBOX-ID91:~# lsdvb

                lsdvb: Simple utility to list PCI/PCIe DVB devices
                Version: 0.0.4
                Copyright (C) Manu Abraham

em28xx (3027502:0 0:0) on PCI Domain:1279721525 Bus:1598243401 Device:3354162 Function:1112099911
        DEVICE:0 ADAPTER:0 FRONTEND:0 (Montage Technology M88DS3103)
                 FE_QPSK Fmin=950MHz Fmax=2150MHz
root@ZBOX-ID91:~#

**Comment by 9000h** [comment]
so tvh is using it exclusively

**Comment by catalinii** [comment]
Closing this as not a minisatip issue. Please open a  forum topic (https://minisatip.org) if you need more help.
