### ISSUE TITLE
IDEA: Demo mode

### ISSUE THREAD

**Issue by anoma** [catalinii/minisatip#460]
I often find that my recommendation that projects adopt SAT>IP support falls on _deaf ears_.

I believe this is primarily because the path to adoption typically requires expensive equipment outlays.

It would be very useful if minisatip included a demo mode where as much of the SAT>IP functionality could be represented without the need for a satellite install.

I imagine a series of test cards "streamed" as live TV channels but I leave the idea out there for those that understand quite how complex this idea is in reality.

**Comment by CvH** [comment]
disclaimer: I have no idea if this is "easily" possible at all

This is a really nice idea and would be really helpful as DVB isn't a thing for a lot ppl (especially for all kind of developers). 
If demo1.ts, demo2.ts ... could be hard wired to some frequencies it would be very easy to create some demo case that are still fully functional without any hardware or needed knowledge.

**Comment by 9000h** [comment]
could be done via https://github.com/catalinii/minisatip/issues/770#issue-721528910
please close
