### ISSUE TITLE
Scanning for Stations does find no/few

### ISSUE THREAD

**Issue by henfri** [catalinii/minisatip#462]
Hello,

I've been running minisatip successfully for quite a while now.
But on one PC on which I have been using DVB-Viewer in the past, I get no picture anymore.
Thus I startet a scan of stations. I only find 5 Stations. There should be hundrets. As I don't know which ones it found, I cannot test, whether I get a picture for those, unfortunately.

So I tried on my mobile. Also here (elgato Sat>IP App), I find no stations.

What could be the reason for this?

In the Webinterface of minisatip the SNR is just 31%. But these are usually not reliable as far as I know.
Also the Picture is fine on other Devices (both using minisatip and also devices not using satip at all).

How can I find the reason for this problem?

Greetings,
Hendrik

**Comment by catalinii** [comment]
hi,

can you upload the logs when no station is found on a frequecy ?

Thank you

**Comment by 9000h** [comment]
@henfri 
if you have the kernel drivers for digital devices cards in use it could be the issue, please try then the ddddvb driver from git.

**Comment by catalinii** [comment]
Hey @henfri, 
if this is till an issue please feel free re-open.

Thanks
