### ISSUE TITLE
db920 FBC twin tuner - parallel channels

### ISSUE THREAD

**Issue by chrs04** [catalinii/minisatip#469]
hey,

i run into issues with minisatip running on a db920 with a twin tuner. I installed minisatip with opkg on the db. I shutdown enigma then i startup minisatip with the following parameters right now:

/usr/bin/minisatip -S "2-4:0,5-7:1" -R /usr/share/minisatip/html  -M "*:1.6"

When i lookup the page on default port 8080 page i see 8 tuner, but the weird thing which i already noticed at this point is, that SNR and Signal is 0. (tvheadend not started at that point, later more..)

I startup tvheadend and right now i configured the adapters as following:

Tuner #1 --> Disabled

Tuner #2 --> Disabled

Tuner #3 - #8 
--AA --> Configured
--AB --> Not Configured
--BA --> Not Configured
--BB --> Not Configured

The reason why i dont configured Tuner #1,2 is that because with that startup parameters mentioned above, i cannot tune on #1,2 ... I dont find any muxes.

So, now it seems to work with 2 parallel channels but sometimes it crashes and i had to start every stream new. I will provide log files later on..

When i watch a stream and lookup the minisatip page on default port 8080, i see now a SNR of 6-8 but no signal. Strange.

I already read something that FBC may be bugy - can someone confirm that?

br,

chris

**Comment by estimadarocha** [comment]
@chrs04 if the tuner is FBC it's normal for you to see 8 adapters!

**Comment by catalinii** [comment]
In general FBC works but for every vendor the behavior is slightly different.

For example for VU+ there is a issue adding -1 0 works best but scanning does not work - have an open discussion with them about it.
Gigablue quad 4k on dvb-s2 almost works, the recent drivers introduces an issue of tuning on master adapters 0 and 1.

The reason is that every provider has their own flavor of drivers that are slightly different that dvbapi as behavior.

**Comment by chrs04** [comment]
hi catalinii,

thank you for your answer.

do you mean adding "-1 0" as a general parameter or as a slave parameter?

Ok, do you think it's worth trying again?

**Comment by chrs04** [comment]
I can also provide access or remote session if you want to see the behavior on a db920...

**Comment by catalinii** [comment]
I do not have much time but I could take a look at some point. Email me at catalinii@yahoo.com

**Comment by catalinii** [comment]
Fbc as far as I know should work. If you want to provide aceess please let me know.

**Comment by chrs04** [comment]
Oh thanks.

I will try it next weekend.



catalinii <notifications@github.com> schrieb am Sa., 13. Juli 2019, 22:28:

**Comment by Jalle19** [comment]
Closing due to simply being too old
