### ISSUE TITLE
[Request] openembedded bitbake yocto build instructions missing

### ISSUE THREAD

**Issue by walterav1984** [catalinii/minisatip#475]
Although @catalinii have supplied a working gigablue minisatip binary on his [forum](https://minisatip.org/forum/download/file.php?id=7), I wasn't able to build a recent minisatip version using the very outdated bitbake version from [@eriksl](https://github.com/eriksl/minisatip/).

Is it possible to include your gigablue bitbake file/folder structure into this github project as a drop in/replacement to the current dated openpli [minisatip](https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-openpli/satip/minisatip.bb) build environment that produces the outdated 0.3.xx version of minisatip?

I'm looking forward in testing the fresh FBC tuner related patches for a triple DVB-C tuner in a mut@nt hd530c (gfutures brand).

**Comment by estimadarocha** [comment]
@walterav1984 why do you want to compile it yourself? the @catalinii one is updated! 

By the way you will face some troubles with the hd530c with network and with own minisatip

**Comment by catalinii** [comment]
Minisatip is already included in the oe alliance and you should get a minisatip pkg file after opkg update.

Here is the bb file used to build minisatip: https://github.com/oe-alliance/oe-alliance-core/tree/b9f3e01f2e7e4b918b9379af9dac3f7e885fd651/meta-oe/recipes-extended/minisatip

**Comment by walterav1984** [comment]
Thanks @catalinii  for pointing me out to the correct bitbake recipe, accompanied with [libdvbcsa](https://github.com/oe-alliance/oe-alliance-core/tree/4.2/meta-oe/recipes-multimedia/libdvbcsa) I was able to build a OpenPLI 6.2 release with current minisatip.

My apologies for expecting this github repo was the place to hold the bitbake recipe like the one from eriksl, it makes indeed sense that its on oe-alliance project but more sense if its also in openembedded.org? About the gigablue version, I was expecting 0.8.x version because of perexg satip-axe instructions and thought it was outdated although we're at 0.7.16.

This ticket will be closed, but offtopic question to @estimadarocha related to troubles with hd530c and own minisatip.

When using the mutant at runlevel "init 4" minisatip will share 3 dvb tuners, but watching only 2 different low pid channels on 2 different muxes works with external/internal tvheadend server. As soon as a third tuner is addressed with a 3rd channel from a third mux, minisatip crashes beyond killable(device will reboot).

A custom native OpenPLI tvheadend build (tried both 4.2.7 and 4.3x) on the mutant behaves the same, is sees the internal FBC DVB-C adapter0 with 3tuner frontends, and as long as not using more than 2 diffrent tuners/muxes and low pid channels it works. 

Will post a topic on the Tvheadend with build instructions for OpenPLI 6.2 on mutant and maybe continue conversation there?

**Comment by estimadarocha** [comment]
@walterav1984 i tried both run it with init 4 and without enigma running, both gave me problems with networks speed after the 40 mbits... i made some tests with @catalinii and with a simple http server i can easily get the maximum network speed of the board (100mbots). 
There was also some problem with filtering pids but we didn't have time yet to debug it properly!

**Comment by walterav1984** [comment]
@estimadarocha  Thanks for technical info, maybe only usefull way of using tvheadend on this hd530c is with IPTV m3u input from enigma2 openwebif. That way I can have 3 HD subscriptions on 3 different mux and a 4th SD as a second channel on one of the 3 muxes with only 40% CPU load. Just need a way to have tvheadend import EPG data from m3u from enigma2.

Build instructions for Tvheadend 4.2.x / 4.3.x on yocto/Openembedded/OpenPLi 6.2
https://tvheadend.org/boards/4/topics/34921

**Comment by estimadarocha** [comment]
@walterav1984 you should be able to pull a lot more than that... i tried a lot more channels and the cpu didn't increase that much from the 40% you told.... the only limit i found was the 3 tuners and the network port speed. On the other way if i try to the same with minisatip the cpu gets a lot more load... i think thats because the drivers/pid filtering is very optimized for enigma.

I can help with more tests!

**Comment by walterav1984** [comment]
Have you tried USB ethernet? 

Trying a couple of 100Mbit/1Gigabit USB2/USB3 adapters but no kernel modules are available (Asix/Realtek) compiling them seems to work but I cannot find any ipk after generating OpenPLi image...

**Comment by estimadarocha** [comment]
Yes of course I tried it... Use the openatv image they change something on request so I was able to use a 1gbit USB asix adapter...
