### ISSUE TITLE
dvbc2 support

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#48]
unfortunatly I cannot test this no hardware/signal :-(

but as we do have dvbc in place the differences a small in the specs

some parameters are defenetly different  c2tft,plp,ds
a=fmtp:33 ver=1.2;tuner=<feID>,<level>,<lock>,<quality>,<freq>,<bw>,<msys>,<mtype>,<sr>,<c2tft>,
<ds>,<plp>,<specinv>;pids=<pid0>,…,<pidn>

for tune a channel the delsys property for dvbc2 need to be set

DTV_STREAM_ID,.u.data = PLP

PLP = 16

if catalinii will add it may someone can with access to dvbc2 can test

**Comment by catalinii** [comment]
Maybe I am wrong but linux s2api does not support dvb c2 :)..

**Comment by 9000h** [comment]
the only cards I know up to now are from DD and they have the also drivers, the latest is
http://download.digital-devices.de/download/linux/dddvb-0.9.17.tar.xz

**Comment by catalinii** [comment]
I am not sure I see in http://lxr.free-electrons.com/source/include/uapi/linux/dvb/frontend.h anything about DVB-C2
Which is the system for DVBC2 ?
How we set c2tft on the tuner ?

**Comment by 9000h** [comment]
I believe we have get the c2tft from the url and add it also in the replys like the ver=1.2 to, we need also to add this to the dtv_properties before using the ioctl  FE_SET_PROPERTY.

there is also a struct dtv_property dvbc2_cmdargs and dtv_properties dvbc2_cmdseq needed

**Comment by catalinii** [comment]
What I meant was that there is no SYS_DVBC2 in frontend.h which to allow tunning using DVBC2 parameters.

On top of that I am not sure there is a country using DVB-C2.

**Comment by 9000h** [comment]
maybe the easy way would be a "#ifdef SYS_DVBC2"  to compile it in only if the driver is supporting it like the dddvb from DD. 

I'm not aware of any usable channel here, there where only some tests by my Cable Provider KDG in Germany 
http://www.digitalfernsehen.de/Kabel-Deutschland-macht-erste-Tests-mit-DVB-C2.102850.0.html

**Comment by catalinii** [comment]
Took a look thru the source code of the driver and I think I figured out how to set those parameters, so I will start work on it at latest next week.

**Comment by 9000h** [comment]
low prio

**Comment by catalinii** [comment]
I have added support for this and atsc :)

If someone is around with the right HW and have access to signal can test this.

Thanks
