### ISSUE TITLE
Incorrect trailing zero byte on the end of the SSDP Discovery message

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#49]
sorry to insist here I do still believe the 0 is not valid

minisatip.c:653
minisatip.c:693

can you really explain why it should be there?

**Comment by catalinii** [comment]
Yeah... A way of making sure its there.
I use strlen so it does not get added to the length of the string. If u will check a tcpdump u will see is not there

**Comment by 9000h** [comment]
ok fine, did not check this in deep detail
