### ISSUE TITLE
adapter issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#496]
adapter.c:647
if (ad->used & (1 << i))
Shifting signed 32-bit value by 31 bits is undefined behaviour

**Comment by catalinii** [comment]
I will fix this in the next commit.

**Comment by 9000h** [comment]
thanks

**Comment by 9000h** [comment]
one more thing
adapter.c:1353
status = (ad->status & FE_HAS_LOCK) > 0;
would it be better to use
status = ad->status ? FE_HAS_LOCK : 0;
for the clients there is only 0 or 1 relevant and specified

**Comment by catalinii** [comment]
Is not the same. Ad->status have different flags not just FE_HAS_LOCK. The result is 0 or 1.

**Comment by 9000h** [comment]
thanks
