### ISSUE TITLE
log time stamp

### ISSUE THREAD

**Issue by vdrtuxnet** [catalinii/minisatip#5]
Hello,

thank you for the first linux sat>IP server!

I have some issues, will catch up with the issues later, so would it be possible to change the run time stamp to real time stamp?
This is because the -l option is very verbose and the real time stamp would make debugging much easier.
You don't need to change it, if you don't like, just pass me the the time stamp location in the source code and I will create a diff for my own.

And please go on with this great developing, linux needs a sat>IP server daemon.

Kind regards

vdr.tuxnet

**Comment by catalinii** [comment]
Hi,

it is done in the last commit.

Thanks

**Comment by vdrtuxnet** [comment]
Thank you!
