### ISSUE TITLE
[REF] RTCP app 200 timestamp issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#503]
the timestamp in the RTCP packet type 204 is not set right
this is from minisatip
![image](https://user-images.githubusercontent.com/3009073/49286919-dfffed80-f49b-11e8-9a21-be9722c58486.png)
this is from a Digibit R1
![image](https://user-images.githubusercontent.com/3009073/49286776-7d0e5680-f49b-11e8-847d-9480840ba66d.png)

**Comment by 9000h** [comment]
we may should also remove b=AS:5000 from describe_streams as it's probably not needed

**Comment by 9000h** [comment]
calculation could be look like https://github.com/asterisk/asterisk/blob/b80c9071e367f6cb1c011d1de6766b9ddb2e83ed/res/res_rtp_asterisk.c#L4031

**Comment by catalinii** [comment]
I know you had an issue, implementing it like this would resolve your problem ?

**Comment by 9000h** [comment]
no it's probably a cosmetic thing

**Comment by 9000h** [comment]
low priority

**Comment by catalinii** [comment]
Feel free to port an PR with that code.

**Comment by 9000h** [comment]
did choose a different approach

**Comment by 9000h** [comment]
PR merged
