### ISSUE TITLE
Inconsitent UDP output packet size

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#510]
I do notice this issue with one of my Panasonic TV's (ASW series from 2014) where artifacts showing up at higher bitrates.
With minisatip 0.5 there the UDP/RTP packet size is constant and there are no artifacts. 
The strange thing is newer Panasonic models did not have the issue.
![image](https://user-images.githubusercontent.com/3009073/49722934-0ecd4f00-fc66-11e8-9a82-b32d325674de.png)
If I got it right the output needs to be multiple of 188 bytes. MTU is 1500 is standart. So, 7x188 = 1316 bytes. If a part of TS package added to left space on MTU, decoders loose sync or you face with pixels/drop frames. Thats why best practice is to set payload with 1316 bytes and padding null.

**Comment by 9000h** [comment]
from the spec

RTP packets shall not be buffered by SAT>IP servers and shall not be delivered in a single burst. As soon as an RTP packet is filled with up to seven MPEG-2 TS packets, the RTP packet shall be released by the server. Buffering of RTP packets by the server will lead to increased packet jitter and may result in the malfunctioning of clients. SAT>IP servers shall therefore send packets at a constant rate, not in bursts, and packets shall be evenly paced.

**Comment by 9000h** [comment]
could this come from the changes in read_dmx?

**Comment by 9000h** [comment]
here are 2 samples to show the difference
vlc-pana a Panasonic TV is the server
vlc-minisatip minisatip is the server

[vlc-pana.zip](https://github.com/catalinii/minisatip/files/2669599/vlc-pana.zip)
[vlc-minisatip.zip](https://github.com/catalinii/minisatip/files/2669600/vlc-minisatip.zip)

**Comment by catalinii** [comment]
-b changes the adapter buffer. There are some conditions in read_dmx that
needs to be taken in account but the point is you can set -b for a packet
to be sent once the buffer

**Comment by 9000h** [comment]
I do see this issue with default threshold only on 1 Panasonic from 2014 (probably also a slow cpu issue with the fragments) which I can workaround with -H5:50 so there is no real need to change the code.
