### ISSUE TITLE
DELSYS parameter and version 1 and 2 of DVB

### ISSUE THREAD

**Issue by sumulu** [catalinii/minisatip#513]
If I start minisatip with "--delsys 0:dvbt2", I got the message "Setting delivery system for adapter 0 to dvbt2 and dvbt". Channel search on my Panasonic TV with MHS 3.0 takes very long time, because only one channel is using DVB-T1 in my region and TV is searching for DVBT1 at first. Is it possible to force DVBT2 only? Another issue is that DVB-Viewer-Pro for windows only found the DVBT1 channel. This is maybe a bug in the software... DVBT2 hardware option is activated.

**Comment by 9000h** [comment]
I think the TV know if it did see the dvbt2 adapter it can also scan dvbt and will do so, you should see this  in the log. There is probably not much we can do, but maybe I'm wrong.
 use  log option -l http,dvb

**Comment by catalinii** [comment]
Generally adding dvb-t2 adds dvb-t as well in minisatip code. You can try removing dvv-t from the codeand let me know if it works.

**Comment by sumulu** [comment]
Yes you are right 9000h. It depends on the client and his transponder list. DVB-Viewer is working now with DVB-T2 transponder list and the DVB-T2 frequencies of my region. Thanks.
