### ISSUE TITLE
dvb.c LOG issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#524]
the LOG seems to be wrong here
https://github.com/catalinii/minisatip/blob/b7e39f0612bc29d1f17ac8576df5278c6b00e1f3/src/dvb.c#L1248
https://github.com/catalinii/minisatip/blob/b7e39f0612bc29d1f17ac8576df5278c6b00e1f3/src/dvb.c#L1051

**Comment by catalinii** [comment]
as part of the macro DVB_DEMUX is expanded.

**Comment by 9000h** [comment]
thanks
