### ISSUE TITLE
LOG issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#527]
https://github.com/catalinii/minisatip/blob/3f13b61a9f5ca661123ca5caf654418ace57b8ed/src/socketworks.c#L1415
I think the LOG make no sense this way

**Comment by catalinii** [comment]
Hi,

what do you mean more specifically ?

Thanks

**Comment by 9000h** [comment]
if I get it right, you printing a pointer and then you print it again with a null pointer deference check

**Comment by catalinii** [comment]
Yean I mean the point is to see if the buffer is allocated and the p is allocated without creating crashing the app (making sure p is not NULL).
