### ISSUE TITLE
RFE: suggestion replace obsolete usleep with nanosleep

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#528]
I like to suggest replaceing usleep with nonosleep and use a util function like:
```
void myusleep(uint64_t usec)
{
    struct timespec ts = { .tv_sec = usec / 1000000,
                           .tv_nsec = (usec % 1000000) * 1000};
#if defined(HAVE_SELECT)
    select(0, NULL, NULL, NULL, &ts);
#else
    nanosleep(&ts, (struct timespec *)NULL);
#endif
}
```
According to usleep() manpage:
POSIX.1-2001 declares this function obsolete; use nanosleep(2) instead.
POSIX.1-2008 removes the specification of usleep().

/////////////
select(0, NULL, NULL, NULL, &ts); is the lazy method wine is using :-) and it's the same on windows (req. winsocket)
////////////
the other option would be
```
#include <ctime>
void myusleep(int ms)
{
    clock_t starting = clock();
    while( clock() - starting < ms ) {}
}
```

**Comment by catalinii** [comment]
Sounds good to me, PR?

**Comment by 9000h** [comment]
I did found some alternatives what do you think is better?

**Comment by catalinii** [comment]
I think the one from oscam is more complete and handling corner cases

**Comment by catalinii** [comment]
@9000h feel free to create a PR
