### ISSUE TITLE
on some polish channels dvbapi send 2 requests to oscam

### ISSUE THREAD

**Issue by Micha-123** [catalinii/minisatip#530]
in PL are some channels double on Transponder, like "TVN TURBO" in this case minisatip ask 2 times oscam to decode channel

> 2019/01/17 15:57:51 607F0FCD c      (ecm) MiniSatIP (0100@000068/5C00/3DD0/64:29FEAC5C43E82CE80A5818287B73A4DF): found (309 ms) by NC+ - TVN Turbo HD
> 2019/01/17 15:57:51 607F0FCD c      (ecm) MiniSatIP (0100@000068/5C00/3DD1/64:29FEAC5C43E82CE80A5818287B73A4DF): cache2 (210 ms) by NC+ - TVN TURBO HD

one time is that channel availible on Transponder with Lower letters and one time with Upper letters, thats the same channel 2 times on Transponder (one time with lower and one time with upper letters), but with 2 different SIDs, now minisat ip ask Always both SIDs and i see Always Decoding from Cache in oscam

**Comment by catalinii** [comment]
Hi,

Except that is asking 2 times for CW, is there a negative impact?

Thanks

**Comment by Micha-123** [comment]
No, there are no negative impact.

niedz., 20 sty 2019, 21:46: catalinii <notifications@github.com> napisał(a):

**Comment by catalinii** [comment]
I think this is by design. It givea oscam the chance of decrypring at least one SID.
