### ISSUE TITLE
Lost frames when second encrypted channel starts

### ISSUE THREAD

**Issue by mtonnie** [catalinii/minisatip#531]
Every time a second encrypted channel will be started the first one will stuck for a moment.
this doesn't occur when at least one of the channels is not encrypted.

Hardware:
ddbridge: Digital Devices PCIE bridge driver 0.9.31intermediate-integrated, Copyright (C) 2010-17 Digital Devices GmbH
ddbridge 0000:01:00.0: enabling device (0000 -> 0002)
ddbridge 0000:01:00.0: detected Digital Devices Cine S2 V6 DVB adapter
ddbridge 0000:01:00.0: HW 00010009 REGMAP 00010004
ddbridge 0000:01:00.0: Port 0: Link 0, Link Port 0 (TAB 1): DUAL DVB-S2
ddbridge 0000:01:00.0: Port 1: Link 0, Link Port 1 (TAB 2): NO MODULE
ddbridge 0000:01:00.0: Port 2: DuoFlex CI 1.0
ddbridge 0000:01:00.0: Port 2: Link 0, Link Port 2 (TAB 3): DuoFlex CI

Alphacrype Light

**Comment by catalinii** [comment]
Hi,

Can you upload logs?

Thanks

**Comment by mtonnie** [comment]
I have attached two log files one with encrypted channels one without

[minisatip_2.log](https://github.com/catalinii/minisatip/files/2779983/minisatip_2.log)
[minisatip_6.log](https://github.com/catalinii/minisatip/files/2779986/minisatip_6.log)

**Comment by mtonnie** [comment]
Shouldn’t be the case for me, I’m using alphacrypt light.
I’ll have a look if it happens with one transponder as well.

**Comment by catalinii** [comment]
Can u upload logs?

./minisatip -f -l http

**Comment by mtonnie** [comment]
[minisatip6.log](https://github.com/catalinii/minisatip/files/2799922/minisatip6.log)
[minisatip5.log](https://github.com/catalinii/minisatip/files/2799923/minisatip5.log)

I have made two log with "sudo minisatip -u 0:0-1284,1:1-1400 -f -l http", the first one with unencrypted channels first the second one without.
If i try to start playing with an encrypted channel it takes a few tries to get it started.
And when I'll start to play the same encrypted channel again it will stop playing after a few seconds.

I'm using a snap packages, maybe that's worth to mention you can try it by yourself e.g. on ubuntu snap install minisatip --devmode

Hope that helps to figure out whats wrong

**Comment by mtonnie** [comment]
Any idea what’s wrong?
Is the problem related to my setup or configuration?

**Comment by 9000h** [comment]
did the current git fix it?

**Comment by Yuri666** [comment]
For my case - not. But now I can't do more tests - my CAM broked...

**Comment by catalinii** [comment]
@Yuri666 for your case there is still a bug I am investigating at this point. the DDCI is still not fully completed, some corner cases like this still exists.

**Comment by mtonnie** [comment]
It seems to be better but not completly fixed.
I tried a few switches an I'still loosing some frame but less than before. 
Now it's just between 5 and 20 frames (I get it from statistics tab from vlc).

Im getting the following message if all steams are stoped.
`[17/02 10:58:52.723 CA2]: ca_lookup_callback: slot_id 0 requested_resource_id 200041
[17/02 10:58:52.723 CA2]: unknown resource id
[17/02 10:59:33.992 CA2]: ca_lookup_callback: slot_id 0 requested_resource_id 200041
[17/02 10:59:33.992 CA2]: unknown resource id

`

And while streams are playing I'm getting 
`[17/02 10:58:10.292 AD1]: PID Continuity error (adapter 1): pid: 098, Expected CC: 6, Actual CC: E, CC Before 5
[17/02 10:58:10.292 AD1]: PID Continuity error (adapter 1): pid: 098, Expected CC: F, Actual CC: 6, CC Before E
[17/02 10:58:10.425 AD1]: PID Continuity error (adapter 1): pid: 098, Expected CC: 7, Actual CC: F, CC Before 6
[17/02 10:58:10.460 AD1]: PID Continuity error (adapter 1): pid: 098, Expected CC: 0, Actual CC: 7, CC Before F
[17/02 10:58:10.503 AD1]: PID Continuity error (adapter 1): pid: 098, Expected CC: 8, Actual CC: 0, CC Before 7
`

**Comment by Yuri666** [comment]
Hi,
since current git i have new behaviour. Two channels on two terminals work fine. After switch on/off second channel on second terminal i don't have any stucks on first channel. But after stop second channel and start third channel, first channel stucks forever.

**Comment by mtonnie** [comment]
From my point of view it's getting better and better. 
I have to spend more time to get a detailed view if I'll still loosing frames.
But there is one new thing, I'm watching two channels on two different transponders and then I start a third channel on one of the other transponders I still watching. 
This will stop the other stream on this transponder, so it looks like I'm just able to play one channel per transponder.

**Comment by catalinii** [comment]
Yes please send new logs and also point out the time the issue happens.

**Comment by mtonnie** [comment]
[minisatip.log](https://github.com/catalinii/minisatip/files/2920055/minisatip.log)
[minisatip2.log](https://github.com/catalinii/minisatip/files/2920056/minisatip2.log)
I have made two additional log one with http and ca and one http only.

I have played the same channel twice in vlc and vlc stoped after a vew seconds of playback.

http: between 15:30:10 and 15:30:15, i guess around 15:30:12
http and ca: between 15:35:28 and 15:35:32, i guess around 15:35:30

Hope that helps
