### ISSUE TITLE
Unicable: Delay after voltage enable

### ISSUE THREAD

**Issue by sreichholf** [catalinii/minisatip#532]
I've got a small feature request that would help NOT having to use -Z *:0 with some unicable LNBs.

The common reason for those LNBs not working properly with power managment enabled is that they require a certain time to "boot".
My DurLINE is one of those candidates.
The Solution we implemented on Dreamboxes/enigma2 is to wait a bit before sending the first diseqc command after voltage enable.

While 1000ms (that's what dreamboxes use as default delay)  are enough for my LNB, we (at Dream Multimedia) do know of Unicable devices that take even longer to boot up.

Maybe you'll give it a thought.

**Comment by sreichholf** [comment]
Sidenote: -q *:1000-..... does help, but it delays EVERY zap not only the first one after powerup.

**Comment by 9000h** [comment]
why not not power the switch with a power inserter they are normally delivered with the switch already?

**Comment by sreichholf** [comment]
It's an LNB not a switch.

**Comment by 9000h** [comment]
we had a similar issue here https://github.com/catalinii/minisatip/issues/313

**Comment by sreichholf** [comment]
PowerInserter or disabled PowerManagement only a workaround imo. A "initial unicable command delay" would fix the issue without waste of energy.

**Comment by catalinii** [comment]
I remember that if there is no signal the jess command will be sent again until there is signal. Is that not working for you ?

Can u upload logs ?

**Comment by sreichholf** [comment]
Well it's not jess in this case but unicable"1".
But yes, I'll get some logs!

**Comment by 9000h** [comment]
https://github.com/perexg/satip-axe/issues/79#issuecomment-463094248

**Comment by catalinii** [comment]
I am closing this, if this is still an issue please feel free to re-open and upload new logs.

**Comment by 9000h** [comment]
https://github.com/perexg/satip-axe/issues/79#issuecomment-463094248
may help here, and there are also known issues with old firmware and "green mode" with all the unicable II switches designed by Inverto (firmware 0.13 seem to be ok, 0.24 seem to be bad, and the latest is 0.25)
please try and close

**Comment by 9000h** [comment]
still open?
