### ISSUE TITLE
DVBAPI: Sync or Async

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#544]
Hi,

I ask if the current implementation of the DVBAPI is working SYNC or ASYNC.

Why I ask for this?
Because, as I commented in #471 I have a continous glitches in the client... just when the DVBAPI is used.

Anyone with similar problems?

**Comment by 9000h** [comment]
not sure what hardware you use for minisatip and what client did show the issues, but I do have an older Panasonic TV (2014) which show some artifacts. I did change with -H3:50 the flush behavior and now it's clean.

**Comment by lars18th** [comment]
> I did change with -H3:50 the flush behavior and now it's clean.

I'll check it! Thank you.

**Comment by lars18th** [comment]
Hi @catalinii ,

Regarding the glitches related to the dvbapi... I see this message a lot of times:
https://github.com/catalinii/minisatip/blob/e4ee5fa587c33605c4baa8eba75d38b15ab5af61/src/dvbapi.c#L216

And I feel the code needs to do a `break` after this block, as the pids doesn't require to update if the same file is requested. So the code can be:
```
				else
				{
					LOG("dvbapi: filter for pid %d and key %d already exists, fid %d", _pid, k->id, new_filter_id);

					if (set_filter_flags(new_filter_id, FILTER_ADD_REMOVE | isEMM))
					{
						k->filter_id[fpos] = -1;
						k->pid[fpos] = -1;
					}
+					break;
				}
```

I'm right?

**Comment by catalinii** [comment]
I do not think is needed, this code is supposed to re-enable the filter for that pid, which could not be in enabled state.

**Comment by lars18th** [comment]
> I do not think is needed, this code is supposed to re-enable the filter for that pid, which could not be in enabled state.

Hi @catalinii ,

I think the opposite because:
1. The pid is active (and it's the ECM of the program).
2. The message indicates that the pid is already active.
3. Futhermore the message appears even if no error is found in the Oscam processing.
4. And finally, if this `break` isn't introduced then what the code execute is doing is **only** a simple "removes and reinsert" of the same pid! Ans this generates innecessary calls to `update_pids()`.

Please, try it! I'm convinced this `break` is required.

**Comment by lars18th** [comment]
When the PR is merged I'll close this issue. The patch resolves the problem!
