### ISSUE TITLE
DVBAPI: Two consecutive timeouts from OSCAM

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#545]
Hi,

When playing an encrypted program with Oscam, I observed this behaviour:

- When for any reason I receive a timeout (in the Oscam server), and in the next key I return another timeout, then the Oscam server sends to the minisatip the command "DVBAPI_DMX_STOP" for the ECM of the program. And this is printed in the log of minisatip:
```
[25/02 22:20:12.087 main]: dvbapi: received DMX_STOP for key 0, index 0, adapter 0, demux 0, filter 0, pid 8B1 (2225)
[25/02 22:20:12.087 main]: deleting filter 14
[25/02 22:20:12.087 main]: Dumping pids table for adapter 0, pid errors 0
```

And after this, the only solution to restablish the decoding is to retune the channel.

However, I feel this is an incorrect behaviour. If we receive to close the dvbapi pid but the program continues playing, then only one scenario is possible: the decoding has failed because a timeout is triggered in the server. The correct strategy is then: Resend the ECM to "reopen" the program and not close the pid.

What you think?

**Comment by catalinii** [comment]
I think it should be like that, can you post the entire log ?

**Comment by catalinii** [comment]
@lars18th, is this still an issue ?
