### ISSUE TITLE
Idea: Solution to timeout decoding errors

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#548]
Hi @catalinii ,

Regarding my problems with my Oscam server, I noticed one issue:

- When the Oscam server generates a "client timeout", in fact it doesn't do anything. So the regular behaviour is to discard the request in this case.

So the current behaviour in this case with minisatip is this:

- When one dvbapi request "fails" then you receive nothing. So, when the key changes the older key is invalited. So when the key changes another time, the key is missing and you reask for it. And this is correct. However, with this behaviour some packets can't be decoded as you need to recive the key, and until that you can't decode the stream.

One solution to this problem is to include one timeout for key requests (user configurable). So, when this timeout is reached then the key is requested another time.

You think it's a good idea?

**Comment by 9000h** [comment]
could this be also related to http://www.streamboard.tv/oscam/changeset/11505

**Comment by lars18th** [comment]
> could this be also related to http://www.streamboard.tv/oscam/changeset/11505

Hi @9000h ,

I don't know! However, in any case, to solve problems with Oscam timeouts the best solution seems to have an internal timer, and when the timer is raised then re-ask for the key. Don't you think so?

**Comment by catalinii** [comment]
@lars18th you do have a point about this:

	valid_cw = pmt->cw != NULL;
	master = get_pmt(pmt->master_pmt);
	if (master)
		valid_cw = master->cw != NULL;

	if ((getTick() - k->last_ecm > 1000) && !valid_cw)
		k->ecm_parity[i] = -1;

So if the key is not received while a key is valid this issue can appear.

k->last_cw < k->last_ecm && k->last_ecm > 2000 ?

**Comment by lars18th** [comment]
Hi @catalinii ,

I'm not sure if I understand this piece of code. Please, can you explain about these questions?
- If `k->ecm_parity[i] == -1` implies to _resend_ the ECM to Oscam?
- What do you do when you receive a `NOK` (aka timeout) from the Oscam server?
- You use a different approach when no key is received _between_ the other parity key is still valid, and when the next (with the same parity) is started to be used?

As I see in the logs of my Oscam server, I feel the minisatip requests when no key is found can be improved.

Thank you for your support!

**Comment by catalinii** [comment]
1)if ecm_parity is set to -1 it forces the ecm to be sent to oscam
2) oscam does not send anything if the CW was not ontained
3) this was solution to this issue

**Comment by catalinii** [comment]
@lars18th  ?
