### ISSUE TITLE
enhancement: http content delivery via port 8080 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#56]
I would be great to have the ability to deliver some web content from a local directory to create a small web interface for status page/config/log access ... 

this partially already there for /icons so what's your opinion?

the content types I have in mind are html, js, xml,png,jpg

for javascript it should be
Content-Type: application/x-javascript and HTTP/1.0 200 OK\r\nConnection: close\r\nPragma: no-cache

then it makes also sense to point the presentationURL from ssdp there

**Comment by catalinii** [comment]
Created new issue in the new system
