### ISSUE TITLE
Suggestion: URL in GUI

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#561]
Hi,

I have one suggestion:
- In the WEB UI in the section "Streams" will be useful to put a link with the URL of the _current_ stream.

Why we like this? To copy it to another program or to debug.

You agree?

**Comment by catalinii** [comment]
Hi Lars,

Feel free to create a PR related to this. I think you can infer the url based on the info from status.html

**Comment by lars18th** [comment]
Hi @catalinii ,

Done in this PR #739 . :wink: 
Regards.
