### ISSUE TITLE
Basic logging request

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#565]
Hi,

The logging `-l general` is quite large. Good for foreground testing, but verbose for log files.
Please, can you add some `-l error` level that prints out only start/stop info plus relevant errors?

Thank you.

**Comment by 9000h** [comment]
from what I understand we have
`utils.h:282:	{"general", "http", "socketworks", "stream", "adapter", "satipc", "pmt", "tables", "dvbapi", "lock", "netceiver", "ca", "axe", "socket", "utils", "dmx", "ssdp", "dvb", NULL};
`
I'm not aware of  -l global

**Comment by lars18th** [comment]
> I'm not aware of -l global

Sorry! It's a typo: `general`.

**Comment by catalinii** [comment]
You can run without -l that should show only errors.

**Comment by lars18th** [comment]
> You can run without -l that should show only errors.

Hi,

Whitout it (`-l`) nearly minisatip prints nothing.
The idea is something between `no-log` and `-l general`; as "general" is very verbose!

**Comment by catalinii** [comment]
In general, there are not many errors. If you have suggestions on which message to go where please feel free to make them. Or you can make a PR.

**Comment by lars18th** [comment]
Hi @catalinii ,

> In general, there are not many errors. If you have suggestions on which message to go where please feel free to make them. Or you can make a PR.

I created this _simple_ PR #674 . Please, review it.
Regards.

**Comment by Jalle19** [comment]
I think we can close this, #674 is merged and like @catalinii you can run with any `-l` to only log the absolute minimum.
