### ISSUE TITLE
When I build the new git version, I get this.

### ISSUE THREAD

**Issue by haarm** [catalinii/minisatip#569]
When I build the new git version, I get this.

gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBCSA -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c pmt.c -o ../build/pmt.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBCSA -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c tables.c -o ../build/tables.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBCSA -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c satipc.c -o ../build/satipc.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBCSA -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c dvb.c -o ../build/dvb.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBCSA -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -o ../minisatip  ../build/minisatip.o  ../build/socketworks.o  ../build/stream.o  ../build/adapter.o  ../build/utils.o  ../build/aes.o  ../build/dvbapi.o  ../build/pmt.o  ../build/tables.o  ../build/satipc.o  ../build/dvb.o  -lpthread -lrt -lcrypto
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: ../build/utils.o: in function `_dump_packets':
/opt/test/minisatip/src/utils.c:1801: undefined reference to `PID_FROM_TS'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:141: ../minisatip] Fehler 1
make[1]: Verzeichnis â/opt/test/minisatip/srcâ wird verlassen
make: *** [Makefile:6: minisatip] Fehler 2

**Comment by 9000h** [comment]
yes was my fault
https://github.com/catalinii/minisatip/pull/568

**Comment by haarm** [comment]
bad Boy ;-)

**Comment by 9000h** [comment]
can you close now please?
