### ISSUE TITLE
bug SETUP

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#57]
from the SES spec
The Session header identifies an RTSP session started by the server in a SETUP response and concluded by a TEARDOWN message. The session identifier is chosen by the server. The session identifier is a string with a minimum length of 8 octets. Once a client receives a session identifier, it must return it for any request related to that session. 

and there should be the leading zeros

"Session: %010d\r\n"

 %010d would be great for VDR compat

and btw should it be random?

**Comment by catalinii** [comment]
No idea...but get_session_id returns now a larger number
