### ISSUE TITLE
hardware ci and softcam

### ISSUE THREAD

**Issue by mtonnie** [catalinii/minisatip#573]
I have some channels which need the hardware ci module and other channels where I relay on OSCam, but I can't get it wotking.
If I set the option -o I can get working all the channels with OSCam but all channels which require ci hardware cam) are not working any more. 
Any hin'ts how to use hardware ci and softcam togehter?

BTW: /usr/bin/minisatip -R /usr/share/minisatip/html -f -u 0:0-1284,1:1-1400,2:2-1516 -o 127.0.0.1:9000

**Comment by catalinii** [comment]
Hi,

Can you provide the log?

./minisatip -f -l http

**Comment by catalinii** [comment]
Closing, if it is still an issue please upload the logs as suggested above
