### ISSUE TITLE
"Stream" column in web status is empty

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#575]
Hi,

Why is the "Stream" column is always empty on the Status info page?

**Comment by 9000h** [comment]
it may show up when you have multistreams active
https://github.com/catalinii/minisatip/blob/cae79dc95d343638340a03688528f9c8cfa65679/src/adapter.c#L2254

**Comment by lars18th** [comment]
Hi @9000h ,

> it may show up when you have multistreams active

What's a "multistream"? Two clients using the same adapter? Or when using PLP signals?

**Comment by 9000h** [comment]
when using PLP

**Comment by lars18th** [comment]
OK. Thank you! :wink:
