### ISSUE TITLE
BUG: Can't stream two programs when using HTTP

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#577]
Hi,

I feel this is a bug:

- I do this test: two SAT>IP clients and one HTTP client (VLC with a full `http://...:8080/?src=...&pids=...`), so a total of 3 clients. I request from the first SAT>IP a program in a transponder. Then in the second SAT>IP client I request another program in the _same_ transponder. Finally, from the HTTP client I request another program in the _same_ transponder.
- The result is: the HTTP client can't receive the stream!

And this is true every time an HTTP client requests some program from an active adapter, even if the same source is used. So the same result when just one SAT>IP client and one HTTP client. Futhermore, if I do the opposite (first tune with the HTTP client and _after_ with the SAT>IP client) then the connection is accepted.

So the problem is only when an HTTP tunning is requested over an already running transponder.

Please, review the code. And check it by yourself! No logs are required. It's trivial to reproduce the behaviour!

**Comment by 9000h** [comment]
card/driver pid limit ?

**Comment by lars18th** [comment]
> card/driver pid limit ?

No! I'm using the SAT>IP client mode. And **indentical** configuration of client programs work when _all_ request are using SAT>IP. The problem is just when connecting using the HTTP protocol.

I feel something is incorrected checked when requesting using the HTTP protocol.

**Comment by catalinii** [comment]
@lars18th, can you try a different client than vlc ?

I tried as you suggested but used ffmpeg as http client and worked good.

**Comment by lars18th** [comment]
Hi @catalinii ,

I discovered the cause of this issue. You can reproduce if you like, and I feel is simple to fix it:

- The problem is caused when the HTTP client requests _less_ parameters than the current tuned parameters. For example, if the `mtype` is missing (because the client assumes to use _auto_ mode) but the previous request specifies a `mtype` then the HTTP connection is refused. At time, when the same HTTP requests without the `mtype` and no session exists, then isn't any problem, as the tuner uses _auto_.

So, the solution I recommend is this: when a client (HTTP _or_ RTSP, don't care about this) requests a new TUNE command and the parameters are a _subset_ of the current parameteres in the same frequency and source, then use the current parameters and accept the command (instead of returning an error).

You agree?

**Comment by 9000h** [comment]
Hi,
HTTP clients/servers are not specified in the SAT>IP spec, it's a freestyle extensions, and more or less only implemented to make tests easier.
CU
9000h

**Comment by lars18th** [comment]
Hi @9000h ,

> HTTP clients/servers are not specified in the SAT>IP spec

False. And futhermore, minisatip is a good HTTP SAT>IP server. In any case the same problem will be true if the RTSP client requests an _incomplete_ (aka with _auto_ values) URL. In fact, the same code processes both: RTSP and HTTP requests. So, the problem is here.

So, I prefer if minisatip catches _malformed_ or _incomplete_ request if it can.
You agree?

**Comment by 9000h** [comment]
Hi,
right :-) 
3.6.2 HTTP Streaming not required 
CU

**Comment by catalinii** [comment]
Added a fix specifically for mtype. Can you check now ?

**Comment by lars18th** [comment]
Hi @catalinii 

> Added a fix specifically for mtype. Can you check now ?

Yes. Tested and fixed! :+1: 
So I close this issue.
Thank you!

**Comment by lars18th** [comment]
Hi @catalinii ,

Error! Now when _no_ `mtype` is included the trouble is fixed. However, if the `mtype` is included... now it doesn't work! :fearful:

**Comment by lars18th** [comment]
Hi @catalinii ,

> Error! Now when _no_ `mtype` is included the trouble is fixed. However, if the `mtype` is included... now it doesn't work!

False alarm! The problem is that _without_ my patches it doesn't work. I tested with vanilla minisatip.
Please, merge the PR #638. Without it serious bug continue with the satipc frontend.

Regards.
