### ISSUE TITLE
new rtsp bug 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#58]
one of the last commits did mess up rtsp streaming with VLC, http is still ok

**Comment by 9000h** [comment]
the rtcp in the dddvb driver has may avalid header

static u8 rtcp_head[] = {
        /* SR off 42:8 len 28*/
        0x80, 0xc8, /* SR type */
        0x00, 0x06, /* len  */
        0x91, 0x82, 0x73, 0x64, /* SSRC */
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /* NTP */
        0x73, 0x64, 0x00, 0x00, /* RTP TS */
        0x00, 0x00, 0x00, 0x00, /* packet count */
        0x00, 0x00, 0x00, 0x00, /* octet count */
        /* SDES off 70:36 len 20 */
        0x81, 0xca, /* SDES */
        0x00, 0x03, /* len */
        0x91, 0x82, 0x73, 0x64, /* SSRC */
        0x01, 0x05, /* CNAME item */
        0x53, 0x41, 0x54, 0x49, 0x50, /* "SATIP" */
        0x00, /* item type 0 */
        /*  APP off 86:52 len 16+string  length */
        0x80, 0xcc, /* APP */
        0x00, 0x04, /* len */
        0x91, 0x82, 0x73, 0x64, /* SSRC */
        0x53, 0x45, 0x53, 0x31, /* "SES1" */
        0x00, 0x00, /* identifier */
        0x00, 0x00, /* string length */
        /* string off 102:68 */
};

**Comment by catalinii** [comment]
Thanks for that
I totally missed the other headers.

Now tcpdump seems happy and the app is seeing the signal.

If you really want signal monitoring use -s (which gets the signal every time).

Check and let me know if everything is ok.

Thanks

**Comment by 9000h** [comment]
the app shows signal now it's fine from the protocol side now i think, but the values still a bit strange

VLC and rtsp is still a issue

root@yavdr2:/usr/src/satip/minisatip-master# ./minisatip -l -l -l  -d6 -f
Starting minisatip version 0.1.28, dvbapi version: 0504
[Fri Jan 23 16:55:11.000 2015]: New UDP socket 3 bound to 0.0.0.0:1900
[Fri Jan 23 16:55:11.000 2015]: setting multicast for 239.255.255.250
[Fri Jan 23 16:55:11.000 2015]: New UDP socket 4 bound to 239.255.255.250:1900
[Fri Jan 23 16:55:11.001 2015]: New UDP socket 7 bound to 0.0.0.0:5500
[Fri Jan 23 16:55:11.001 2015]: New UDP socket 8 bound to 0.0.0.0:5501
[Fri Jan 23 16:55:11.001 2015]: sockets_add: handle 3 (type 0) returning socket index 0 [0.0.0.0:0]
[Fri Jan 23 16:55:11.001 2015]: sockets_add: handle 4 (type 0) returning socket index 1 [0.0.0.0:0]
[Fri Jan 23 16:55:11.001 2015]: sockets_add: handle 5 (type 2) returning socket index 2 [0.0.0.0:0]
[Fri Jan 23 16:55:11.001 2015]: sockets_add: handle 6 (type 2) returning socket index 3 [0.0.0.0:0]
[Fri Jan 23 16:55:11.001 2015]: starting init_hw 0
[Fri Jan 23 16:55:11.001 2015]: trying to open [0] adapter 0 and frontend 0
adapter.c:103 allocation_wrapper malloc allocated 9222 bytes at 0x2041cb0
[Fri Jan 23 16:55:11.002 2015]: opened DVB adapter 0 fe:9 dvr:10
[Fri Jan 23 16:55:11.003 2015]: Done setting DVR buffer to 5775360 bytes
[Fri Jan 23 16:55:11.003 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Fri Jan 23 16:55:11.533 2015]: sockets_add: handle 10 (type 5) returning socket index 4 [0.0.0.0:0]
[Fri Jan 23 16:55:11.533 2015]: done opening adapter 0 fe_sys 1
[Fri Jan 23 16:55:11.533 2015]: trying to open [1] adapter 1 and frontend 0
adapter.c:103 allocation_wrapper malloc allocated 9222 bytes at 0x20440c0
[Fri Jan 23 16:55:11.533 2015]: opened DVB adapter 1 fe:11 dvr:12
[Fri Jan 23 16:55:11.534 2015]: Done setting DVR buffer to 5775360 bytes
[Fri Jan 23 16:55:11.534 2015]: deleting pids on adapter 1, sid -1, pids=NULL
[Fri Jan 23 16:55:12.589 2015]: sockets_add: handle 12 (type 5) returning socket index 5 [0.0.0.0:0]
[Fri Jan 23 16:55:12.589 2015]: done opening adapter 1 fe_sys 6
[Fri Jan 23 16:55:12.589 2015]: trying to open [2] adapter 2 and frontend 0
adapter.c:103 allocation_wrapper malloc allocated 9222 bytes at 0x20464d0
[Fri Jan 23 16:55:12.589 2015]: opened DVB adapter 2 fe:13 dvr:14
[Fri Jan 23 16:55:12.590 2015]: Done setting DVR buffer to 5775360 bytes
[Fri Jan 23 16:55:12.590 2015]: deleting pids on adapter 2, sid -1, pids=NULL
[Fri Jan 23 16:55:12.617 2015]: sockets_add: handle 14 (type 5) returning socket index 6 [0.0.0.0:0]
[Fri Jan 23 16:55:12.617 2015]: done opening adapter 2 fe_sys 16
[Fri Jan 23 16:55:12.617 2015]: done init_hw 1
Initializing with 3 devices
[Fri Jan 23 16:55:12.818 2015]: ssdp_discovery fd: 3 -> NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=1800
LOCATION: http://192.168.178.133:8080/desc.xml
NT: upnp:rootdevice
NTS: ssdp:alive 
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::upnp:rootdevice
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6


[Fri Jan 23 16:55:20.973 2015]: sockets_add: handle 16 (type 1) returning socket index 7 [192.168.178.130:62966]
[Fri Jan 23 16:55:20.974 2015]: read RTSP (from handle 16 sock_id 7):
OPTIONS rtsp://192.168.178.133:554/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106 RTSP/1.0
CSeq: 2
User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)


[Fri Jan 23 16:55:20.974 2015]: minisatip.c:484 get_sid returns NULL for s_id = -1
[Fri Jan 23 16:55:20.974 2015]: reply -> 16 (CL:0) :
RTSP/1.0 200 OK
Cseq: 2
Date: Fri Jan 23 16:55:20.974 2015
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN


[Fri Jan 23 16:55:20.978 2015]: read RTSP (from handle 16 sock_id 7):
DESCRIBE rtsp://192.168.178.133:554/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106 RTSP/1.0
CSeq: 3
User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Accept: application/sdp


[Fri Jan 23 16:55:20.978 2015]: minisatip.c:484 get_sid returns NULL for s_id = -1
[Fri Jan 23 16:55:20.978 2015]: starting init_hw 1
[Fri Jan 23 16:55:20.978 2015]: starting init_hw 1
[Fri Jan 23 16:55:20.978 2015]: starting init_hw 1
[Fri Jan 23 16:55:20.978 2015]: reply -> 16 (CL:234) :
RTSP/1.0 200 OK
CSeq: 3
Date: Fri Jan 23 16:55:20.978 2015
Content-type: application/sdp
Content-Base: rtsp://192.168.178.133/
Content-Length: 234

v=0
o=- 0000000000 0000000000 IN IP4 192.168.178.133
s=SatIPServer:1 1 1 1
t=0 0
m=video 0 RTP/AVP 33
c=IN IP4 0.0.0.0
a=control:stream=0000000000
a=fmtp:33 ver=1.2;src=1;tuner=0,0,0,0,0.00,8,dvbc,qpsk,0,,,;pids=0
a=inactive



[Fri Jan 23 16:55:20.981 2015]: read RTSP (from handle 16 sock_id 7):
SETUP rtsp://192.168.178.133/stream=0000000000 RTSP/1.0
CSeq: 4
User-Agent: LibVLC/2.2.0-rc1 (LIVE555 Streaming Media v2014.01.21)
Transport: RTP/AVP;unicast;client_port=58142-58143


[Fri Jan 23 16:55:20.981 2015]: decode_transport ->2 0 58142 192.168.178.130
[Fri Jan 23 16:55:20.981 2015]: starting init_hw 1
[Fri Jan 23 16:55:20.981 2015]: no ? found in URL
[Fri Jan 23 16:55:20.981 2015]: Setup stream -1 parameters, sock_id 7, handle 16
[Fri Jan 23 16:55:20.981 2015]: New UDP socket 17 connected to 192.168.178.130:58142
stream.c:258 allocation_wrapper malloc allocated 321 bytes at 0x2041500
stream.c:260 allocation_wrapper malloc allocated 321 bytes at 0x20488e0
stream.c:262 allocation_wrapper malloc allocated 321 bytes at 0x2048a30
stream.c:264 allocation_wrapper malloc allocated 1326 bytes at 0x2048b80
[Fri Jan 23 16:55:20.981 2015]: copy_dvb_param start -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=0, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Fri Jan 23 16:55:20.981 2015]: copy_dvb_parameters -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=0, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Fri Jan 23 16:55:20.981 2015]: Setup stream done: sid: 0 (e:1) for sock 7 handle 16
[Fri Jan 23 16:55:20.981 2015]: reply -> 16 (CL:0) :
RTSP/1.0 200 OK
Cseq: 4
Date: Fri Jan 23 16:55:20.981 2015
Transport: RTP/AVP;unicast;client_port=58142-58143;source=192.168.178.133;server_port=45424-45425
Session:0001000000;timeout=30
com.ses.streamID: 1


[Fri Jan 23 16:55:40.216 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:40.216 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:40.216 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:40.216 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:40.467 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:40.467 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:40.467 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:40.467 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:41.718 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:41.718 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:41.718 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:41.718 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:41.969 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:41.969 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:55:41.969 2015]: ssdp_reply fd: 3 -> 192.168.178.132
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Fri Jan 23 16:55:41.969 2015
EXT:
LOCATION: http://192.168.178.133:8080/desc.xml
SERVER: Linux/1.0 UPnP/1.1 minisatip/0.1.28
ST: urn:ses-com:device:SatIPServer:1
USN: uuid:11223344-9999-0000-b7ae-0040caa2c79d::urn:ses-com:device:SatIPServer:1
BOOTID.UPNP.ORG: 33
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6

[Fri Jan 23 16:56:12.602 2015]: sockets_del: 4 -> handle 10, sid 0
[Fri Jan 23 16:56:12.602 2015]: closing DVR socket -1 pos 4 aid 0
[Fri Jan 23 16:56:12.602 2015]: closing adapter 0  -> fe:9 dvr:10
[Fri Jan 23 16:56:12.602 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Fri Jan 23 16:56:12.602 2015]: sockets_del: 4 -> handle -1, sid 0
[Fri Jan 23 16:56:12.602 2015]: done closing adapter 0
[Fri Jan 23 16:56:12.602 2015]: sockets_del: 4 Last open socket is at index 7 current_handle 10
[Fri Jan 23 16:56:12.602 2015]: sockets_del: 5 -> handle 12, sid 1
[Fri Jan 23 16:56:12.602 2015]: closing DVR socket -1 pos 5 aid 1
[Fri Jan 23 16:56:12.602 2015]: closing adapter 1  -> fe:11 dvr:12
[Fri Jan 23 16:56:12.602 2015]: deleting pids on adapter 1, sid -1, pids=NULL
[Fri Jan 23 16:56:12.602 2015]: sockets_del: 5 -> handle -1, sid 1
[Fri Jan 23 16:56:12.602 2015]: done closing adapter 1
[Fri Jan 23 16:56:12.603 2015]: sockets_del: 5 Last open socket is at index 7 current_handle 12
[Fri Jan 23 16:56:12.803 2015]: sockets_del: 6 -> handle 14, sid 2
[Fri Jan 23 16:56:12.803 2015]: closing DVR socket -1 pos 6 aid 2
[Fri Jan 23 16:56:12.803 2015]: closing adapter 2  -> fe:13 dvr:14
[Fri Jan 23 16:56:12.803 2015]: deleting pids on adapter 2, sid -1, pids=NULL
[Fri Jan 23 16:56:12.803 2015]: sockets_del: 6 -> handle -1, sid 2
[Fri Jan 23 16:56:12.803 2015]: done closing adapter 2
[Fri Jan 23 16:56:12.804 2015]: sockets_del: 6 Last open socket is at index 7 current_handle 14
^Cselect_and_execute: select() error: Interrupted system call
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 7 -> handle 16, sid 0
[Fri Jan 23 16:56:47.685 2015]: Closing stream 0
[Fri Jan 23 16:56:47.685 2015]: closing stream 0
[Fri Jan 23 16:56:47.685 2015]: closed stream 0
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 7 Last open socket is at index 3 current_handle 16
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 3 -> handle 6, sid -1
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 3 Last open socket is at index 2 current_handle 6
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 2 -> handle 5, sid -1
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 2 Last open socket is at index 1 current_handle 5
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 1 -> handle 4, sid -1
[Fri Jan 23 16:56:47.685 2015]: sockets_del: 1 Last open socket is at index 0 current_handle 4
stream.c:670 allocation_wrapper free called with argument 0x2041500 - done free
stream.c:672 allocation_wrapper free called with argument 0x20488e0 - done free
stream.c:674 allocation_wrapper free called with argument 0x2048a30 - done free
stream.c:676 allocation_wrapper free called with argument 0x2048b80 - done free
adapter.c:710 allocation_wrapper free called with argument 0x2041cb0 - done free
adapter.c:710 allocation_wrapper free called with argument 0x20440c0 - done free
adapter.c:710 allocation_wrapper free called with argument 0x20464d0 - done free
root@yavdr2:/usr/src/satip/minisatip-master#

**Comment by catalinii** [comment]
The values are relative to the max signal that is received by the dvb card, which I think is the only way to go due to different values returned by different adapters (ofc if u have a better idea let me know)

I will close this as we have an open issue about rtsp and vlc

**Comment by 9000h** [comment]
with the commits from today and app is seeing again no signal :-/

**Comment by catalinii** [comment]
this is fixed (again), it seems the work of adding rtsp over tcp screwed this
