### ISSUE TITLE
autostart minisatip no adapter found

### ISSUE THREAD

**Issue by riegaz** [catalinii/minisatip#583]
I run minisatip on ubuntu and autostart it by executing it in /etc/rc.local

However, it doesn't detect my adapter. I guess this is because it is loaded before the adapter is loaded. Is there a way to handle this problem?

Is there a parameter? Should I delay the start of minisatip?

**Comment by Ntemis** [comment]
thats an issue of your distro not minisatip go ask at #ubuntu channels

**Comment by 9000h** [comment]
it's not specific to any distro, the device modules need to be loaded and the network should be up before minisatip is started. 
a systemd service can do this

**Comment by riegaz** [comment]
Thanks!
