### ISSUE TITLE
Switching to scrambled channel and back fails

### ISSUE THREAD

**Issue by riegaz** [catalinii/minisatip#585]
I found the following problem: When I switch to some scrambled channel that for some reason can not be descrambled (e.g. signal too weak) and back to another free one, TVH doesn't show a stream at all anymore. The only thing I can do is to restart minisatip.

Here is a log file:

https://pastebin.com/raw/Ajh4qUaT

Any help is welcome.

**Comment by catalinii** [comment]
Hi,

I do not see any usage of oscam setup here so I think you should probably ask help from TVH team.

Thanks
