### ISSUE TITLE
Sundtek dvb-s2 powersave

### ISSUE THREAD

**Issue by riegaz** [catalinii/minisatip#586]
I have a sundtek dvb-s2 USB connected to a linux machine(A) with minisatip installt. For watching live TV I use another box(B) to access the dvb-s2 via minisatip. After shutting down B where I use tvheadend. I would expect the dvb-s2 to go to sleep. However, the A driver detects that minisatip is still accessing the dvb-s2 and thus doesn't send the dvb-s2 to powersave.

Any ideas on this one?

**Comment by Ntemis** [comment]
This is not a minisatip issue, as there is no mechanism to check if the usage of the adapters are nil then go to sleep and when rtsp is requested to wake up :)

**Comment by riegaz** [comment]
I see your point. However, at the Sundtek forum they tell me otherwise. Honestly, I like the approach that minisatip should release /dev/dvb/adapter0/frontend0 if there is no rtsp.

What do you think?

The post is in german: https://support.sundtek.com/index.php?topic=2399.0

**Comment by Ntemis** [comment]
And then there was /dev/dvb/adapter1 /dev/dvb/adapter2 etc

**Comment by riegaz** [comment]
Exactly, my question is why minisatip shouldn't release them when not used?

**Comment by Ntemis** [comment]
You have to kill the app

**Comment by riegaz** [comment]
I know that killing minisatip would help it but this isn't the goal. Minisatip should keep running. However, release the tuner when not used.

**Comment by Ntemis** [comment]
Then go back to my initial answer.

**Comment by catalinii** [comment]
Minisatip should release any adapter after 30s after the last client
disconnected. If you do not have any client connected and see minisatip
holding the adapter open, please upload logs.

You can use lsof | grep adapter0 to see who keeps the adapter open

**Comment by catalinii** [comment]
If this is still an issue please feel free to re-open
