### ISSUE TITLE
Feature request: command line option to change friendly name

### ISSUE THREAD

**Issue by nmaster2042** [catalinii/minisatip#587]
I'm running 2 minisatip servers on my LAN, both broadcasts the same friendly name (minisatip).

It would be a nice feature to add a option to start the server with a custom friendly name, like it's doable for example on DLNA servers.

**Comment by 9000h** [comment]
is the -X not sufficient

-X --xml PATH: the path to the xml that is provided as part of the satip protocol

    by default desc.xml is provided by minisatip without needing an additional file, however satip.xml is included if it needs to be customized

**Comment by nmaster2042** [comment]
Probably, but customizing the full xml file to change name is not the easiest way, specially when using in docker containers.

It's like other options as -p for playlist. It changes default desc.xml so we don't need to rewrite it.

**Comment by lars18th** [comment]
Hi,

I have a small suggestion to overcome this problem: It's to use as the server name something like `minisatip-000` where `000` corresponds to the last numbers of the IP address (ex. 192.168.1.33, then `minisatip-033`).

This solution is deterministic and easy to implement.
What you think?

**Comment by nmaster2042** [comment]
Hi.

Your idea to use a default name is good.

Instead of minisatip-000 why not simply use server's hostname ?

Its easier to implement.

**Comment by lars18th** [comment]
> why not simply use server's hostname ?

Because some reasons:

1. The server hostname can be long.
2. The SAT>IP protocol has a method to use the last three digits of the IP address for reserving the multicast address for each server (up to 254 servers).
3. It's quite more easy to implement it.

In any case. Personally I don't have time to implement it. I hope @catalinii will want to do it.
Regards.

**Comment by Jalle19** [comment]
This was AFAICT added in https://github.com/catalinii/minisatip/commit/aa396a052c32dfb459a5de6e0bdcce02727cef96
