### ISSUE TITLE
[question] allowed and disallowed frequencies

### ISSUE THREAD

**Issue by sz-po** [catalinii/minisatip#589]
Big thanks to all community for working on minisatip!

Sorry if this is not right place for that, but I have a question about limiting access to given frequencies. I can't see proper configuration option, so I have two ideas how to realize that.

1) Edit source of dvb.c and allow to pass on adapter struct allowed frequency, and after having possibility to pass freq from args, just simple if for comparation and return -404 near dvb.c:837
2) Filter requests on http proxy (allowing in eg. urls with freq=allowed_freq.

With way is better and less error-prone?

**Comment by catalinii** [comment]
Probably an proxy configuration might be easier to maintain, otherwise you would need to apply the patch every time you compile minisatip.

**Comment by sz-po** [comment]
Thank You for a reply. I use front nginx as filter, works perfectly!
