### ISSUE TITLE
Web-GUI is not loading tuner list

### ISSUE THREAD

**Issue by sumulu** [catalinii/minisatip#591]
I just installed last release (commit b904069facce81d8f4bf592e3d56b2a948539216).
If I open the Web-GUI, the tuners are not loading.

![webguiloading](https://user-images.githubusercontent.com/26624688/61319185-ff6b4100-a806-11e9-81eb-3c696482e806.PNG)

Tested Mozilla-Firefox and Google-Chrome.

**Comment by haarm** [comment]
Here exactly the same problem

**Comment by 9000h** [comment]
confirmed

**Comment by catalinii** [comment]
Thid patch is already merged

**Comment by 9000h** [comment]
@sumulu if it works for you also please close

**Comment by sumulu** [comment]
Thanks for quick fix. It's working for me now.
