### ISSUE TITLE
diseq issue

### ISSUE THREAD

**Issue by michaeladams123** [catalinii/minisatip#596]
hi,

kindly i have issue when i applied -d *:2-0 to use the port b from diseq but still not working please advise

**Comment by 9000h** [comment]
Hi,
you may need to explain how your dish setup/diseqc installation looks like before we can help, but if you have a "simple" diseqc like A = 19.2E, B = 13.0E then "-d ..." is probaly not useful.
You choose the needed diseqc with  src=1-4 in the request URL.
CU
9000h

**Comment by catalinii** [comment]
Please reopen the issue if you could not fix the problem.
