### ISSUE TITLE
TBSDVB 6590 

### ISSUE THREAD

**Issue by michaeladams123** [catalinii/minisatip#598]
Hi,

Kindly note that why when i used the card tb6904 working will without any issue and if used the card tbs6590 with dual CI not working and no response ?

Regards

**Comment by 9000h** [comment]
Hi,
looks like a kernel/driver issue.
CU

**Comment by michaeladams123** [comment]
Hi,

on dvblast and astra working well but when try to use minisatip not working

**Comment by catalinii** [comment]
Can you upload logs ./minisatip -f -l http

**Comment by catalinii** [comment]
Please reopen the issue if you could not fix the problem.
