### ISSUE TITLE
to decrypt channels using an official subscription and support dvbca protocol (requires dvben50221 library) for dvb cards with CA hardware

### ISSUE THREAD

**Issue by michaeladams123** [catalinii/minisatip#599]
to decrypt channels using an official subscription and support dvbca protocol (requires dvben50221 library) for dvb cards with CA hardware

how I can use this library and enable it ?

**Comment by 9000h** [comment]
Hi,
depending on your distribution it in the "dvb-apps" package, install it.
dvb-apps: /usr/lib/libdvben50221.a
dvb-apps: /usr/lib/libdvben50221.so
CU
9000h

**Comment by michaeladams123** [comment]
Hi,

I used ubuntu 16.0.4

Regards

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 9000h** [comment]
apt-get install dvb-apps

then in minisatip source

make clean
./configure
make

**Comment by michaeladams123** [comment]
Yes sure but this command will support dvb s2 with  ca ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by catalinii** [comment]
Yes it should

**Comment by catalinii** [comment]
Please reopen the issue if you could not fix the problem.
