### ISSUE TITLE
desc.xml

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#60]
add mime type to http_response 

missing escape should be
"<\?xml version=\"1.0\"\?>\r\n"  

Content-Type: text/xml\r\nMime-Version: 1.0\r\n

add additional CRLF after /root

make configid a variable like

may change modelDescription to minisatip only

may remove UPC

**Comment by catalinii** [comment]
Hi,

Mime-version is not a required field.
This is how the xml looks like in the specifications:
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" configId="0">

minisatip produces the following:

<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" configId="0">

To me they look the same.
At this point the xml is compatible with all the sat>ip clients and it looks more or less like in the specifications.

As theoretically what you said should be fine, however the clients are not perfect (or minisatip for that matter) and it might introduce additional incompatibilities with some clients, I would prefer to leave it as it is, to avoid fixing something is not broken.

Thank you
