### ISSUE TITLE
Channel Name in Web-GUI missing

### ISSUE THREAD

**Issue by peos3** [catalinii/minisatip#600]
I noticed in recent versions of minisatip that the Web-GUI does nolonger show the current adapter channel name. Instead the row is completely empty.

Here is a picture of it before and and after:
![minisatip_before](https://user-images.githubusercontent.com/17992709/62521472-0565a800-b830-11e9-9635-4ad02ab98ccf.png)
![minisatip_now](https://user-images.githubusercontent.com/17992709/62521482-08609880-b830-11e9-9264-860ad48f88a8.png)

I looked into the `state.json`, but the ad_channel looked like this:  
`"ad_channel":["","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""]`
So there was actually no info to display in the newer version.

I also found that pmt_running differs.  
Old:
`"pmt_running":[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],`
New:
`"pmt_running":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],`  

I tracked this issue down to a specific commit: b354345.
The removal of `pmt->running = 1` in pmt.c seemed to stop pmt from running and therefore not getting the channel name for the adpater.

I reverted this change in the current master, and everything seems fine so far. I don't now if it has any side effects though or if it was an intended change to remove the channel name from the web-gui.  

Here the patch to revert this change and reactivate the channel name in the web-gui:

```
diff --git a/src/pmt.c b/src/pmt.c
index abddaaa..82b5e6e 100644
--- a/src/pmt.c
+++ b/src/pmt.c
@@ -1703,6 +1703,7 @@ int process_pmt(int filter, unsigned char *b, int len, void *opaque)
 		if ((cp = find_pid(ad->id, spid))) // the pid is already requested by the client
 		{
 			enabled_channels++;
+			pmt->running = 1;
 			cp->pmt = pmt->master_pmt;
 		}
 	}
```

**Comment by catalinii** [comment]
Thanks for finding the issue, can you create a pull request?

**Comment by peos3** [comment]
@catalinii  
Pull request is open. Please review the small change.  
I hope this does not break other functions related to CA clients.

**Comment by catalinii** [comment]
Merged. Thanks for fixing it
