### ISSUE TITLE
ca.c:2678 Invalid usleep() argument nr 1.

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#607]
https://github.com/catalinii/minisatip/blob/6ea7837967a13b5036c06266fa7e41da1859eae5/src/ca.c#L2678
in the man page
```
       The type useconds_t is an unsigned integer type capable of holding
       integers in the range [0,1000000].
```

**Comment by Jalle19** [comment]
Related to https://github.com/catalinii/minisatip/issues/528
