### ISSUE TITLE
TBS 6590 CI

### ISSUE THREAD

**Issue by michaeladams123** [catalinii/minisatip#608]
Hi,

Kindly I have server with 4 cards TBS 6590 CI and the connectivity field from satip with minisatip and if used FTA cards without CI and working well but TBS 6590 CI failed to connect and no tuning request.

Regards

**Comment by catalinii** [comment]
Hi,

Can you run:

./minisatip -f -l http,dvb

And upload the logs?

Thanks

**Comment by michaeladams123** [comment]
[alaa.log](https://github.com/catalinii/minisatip/files/3685011/alaa.log)
[config.log](https://github.com/catalinii/minisatip/files/3685014/config.log)
Kindly find the attached files,

**Comment by Yuri666** [comment]
tbs 6950 driver create two frontends - firrst for dvbt and second for dvbs. minisatip can recognize only one - first. 
If you want to use SAT sourrce i can suggest you workaroung - just rename /dev/dvb/adapterX/frontend1 to frontend0

**Comment by michaeladams123** [comment]
sorry I used to rename the file the frequency successfully but failed to tuning and received data from Minisatip

**Comment by Yuri666** [comment]
please upload new log

**Comment by michaeladams123** [comment]
can you connect team viwer or anydesk please ?

**Comment by michaeladams123** [comment]
[minisatip.log](https://github.com/catalinii/minisatip/files/3687702/minisatip.log)

no data from dvb just send the frequency and tuning failed

**Comment by michaeladams123** [comment]
I used the command ./minisatip -d 0-7

**Comment by michaeladams123** [comment]
![minisatip-master](https://user-images.githubusercontent.com/50541307/66157389-617c5b00-e62c-11e9-9210-50a6c730393f.jpg)

**Comment by Yuri666** [comment]
Your log file is empty. Please run ./minisatip -l http,dvb

**Comment by michaeladams123** [comment]
[minisatip.log](https://github.com/catalinii/minisatip/files/3687749/minisatip.log)

please I need your support

**Comment by michaeladams123** [comment]
[minisatip.log](https://github.com/catalinii/minisatip/files/3687785/minisatip.log)


new log

**Comment by michaeladams123** [comment]
[minisatip.log](https://github.com/catalinii/minisatip/files/3687816/minisatip.log)
last log file

**Comment by Yuri666** [comment]
1. You change frontend only for first adapter but trying to use second, third, etc - needs to change frontend1 to frontend0 for all 8 adapters.
2. You have stream from minisatip:
[03/10 22:32:50.340 signal]: BW 4438KB/s, Total BW: 64 MB, ns/read 1090, r: 63, w: 63 fw: 0, tt: 68 ms
so, minisatip works with tbs 6590 and you problem is not issue, but configuration troubles.

**Comment by michaeladams123** [comment]
thanks for your kindly support, i changed for all adapters and the traffic can received only 35 mega and no channels or any info just try to connect 
![minisatip-master](https://user-images.githubusercontent.com/50541307/66175890-1c741b00-e664-11e9-9371-150af2349374.jpg)
![35000](https://user-images.githubusercontent.com/50541307/66175891-1e3dde80-e664-11e9-9a9d-7c6c4f627e73.jpg)
[minisatip.log](https://github.com/catalinii/minisatip/files/3688686/minisatip.log)

**Comment by michaeladams123** [comment]
and quality of signal very good and working well

**Comment by michaeladams123** [comment]
![22222](https://user-images.githubusercontent.com/50541307/66176116-3e21d200-e665-11e9-8932-4f6f35c189da.jpg)

same traffic for another adapter and different freq and adapter and no channels received
maybe eno0 error ?
[minisatip.log](https://github.com/catalinii/minisatip/files/3688702/minisatip.log)

**Comment by michaeladams123** [comment]
![snr](https://user-images.githubusercontent.com/50541307/66176240-ae305800-e665-11e9-8622-c48d175134b0.jpg)
and snr equal zero

**Comment by michaeladams123** [comment]
sorry maybe the error from net0 inside adapters ?

**Comment by michaeladams123** [comment]
the problem solved
