### ISSUE TITLE
Server side decryption - No issue

### ISSUE THREAD

**Issue by vdrtuxnet** [catalinii/minisatip#61]
Just some good news, regarding the server side decryption. <- it's working!

But I think, this is the wrong place to discus those kind of goodies.

Is some one around, who could spend some web space for a tiny discussion forum?

kind regards

**Comment by 3PO** [comment]
>Is some one around, who could spend some web space for a tiny discussion forum?

--> http://dreipo.cc/forum/

**Comment by 9000h** [comment]
as long you like to talk the https://www.kernel.org/doc/Documentation/dvb/ci.txt it's ok to do it here

**Comment by catalinii** [comment]
Can you detail what you did ? :)

**Comment by 9000h** [comment]
so from the handbook of the octonet some sample url's where the extra parameters are shown

„Auto CI“ and note the pid 97 in pid and pmt
rtsp://@192.168.1.2/?src=1&freq=12070&pol=h&msys=dvbs&sr=27500&pids=0,97,511,32,512&x_pmt=97

select „CI 1“
rtsp://@192.168.1.2/?src=1&freq=12070&pol=h&msys=dvbs&sr=27500&pids=0,97,511,32,512&x_pmt=97&x_ci=1

**Comment by catalinii** [comment]
Yeah i think en50221 CIs need the pmt pid in order to decrypt the current channel.

**Comment by catalinii** [comment]
https://toda.ro/issues/6
