### ISSUE TITLE
Suggestion: Disable SSDP announcement

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#613]
Hi,

I want to run two instances of minisatip in the same machine. The second instance is for an special use, so I don't need to use the SAT>IP discovery announcement. To overcome the problem of used socket ports, we can start the second instance using a different RTSP, HTTP, UDP ports. That's easy.

However, the SSDP announcement is binded to the fixed address `239.255.255.250:1900`. So I suggest a _simple_ solution:

- When the option `-m` is set to `000000000000` (this MAC address is invalid) then DISABLE the binding of the UDP SSDP port.

You agree?

**Comment by catalinii** [comment]
I think is more straightforward if you just add another argument that disables listening on ssdp.
Using -m is not intuitive at all why ssdp should be disabled.

**Comment by 9000h** [comment]
the SO_REUSEADDR on udp bind should allow multiple instances already

**Comment by lars18th** [comment]
> the SO_REUSEADDR on udp bind should allow multiple instances already
> (the only exception is OSX where you have to use both SO_REUSEADDR and SO_REUSEPORT)

The idea is to DISABLE the announcement, not only to run multiple instances without troubles!

**Comment by lars18th** [comment]
> I think is more straightforward if you just add another argument that disables listening on ssdp.
> Using -m is not intuitive at all why ssdp should be disabled.

Done, https://github.com/catalinii/minisatip/pull/615 !
So, please merge it.

Regards.
