### ISSUE TITLE
CI tbs 6590

### ISSUE THREAD

**Issue by michaeladams123** [catalinii/minisatip#614]
hi,

kindly note that I have issue the channels scrambled 

[minisatip.log](https://github.com/catalinii/minisatip/files/3739042/minisatip.log)

**Comment by michaeladams123** [comment]
and how we can install dvben50221 library on ubuntu 14.0.4 i386?

**Comment by 9000h** [comment]
looks like the CA Module get not initialized right, most probably a driver issue

**Comment by 9000h** [comment]
apt install dvb-apps probably

**Comment by michaeladams123** [comment]
already installed

**Comment by Yuri666** [comment]
try to use -C option to disable CI+ mode.

**Comment by michaeladams123** [comment]
same issue

**Comment by Yuri666** [comment]
Guess you use astra as client. To working descrambling by CAM you need indicate specify pids what should be unscramble. But astra sets pids=all. In this case descrambling by CAM impossible.

**Comment by michaeladams123** [comment]
many thanks ,yes correct and after filter the PID the problem solved,thanks again for your kindly support :)

**Comment by 9000h** [comment]
@michaeladams123 can you please close then here

**Comment by michaeladams123** [comment]
many thanks
