### ISSUE TITLE
RFC: SAT>IP client mode and SRC= parameter with different orbital positions

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#619]
Hi,

I don't know how to configure minisatip using the satip client mode indicating that one server is for the sat position AA and another for the position AB. Any idea to describe that the tuner 1 is for source 1 and tuner 2 is for source 2? I don't request about _passing_ the `&src=` parameter, but to use the SAT>IP server 1 when `src=1` and the SAT>IP server 2 when `src=2`.

Any idea?
Thank you!

**Comment by lars18th** [comment]
Hi,

I implemented this partially: see PR #623 .

However, I need your help! I don't have time to implement the command-line configuration.
I suggest to add something like: `minisatip -0 0:1-4;1:1,3;2:4;3:3` that indicates: tuner 0 has all four sat positions, tuner 1 only pos 1 and 3, tuner 2 only pos 4, and tuner 3 only pos 3.

The code is running OK in my environment with the hardcoded lines at 
https://github.com/catalinii/minisatip/pull/623/files#diff-043ce3ca6350feed57b6c81d93d1f3f6R512

I request that someone will finish the command-line and merge it.
Regards.

**Comment by catalinii** [comment]
Source is per-tuner setting. Is not clear why would you want to do server A connects to server X tuner 1 src A and server B connects to server X tuner 1 src B.

If we are talking about ability to connect any tuner (0-X) to an INPUT (A, B), that is a different story.
There are currently 2 ways: enigma2 or axe implementation.

As @9000h  said, unicable resolves this issue much better and yes there is a room for better implementation there too.

**Comment by lars18th** [comment]
Hi @catalinii ,

> Source is per-tuner setting. Is not clear why would you want to do server A connects to server X tuner 1 src A and server B connects to server X tuner 1 src B.

It's quite simple: In the server X the tuner 1 is connected to a coax wire that have access to a sats A and B, using a Diseqc Switch (A-B). And the server Y is connected to _another_ coax wire that has only a tuner connected to a fixed antenna pointing to sat B.

So, the problem is this: With the current implementation _all_ tuners are connected to the same sat positions. And this is false with multiple wires.

> If we are talking about ability to connect any tuner (0-X) to an INPUT (A, B), that is a different story.
> There are currently 2 ways: enigma2 or axe implementation.

Yes. That's a different story. I don't want to target this, as it's out of scope in my case.

> As @9000h said, unicable resolves this issue much better and yes there is a room for better implementation there too.

Unicable is a very good protocol to target the problem of _one_ wire. But my suggestion is to target _multiple_ wires. In fact, you can continue to use Unicable over each wire. But we need a _global_ solution to identify sat position of a group of tuners that can or can't share the wire.

I hope you agree with the idea of improving the current implementation with "tuner groups using the SRC parameter for shared sat positions".

Regards.

**Comment by catalinii** [comment]
We can turn it in RFC and see how many people are interested in it.

**Comment by lars18th** [comment]
> We can turn it in RFC and see how many people are interested in it.

I hope other users comment about it.

At time, I'm using it to _merge_ two SAT>IP servers with different antennas pointing to different orbital positions (server 1 points to SRC=A and server 2 to SRC=B). And it works like a charm (now hardcoded only).

Regards.

**Comment by lars18th** [comment]
Hi to all,

I implemented a simple solution. You can check it with the PR #623 .
If you don't declare nothing, then all adapters will use all position.
However, if you use `-U` or `--sources` then you can restrict the adapters enabled for each source.
See the documention to use it!

Regards.

**Comment by lars18th** [comment]
Hi,

Regarding my last version of the patch listed in PR #736 , I recommend to users with _complex_ environments of tuners/antennas to check it. Some examples of useful use cases:
- `-U 0:1:2:3` : Four antennas with four wires and four tuners, each tuner only one antenna.
- `-U 0,1:0,1:2,3:2,3`: Four antennas with two wires, four tuners. Tuners 0 and 1 use diseqc A/B for antennas A+B, and tuners 2 and 3 use another pair of antennas C+D with a different disqc A/B.
- `-U 0,1,2,3:0,1,2,3:0,1,2,3:0,1,2,3:4,5,6,7:4,5,6,7:4,5,6,7:4,5,6,7`: Eight antennas and eight tuners, with two wires. The first group of four uses diseqc AA/AB/BA/BB over the wire 1, and the second group uses similar infrastructure over the second wire.
- `-U *:*:0,1,2,3:0,1,2,3:4,5,6,7:4,5,6,7`: Quite complex environment with 6 antennas. The first two with dual LNBs, and the rest with single LNBs. Using two 4x1 diseqc switches. Inputs AA and AB of the two switches uses the same antennas (using the dual LNBs). And the other inputs use the corresponding antennas with single LNBs.

Please, compile with this patch and test it in your environment. If all goes right then please post here. When we have sufficient feedback it will be possible to merge this patch.

Thank you!

**Comment by Jalle19** [comment]
AFAICT this has been implemented with -A
