### ISSUE TITLE
RTP-Info: sequence number issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#627]
looks like the seq= numbers not handled right as the RFC's for RTSP say it has to be 16bit modulo but seems to count up 
```
Oct 29 20:45:06 localhost minisatip[17385]: Date: Tue, Oct 29 19:45:06 2019 GMT
Oct 29 20:45:06 localhost minisatip[17385]: Session: 0846930886
Oct 29 20:45:06 localhost minisatip[17385]: CSeq: 50
Oct 29 20:45:06 localhost minisatip[17385]: Server: minisatip/1.0.2-f5f9ccc
Oct 29 20:45:06 localhost minisatip[17385]: RTP-Info: url=rtsp://192.168.178.129/stream=1;seq=528978;rtptime=4679875
Oct 29 20:45:06 localhost minisatip[17385]: Range: npt=0.000-
```
https://github.com/catalinii/minisatip/blob/773f3a52a8c6928f2d9f0ca15cb7dfa02c41895a/src/minisatip.c#L1250-L1252

for reference
https://github.com/catalinii/minisatip/issues/87#issue-56964516

**Comment by 9000h** [comment]
would it make sense for you to replace the getTick() with sid->seq

**Comment by catalinii** [comment]
Which RFC are you referring to?

**Comment by 9000h** [comment]
I may confuse seq= with the sequence in the rtp proto which is 16bit and this is right in minisatip

**Comment by 9000h** [comment]
so sid->seq is maybe right as it's also used for the rtp header and should the seq of the next rtp packet
https://tools.ietf.org/html/rfc2326
```
seq:
          Indicates the sequence number of the first packet of the
          stream. This allows clients to gracefully deal with packets
          when seeking. The client uses this value to differentiate
          packets that originated before the seek from packets that
          originated after the seek.
```
