### ISSUE TITLE
strange log

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#628]
```
Nov  1 15:59:05 localhost minisatip[18492]: [01/11 15:59:05.444 main]: satipc_http_request (ad 8): sending to sock 15:
Nov  1 15:59:05 localhost minisatip[18492]: OPTIONS rtsp://192.168.178.1:554/ RTSP/1.0
Nov  1 15:59:05 localhost minisatip[18492]: CSeq: 1
Nov  1 15:59:05 localhost minisatip[18492]: User-Agent: minisatip 1.0.2-f5f9ccc
Nov  1 15:59:05 localhost minisatip[18492]: #015
Nov  1 15:59:05 localhost minisatip[18492]: [01/11 15:59:05.445 main]: done opening adapter 8 delivery systems: dvbc undefined undefined undefined
No
```
where did the # 015 come from ?

**Comment by catalinii** [comment]
Can you do make clean && make 
and see if you have #015 in the gcc command line.

If no, is it reproducible ?

**Comment by 9000h** [comment]
hmm
https://minisatip.org/forum/search.php?author_id=51&sr=posts
maybe it's one of the log macros

**Comment by 9000h** [comment]
View logs for a container with a TTY enabled

If TTY is enabled on a container you may see [10B blob data] in the output when retrieving log messages. The reason for that is that \r is appended to the end of the line and journalctl doesn’t strip it automatically unless --all is set:

$ sudo journalctl -b CONTAINER_NAME=webserver --all

**Comment by 9000h** [comment]
as it is probably not minisatip I will close
