### ISSUE TITLE
warnings while compiling, CI mnodule dont work

### ISSUE THREAD

**Issue by Micha-123** [catalinii/minisatip#629]
hi, while compiling i have some warnings

ca.c: In function ‘check_ci_certificates’:
ca.c:1796:79: warning: ‘%s’ directive output may be truncated writing up to 127                                                                                                  bytes into a region of size 53 [-Wformat-truncation=]
       snprintf(ci_cert_file, sizeof(ci_cert_file) - 1, "/%s/ci_cert_%s_%d.der",                                                                                                  getenv("HOME"), ci_name_underscore, ci_number);
                                                                     ^~                                                                                                                           ~~~~~~~~~~~~~~~~~~

ca.c:1796:17: note: ‘snprintf’ output 17 or more bytes (assuming 144) into a des                                                                                                 tination of size 63
                 snprintf(ci_cert_file, sizeof(ci_cert_file) - 1, "/%s/ci_cert_%                                                                                                 s_%d.der", getenv("HOME"), ci_name_underscore, ci_number);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ci modules after kompile wont work (no picture ons scrambled channels

**Comment by catalinii** [comment]
Can you check now if you still have the compilation issues?

**Comment by Micha-123** [comment]
checked to kompile 

> minisatip.c: In function ‘ssdp_notify’:
minisatip.c:1521:25: warning: ‘%s’ directive writing up to 99 bytes into a region of size 93 [-Wformat-overflow=]
  sprintf(nt[1], "::uuid:%s", uuid);
                         ^~   ~~~~
minisatip.c:1521:2: note: ‘sprintf’ output between 8 and 107 bytes into a destination of size 100
  sprintf(nt[1], "::uuid:%s", uuid);


> ca.c: In function ‘check_ci_certificates’:
ca.c:1797:79: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size 117 [-Wformat-truncation=]
                 snprintf(ci_cert_file, sizeof(ci_cert_file) - 1, "/%s/ci_cert_%s_%d.der", getenv("HOME"), ci_name_underscore, ci_number);
                                                                               ^~                          ~~~~~~~~~~~~~~~~~~
ca.c:1797:17: note: ‘snprintf’ output 17 or more bytes (assuming 144) into a destination of size 127
                 snprintf(ci_cert_file, sizeof(ci_cert_file) - 1, "/%s/ci_cert_%s_%d.der", getenv("HOME"), ci_name_underscore, ci_number);
                 ^

**Comment by catalinii** [comment]
Can you tell me which OS/version are you using?

**Comment by Micha-123** [comment]
Im using raspbian,
pi@Domoticz:~/minisatip $ gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


niedz., 10 lis 2019, 05:14 użytkownik catalinii <notifications@github.com>
napisał:

**Comment by 9000h** [comment]
with the same gcc version on x86_64 I get
```
minisatip.c: In function ‘ssdp_notify’:
minisatip.c:1521:25: warning: ‘%s’ directive writing up to 99 bytes into a region of size 93 [-Wformat-overflow=]
  sprintf(nt[1], "::uuid:%s", uuid);
                         ^~   ~~~~
minisatip.c:1521:2: note: ‘sprintf’ output between 8 and 107 bytes into a destination of size 100
  sprintf(nt[1], "::uuid:%s", uuid);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ca.c: In function ‘check_ci_certificates’:
ca.c:1797:79: warning: ‘%s’ directive output may be truncated writing up to 127 bytes into a region of size 117 [-Wformat-truncation=]
                 snprintf(ci_cert_file, sizeof(ci_cert_file) - 1, "/%s/ci_cert_%s_%d.der", getenv("HOME"), ci_name_underscore, ci_number);
                                                                               ^~                          ~~~~~~~~~~~~~~~~~~
ca.c:1797:17: note: ‘snprintf’ output 17 or more bytes (assuming 144) into a destination of size 127
                 snprintf(ci_cert_file, sizeof(ci_cert_file) - 1, "/%s/ci_cert_%s_%d.der", getenv("HOME"), ci_name_underscore, ci_number);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Jalle19** [comment]
This is no longer an issue, @catalinii can you close?
