### ISSUE TITLE
dual delsys frontend issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#63]
if one frontend supports more the one delsys, then it's get counted in each delsys by the detection but cannot be used at the same time 

dvb-fe-tool -a 2
Device Sit2 DVB-T2/C (/dev/dvb/adapter2/frontend0) capabilities:
	CAN_2G_MODULATION CAN_FEC_1_2 CAN_FEC_2_3 CAN_FEC_3_4 CAN_FEC_5_6 CAN_FEC_7_8 CAN_FEC_AUTO CAN_GUARD_INTERVAL_AUTO CAN_HIERARCHY_AUTO CAN_INVERSION_AUTO CAN_MUTE_TS CAN_QAM_16 CAN_QAM_32 CAN_QAM_64 CAN_QAM_128 CAN_QAM_256 CAN_QAM_AUTO CAN_QPSK CAN_TRANSMISSION_MODE_AUTO 
DVB API Version 5.10, Current v5 delivery system: DVBC/ANNEX_A
Supported delivery systems: DVBT DVBT2 [DVBC/ANNEX_A]

**Comment by catalinii** [comment]
Yeah, I was thinking of this being far from perfect for few days, and I think what you just said gave me another perspective about how to implement this, keeping in mind I want multiple streams (or multiple clients) to share the same adapter.

**Comment by catalinii** [comment]
Probably I should bind dynamically the stream to the adapter at each tune, rather than just at the first tune.

**Comment by catalinii** [comment]
Let me know if this works.

Thanks

**Comment by catalinii** [comment]
Hi,

can you test this ?

Thanks

**Comment by 9000h** [comment]
I try to setup a vtuner with a device with dvb-c/dvb-t  for you, need to find a combiner for that.

**Comment by 9000h** [comment]
I did try with a HVR930C stick and had to set the frontend manually with dvb-fe-tool  -a3 -d dvbc/annex_c
to get DD-TV to find channels.

**Comment by 9000h** [comment]
I'm not able to combine the cable and terr signal here to verify so I will close it for now
