### ISSUE TITLE
OSCAM PID

### ISSUE THREAD

**Issue by engalaaodeh** [catalinii/minisatip#633]
Hi,

I am working with Minisatip and working very good and very stable,but I have a small issue for channels required Oscam and if filter the channels by PID will block the connectivity between channel and Oscam 
and please why if filter by PID for channel not connected to Oscam ?

**Comment by engalaaodeh** [comment]
[minisatip.log](https://github.com/catalinii/minisatip/files/3827027/minisatip.log)
adapter number 4 working without filter pid

**Comment by engalaaodeh** [comment]
and the frequency freq=11766&pol=v&sr=29900
i need to filter to channels named RAI 1  hd pids only and keep oscam working without blocking

**Comment by engalaaodeh** [comment]
PID for RAI 1 HD
3101,3012,3011,2012,2011,567,621,621,601,501,1101,0,3401

**Comment by engalaaodeh** [comment]
2019/11/09 10:02:26 25546F0 c ala2 (183D&000000/0000/0D49/91:5A8F05C3AF9DF8CBE267391CAA3D95CB): found (88 ms) by samba1

**Comment by catalinii** [comment]
Can you tell me when exactly the issue happens ? (HH:MM:SS)
I do not understand what is the exact problem, but please provide the output of:

./minisatip -f -l http,dvbapi

**Comment by engalaaodeh** [comment]
Hi,
may thanks for your kindly support, the main issue from PID and the problem solved

**Comment by 9000h** [comment]
@engalaaodeh  please close

**Comment by lars18th** [comment]
> @engalaaodeh please close

Yes, please!
