### ISSUE TITLE
possible protocol issue 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#634]
if I do some tests on an idle minisatip server
```
root@satip:/tmp# (echo 'OPTIONS RTSP/1.0'; echo 'Cseq: 1';echo 'Session: 3432424'; printf '\r\n\r\n';) | nc 192.168.178.129 554
RTSP/1.0 200 OK
Date: Mon, Nov 11 12:05:43 2019 GMT
CSeq: 1
Server: minisatip/1.0.2-70acd73
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN

^C
root@satip:/tmp# (echo 'DESCRIBE RTSP/1.0'; echo 'Cseq: 1';echo 'Accept: application/sdp'; printf '\r\n\r\n';) | nc 192.168.178.129 554
RTSP/1.0 404 Not Found
Date: Mon, Nov 11 12:06:11 2019 GMT
CSeq: 1
Server: minisatip/1.0.2-70acd73
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN

^C
root@satip:/tmp# (echo 'DESCRIBE RTSP/1.0'; echo 'Cseq: 1';echo 'Accept: application/sdp'; printf '\r\n\r\n';) | nc 192.168.178.129 554
RTSP/1.0 404 Not Found
Date: Mon, Nov 11 12:06:23 2019 GMT
CSeq: 1
Server: minisatip/1.0.2-70acd73
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN

^C
root@satip:/tmp# (echo 'PLAY rtsp://192.168.178.129/?stream=1 RTSP/1.0'; echo 'Cseq: 1';echo 'Session: 3432424'; printf '\r\n\r\n';) | nc 192.168.178.129 554
RTSP/1.0 454 Session Not Found
Date: Mon, Nov 11 12:06:29 2019 GMT
CSeq: 1
Server: minisatip/1.0.2-70acd73

^C
root@satip:/tmp# (echo 'DESCRIBE RTSP/1.0'; echo 'Cseq: 1';echo 'Accept: application/sdp'; printf '\r\n\r\n';) | nc 192.168.178.129 554
RTSP/1.0 200 OK
Date: Mon, Nov 11 12:06:31 2019 GMT
CSeq: 1
Server: minisatip/1.0.2-70acd73
Content-type: application/sdp
Content-Base: rtsp://192.168.178.129/
Content-Length: 215

v=0
o=- 0000000000 0000000000 IN IP4 192.168.178.129
s=SatIPServer:1 4,2,4
t=0 0
m=video 54296 RTP/AVP 33
c=IN IP4 0.0.0.0
a=control:stream=1
a=fmtp:33 ver=1.0;src=1;tuner=1,0,0,0,0,,,,,,,;pids=
a=inactive
```
the last answer looks like an issue  to me as there is and was no active stream=1 and a 404 should come back from minisatip

**Comment by 9000h** [comment]
also a wrong command should give back a 501, but the example below hangs
```
(echo 'PAUSE rtsp://192.168.178.129/?stream=1 RTSP/1.0'; echo 'Cseq: 1';echo 'Session: 3432424';echo 'Connection:close'; printf '\r\n\r\n';) | nc 192.168.178.129 554
```

**Comment by lars18th** [comment]
Hi @9000h ,

> the last answer looks like an issue to me as there is and was no active stream=1 and a 404 should come back from minisatip

I think so. Futhermore with the description of RTCP message is intuited an empty stream.

> also a wrong command should give back a 501, but the example below hangs
> 
> ```
> (echo 'PAUSE rtsp://192.168.178.129/?stream=1 RTSP/1.0'; echo 'Cseq: 1';echo 'Session: 3432424';echo 'Connection:close'; printf '\r\n\r\n';) | nc 192.168.178.129 554
> ```

In this case the `PAUSE` command violates the SAT>IP specification. But, as you commented in this case an error message is required in return.

So, I suggest to include the response of _any_ unknown message (error 501). And in case of any inconsistency (like the case of PLAY of an unkown stream) by default execute the same logic as for a `OPTIONS` message (that's a neutral response).

Regards.

**Comment by 9000h** [comment]
there is another case when:
(echo 'SETUP rtsp://192.168.178.129/?src=1&freq=12480&sr=27500&fec=34&pol=v&msys=dvbs&pids=0,108,3327,3328,8192 RTSP/1.0'; echo 'Cseq: 1'; printf '\r\n\r\n';) | nc 192.168.178.129 554

a 403 should come back as 8192 pid is out of range

**Comment by lars18th** [comment]
> a 403 should come back as 8192 pid is out of range
> the wrong pid is ignored an logged atm, but the spec says the server should reply with 403

Ummm... I'm not sure it's a good idea to return an error (403) if some pid number is out of range. I prefer to ignore it. However, if you prefer to enforce it, then it's possibe to do it.

Regards.

**Comment by catalinii** [comment]
Does the satip specifies what happens if you provide an unknown command (eg PAUSE) ?
Basically minisatip does not reply at all at that message (which is a simple fix)


According to the standard are some specific things we can do ?

**Comment by 9000h** [comment]
Theoretisch PAUSE example ist from the spec

**Comment by lars18th** [comment]
> Does the satip specifies what happens if you provide an unknown command (eg PAUSE) ?
> Basically minisatip does not reply at all at that message (which is a simple fix)
> 
> According to the standard are some specific things we can do ?

Hi @catalinii ,

The Standard defines a LOT of error codes. See the section 3.5.14 Status Code Definitions.

Regarding the special case of unkown command (eg PAUSE), the correct return value is 501-Not Implemented. From "3.5.14.2 Server Error Response Messages (5xx)": 
```
The server does not support the functionality required to fulfil the request.
Issuing a request that is not implemented (e.g. PAUSE).
```

Regards.

**Comment by 9000h** [comment]
it may has no prio, but would be nice to get closer to the spec

**Comment by catalinii** [comment]
Fixed PAUSE with 501
