### ISSUE TITLE
Buffer

### ISSUE THREAD

**Issue by michaeladams123** [catalinii/minisatip#637]
Hi,

kindly note that what is the best values can i used to solve CC error with astra please ?

-b --buffers X:Y : set the app adapter buffer to X Bytes (default: 72192) and set the kernel DVB buffer to Y Bytes (default: 5775360) - both multiple of 188

    eg: -b 18800:18988

-B X : set the app socket write buffer to X KB.

**Comment by lars18th** [comment]
Hi @michaeladams123 ,

At time I use a _VERY AGGRESIVE_ values: `minisatip -i 32 -H 1:5 -b 18048:5775360 -B 750`.
Adding also a `nice -n -20` I can run the ministatip server inside a slow server without troubles.

I hope it helps.

**Comment by michaeladams123** [comment]
many thanks I used the option minisatip -i 32 -H 1:5 -b 18048:5775360 -B 750 and working well
but when I tried to add -n -20 required to change the config file?
how please and why ?

**Comment by michaeladams123** [comment]
and do you have any tool to full scan dvb sat and download xml epg file ?

**Comment by lars18th** [comment]
> many thanks I used the option minisatip -i 32 -H 1:5 -b 18048:5775360 -B 750 and working well
> but when I tried to add -n -20 required to change the config file?
> how please and why ?

:laughing: 

The `nice -n -20` it's a command (nice tool) to assign initial value of CPU priority to a process. I recommend to read `man renice` and `man nice`. The full command will be:
`nice -n -20 minisatip -i 32 -H 1:5 -b 18048:5775360 -B 750`.
That's indicates to execute the `minisatip` with a +20 high priority.

Regards.

**Comment by michaeladams123** [comment]
mant thanks for your kindly support,the problem solved
