### ISSUE TITLE
emm issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#646]
found this one in the log

Nov 18 21:25:19 localhost minisatip[28344]: [18/11 21:25:19.735 AD0]: assemble_emm: data too large 2563
Nov 18 21:25:19 localhost minisatip[28344]: Message repeated 2 times

**Comment by catalinii** [comment]
Can you do provide a log with -v pmt ?

**Comment by 9000h** [comment]
````
Nov 17 20:43:42 localhost minisatip[22563]: [17/11 20:43:42.574 main]: dvbapi: ECM_INFO: key 0, SID = EF75, CAID = 1860 (nagra), PID = 7916 (1EEC), ProvID = 000000, ECM time = 325 ms, reader
 = HD03, from = local, protocol = mouse, hops = 0
Nov 17 20:43:42 localhost minisatip[22563]: [17/11 20:43:42.651 AD0]: assemble_emm: data too large 2563
````

**Comment by catalinii** [comment]
with -v pmt not with -l pmt 
There should be a dump of the EMM

**Comment by 9000h** [comment]
hmm, the I sent over was with
"-H5:50 -D5  -o 192.168.178.129:2000  -Y 4:dvbt2,5:dvbt2,6:dvbc2,7:dvbc2  -u 0:4-984[-48],1:5-1020[-23],2:6-1056[-88],3:7-1092[-204] -m 0040caa2c79d   -lhttp -v pmt"

**Comment by catalinii** [comment]
Try the latest commit

**Comment by 9000h** [comment]
Ok, will have a close look for it

**Comment by 9000h** [comment]
looks like it did happen on HD+ channels like RTL HD Astra 19.2E
```
Dec  9 20:02:50 localhost minisatip[29827]: [09/12 20:02:50.900 AD0]: assemble_emm: data too large 4027
Dec  9 20:06:48 localhost minisatip[29827]: [09/12 20:06:48.612 AD0]: assemble_emm: data too large 4027
Dec  9 20:10:46 localhost minisatip[29827]: [09/12 20:10:46.166 AD0]: assemble_emm: data too large 4027
```

**Comment by catalinii** [comment]
4220 ?

**Comment by 9000h** [comment]
hmm, with 4220
````
Dec 12 12:42:29 localhost minisatip[7038]: [12/12 12:42:29.678 AD0]: assemble_emm: data too large 4393
Dec 12 12:46:17 localhost minisatip[7038]: [12/12 12:46:17.000 AD0]: assemble_emm: data too large 4393
````

**Comment by catalinii** [comment]
BTW, can we look at the dump of the EMM ?

**Comment by 9000h** [comment]
-v pmt and did add a extra hexdump
````
                // f >1500
                if (f->len + 183 > FILTER_PACKET_SIZE)
                {
                        LOG("%s: data too large %d", __FUNCTION__, f->len + 184);
                hexdump("emm full: ", f->data + len - 188, 190);
                        f->len = 0;
                        return 0;
                }

````
[emm.txt](https://github.com/catalinii/minisatip/files/3960075/emm.txt)

**Comment by catalinii** [comment]
Hey, 

can you print the entire EMM ?
also can you do -v pmt ?

**Comment by 9000h** [comment]
can you suggest how, like
hexdump("emm full: ", f->data + len - 188, FILTER_PACKET_SIZE);

**Comment by catalinii** [comment]
yeah but add also -v pmt

**Comment by 9000h** [comment]
sent via gmail

**Comment by 9000h** [comment]
could you identify something unusual?

**Comment by 9000h** [comment]
did not happen with latest git
