### ISSUE TITLE
[question] vdr channel switch issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#650]
maybe it's not related to minisatip but are we sure about the handling of "pids=" that  issuing the "pids=" statement replaces any previously configured pids list (maybe not the explicit added  pid 0)

![69340573-19f77000-0c68-11ea-9479-f97682860ef6](https://user-images.githubusercontent.com/3009073/69485529-25ea5a00-0e41-11ea-94eb-454ca62c1ec6.png)
+
http://www.satip.info/sites/satip/files/resource/satip_specification_release_notes_version_1_2_2.txt
Section 3.5.11 added clarifying text: Issuing the "pids=" statement replaces any previously configured pids list

in ref to:
https://github.com/rofafor/vdr-plugin-satip/issues/58#issue-520576580

**Comment by catalinii** [comment]
This should be already the way it works. If you see any issues let me know.

**Comment by 9000h** [comment]
thanks
