### ISSUE TITLE
BUG satipc frontend never expires streams

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#655]
Hi @catalinii ,

This is related to #636, however it's a different problem: When a SAT>IP client doesn't sends the TEARDOWN to the minisatip process, and the frontend is a `satipc` tuner, then in this case the opened stream continues open _forever_. The target SAT>IP server continues receiving the keepalive OPTIONS command from minisatip.

So, I suspect that some expire whatdog in the `satipc` isn't working.
Please, can you review it?
Thank you!

**Comment by catalinii** [comment]
Can you reproduce and send me the logs ? Also indicate the time you stop the last channel.

**Comment by lars18th** [comment]
> Can you reproduce and send me the logs ? Also indicate the time you stop the last channel.

Hi @catalinii ,

Please reopen this issue, it is not resolved at all! As indicated in #636 the current _close_ process in the `satipc` module is incorrect. The TEARDOWN is _never_ sended _and_ as pointed in this issue the stream in the server continues open and no timeout closes it.

So, please check it. You can do it without any log, as you can reproduce it:
- Configure one minisatip server as a client of a SAT>IP server (it can be hardware or another minisatip).
- Use a client (RTP or HTTP) to receive any stream from minisatip.
- Enable your debug (tcpdump) for the RTSP stream between the minisatip and the SAT>IP server.
- Close (not channel change, so a true stop) the session from the client...

...And then you will see that the SAT>IP server doesn't receive the corresponding TEARDOWN command. Futhermore the session will continue opened until the SAT>IP _server_ will close it because his internal timeout. As the minisatip `satipc` never expires it.

I hope you'll want to fix this.
Regards.

**Comment by lars18th** [comment]
Hi @catalinii ,

This bug is quite annoying! When the client connected to the minisatip closes the session, the satipc module continues without closing the tuner in the target SAT>IP server. The bug is clear: _the TEARDOWN command is never sended to the SAT>IP server when the adapter is closed_.

Please, can you fix this problem?
Thank you!

**Comment by catalinii** [comment]
Lars, I tried to reproduce this issue:
printf 'PLAY rtsp://192.168.1.1:554/?src=1&fe=2&freq=11671&pol=h&msys=dvbs2&mtype=8psk&sr=23000&pids=0\r\nTransport: RTP/AVP/TCP;interleaved=0-1\r\n\r\n' | nc localhost 554

hit ctrl+c, but on my side I see the adapter is being closed.
Can you provide a repro ?

**Comment by lars18th** [comment]
Hi @catalinii ,

When the `minisatip` process is closed (using the "ctrl+c" key) the SAT>IP server is released.
However, the problem is when _running_.

Please, repeat your test in another way:
- In the server running the `minisatip` run this command: `tcpdump -i eth0 -A dst 192.168.1.1 and dst port 554`. Then you will be see the RTSP commands from any SAT>IP client.
- Check you real SAT>IP server (perhaps with the web UI).
- With some SAT>IP client, open a session, play a program, and exit from the client.

At the point that you see the `TEARDOWN` in the RTSP session from the client to the minisatip with the `tcpdump` tool, then check the status of the SAT>IP server. Is the tuner released, or the tuner continues open and sending the stream forever until some timeout expires in the server?

**Comment by catalinii** [comment]
There are 2 possibilities related to RTSP:
1) UDP -> according to the specs the server closes the connection after timeout
2) TCP -> connection is closed right away

If a client is connected to minisatip which is connected to another satip server then minisatip will keep the connection an additional 30 seconds (configurable value)

You mentioned that minisatip keeps the connection open forever.  How do you reproduce this scenario ?

**Comment by lars18th** [comment]
> 1. UDP -> according to the specs the server closes the connection after timeout

SORRY? The client has sended a TEARDOWN command. This implies to close the session, so the _remote_ tuner requires to be closed. What I'm missing?

**Comment by lars18th** [comment]
Please @catalinii , see the image "RTSP State machine" at the page 41 in section 3.5.9 of http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf

The state PLAYING goes to INI state when Timeout *or* TEARDOWN event are triggered.

So, when a client closes a session, the tuner is released. As a consequence the satipc module requires to close his session if no more clients are using it. What I'm missing?

**Comment by catalinii** [comment]
> So, when a client closes a session, the tuner is released. As a consequence the satipc module requires to close his session if no more clients are using it. What I'm missing?
For UDP this is not correct as you can manipulate the same stream from multiple TCP connections (in RTSP UDP mode). Of course the standad does not discusses RTSP over TCP:

'An RTSP session generally spans multiple TCP connections (e.g. one TCP connection per
request-response). It is however also possible for an RTSP session to consist of a single TCP connection
(persistent mode) including several RTSP request-response pairs'

**Comment by lars18th** [comment]
Hi @catalinii ,

Perhaps what I'm missing is your understanding about the SAT>IP protocol. So, please try to re-think about this:

- The problem is when the session from the client receives a TEARDOWN command. In this case, if no other client is sharing the same tuner, the specification mandates to change to the INI state.

I feel that your understanding is to maintain the tuner (the remote SAT>IP server) opened for future use. However, this is IMHO a wrong behaviour. Although the specification doesn't indicate how the internal tuner should work, it's obvious that in the INI state the tuner is off. As a consequence, _any_ final TEARDOWN from a client implies a TEARDOWN in the satipc module. And this is not true at time.

Please, can you explain why this is not the current behaviour?
Thank you for taking the time to answer our questions.
Regards.

**Comment by lars18th** [comment]
> 'An RTSP session generally spans multiple TCP connections (e.g. one TCP connection per
> request-response). It is however also possible for an RTSP session to consist of a single TCP connection
> (persistent mode) including several RTSP request-response pairs'

In case you think that I'm speaking when a client _closes the TCP socket of an RTSP session_ this is **not** case. The issue is when the client sends the TEARDOWN command.

**Comment by lars18th** [comment]
Hi @catalinii ,

Sorry! I think this problem is related to my environment. After inserting this line
`ad->restart_needed = 1;`
inside the function `int satipc_reply(sockets *s)` the problem has gone.

I'm thinking on provide some more tweaking SAT>IP server parameters to adjust some particular bahaviours of dummy SAT>IP servers. What do you think?

Regards.

**Comment by catalinii** [comment]
I am not sure this is the right thing to do. This will close the rtsp stream every time and have one PLAY/connection which will be really bad for high latency links.

**Comment by catalinii** [comment]
I think we can focus on the actual issue that happens here, probably sending a TEARDOWN after the adapter is closed. 
Of course, -Z can be used for that.

**Comment by lars18th** [comment]
Hi @catalinii ,

OK, I'll try then to overcome the problem with a flag similar to `restart_needed` that will trigger the TEARDOWN. In my environment I feel this will fix the problem.

Thank you for the tip!

**Comment by lars18th** [comment]
Hi @catalinii ,

Based on your comments I created the PR #728 to fix this problem.
Please, check it!

**Comment by catalinii** [comment]
@lars18th, does -Z 1 works for you ?

**Comment by lars18th** [comment]
Hi,

> @lars18th, does -Z 1 works for you ?

I not tested it (I'll do it). However, I can't understand why a parameter related to Diseqc and LNBs can solve problems with the SAT>IP _protocol_ using a remote SAT>IP server. Please, can you explain the relation between this parameter and the satipc module?

And please test my patch #728. It really works!
Regards.

**Comment by catalinii** [comment]
Try it, -Z sets the adapter timeout to small values.

**Comment by lars18th** [comment]
I close it as it's now resolved.
