### ISSUE TITLE
Improve RTP-Info: Correct SEQ value

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#658]
Hi @catalinii ,

After reading a lot I discovered that @9000h has pointed a defect in the current implementation. Check the issue #627 .

The SAT>IP specification doesn't describe the RTP-Info. But this is because it's part of the standard RTSP protocol. So I checked it at: https://tools.ietf.org/html/rfc2326#page-55

Then in "12.33 RTP-Info" it's described the `seq:` value. And we can understand that it's the RTP _sequence_ number. So the current code is wrong using a clock timer sequence.

Futhermore, I discovered the utility of this value. Check this use case:
- A SAT>IP _client_ opens a session with a SETUP command.
- The SAT>IP _server_ opens the RTP/RTCP sockets and sends the stream.
- The _client_ requests another frequency over the same stream...
- ...and the _server_ then using the **same** stream (aka the same RTP/RTCP flow) injects the new stream.

So, in this case, how the client detects the change of the channel? Think that the decoder can or cannot know the change, so it can continue decoding. So, in the worst case the same pids can be corresponding to the old frequency. To overcome the problem the SAT>IP client needs to control the decoder and reinitialize (reset) the decoder when a channel change is detected.

However, when using a TELEVISION the channel change can be different. The controller can request a new RTSP, and how many time is pased between the request and the change? You don't know! The RTP continues until the _server_ changes it... The client can use the RTCP info to detect the change (in the `frequency` section of the "a=fmtp:33" attribute). But the resolution is then around 1 second (depending on the server). So in this case, the `RTP-Info` helps. The server is indicating in this case the _exact_ RTP sequence number where the change will appear. So the client can use this point to reset the decoder. Interesting, right?

I see this problem with my new Panasonic TV. When zapping I see sometimes that the image of the old channel appears after the black for a fraction, then the new channel starts to be played. I'm not sure if the Panasonic SAT>IP client checks or not this value. However, I feel is good to implement it.

You agree?

**Comment by 9000h** [comment]
did create a PR for it and it seems to be ok so far

**Comment by lars18th** [comment]
Hi @lars18th & @catalinii ,

Check https://github.com/catalinii/minisatip/pull/662#issuecomment-560484525

**Comment by lars18th** [comment]
Hi,

I close this issue as the commit https://github.com/catalinii/minisatip/commit/e9535a6ba276f80e9f6664b93c839891db8a12d4 fixes the pending warning.

Thank you all! :wink:
