### ISSUE TITLE
Error on Crosscompile

### ISSUE THREAD

**Issue by googles10000** [catalinii/minisatip#66]
I get an error on cross Compiling with 
arm-none-linux-gnueabi-gcc (CodeSourcery Sourcery G++ Lite 2007q3-51) 4.2.1

minisatip.c:869: error: storage size of 'sb' isn't known

I have modified the Makefile like this to Compile:

CC=arm-none-linux-gnueabi-gcc
CFLAGS= -ggdb -fPIC
LDFLAGS=-lpthread -lrt
INC=-I/home/freetz/cross-qnap/arm-none-linux-gnueabi/include
minisatip: minisatip.o socketworks.o stream.o dvb.o adapter.o
        $(CC) $(CFLAGS) $(INC) -o minisatip minisatip.o socketworks.o stream.o dvb.o adapter.o $(LDFLAGS)
minisatip.o: minisatip.c minisatip.h socketworks.h stream.h
        $(CC) $(CFLAGS) $(INC) -c -o minisatip.o minisatip.c

socketworks.o: socketworks.c minisatip.h socketworks.h
        $(CC) $(CFLAGS) $(INC) -c -o socketworks.o socketworks.c

stream.o: stream.c minisatip.h socketworks.h stream.h
        $(CC) $(CFLAGS) $(INC) -c -o stream.o stream.c

dvb.o: dvb.c dvb.h
        $(CC) $(CFLAGS) $(INC) -c -o dvb.o dvb.c

adapter.o: adapter.c adapter.h
        $(CC) $(CFLAGS) $(INC) -c -o adapter.o adapter.c

all: minisatip

clean:
        rm *.o minisatip

without the additional Include Path I get DVB API Versioncheck error.

Is there a simple way to Crosscompile this Programm without modified Makefile.

OT: Are you active in an Forum to discuss about this programm?

**Comment by googles10000** [comment]
I have found it.
in minisatip.c
#include <sys/stat.h>
is missing can you add it?
and would be nice to extend the Makefile for easy crosscompiler usage.

**Comment by catalinii** [comment]
Fixed

Thanks
