### ISSUE TITLE
[RFE] missing IP6 for IPv6 in describe

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#661]
https://github.com/catalinii/minisatip/blob/20c5652337e80028510131509c414dbc73f5ff32/src/stream.c#L89
...
should be also adjusted with AF_INET ? "IP4" : "IP6"
the ssdp IPv6 (ff02::c and ff05::c) is also to be done
btw only IPv4 multicast shall have a TTL

**Comment by lars18th** [comment]
Just to comment it: The SAT>IP specification doesn't support IPv6.

So, I'm not sure if IPv6 support in minisatip has sense.
Please, take this only as a constructive comment. I agree with all enhancements, but I'm not sure about the effort involved in add such support.

**Comment by 9000h** [comment]
the DD octopus NET did have it also :-)

**Comment by lars18th** [comment]
> the DD octopus NET did have it also :-)

Yes. But think, for example, that IPv6 support implies to handle with MLD instead of IGMP. I'm not sure about the cost of such enhancement.

But anyway, if you want to implement it... then I'm not against it. :wink:

**Comment by catalinii** [comment]
@lars18th totally agree is not specified by either RTSP/1.0 spec nor satip.

But ipv6 is more widely spread as before and as minisatip can act as http/rtsp standalone server I was thinking there is no harm.

I also wanted to keep even the ipv6 mode compatible with ipv4 clients by converting ipv4 in ipv6 addresses to ipv6.

When It comes to ssdp, not sure if it worths but if someone is open to implement it, I am willing to accept.

I will change the IP4 / IP6 text accordingly.

**Comment by lars18th** [comment]
> But ipv6 is more widely spread as before and as minisatip can act as http/rtsp standalone server I was thinking there is no harm.

Ok then. No problem!

> When It comes to ssdp, not sure if it worths but if someone is open to implement it, I am willing to accept.

Regarding SSDP messges using IPv6 please read this:
https://stackoverflow.com/questions/54802371/upnp-ssdp-discovery-with-ipv6

I hope it helps!
