### ISSUE TITLE
possible issue with pids

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#667]
https://github.com/catalinii/minisatip/blob/3a6d9f3cf58d2dc228a71273386d624ba6307185/src/adapter.c#L1031

cppcheck says
if (sid == -1) // delete all sids and the pid<--- Condition 'sid==-1' is always true

could be in reference to
https://github.com/catalinii/minisatip/issues/502#issuecomment-561572274

**Comment by lars18th** [comment]
Hi @9000h ,

> cppcheck says
> if (sid == -1) // delete all sids and the pid<--- Condition 'sid==-1' is always true

In your log I see `sid == -1` (a lot), but also `sid == 0` and `sid == 1`. So this seems to be false.
Futhermore, what I see in all prints of you log is that `pids == NULL` in the log message from `mark_pids_deleted()`.

**Comment by 9000h** [comment]
it may comes fom int vs unsigned int
````
#include <stdio.h>
int main()
{
int i= -1;
unsigned int j=-1;
if(i>j)
printf("greater i\n");
else
printf("greater j\n");
if (i == -1)
printf("i == -1\n");

return 0;
}
cc x.c -o x
./x
greater j
i == -1
````
could be a pitfall

**Comment by lars18th** [comment]
> could be a pitfall

It could be, be the definition of `sid` in the `sockets` structure is `int`:
https://github.com/catalinii/minisatip/blob/20c5652337e80028510131509c414dbc73f5ff32/src/socketworks.h#L36

So I don't see any part of the code that uses an unsignedint for sid.

**Comment by lars18th** [comment]
And please, fix your code:

> ```
> #include <stdio.h>
> int main()
> {
> int i= -1;
> unsigned int j=-1;
> if(i>j)
> printf("greater i\n");
> if(j>i)
> printf("greater j\n");
> if(j==i)
> printf("equals\n");
> if (i == -1)
> printf("i == -1\n");
> if (j == -1)
> printf("j == -1\n");
> 
> return 0;
> }
> ```

**Comment by 9000h** [comment]
anyway the cppcheck is probably a false positive and cata is right :-)
