### ISSUE TITLE
apids issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#671]
https://github.com/catalinii/minisatip/blob/403380412937d110f4cecdd46a91e126d1aac99c/src/adapter.c#L1251-L1258
if the ad->tp.apids is already true did the pobe ? makes any sense afterwards?

**Comment by 9000h** [comment]
any comments?

**Comment by catalinii** [comment]
I think this happens in the stream code, if you do addpids=... ad->tp.apids will be set. Otherwise add the pids from pids=... (if that is set).
