### ISSUE TITLE
Potential MAX_CW_TIME issue?

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#673]
Hi @catalinii ,

I do this simple test: change the `MAX_CW_TIME` to some small value (between 10-12 seconds).

The _expected_ behaviour with this change is (as far as I know) to repeat the ECM request, right? However, with this change the play of a service starts well, and after the key changes the image freezes. But then the `minisatip` logs every 1-2 seconds a message sending the ECM (with `minisatip -l pmt`). However, in the log of the Oscam the request is not received.

It's possible that some bug exists when the `pmt->cw->expiry` is reached?
Please, try to reproduce this issue in your environment changing the `MAX_CW_TIME` value.

Regards.

**Comment by catalinii** [comment]
Hey,

MAX_CW_TIME is used to expire the CWs that are received. Changing that may affect how the the expiry is handled which is different by provider.

You can do a tcpdump on port 9000 or whatever port you are using. Generally if send_ecm is called oscam should receive the packet. Check using tcpdump if the packet is received.

Thanks

**Comment by catalinii** [comment]
@lars18th I am closing this issue, please reopen if you have additional comments
