### ISSUE TITLE
Support Forum?

### ISSUE THREAD

**Issue by vdrtuxnet** [catalinii/minisatip#68]
Catalini,

how would you think about a support forum?

I think the github issue tracker is not the right place to discus certain things, the issue tracker should just stay as it is.

Minisatip is the one and only full customisable Sat>IP server available at the moment, and a support forum is am must have in my opinion, all the credit belongs to you and 9000h.

Without talking back to 3PO, I think he would be happy to host a support forum for a certain time.

Its just on you to say Yes or No.

**Comment by catalinii** [comment]
Hi,

I think it is a very good idea and I was thinking as well to host both the discussions and the issues as well.

I will try to setup something tomorow or the next day and will let you know the link.

Thanks

**Comment by catalinii** [comment]
Hi,

I have just created a new site for the project:

https://toda.ro
