### ISSUE TITLE
inside DESCRIBE  setup_stream ?

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#680]
https://github.com/catalinii/minisatip/blob/0f8418ff2e6753b9d2e7715a94d2035e3ca45a28/src/stream.c#L80-L81
is there really any need for this, and if yes we should refuse query's like
DESCRIBE rtsp://192.168.178.138/?stream=x
````
--- stream.c    2019-12-18 07:06:45.531910928 +0100
+++ stream.c.new        2019-12-18 07:30:28.143482547 +0100
@@ -77,7 +77,7 @@
        int do_all = 1;
        int is_ipv6 = 0;

-       if (s->sid == -1 && strchr(req, '?'))
+       if (s->sid == -1 && strchr(req, '?') && !strstr(req, "?stream="))
                setup_stream(req, s);

        sidf = get_session_id(s->sid);
````

**Comment by catalinii** [comment]
Where does those queries appear from ?

**Comment by 9000h** [comment]
I have not see any client doing this, but did overcome the wrong behavior by some tests.
