### ISSUE TITLE
Configure problem

### ISSUE THREAD

**Issue by gentlel** [catalinii/minisatip#684]
Hello,

I have a raspberry pi with the latest raspbian image.
When I try to ./configure I get this output:

configure:  == Checking OpenSSL == 
checking openssl/aes.h usability... no
checking openssl/aes.h presence... no
checking for openssl/aes.h... no

Linux DVB:                                enabled
Common Interface (needs DVBEN50221):      disabled
OpenSSL (AES as part of DVBAPI):          disabled
Embedded system:                          disabled
DVBCSA (needs libdvbcsa):                 enabled
Netceiver support:                        disabled
SatIP Client:                             enabled
Static:                                   disabled
dvbapi:                                   enabled
axe:                                      disabled
enigma:                                   disabled

openssl is installed properly and is working.

When I try to compile the programm I get following output:

pi@raspberrypi:~/minisatip-master $ sudo make
make -C src
make[1]: Entering directory '/home/pi/minisatip-master/src'
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c minisatip.c -o ../build/minisatip.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c socketworks.c -o ../build/socketworks.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c stream.c -o ../build/stream.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c adapter.c -o ../build/adapter.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c utils.c -o ../build/utils.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c csa.c -o ../build/csa.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c dvbapi.c -o ../build/dvbapi.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c pmt.c -o ../build/pmt.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c tables.c -o ../build/tables.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c satipc.c -o ../build/satipc.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c dvb.c -o ../build/dvb.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DDISABLE_DVBAES -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -o ../minisatip  ../build/minisatip.o  ../build/socketworks.o  ../build/stream.o  ../build/adapter.o  ../build/utils.o  ../build/csa.o  ../build/dvbapi.o  ../build/pmt.o  ../build/tables.o  ../build/satipc.o  ../build/dvb.o -lpthread -lrt -ldvbcsa 
make[1]: Leaving directory '/home/pi/minisatip-master/src'

Can somebody help me?

**Comment by 9000h** [comment]
you need to install libssl-dev

**Comment by gentlel** [comment]
thanks !!! works... sorry for my dumb question

**Comment by 9000h** [comment]
your welcome, but please close
