### ISSUE TITLE
APP Packet String Payload Format issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#691]
can you remember why the order of the params for ver=1.0 is as it is an not as it should be?
https://github.com/catalinii/minisatip/blob/d246dba7ac93a685ad26d2567d4bf7fe69ae0f57/src/adapter.c#L1371-L1376
```
ver=<major>.<minor>;src=<srcID>;tuner=<feID>,<level>,<lock>,<quality>,<frequency>,<polarisation>,
<system>,<type>,<pilots>,<roll_off>,<symbol_rate>,<fec_inner>;pids=<pid0>,...,<pidn>
should look like:
ver=1.0;src=1;tuner=1,240,1,7,12402,v,dvbs,,,,27500,34;pids=0,16,56,112,168,1709
```
maybe it was from here:
https://github.com/catalinii/minisatip/issues/15#issuecomment-70304379

**Comment by catalinii** [comment]
I do not think there is a good reason

**Comment by 9000h** [comment]
PR created
