### ISSUE TITLE
missing DTV_ENUM_DELSYS in dvb headers

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#7]
maybe it's a good idea to add some comments regarding Kernel and DVBAPIVERSION to build on.

and may catch this also in the code like:

#define DVBAPIVERSION (DVB_API_VERSION << 8 | DVB_API_VERSION_MINOR)
#if DVBAPIVERSION < 0x0500
#error minisatip requires Linux DVB driver API version 5.0 or higher!
#endif

#if DVBAPIVERSION < 0x0505
#define DTV_ENUM_DELSYS 44
#endif

**Comment by catalinii** [comment]
Done in the latest commit.
