### ISSUE TITLE
pids=all  issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#70]
if (tp->pids && strncmp (tp->pids, "all", 3) == 0)
        {
                strcpy (def_pids, default_pids);

is probably also not right as it sets only the defined ones

**Comment by catalinii** [comment]
Yes this was the point, in order to avoid the entire dvb stream to be sent over the network, however to keep the apps that are using pids=all working (tvheadend was working with this workaround).

**Comment by catalinii** [comment]
Do you have an example where this is not working out ?
I would hate to open all the streams and flood the local network.

**Comment by 9000h** [comment]
the pids=all is working with the Digibit R1 here and gives you the complete TS, you can access then via VLC  the TS
in the VLC menu there is a point called program list or so from there you can chose a channel from the TS

the mode can be enabled by setting only one special pid 8192 and may not work if the driver or card did not support it right

**Comment by 9000h** [comment]
I did test this by setting pid 8192 in case of pids=all and allow the 8192 in dvb.c, it works the same then as on my digbit r1
so I suggest to get this in to be as close as possible to the SES spec

**Comment by catalinii** [comment]
I am still thinking how to make this....

**Comment by 9000h** [comment]
in principal it's nothing else than

if (tp->pids && strncmp (tp->pids, "all", 3) == 0)
    {
            strcpy (def_pids, "8192");

and allow the the 8192 in dvb.c as we do have the check for bigger than 8191

**Comment by catalinii** [comment]
:)

Not really.

Think about 2, 3 clients, one with pids all, one without.
And possibilities :)

**Comment by 9000h** [comment]
not all Sat>Ip Server Support pids=all Parameter
the Triax tss 400 is one of that

"TS Recorder" and VLC are clients that can use this mode probably others, so I believe we should support it or not and nothing in between.

The spec is not specific how to implement this for both server and client

**Comment by catalinii** [comment]
Well i meant on minisatip side. That u need to look at all the packets afnd choose based on pid. But my thoughts are on the manipulation of internal tables.

**Comment by 9000h** [comment]
look good after a quick test
