### ISSUE TITLE
Error after the last pull

### ISSUE THREAD

**Issue by haarm** [catalinii/minisatip#700]
After the last update I have this here 
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.2-4682fb5\" -DDISABLE_DVBCSA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c adapter.c -o ../build/adapter.o
adapter.c: In function ‘signal_thread’:
adapter.c:2103:16: error: ‘SMutex {aka struct struct_mutex}’ has no member named ‘mutex_state’
   if (ad->mutex.mutex_state != 0)
                ^
make[1]: *** [Makefile:156: ../build/adapter.o] Fehler 1
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[1]: Verzeichnis „/opt/hhh/minisatip/src“ wird verlassen
make: *** [Makefile:11: minisatip] Fehler 2

**Comment by 9000h** [comment]
you have to correct it by hand like
https://github.com/catalinii/minisatip/commit/4682fb515c1b9b3bbff74f52d7c46a9069cc5989
or wait for @catalinii

**Comment by catalinii** [comment]
I just fixed it. Thanks for reporting.
