### ISSUE TITLE
unused code clarification

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#701]
should the ad-fe check not locking for -1 only?
https://github.com/catalinii/minisatip/blob/72bc27e0cf4fd9bd6aa3652faf63329645da3b73/src/adapter.c#L2097

the function returns only 0 under all conditions
https://github.com/catalinii/minisatip/blob/72bc27e0cf4fd9bd6aa3652faf63329645da3b73/src/adapter.c#L846
but used in checks where a positive value where checked like, but this makes no sense
https://github.com/catalinii/minisatip/blob/72bc27e0cf4fd9bd6aa3652faf63329645da3b73/src/adapter.c#L978
https://github.com/catalinii/minisatip/blob/72bc27e0cf4fd9bd6aa3652faf63329645da3b73/src/adapter.c#L992
https://github.com/catalinii/minisatip/blob/72bc27e0cf4fd9bd6aa3652faf63329645da3b73/src/adapter.c#L1227

**Comment by catalinii** [comment]
>should the ad-fe check not locking for -1 only?
yes


About update_pids you are right, the code never gets executed. In case update pids will change to return non zero value the code could become handy.

**Comment by 9000h** [comment]
do you plan to change it this way?

**Comment by 9000h** [comment]
I did change the topic for the issue as the tune issue is may come from VDR/plugin.

**Comment by 9000h** [comment]
@catalinii will you clean up the code so that there is no dead code or change update_pids to return 1 one on success and -1 or 0 if it fails?

**Comment by catalinii** [comment]
I will change it to return != 0 on failure.
