### ISSUE TITLE
Characters not displayed correctly in webinterface

### ISSUE THREAD

**Issue by bccrew** [catalinii/minisatip#702]
Belgian Channel "één HD" is not displayed correctly in the webinterface. Is it possible to support the display of these characters please?

![image](https://user-images.githubusercontent.com/8138958/73608290-87f1d900-45c1-11ea-98c5-28cc0cbedf5a.png)

**Comment by lars18th** [comment]
I see this too!

**Comment by bccrew** [comment]
Does it have something to do with charset in css file?

**Comment by lars18th** [comment]
> Does it have something to do with charset in css file?

I don't know it. However, if someone knows how to fix it, them it will be interesting.

**Comment by Jalle19** [comment]
Closing in favor of the previously reported https://github.com/catalinii/minisatip/issues/398
