### ISSUE TITLE
Time counters: signed or unsigned?

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#703]
Hi,

I don't have any particular problem with this commit: https://github.com/catalinii/minisatip/commit/7f1987f07ae880cd34e465101687de9c6d2262af (from this PR #696).

However, I'm doing some enhancemet to the `satipc` module, and I need to use timestamps (`getTickUs()`). So I feel that the correct values for monotonic clocks are unsigned. Any comment to assert the current code is correct?

Regards.

**Comment by 9000h** [comment]
it comes from here:
https://github.com/catalinii/minisatip/commit/a989fe0b5ec7edbde48e913bea843ccf49637e0d

**Comment by lars18th** [comment]
OK. Thank you. I understand to use the same type for all clock timers.
Futhermore, even it's true that _valid_ values for `timespec` are _positive_ only, the used types for `tv_sec` and `tv_nsec` are _signed_. Check it here: https://en.cppreference.com/w/c/chrono/timespec

So, the current code is correct. I close the issue.
Thank you!
