### ISSUE TITLE
incorrect SNR and STR State transmit

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#71]
Hi,

it seems, that minisatip does not transmit the correct Values for SNR and STR.

This is the issue from femon on the minisatip Server:

>server02 ~ # femon -a0 -H -c1
>FE: STV090x Multistandard (DVBS)
>status SCVYL | signal  78% | snr  78% | ber 0 | unc 0 | FE_HAS_LOCK
>server02 ~ #

And this is the issue from the VDR:

![150126_162617](https://cloud.githubusercontent.com/assets/945108/5902131/6b4268c2-a578-11e4-8e0b-9bbe0098600f.jpg)

**Comment by 9000h** [comment]
It's a know  issue atm

**Comment by 9000h** [comment]
there are also a new dvb api for that, where the values changed from db to %, it's low prio I believe

**Comment by catalinii** [comment]
9000h can you please let me know which api are you refering exactly ?

Thanks

**Comment by 9000h** [comment]
we need to investigate this a bit deeper, but if you look at tvheadend they make some use of them
https://github.com/tvheadend/tvheadend/blob/dcdef424fc5296b8083b4c7f00544a300916d30f/src/input/mpegts/linuxdvb/linuxdvb_frontend.c#L745

**Comment by catalinii** [comment]
Thanks 9000h for pointing this out, will add this :)

**Comment by catalinii** [comment]
Hi, I added initial support for this.

can someone test ?

**Comment by 3PO** [comment]
Does'nt work with VDR.
Now i get no issueses about SNR/STR anymore.


![150130_083539](https://cloud.githubusercontent.com/assets/945108/5972516/443c282c-a85b-11e4-8306-5f1d75a4098a.jpg)

**Comment by catalinii** [comment]
I have no dvb v5,10 kernel so i could not test. Now i revert to the old way if sttrength is 0 woth the new api

**Comment by catalinii** [comment]
I will have to make some time to test this, as the new api does not return anything usefull.

**Comment by catalinii** [comment]
My 3.13 kernel does not return anything on those APIs...if someone have he that returns something on new api and can provide feedback on this I would be grateful.

Thanks

**Comment by 9000h** [comment]
the signal reporting for vdr is here also broken with today's 17.02 git

**Comment by 9000h** [comment]
I did play around a bit yesterday and it looks like the issue is in describe_adapter where dad is cleared and then not filled with the signal values afterwards

**Comment by catalinii** [comment]
Can u provide me the logs with  -l five times?

Thanks

**Comment by 9000h** [comment]
the signal report is back in vdr and also for the Alignment app

**Comment by 3PO** [comment]
It seems, the STR/SNR issue ist not workink correct:

minisatip Server:

>server02 ~ # femon -H -a0 -c1
>FE: STV090x Multistandard (DVBS)
>status SCVYL | signal  83% | snr  80% | ber 0 | unc 0 | FE_HAS_LOCK
>server02 ~ #

VDR satip Plugin:

>vdr01_64 ~ # svdrpsend plug satip INFO
>220 vdr01_64 SVDRP VideoDiskRecorder 2.2.0; Sun Mar  8 11:37:20 2015; UTF-8
>900-SAT>IP device: 0
>900-CardIndex: 7
>900-Stream: rtsp://192.168.177.11/?freq=11914&src=1&sr=27500&pol=h&fec=910&mtype=qpsk&ro=0.35&msys=dvbs2 [stream=1]
>900-Signal: lock=1 strength=98 quality=93 frontend=0
>900-Stream bitrate: 14440 kbit/s
>900-Buffer bitrate: 14440 kbit/s
>900-Buffer usage: 416/8192 kbit (5,1%)
>900-Channel: Nat Geo Wild HD,NGWildHD;SKY:11914:HC910M2O35P0S1:S19.2E:27500:511=27:0;515=deu@106,516=eng@106:32:1833,9C4,9AF,98C:118:133:6:0
>900-Active pids:
>900-Pid 0:  511 (10928 kbit/s)
>900-Pid 1:   18 (1032 kbit/s)
>900-Pid 2: 4104 ( 968 kbit/s)
>900-Pid 3:  516 ( 368 kbit/s)
>900-Pid 4:  515 ( 368 kbit/s)
>900-Pid 5:   32 ( 136 kbit/s)
>900-Pid 6:    1 (   8 kbit/s)
>900-Pid 7:    0 (   8 kbit/s)
>900-Pid 8: 6296 (   0 kbit/s)
>900-Pid 9:   99 (   0 kbit/s)
>900-Active section filters:
>900-Filter 0: 376563 ( 880 kbit/s) Pid=0x12 (EIT)
>900-Filter 1: 1168 (   0 kbit/s) Pid=0x14 (TDT)
>900-Filter 2: 17988 (   0 kbit/s) Pid=0x00 (PAT)
>900-Filter 3: 4493 (   0 kbit/s) Pid=0x11 (SDT)
>900-Filter 4:  719 (   0 kbit/s) Pid=0x10 (NIT)
>900 Filter 5:    0 (   0 kbit/s) Pid=0x61 (---)
>221 vdr01_64 closing connection
>vdr01_64 ~ #

 
I dont know, if this is a Problem of minisatip or the VDR satip Plugin?

**Comment by catalinii** [comment]
For now what we do is get the max of signal and snr based on tuned frequencies and calculate the signal and snr based relative to max.

The reason for this is that not all the cards are reporting max as 65535.
I implemented the new api but did not get any feedback yet.

**Comment by 3PO** [comment]
>I implemented the new api but did not get any feedback yet.

OK, here some Feedback. :)

In the minisatip log i can find something like this:

>[14/03 15:14:55.20001352]: get_signal took 352 ms for adapter 0 handle 7 (status: 31, ber: 0, strength:55049, snr: 41465, max_strength: 55704, max_snr: 52940 0)

If check at the same time with femon, i get this issue:

>server02 ~ # femon -a0 -c1
>FE: STV090x Multistandard (DVBS)
>status SCVYL | signal d47a | snr c60b | ber 00000000 | unc 00000000 | FE_HAS_LOCK
>server02 ~ #

If i convert hex to dec, you can see, it is exactly the same:

>server02 ~ # echo $((16#d47a))
>54394
>server02 ~ #

The "human readable output" of femon is 82%,

>server02 ~ # femon -a0 -c1 -H
>FE: STV090x Multistandard (DVBS)
>status SCVYL | signal  82% | snr  77% | ber 0 | unc 0 | FE_HAS_LOCK
>server02 ~ #

but the VDR satip-Plugin says 97%:

>vdr01_64 ~ # svdrpsend plug satip stat
>220 vdr01_64 SVDRP VideoDiskRecorder 2.2.0; Sat Mar 14 15:26:23 2015; UTF-8
>900-Device: SAT>IP 0 192.168.177.11|DVBS2-6,DVBT2-2|minisatip
>900-CardIndex: 6  HasLock: yes  Strength: 97  Quality: 93  Live: yes
>900-Transponder: 111082  Channel: SUPER RTL HD
>900
>221 vdr01_64 closing connection
>vdr01_64 ~ #

The question is now, what does femon compute in a different manner?

Myabe it helps if we (you) have a look into the soucecode of femon?

--> http://www.linuxtv.org/wiki/index.php/LinuxTV_dvb-apps

**Comment by 3PO** [comment]
The Maintainer of the vdr-satip-plugin wrote:

>My guess is that your minisatip is scaling the signal level and quality values incorrectly. The level must be scaled between 0-255 and the quality between 0-15. 

--> http://www.vdr-portal.de/index.php?page=Thread&postID=1238266#post1238266

**Comment by catalinii** [comment]
I guess that the signal is taken from the ioctl directly without any conversion, but as I said, the signal is not the same between all the devices. MY dvb-s device returns 1450 as max signal and not 65535.

I will  find a way to make it work better for the devices that report it correctly (which seems to be most of the devices anyway).

Thanks

**Comment by rofafor** [comment]
You should utilize the FE_SCALE_DECIBEL of DVB API v5 and only fallback to FE_SCALE_RELATIVE if the fore-mentioned mode isn't supported.

**Comment by catalinii** [comment]
Hi rofafor,

yes I implemented the new api, but could not test since no hardware I have provides the new api.
In the next commit, I will just take the output of the ioctl (if snr> 4096 ) and do the binary shift to get the result between 0..255 and 0..15.

Thanks

**Comment by catalinii** [comment]
Hi,

please let me know if this is ok with the new commit.

Thanks

**Comment by 3PO** [comment]
Now it seems, it wokrs. ;)

Server:

>server02 ~ # femon -H -c1 -a0
>FE: STV090x Multistandard (DVBS)
>status SCVYL | signal  84% | snr  80% | ber 0 | unc 0 | FE_HAS_LOCK
>server02 ~ #

VDR:

![150412_141453](https://cloud.githubusercontent.com/assets/945108/7105531/ae31849c-e11e-11e4-9358-2e1c1491c9b7.jpg)
