### ISSUE TITLE
RFE: Listening in specific IP address

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#734]
Hi,

With the current implementation the listening **address** is automatically determined in the function 
`socketworks->getlocalip()`:
https://github.com/catalinii/minisatip/blob/681f099c8dd6494e24db65129e5ee44d3b6bc96f/src/socketworks.c#L136

Then it will be impossible to use the loopback or in a multi-homed server. So I request a method to configure the listening address.

Please @catalinii !

**Comment by 9000h** [comment]
Hi,
this should be optional, in a multihomed env multiple programs may need the same listening ports and you may need to be specific on which IP the services are listening as there is only one 0.0.0.0 interface (lo). As an example if you will have tvh and minisatip on the same host on the same standard rtsp port 554 you need at least 2 IP's in the same network range, if you have multiple networks it makes it even more complex as you may need then policy based routing when they are on different network adapters.
CU
9000h

**Comment by lars18th** [comment]
Hi @9000h ,

And the problem can be worse: in a multi-homed server perhaps not all interfaces will support multicast, and the SSDP announcement requires to use the correct networks.

So my suggestion is more simple than you think: By default the current behaviour will continue to be the main behaviour. And **only** if the user sets an alternative listening address, only in this case this address is used. Futhermore, the address will be limited to dot IP (0.0.0.0, 127.0.0.1, 192.168.1.1, etc.), then no resolve host is required, and no "loopback" or "lo" or "eth0" will be supported.

This will provide the option, for example, to listen in the loopback or in VPN connections, and in all interfaces. That is not supported at time.

Regards.

Note: If you want to use minisatip, tvh and satpi in the same server, you only need to use _different_ rtsp ports. For example, 554, 8554 and 9554. All these servers supports the use of alternative ports. However, in this case not all SAT>IP clients will support it. For _regular_ SAT>IP clients I suggest a different IP address for each server. To do this, you can use aliases in Unix to use addresses in the same subnetwork.

**Comment by gompf01** [comment]
HI , I second this option, as I am facing exactly this issue as well.  Regards

**Comment by lars18th** [comment]
Hi @catalinii ,

Will you address this suggestion?

**Comment by catalinii** [comment]
I think it is a good idea.
If you have time feel free to create a command line option and pass it here instead of NULL:
https://github.com/catalinii/minisatip/blob/master/src/minisatip.c#L1813-L1815

**Comment by Jalle19** [comment]
AFAICT this was closed by https://github.com/catalinii/minisatip/pull/858
