### ISSUE TITLE
logging inconsistent

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#74]
there are still printf's which should be done via the LOG macro

**Comment by catalinii** [comment]
Hey,

this and the logging levels are going to be part of the next log implementation (including __FILE__ and __LINE__), however this is low priority for now.
Can you open an RFE with what you would want to see in there ?

Btw, my thought is to make a dynamic logging (controlled from the options) and not with defines at compile time.

Thank you

**Comment by catalinii** [comment]
Actually I have opened:

https://toda.ro/issues/5
Please add there what you think it is relevant
