### ISSUE TITLE
autostart

### ISSUE THREAD

**Issue by engalaaodeh** [catalinii/minisatip#740]
Hi,

any method how we can run minisatip auto start Ubuntu please ?

**Comment by lars18th** [comment]
Hi @engalaaodeh ,

To run it as a service, you have different alternatives:

1. Install the `monit` package an configure it (it's very easy).
2. Generate a init.d script, you can use this as example: https://gist.github.com/bigmonkeyboy/9962293/
3. Configure a systemd script for it.

That's the common problem of running binaries as services in Linux.
Regards.

**Comment by bccrew** [comment]
I just have an entry in my /etc/rc.local file

**sleep 5
cd /root/minisatip
sudo ./minisatip -f -Z *:0 -M 0 &
exit 0**

**Comment by lars18th** [comment]
Hi @bccrew ,

> I just have an entry in my /etc/rc.local file
> 
> *_sleep 5 cd /root/minisatip sudo ./minisatip -f -Z _:0 -M 0 & exit 0__

Not bad, but...
- You can use just one line: `sudo /root/minisatip/minisatip -f -Z :0 -M 0 &`
- The minisatip binary can daemonize so... why you use the `&`.
- This entry inside `rc.local` has two problems: it doesn't handle the crash/exit of the minisatip process (perhaps you want to add a `nohup` call); and using this mode to start you can't stop it when booting.

**Comment by bccrew** [comment]
Can someone share his systemd script please? I tried it like this but process is running but server not accesible..

[Unit]
Description=Multi-threaded SAT>IP server
After=network-online.target

[Service]
User=root
Group=root

WorkingDirectory=/root/minisatip/
Type=simple
EnvironmentFile=/root/minisatip/
ExecStart=/root/minisatip/minisatip -f -Z *:0 -M 0 -o 192.168.1.17:9000

[Install]
WantedBy=multi-user.target


I also enabled systemd-networkd-wait-online.service with 

systemctl enable systemd-networkd-wait-online.service

**Comment by lars18th** [comment]
Hi,

Even I'm not a big fan of daemon scripts, perhaps it will useful (as other projects do) to include inside the project a subdirectory with useful example scripts. For example, for systemd, for debian/ubuntu init.d, monit.config, etc. Then the users can copy them to his environment and use it.

What you think?

**Comment by bccrew** [comment]
I would like that, as I cannot get it to work properly.

What is your approach Lars? I actually never needed it to run as a daemon or service because it runs very stable for me. I just reboot the whole system every night :D

**Comment by 9000h** [comment]
I do have 2 files for starting minisatip with systemd
minisatip.path
```
[Path]
PathExists=/dev/dvb/adapter0/frontend0
Unit=minisatip.service

[Install]
WantedBy=sockets.target

```
and minisatip.service
````
[Unit]
Description=Multi-threaded SAT>IP server
After=network-online.target
#Wants=oscam.service

[Service]
#User=minisatip
#Group=minisatip
WorkingDirectory=/var/lib/minisatip
Type=simple
EnvironmentFile=-/etc/conf.d/minisatip
ExecStart=/usr/bin/minisatip -f $SERVER_ARGS

[Install]
WantedBy=multi-user.target
````
the conf file looks like
```
SERVER_ARGS=" -H5:50 -D5 -o 192.168.178.129:2000 -Y 4:dvbt2,5:dvbt2,6:dvbc2,7:dvbc2 -u 0:4-984[-48],1:5-1020[-23],2:6-1056[-88],3:7-1092[-204] -m 0040caa2c79d  -l http"
```

**Comment by bccrew** [comment]
@9000h What files/directories are required in /var/lib/minisatip  ?

Can you explain a bit more about the path file? Or how to enable the service for autostart with these 2 separate files for systemd? Thanks

**Comment by 9000h** [comment]
the folder html has to be copied over to /var/lib/minisatip for webfrontend

**Comment by 9000h** [comment]
I think the question is answered, so please close.

**Comment by bccrew** [comment]
Yes, I added a commit

https://github.com/catalinii/minisatip/commit/3d622ba6647abdadd7a0bf9ae7861edd33d07461
