### ISSUE TITLE
pids missing

### ISSUE THREAD

**Issue by Kitoko86** [catalinii/minisatip#748]
Hi,

I have a strange issue when I'm tuning frequencies in the Ka band to my minisatip server. When I send the tuning parameters, the specified pids are missing. Is it normal or is it related to my tuner (TBS 5520 SE) ? 

![Capture du 2020-04-27 17-08-01](https://user-images.githubusercontent.com/64423429/80388071-bb36c200-88a9-11ea-86ee-a6c59012a300.png)

Regards.

**Comment by 9000h** [comment]
you minisatip version 1.0.2 is pretty "old", can move up to the current git version

**Comment by Kitoko86** [comment]
Update done like you told me but the problem continues. Thanks anyway.

**Comment by 9000h** [comment]
ok then do provide a debug log  with -l http,dvb

**Comment by Kitoko86** [comment]
I had a look to the log, the frequency "x" is not within so my LNB works only for the Ku band and not for the Ka band. That's explain the issue. Shame on me!

Sorry for the inconvenience and thanks for your support.

**Comment by 9000h** [comment]
great, the please close here
