### ISSUE TITLE
Please use the forum for questions: https://minisatip.org/forum/

### ISSUE THREAD

**Issue by catalinii** [catalinii/minisatip#75]

**Comment by 3PO** [comment]
Maybe you sould this info put into the RAEDME.md?

**Comment by vdrtuxnet** [comment]
Maybe you should keep the issues here on the development site, would make things easier.

But anyway Redmine is not very end-user-friendly, its more tech2tech based, and as you maybe see, its gonna getting quieter 2day.

**Comment by 3PO** [comment]
>Maybe you should keep the issues here on the development site, would make things easier.

:+1:  :+1:

**Comment by catalinii** [comment]
OK then let's submit the issues here, the ERs there .
Readme updated.

**Comment by vdrtuxnet** [comment]
Good solution!

**Comment by catalinii** [comment]
I have enabled the forum on https://toda.ro/ , please use it for any questions.

**Comment by catalinii** [comment]
.
