### ISSUE TITLE
SATIPC: Limited retrying whith 5xx replies

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#750]
Hi @catalinii ,

I observed this behaviour:

- When using the `satipc` module, if the SAT>IP server responds with an error (for example, with `503 Service Unavailable`), then the adapter at time will retry the command forever.

And this is the correct behaviour... but we need to impose some limits:
1. The loop requires to wait some time before the next command (500ms for example?).
2. After a X number of continuous errors, the adapter needs to be closed.

I feel this is a more correct behaviour to not sature the SAT>IP server. For example, if the server is used by another client, the current behaviour can interfere with the streaming, as the `satipc` is saturating the server with a lot of requests... and without ending (the end actually arrives when the client closes the session because the data never arrives).

What you think about this?

**Comment by catalinii** [comment]
I agree with 1, not sure if I agree with 2. You could have just bad signal and then you do not want to close the adapter because of that.

I think for server errors, the adapter may be needed to be closed.

**Comment by lars18th** [comment]
Hi @catalinii ,

> I agree with 1,

Great!

> not sure if I agree with 2. You could have just bad signal and then you do not want to close the adapter because of that.

Ummm... Closing the adapter is a simple action. You can reopen it anytime after. So I don't see any real side effect on this behaviour. Futhermore almost it can help in one scenario: if you have two or more tuners with the same sat position, and one has insufficient signal, then it's best to close this adapter and try the next. so in this case, closing the adapter is the best way. Don't you think?

> I think for server errors, the adapter may be needed to be closed.

Yes, but not for all "errors". The standard defines a variety of error messages to inform to the client about the current status of the server with some accuracy. So not in all cases the behaviour requires to be "all" or "nothing", in the sense of "close the adapter" or "continue". In some cases a waiting time is a good solution, in some others it's best to try for a different command. In fact every case is different. So, please don't close the adapter and reopen it forever.

**Comment by catalinii** [comment]
About 2) I think this will cause an issue for people that do not have this setup (multiple adapters on the same satellite). This generally should fall on the satip client side (tvh, ... ) to try different adapter if there is no signal. As this is a change in behavior I am against it.

Errors:
Yes, the retry should depend on the rtsp code returned by the server. I do not have a clear idea about this, but if you have a specific proposal (code - behavior) I think is a good idea to implement it.

**Comment by lars18th** [comment]
Because this reflects the same issue #904 I close it.
