### ISSUE TITLE
minisatip build fails with gcc 10.0.1

### ISSUE THREAD

**Issue by ghost** [catalinii/minisatip#752]
It depends on CFLAGS=-fno-common which is default in gcc 10.

./configure
make

make -C src
make[1]: Entering directory '/home/fedora/minisatip/src'
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c minisatip.c -o ../build/minisatip.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c socketworks.c -o ../build/socketworks.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c stream.c -o ../build/stream.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c adapter.c -o ../build/adapter.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c utils.c -o ../build/utils.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c aes.c -o ../build/aes.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c csa.c -o ../build/csa.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c dvbapi.c -o ../build/dvbapi.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c pmt.c -o ../build/pmt.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c tables.c -o ../build/tables.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c satipc.c -o ../build/satipc.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -c dvb.c -o ../build/dvb.o
gcc -Wall -Wno-switch -ggdb -fPIC   -DVERSION=\"1.0.3-67c86b4\" -DDISABLE_DVBCA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI  -o ../minisatip  ../build/minisatip.o  ../build/socketworks.o  ../build/stream.o  ../build/adapter.o  ../build/utils.o  ../build/aes.o  ../build/csa.o  ../build/dvbapi.o  ../build/pmt.o  ../build/tables.o  ../build/satipc.o  ../build/dvb.o -lpthread -lrt -lcrypto -ldvbcsa
/usr/bin/ld: ../build/socketworks.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/socketworks.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/stream.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/stream.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/adapter.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/adapter.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/utils.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/utils.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/aes.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/aes.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/csa.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/csa.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/dvbapi.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/dvbapi.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/pmt.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/pmt.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/tables.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/tables.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/satipc.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/satipc.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
/usr/bin/ld: ../build/dvb.o:/home/fedora/minisatip/src/utils.h:91: multiple definition of `httpc'; ../build/minisatip.o:/home/fedora/minisatip/src/utils.h:91: first defined here
/usr/bin/ld: ../build/dvb.o:/home/fedora/minisatip/src/adapter.h:119: multiple definition of `source_map'; ../build/minisatip.o:/home/fedora/minisatip/src/adapter.h:119: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:149: ../minisatip] Error 1
make[1]: Leaving directory '/home/fedora/minisatip/src'
make: *** [Makefile:11: minisatip] Error 2

**Comment by kmdewaal** [comment]
I have added pull request #754 which fixes this.

**Comment by catalinii** [comment]
Thanks for fixing it
