### ISSUE TITLE
adapter number

### ISSUE THREAD

**Issue by engalaaodeh** [catalinii/minisatip#755]
Hi,

how I can to specify the adapter number by http:

i used adapter=2 but not working

Astra 19.2E, Kika HD: "rtsp://MINISATIP_HOST:554/?src=1&freq=11347&pol=v&ro=0.35&msys=dvbs2&mtype=8psk&plts=on&sr=22000&fec=23&pids=0,17,18,6600,6610,6620,6630"

Thanks

**Comment by catalinii** [comment]
fe=X where X is adapter-1. Also depends how they are mapped. In general if you have a combo of DVB-S, DVB-C, all the DVB-S will be before DVB-C and so on
