### ISSUE TITLE
Can not create any new topic or PM

### ISSUE THREAD

**Issue by Wanninger** [catalinii/minisatip#756]
Hi Cata,

sorry for choosing this way to contact you,
but I do not find any other way to contact you.
Your forum at minisatip seems to be readonly.

I cannot write a PM or answer to one or create
a new topic at "https://minisatip.org/forum"

Sorry...

**Comment by catalinii** [comment]
Hey,

Can you tell me your user?

**Comment by Wanninger** [comment]
Hi,

it's carter

and it looks like this:



Am 25.06.20 um 07:58 schrieb catalinii:

**Comment by catalinii** [comment]
Can you check now?

**Comment by Wanninger** [comment]
I checked it, but it did not fix the problem.
Since a few weeks, the whole site seems to be down...

**Comment by catalinii** [comment]
Does it work now ?

**Comment by Wanninger** [comment]
Well, the forum is back online again, but my first issue still exist.
I cannot add any new post, because i cannot write into the text field.

**Comment by catalinii** [comment]
Do you think is a permission problem or related to JS/forum rendering ?

**Comment by Wanninger** [comment]
I don't think that it is a permission problem.
When I try post reply, a window opens as usual, I can enter a text into the subject field
but not in the comment field. There is only a small rectangle visible on the upper left side.
of the comment field. It is also not possible to paste something into.

**Comment by Wanninger** [comment]
Hint:
The "quick reply" box works again in the meantime, but "new topic" or "post reply" or "new pm" do not.

**Comment by catalinii** [comment]
What browser are you using ?

**Comment by Wanninger** [comment]
The same browser(s) as the last years
Firefox and Chrome - I already cleared cookies and cache on both browsers
I'll try to send you a screenshot

**Comment by Wanninger** [comment]
...under the BOLT button, you see the rectangle.
Nothing more...

**Comment by Wanninger** [comment]
I sent the screenshot also to your forum's mail account

**Comment by catalinii** [comment]
Can you try now ? I've upgraded the board and reset the images.

**Comment by Wanninger** [comment]
That did the trick - it seems to be ok now
