### ISSUE TITLE
Two clients connect to one minisatip instance.

### ISSUE THREAD

**Issue by marian3** [catalinii/minisatip#758]
Hi, what is the standard behavior of one minisatip instance when two clients connect at the same time?
They should both get a stream from one transponder, but this is not the case for me. Clients Vu + (Vti image) and Dvbviewer, the first will receive a stream, the second in order the same channel - "channel not available from the server" ???

PS: otherwise it goes famously, a great job, thanks.

**Comment by Jalle19** [comment]
minisatip will reuse the same tuner/transponder pair if multiple clients request the same parameters. If it doesn't work then maybe your tuners are configured incorrectly?

**Comment by catalinii** [comment]
Correct.

But please make sure they use the same parameters( all parameters have the same value)

**Comment by 9000h** [comment]
as there is a fix already committed if  clients request freq +- Mhz this could probably closed
