### ISSUE TITLE
dvbapi_offset

### ISSUE THREAD

**Issue by ddimension** [catalinii/minisatip#759]
Hi!

Please add an option for the dvbapi_offset. This created hard to debug stability issues.

Kind regards!

**Comment by 9000h** [comment]
it's already there
https://github.com/catalinii/minisatip/blob/c1da0b5b369b5fe3b4711a52500d2d9990029825/src/minisatip.c#L598

**Comment by ddimension** [comment]
Hi!

Thanks for the hit. My C foo is not very good, perhaps you can improve this:

[dvbapi_offset.patch.txt](https://github.com/catalinii/minisatip/files/5081364/dvbapi_offset.patch.txt)

**Comment by 9000h** [comment]
if @catalinii  agrees why not make a pull request?

**Comment by catalinii** [comment]
I am fine with that

**Comment by ddimension** [comment]
Please see pull request #760.

**Comment by catalinii** [comment]
merged
