### ISSUE TITLE
minisatip openatv 6.4 Vu+ zero 4

### ISSUE THREAD

**Issue by quinquelhas** [catalinii/minisatip#765]
hello
I installed minisatp on my vu + zero 4k, with openatv 6.4 image, but it doesn't work ... the tuner appears, but I can't see any channels ... will it only work with 6.2?
thanks....

**Comment by catalinii** [comment]
Hi,
Can you upload the logs of minisatip:
./minisatip -f -l http,dvb

**Comment by quinquelhas** [comment]
Hi....
Doesn’t work...it says 
No such file or directory.....

**Comment by catalinii** [comment]
opkg update && opkg install minisatip

If you run this command can you start minisatip ?
