### ISSUE TITLE
Suggestion: Tuner "disabled" in UI

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#768]
Hi @catalinii ,

When starting minisatip with `-e 1,2` and you have three tuners, in the UI we don't have any feedback about the tuner _disabled_. In fact the tuner 0 is listed as regular. So, I suggest a simple change: in the SIGNAL column write "DISABLED" instead "OFFLINE" if the tuner is disabled.

You agree with this?

**Comment by catalinii** [comment]
implemented
