### ISSUE TITLE
Suggestion: Improvement in the WEB UI

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#776]
Hi @catalinii ,

Time to time I see some glitches in the reproduction of a program using a card. So I want to ask you if it's possible to add to the Cyptinfo section of the WEB UI a counter of _undecrypted packets_. This info will be useful to isolate playing errors.

Please consider this enhancement.
Thank you!

**Comment by catalinii** [comment]
This is very easy to achieve. You can expotrt at the bottom of adapter.c dec_err from adapter structure. Then you can just add that to html page

**Comment by lars18th** [comment]
Hi @catalinii ,

Done in #780 (with another small improvement). I hope you want to merge it. :wink: 

Regards.
