### ISSUE TITLE
Register in forum is not working

### ISSUE THREAD

**Issue by roisiano** [catalinii/minisatip#777]
Hi:

I have registered in the forum, but it DOES NOT send the activation e-mail.

Several attempts, with 3 different users, and 3 user accounts in different hostings, and none of them send the activation e-mail.

Kind regards

**Comment by catalinii** [comment]
Will need to look into it

**Comment by catalinii** [comment]
I activated your account and fixed the issue. Thanks for reporting it.

**Comment by roisiano** [comment]
Thanks to you
