### ISSUE TITLE
BUG: Enigma based STB (OpenATV) incorrect "bootid" file

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#784]
I discovered that inside Enigma based STBs the file "bootid" is not well targeted. The problem is the path. In the "/etc/default/bootid" you can see one file, but another inside "/etc/rc3.d/bootid". Futhermore, the values aren't readed correctly and only values 0 and 0 are used.

Perhaps a different approach is required. For example using a fixed path, using a parameter to use a fixed path, or whatever other solution.

Please, check it.
Regards.

**Comment by catalinii** [comment]
The issue here is tha tminisatip is run from different directories, as you can see here: https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/recipes-connectivity/minidlna/minidlna/init
I think if minisatip is started just by the script bootid will be in a consistent location.

**Comment by lars18th** [comment]
Ok. Thank you for the feedback.
But one question: Why minisatip don't use a fixed path for that file?

**Comment by catalinii** [comment]
Not a good reason, feel free to set it in the script and commit it.

**Comment by lars18th** [comment]
Hi @catalinii ,

The problem seems because the default file path is not set. See this:
https://github.com/catalinii/minisatip/blob/7ba80e07884466dfa63d97b50396b336eb9372af/src/minisatip.c#L1867

Then, depending of where is set the default directory, the file is put in some location.

I suggest to improve it: or with a command line parameter to set the path of the bootid file; or searching for it in the common directories (first in the same as the binary, second in /etc ...).

What you think?

**Comment by catalinii** [comment]
Searching to list of predefined location would make sense more.

You can create a wrapper for fopen and you can replace the usages for the web page as well making -R redundant
~/.minisatip/
/etc/minisatip

**Comment by Jalle19** [comment]
This is fixed by https://github.com/catalinii/minisatip/pull/921

**Comment by lars18th** [comment]
> This is fixed by #921

Yes. So thank you @Jalle19 !
Now I hope the maintainers of the OpenATV project will update the minisatip package and the scripts to use it.
