### ISSUE TITLE
sendmmsg(): errno 38: Function not implemented

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#795]
Reported here: https://github.com/Jalle19/satip-axe/issues/3

satip-axe runs Linux 2.6, while `sendmmsg` was introduced in Linux 3.0 (https://man7.org/linux/man-pages/man2/sendmmsg.2.html)

https://github.com/catalinii/minisatip/issues/346 seems to be related - apparently the Android NDK doesn't expose `sendmmsg` either.

@catalinii what do you suggest? The ifdef should probably be extended somehow.

**Comment by catalinii** [comment]
Thanks for reporting this, was not aware.
I think the only thing needed is to test for AXE here:
https://github.com/catalinii/minisatip/blob/31c8d4b99d226568a9322bc4eaa6c3606786088b/src/socketworks.c#L1220

**Comment by Jalle19** [comment]
Yeah that should work, I'll try to get some actual runtime testing done during the weekend.

**Comment by Jalle19** [comment]
@catalinii is it really worth keeping macOS compilation support around?

**Comment by catalinii** [comment]
I use it for local development.... if the delta is small then why not.

**Comment by Jalle19** [comment]
Ran into this again when attempting to run this on an ancient DM800 HD. I modified it so that I could pass `CFLAGS="-DNEEDS_SENDMMSG_SHIM"` in order to force the compiler to include the custom version of it. Do you think that's worth making a pull request for @catalinii ? I also tried using AC_CHECK_FUNCS but it does the detection on the host system so it's not very useful.

**Comment by catalinii** [comment]
Yes, I think is a good idea
