### ISSUE TITLE
Question about grace_time

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#798]
Hi @catalinii ,

I want to clear understand the use of the `grace_time` value inside the `pmt.c`. I'm using some "hack" increasing the value from 2000 to 4000, but I'm not sure if it has other side effects (see #708). From my understanding this value is used to not send any data at all until the PMT is readed/processed and the decoding is started. So from the client point of view this value only increases the time to tune a new frequency. That's correct? If this is true, and no other side effect is affected then I suggest you to provide a command line option to change the current value. The cause is to overcome the clients that refuse to play if the comming stream is scrambled (as previosly explained). So please comment about this.

Thank you!

**Comment by catalinii** [comment]
Hey Lars.

The grace_time purpose is to wait for that specific time before deciding if a channel is encrypted or no. If the channel is decrypted (has the mpeg start header) the CA (dvbapi, CI) will be informed about it (either way).

As this method is not that reliable in the last PR I took a different approach: test if the CW can decrypt the channel to prevent sending garbled stream in the first place. Packet s will be cleaned by mark_pids_null

**Comment by lars18th** [comment]
Hi @catalinii ,

I run minisatip with the `-E` parameter. And my concern is with the use case when the SAT>IP client checks, and _only_ for a short period of time, if the stream is encrypted _at the start_ (that's when tunning). So in this case, if the first packets sended to the client at start are encrypted for a longer period of around 250ms, then the play of such service is rejected; otherwise the player discards initial packets and starts to play from the first clear packet. My workaround to this problem is to block the encrypted packets at start. The perception of the SAT>IP client is then reduced to a more longer tunning period. So the workaround works. However, I don't have time to reimplement something like #445.

After this summary, a direct question: With the _current_ implementation (with the last changes), what's the actually behaviour when using the `-E` option? First encrypted packets are delivered or not? And if not, for how long?

Thank you for your comments!

**Comment by catalinii** [comment]
There is no change from that perspective. The encrypted packets are sent to the client as before

**Comment by lars18th** [comment]
OK. So last question: During the `grace_time` period while the minisatip process is deciding if the channel is encrypted or not, with the `-E` parameter enabled... are the encrypted packets sended to the client or they are blocked until the grace time expires?

Please forgive me for this stupid question, but I need to be 100% sure of the answer.
Thank you!

**Comment by catalinii** [comment]
The behavior of -E is not changed by the grace_time

**Comment by lars18th** [comment]
> The behavior of -E is not changed by the grace_time

Ok, but the `grace_time` blocks the stream or not? So, while the test is running until the timeout expires, the incoming encrypted packets are sended to the client or not?

Please be precise. And sorry for being insistent.
Thank you!

**Comment by catalinii** [comment]
Grace_time does not block the stream, so the encrypted stream is sent to the client

**Comment by lars18th** [comment]
> Grace_time does not block the stream, so the encrypted stream is sent to the client

OK. Thank you for the response! :+1:
