### ISSUE TITLE
No data on transponder timeout reading pat

### ISSUE THREAD

**Issue by dvbstream** [catalinii/minisatip#799]
Hi,
I would like to use minisatip to stream DVB-C to a VU Duo 4k without using the SAT-IP tuner. Therefore I try to only add the http stream links to the channel list. If I use the whole transponder it works, but if I just stream one channel it always says "No data on transponder timeout reading pat".

Working:
`http://11.11.11.11:8080/?freq=330&msys=dvbc&mtype=256qam&sr=6900&pids=all`

Error:
`http://11.11.11.11:8080/?freq=330&msys=dvbc&mtype=256qam&sr=6900&pids=0,1,16,17,18,20,1170,1176,2171,2172,5100,5101,5102,5103,5104,5105`

I read that the PAT has PID 0 so I thought it should work but it doesn't. Hopefully someone knows why it is not working like this.

(Also tried to register in the minisatip forum, but I do not get a verification mail.)
Thank you!

**Comment by 9000h** [comment]
works here on dvb-c with the same params
![Screenshot from 2021-01-22 13-52-05](https://user-images.githubusercontent.com/3009073/105493086-31d9e200-5cb9-11eb-9bfc-47753c323ea6.png)

**Comment by dvbstream** [comment]
Yes, I can also confirm that it works with VLC even with just the video PID in the stream. But it seems that there is a problem when the VU Duo tries to parse the PAT.

**Comment by catalinii** [comment]
I am assuming you want to use minisatip. Can you provide the log of ./minisatip -f -l http

**Comment by dvbstream** [comment]
Thank you for the fast response. I finally got it working:

`http://11.22.33.44:8080/?freq=330&msys=dvbc&mtype=256qam&sr=6900&pids=0,1,16,17,18,20,5100,5101,5102,5103,5104,5105,8187`

If you place this link directly into the channel list of a VU box with VTI installed it works. I looked a little deeper into the TS of the full transponder and found another metadata PID (8187). Adding this and removing the unnecessary ones were the key to success. I think this is very specific for the dvbsink implementation of VU.

The final channel list entry is then:
`#SERVICE 1:0:19:2b5c:41b:1:FFFF0000:0:0:0:http%3A%2F%2F11.22.33.44%3A8080%2F%3Ffreq%3D330%26msys%3Ddvbc%26mtype%3D256qam%26sr%3D6900%26pids%3D0%2C1%2C16%2C17%2C18%2C20%2C5100%2C5101%2C5102%2C5103%2C5104%2C5105%2C8187`
