### ISSUE TITLE
Scanning channels not work

### ISSUE THREAD

**Issue by 420Dope** [catalinii/minisatip#808]
I have installed it on my VU UNO 4K SE. https://www.opena.tv/openatv-6-2-image-rueckmeldungen/38695-satip-server-test.html
When I try to scan channels on a client, there are no channels found.

**Comment by catalinii** [comment]
Please read this: https://minisatip.org/forum/viewtopic.php?f=5&t=670

**Comment by 420Dope** [comment]
Ah ok thank you for the Link. Now I know that.

Quick question or idea for maybe a "workaround":
Can I switch to "standalone" and lets the client scanning the channels and after finish switch back to "using enigma2 as backend"?

**Comment by catalinii** [comment]
Yes this is how I do it.
