### ISSUE TITLE
latest commit's breaks signal information on webfrontend

### ISSUE THREAD

**Issue by holli73** [catalinii/minisatip#809]
hello,

with the latest commit's the web interface does not show signal information anymore (STR/SNR).

thanks
holli

**Comment by catalinii** [comment]
Hey,

Which commit exactly?

**Comment by 9000h** [comment]
cannot confirm any issue in regards to minisatip
![Screenshot from 2021-02-06 21-32-03](https://user-images.githubusercontent.com/3009073/107129045-f2b7ad80-68c2-11eb-82e7-920c11bf2c90.png)

**Comment by holli73** [comment]
hello,

i was on 191fe62a7a5aaada03ef274511b24238c210693c and today i updated to the latest - so i don't know which did break it - but before i had 2 green bars.

![Bildschirmfoto 2021-02-06 um 23 03 19](https://user-images.githubusercontent.com/1434090/107130636-ce160280-68cf-11eb-91ba-0ca9726fcee7.png)

thanks
holli

**Comment by holli73** [comment]
hello,

i did revert to the commit i thought it was working and the signal bars were gone as well - so i did build the latest ddevices (ddbridge) modules and there were some changes - and now the bars are back even with the latest commit of minisatip.

sorry - but it looks like the ddbridge modules did have an issue and i did rebuild them a couple of days ago as well but for sure did not check the signal bars...

sorry for the in circumstances.
holli
![Bildschirmfoto 2021-02-06 um 23 35 07](https://user-images.githubusercontent.com/1434090/107131178-8a71c780-68d4-11eb-87b7-01bbd8725d54.png)
