### ISSUE TITLE
Cannot switch to Hotbird, only to ASTRA

### ISSUE THREAD

**Issue by pbriesch** [catalinii/minisatip#83]
Hi,

the server has two DVB-S2 adapters which are hooked up to a multi switch with ASTRA and Hotbird.The client is VDR in two flavours:
* VDR using virtual DVB adapters (satip/vtuner combination). Here I can switch to channels of both ASTRA and Hotbird http://pastebin.com/wKEMSGJP
* VDR using vdr-plugin-satip (http://www.saunalahti.fi/~rahrenbe/vdr/satip/) Here I can only watch channels on ASTRA. http://pastebin.com/aHUGSPFz

I don't know if this an issue of the vdr-plugin-satip or minisatip or both. Maybe the logs help you to find out.

Paul

**Comment by catalinii** [comment]
Hi,

I think you should configure vdr in some way to tell it that the first device is Astra and the other is hotbird.
The protocol has 2 ways of controlling this:
fe=1 // astra
fe=2 // hotbird.

In general you can control the diseqc by specifying src=X (where X is the position with values from 1 to 4), but I guess fe= is what you need for this case.

I am not sure how you can configure vdr to do that, but in the minisatip urls, I did not see any of those options specified, which would tell minisatip which adapter to select .

**Comment by 9000h** [comment]
for vdr-plugin-satip and multifeed there is a special config in VDR needed that it works right, it's definitely not a minisatip issue.

please read the README from the plugin and change your "sources.conf" from VDR

**Comment by vdrtuxnet** [comment]
Should work like this in /etc/vdr/sources.conf

S19.2E   1     Astra 1B/C/E/F/G/H/2C 
S28.2E   2     Astra 2D/A/B
S28.5E   2     Eurobird
S13E      3     Hotbird 1-(5)-6

and disable all none needed sources by using the 0, like:

S21.5E   0    Eutelsat II F3
26E        0    Arabsat 2A/3A
.......
and check your /etc/vdr/diseqc.conf for the order.

kind regards

**Comment by 9000h** [comment]
we should close here, I can confirm it works with the right configured VDR and 4 sat pos. diseqc

**Comment by pbriesch** [comment]
Thanks for the information 9000h and vdrtuxnet.

**Comment by TheTroll** [comment]
Hey,

I tried it and there is a little typo + a misconfig of the uncmd.
here is fix:

diff --git a/adapter.c b/adapter.c
index 61aae76..e898804 100755
--- a/adapter.c
+++ b/adapter.c
@@ -989,7 +989,7 @@ void set_diseqc_adapters(char *o)
                        continue;
 
                a[a_id].committed_no = committed_no;
-               a[a_id].committed_no = uncommitted_no;
+               a[a_id].uncommitted_no = uncommitted_no;
                LOGL(0, "Setting diseqc adapter %d committed_no %d uncommitted_no %d", a_id, committed_no, uncommitted_no);
        }
 }
diff --git a/dvb.c b/dvb.c
index e069f0c..5a3bafe 100755
--- a/dvb.c
+++ b/dvb.c
@@ -247,6 +247,7 @@ int dvb_open_device(adapter *ad)
 void diseqc_cmd(int fd, int times, char *str, struct dvb_diseqc_master_cmd *cmd)
 {
        int i;
+
        for( i = 0; i < times; i++)
        {
                usleep(15000);
@@ -265,7 +266,7 @@ int send_diseqc(int fd, int pos, int pol, int hiband, int committed_no, int unco
  /* DiSEqC 1.1 */
        struct dvb_diseqc_master_cmd uncmd = { {0xe0, 0x10, 0x39, 0xf0, 0x00, 0x00}, 4 };
        cmd.msg[3] = 0xf0 | ( ((pos << 2) & 0x0c) | (hiband ? 1 : 0) | (pol ? 2 : 0));
-       uncmd.msg[3] = 0xf0 | ( (pos & 0x0c) | (hiband ? 1 : 0) | (pol ? 2 : 0));
+       uncmd.msg[3] = 0xf0 | (pos & 0x0f);
 
        if(uncommitted_no > committed_no)
                uncommitted_first = 1;

**Comment by TheTroll** [comment]
There is a problem with the status string, and it looks like a problem is the protocole ?
The only identifier in the string is  tuner=XX
But how the client is supposed to know which tuner it is for him ?

For instance, tvheadend can't know if tuner 2 or 3 is what he asked for, so it is not possible to match correctly
