### ISSUE TITLE
No Picture

### ISSUE THREAD

**Issue by haarm** [catalinii/minisatip#831]
Has anything been fundamentally changed ?
None of my VDR runs anymore, I get this everywhere:
Apr 10 13:18:32 vdr1 vdr: [767] SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.1.38/ [device 0]
Apr 10 13:18:32 vdr1 vdr: [898] video directory scanner thread ended (pid=504, tid=898)
Apr 10 13:18:32 vdr1 vdr: [767] SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.1.38/ [device 0]
Apr 10 13:18:32 vdr1 vdr: [767] SATIP-ERROR: Pid update failed - retuning [device 0]
Apr 10 13:18:32 vdr1 vdr: [767] SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.1.38/ [device 0]
Apr 10 13:18:32 vdr1 vdr: [767] SATIP-ERROR: Detected invalid status code 404: rtsp://192.168.1.38/ [device 0]
Apr 10 13:18:32 vdr1 vdr: [767] SATIP-ERROR: Pid update failed - retuning [device 0]

**Comment by MusterGit** [comment]
Hi,
there is a fresh bug in the master branch.
See https://github.com/catalinii/minisatip/commit/2f9abc56592f68047647c921672a4ad821527788#commitcomment-49342843

**Comment by haarm** [comment]
Thanks for the info

**Comment by 9000h** [comment]
should be closed as it is fixed already
