### ISSUE TITLE
-D serial is ignored

### ISSUE THREAD

**Issue by Neolo** [catalinii/minisatip#837]
Option -D serial is ignored, desc.xml always reports it as 1 whatever you do. Set it 2, or 222 or 9999, put at the beginning of the command or at the end - no changes.

minisatip --satip-tcp -x 8082 -U 0:1 -e 2,3 -c 0:2,1:2 -a 2 -j 2:5-1120,3:6-1155 -M *:5.0-5.0 -l ca -t -f -y 555 -D 222

**Comment by 9000h** [comment]
-D is not a serial number it's the device id and has nothing to do with the desc.xml

```

-D --device-id DVC_ID: specify the device id (in case there are multiple SAT>IP servers in the network)

    eg: -D 4
`````

**Comment by Neolo** [comment]
> -D is not a serial number it's the device id and has nothing to do with the desc.xml

Great and why minisatip instances overlap one another in the same network? Huh?

**Comment by lars18th** [comment]
Hi @Neolo ,

You have misinterpreted the functionality of the `-D` parameter. This indicates the value of the `BOOTID.UPNP.ORG` in the SSDP announcement. That's based on the specifications of the SAT>IP standard. On the other hand, the `serial` value in the XML description file is only an informative value. And at time, it's hardcoded. Both value can't be related, as the serial should not change (as identifies the device) and the bootid is a value that requires to chenge.
Please, if you need to change this value then explain the reason.

Regards.

**Comment by Neolo** [comment]
> Please, if you need to change this value then explain the reason.

TVH sees only one server at a time.
Running both:
minisatip --satip-tcp -x 8082 -U 0:1 -e 2,3 -c 0:2,1:2 -a 2 -j 2:5-1120,3:6-1155 -M *:5.0-5.0 -l ca -t -f -y 555 -D 222
minisatip -D 1 --satip-tcp -x 8081 -U 0:1 -e 0,1 -c 0:1-1856,1:1-1712 -a 2 -j 0:13-1400,1:23-1750 -M *:5.0-5.0 -l ca -t -f -g -D 111

TVH:
TVH_ARGS="--satip_xml http://localhost:8081/desc.xml --satip_xml http://localhost:8082/desc.xml" 

Results TVH showing only one of them.

**Comment by lars18th** [comment]
Hi @Neolo ,

These "TVH_ARGS" are to configure the SERVER part of the TVH. It can run as a SAT>IP server too. So forget them to configure it as a CLIENT of a minisatip server. Please, read this: https://tvheadend.org/boards/5/topics/30495

Futhermore, execute both minisatip instances with the `-A` parameter to disable the SSDP announcement. And I recommend (for better readability) to use the `-y` in both, even using the default `554` value. In example:
```
minisatip --satip-tcp -x 8082 -A -y 555 -D 222 -l ca -t -f    -U 0:1 -e 2,3 -c 0:2,1:2 -a 2 -j 2:5-1120,3:6-1155 -M *:5.0-5.0
minisatip --satip-tcp -x 8081 -A -y 554 -D 111 -l ca -t -f -g -U 0:1 -e 0,1 -c 0:1-1856,1:1-1712 -a 2 -j 0:13-1400,1:23-1750 -M *:5.0-5.0
```

Regards.

**Comment by lars18th** [comment]
Hi @Neolo ,

And if you want to tweak or edit the XML description file, then use the parameter `-X` of minisatip. Then you can edit the file for each server manually. And for example, use different serial values. Search for "-X --xml PATH:" in the README.md.

Regards.

**Comment by Neolo** [comment]
> These "TVH_ARGS" are to configure the SERVER part of the TVH

No, this is exactly what it is, adding REMOTE servers to TVH manually https://tvheadend.org/boards/5/topics/23279 if can't be detected automatically due NAT or, like in my case, of different ports.
Your link describes server/client between two TVH on different PCs, nothing to do with.

**Comment by lars18th** [comment]
Hi @Neolo ,

Please close this issue and continue in the other #836 , as they are the same.
Thank you!

**Comment by lars18th** [comment]
Hi @Neolo ,

Perhaps you want to recompile minisatip with my new PR #838 . With it you can change the "name" of the server to distinguish between different instances.

Regards.
