### ISSUE TITLE
sat>ip DESCRIBE

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#84]
if it's not to much effort, it would be nice to have filled all attributes

like 

a=fmtp:33 ver=1.0;src=1;tuner=1,123,1,4,10744.00,h,dvbs,qpsk,off,0.35,22000,56;pids=0,400,401,402

**Comment by catalinii** [comment]
Yes you are right.
I got everything prepared for that, just to make it work.

Thanks

**Comment by 9000h** [comment]
looks good now
