### ISSUE TITLE
dvbapi connection with default port 9000 specified doesn't work

### ISSUE THREAD

**Issue by bccrew** [catalinii/minisatip#845]
Working: -o 192.168.1.17

Not working: -o 192.168.1.17:9000

Can someone please confirm this?

**Comment by catalinii** [comment]
Can you provide logs:

./minisatip -f -l http -o 192.168.1.17:9000

**Comment by bccrew** [comment]
Sorry, I can't seem to reproduce the issue anymore :(  strange...
