### ISSUE TITLE
minisatip hang: free(): corrupted unsorted chunks

### ISSUE THREAD

**Issue by floek** [catalinii/minisatip#848]
Hi,

when switching a number of channels the latest minisatip stops working with `free(): corrupted unsorted chunks`.
No response from the daemon after this message, no webinterface.
Also no reaction to a normal kill signal. I need to `kill -9`.

I have Oscam with dvbapi and netceiver tuners.

Any ideas?

Thanks,

floek

**Comment by catalinii** [comment]
Hi,

Can you reproduce and provide the output of 
./minisatip -f -l http .....

Thanks

**Comment by floek** [comment]
Hi,

okay, wasn't able to reproduce today. I've switched all >100 channels and got no problem. There was a reboot of my rpi4 in the meantime. So may it was just a temporary problem.

I'm closing for now.

Floek
