### ISSUE TITLE
Questions about TBS6900 CI

### ISSUE THREAD

**Issue by Kitoko86** [catalinii/minisatip#851]
Hi @catalinii,

I have some questions about the independent CAM reader TBS6900 CI and minisatip:

1. How can I get it work to decrypt channels with a given tuner?
2. In this case, do I have to enable a feature when I compile minisatip?

**Comment by catalinii** [comment]
Hi,
You need to make sure that src/Makefile contains DDCI=1 

Other than that it should work with a CAM.

Thank you

**Comment by Kitoko86** [comment]
I run the latest version of minisatip with DDCI enabled but unfortunately, channels are always scrambled. I noticed that everytime, during the authentication, the CI+ CAM menu displays an error message and reboot. Anyway, here is the log coming from the following command: minisatip -l ca -R ~/minisatip/html -x 8090:

[minisatip.zip](https://github.com/catalinii/minisatip/files/6571978/minisatip.zip)

**Comment by 9000h** [comment]
CA module not present or not ready

you may forgot to install the needed keys for the CI+

**Comment by Kitoko86** [comment]
I put the required certificates in the /etc/ssl/certs directory. Anyway, I close temporarily this issue because the support for this device is still in development.

**Comment by catalinii** [comment]
This device should work.

**Comment by Jalle19** [comment]
@Kitoko86 did you end up getting it to work? I'm wondering if I should buy a TBS-6900 or not.

**Comment by Yuri666** [comment]
I have this device. Works fine.

**Comment by catalinii** [comment]
I have a TBS 6900 too...the driver is pretty simple to understand as well.

**Comment by Jalle19** [comment]
Great, thanks!
