### ISSUE TITLE
CI messages in cyrillic are displayed as rectangles in the log

### ISSUE THREAD

**Issue by Delitants** [catalinii/minisatip#854]
CI messages in cyrillic are displayed as rectangles in the log, unreadable.

`[16/06 12:07:17.882 CA3]: MMI menu from CAM in the slot 0:
[16/06 12:07:17.882 CA3]:   title:    ▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒
[16/06 12:07:17.882 CA3]:   subtitle: ▒▒▒▒▒▒▒▒▒
[16/06 12:07:17.882 CA3]:   item 1:   ▒ ▒▒▒ ▒▒▒ ▒▒▒▒ ▒▒▒ ▒▒▒▒▒▒▒ ▒
[16/06 12:07:17.882 CA3]:   item 2:   ▒▒▒▒▒▒▒▒▒
[16/06 12:07:17.882 CA3]:   bottom:   ▒▒▒▒▒▒▒ 'OK' ▒▒▒ ▒▒▒▒▒▒▒▒▒▒▒▒▒`

**Comment by Yuri666** [comment]
As workaround you can switch CAM language to english in cam menu in tv-box

**Comment by catalinii** [comment]
I think minisatip sends the language as english. @Yuri666 any idea why the menu is not in english?

**Comment by Yuri666** [comment]
minisatip sends Host language and country setting. As descrypt in ci+ specifications the CICAM may set its menu language to reflect the Host's setting. But may not set. And usually not set.

**Comment by Neolo** [comment]
> As workaround you can switch CAM language to english in cam menu in tv-box

I don't have such option at all. And putting CAM in other tuner makes it locked and I have to call support every time. Any solution without disconnecting it from minisatip?

**Comment by catalinii** [comment]
This could be fixed by implementing https://github.com/catalinii/minisatip/issues/185

If someone has time I can help but don't generally have access to a CAM atm nor much time

**Comment by Jalle19** [comment]
> And putting CAM in other tuner makes it locked and I have to call support every time.

Is this normal? Will moving a CAM temporarily to my TV prevent it from working in minisatip?

**Comment by Jalle19** [comment]
I think this has to be solved by minisatip explicitly asking the CAM to change language. My CAM "speaks" Finnish in minisatip, but English in my TV, so the TV must be overriding the language somehow. Would probably help debugging as well.

**Comment by Yuri666** [comment]
yes. try this
https://github.com/Yuri666/minisatip/commit/e45a71775c2490d072f24156d3bf0dbcea4c8b98

**Comment by Jalle19** [comment]
@Yuri666 works like a charm (picked it into my personal branch as https://github.com/Jalle19/minisatip/commit/f02b001785016d32da1476f5be189bb85ad8a68c):

```
CA4]: MMI menu from CAM in the slot 0:
CA4]:   title:    Information message
CA4]:   subtitle:
CA4]:   item 1:   The authentication proce
CA4]:   item 2:   host and the module has 
CA4]:   item 3:   successfully.
CA4]:   bottom:   Press Ok or Exit to quit
```

**Comment by Jalle19** [comment]
Now that I wrote that I see that it caps the messages, so there is probably some improvements that could be done still.

**Comment by Yuri666** [comment]
> Now that I wrote that I see that it caps the messages
Should not affect in any way, these are different sessions..

**Comment by Jalle19** [comment]
@catalinii this can be closed, was practically fixed in https://github.com/catalinii/minisatip/pull/935

**Comment by catalinii** [comment]
Thank you @Jalle19
