### ISSUE TITLE
ROLL-OFF not handled correctly

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#859]
Hi,

I've this problem: With some satellite transponders after some time running the stream will be stalled. After installing the "v4l-util" package I've started to run in the background the frontend monitor (`dvb-fe-tool -m -f 0`). And I discovered that when this happens, the LOCK is lost. But minisatip never recovers from this point. So the only solution is to change to another frequency and return to the same transponder.

However, I feel it will be more interesting if the minisatip detects (using the DVB v5 interface) that the LOCK is lost, and then retune to the same frequency. After a small review of the Linux DVB drivers, I see that some tuners support auto relock, but others not. For example, please check: https://code.woboq.org/linux/linux/include/media/dvb_frontend.h.html and see about the `DVBFE_ALGO_RECOVERY`.

So, the question is: It has sense to provide some LOCK RECOVERY functionality in minisatip?

**Comment by lars18th** [comment]
Hi,

And just to know it. Anyone knows why when minisatip indicates that the LNB is OFFLINE (several minutes after the last tunning), when using the command `dvb-fe-tool -m -f 0` the frontend seems to continue locking the signal? I observe this in _all_ of my different Enigma2 boxes. You think this has sense? Why the tuner is not totally power off after some time?

**Comment by lars18th** [comment]
Hi @catalinii ,

I'm not sure, but I suspect that the problem could be related to an incorrect ROLL-OFF handle in minisatip. Please, check this:

- The tunning testing transporder is 13E 10834V DVB-S2 8PSK 27500 3/4 **Roll-Off=0.20**.
- I execute minisat and I do a simple call to tune this transponder with a simple HTTP resquest. Then in the log I see:
```
[18/01 14:09:29.472 main]: detect_dvb_parameters (S)-> fe=0&src=2&freq=10834&pol=V&msys=DVBS2&mtype=8psk&sr=27500,ro=0.20&pids=0,1,17,18,20,21
[18/01 14:09:29.473 main]: detect_dvb_parameters (E) -> src=2, fe=0, freq=10834000, fec=9, sr=27500000, pol=1, ro=3, msys=6, mtype=9, plts=2, bw=8000000, inv=2, pids=0,1,17,18,20,21 - apids=NULL - dpids=NULL x_pmt=NULL
```

Please, note that the request includes "ro=0.20". But the tuned command includes "ro=3" that implies "auto".
Using the `dvb-fe-tool` I can see that every time the roll-off used it's "0.35/auto".
And the behaviour observed by my Enigma2 box is that the lock of the signal it's only stable for 3-4 seconds. Then the lock disappears and the tuner never retunes. In this case, I feel the driver doesn't support "auto roll-off" and then, at some time the algorithm to follow the signal snr seems that fogets the locking because the roll-off vaule is incorrect.

So, I checked the code here:
https://github.com/catalinii/minisatip/blob/1f40bbefd5b24361098da269924733ecb278666f/src/dvb.c#L189-L190

And I feel here we've a bug, and the `map_int()` call fails because the source is with the form `#.##`.
Please, could you try to fix it?

Thank you!

**Comment by Jalle19** [comment]
Your HTTP/RTSP request query string is invalid, leading to `ro=` not being parsed at all and thus defaulting to 0.35. `fe=0&src=2&freq=10834&pol=V&msys=DVBS2&mtype=8psk&sr=27500,ro=0.20&pids=0,1,17,18,20,21` <- note the `&sr=27500,ro=0.20` part - it should be `&sr=27500&ro=0.20`.

**Comment by Jalle19** [comment]
Closing this for now
