### ISSUE TITLE
RTP-Info

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#87]
can we get the RTP-Info right, the seq=0 is fixed atm and we miss rtptime=123123123
like
RTP-Info: url=rtsp://192.168.178.21/stream=18;seq=55446;rtptime=411856963

**Comment by catalinii** [comment]
I have changed the url a bit, basically cutting everything after ? from the initial URL.

However rtptime is not mandatory according to the RFC and seq is the position in the string.
0 has bigger changes than being valid than any other number.
