### ISSUE TITLE
Please add a ChangeLog file or update RELEASE_NOTES.md

### ISSUE THREAD

**Issue by marillat** [catalinii/minisatip#877]
Hi,

With all the releases you have done, would be nice if you can document what has been changed/added/modified to minisatip.

Christian

**Comment by Jalle19** [comment]
The way it works nowadays is that a new release is automatically made every time a commit is made to `master`, so the changes for each version is visible in the releases section on GitHub. Maintaining a change log file with only a single change per version would be too cumbersome.

**Comment by marillat** [comment]
For the record I'm packaging minisatip for the DMO repository.
https://www.deb-multimedia.org/
For me it's boring to go to github to read git commits for each release, for users is even more boring.

**Comment by Jalle19** [comment]
I think we should probably remove RELEASE_NOTES.md since no one is keeping it up to date.

Maybe we could generate a git shortlog or something for your Debian packages?

**Comment by marillat** [comment]
Yes, it's what others repositories do.

**Comment by Jalle19** [comment]
So something like this?

```
$ git shortlog v1.2.9..v1.2.10
Catalin Toda (1):
      Fix URL for non DVB-s2 signals #966

```

**Comment by Jalle19** [comment]
@marillat would it be possible to upstream the packaging scripts etc.? We have an issue for systemd units (https://github.com/catalinii/minisatip/issues/938) that could be solved if we could tell people to just build and install a `.deb` package or use the systemd unit that gets packaged.

**Comment by marillat** [comment]
It's fine for the log.
The units come from https://github.com/catalinii/minisatip/blob/master/tools/autostart.readme
debian directory to build the package is here https://www.deb-multimedia.org/pool/main/m/minisatip-dmo/minisatip-dmo_1.2.10-dmo1.debian.tar.xz

**Comment by Jalle19** [comment]
What I'd love to see is a `minisatip` user being created and the systemd service would then use it. Do you know how to do that? I'm not very familiar with building Debian packages.
