### ISSUE TITLE
Transport issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#88]
from the SES spec

Example SETUP of a client joining an existing stream for which it will not have ownership
Request>
SETUP rtsp://192.168.128.192:554/stream=27 RTSP/1.0 CSeq:1
Transport: RTP/AVP;unicast;client_port=42494-42495 Connection:close
Response>
RTSP/1.0 200 OK
Session:43ae7c353e77bc;timeout=60
com.ses.streamID:27 Transport:RTP/AVP;unicast;destination=192.168.128.100;client_port=42494-42495 CSeq:1

but we have

RTSP/1.0 200 OK
Cseq: 123
Date: Sun, Feb 8 19:45:51 2015 GMT
Transport: RTP/AVP;unicast;source=192.168.178.133;client_port=51338-51339;server_port=5500-5501
Session: 0424238335;timeout=30
com.ses.streamID: 2

and if you look at the dump from Panasonic/Digibit there is source and destination in

**Comment by catalinii** [comment]
Well, the digibit always returns the source and destination always . The fact that you see signal means that panasonic actually receives the data minisatip is sending.

Anyway I did some changes to look more like digibit, to see if it will make any difference,
