### ISSUE TITLE
ssdp

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#89]
we have only a simplified ssdp which can be also a issue for some clients like the hd+ android app

the spec is here specific
3.3.2 Server Advertisements

**Comment by catalinii** [comment]
HD+ is getting to request the XML, so it passes of the SSDP part, I doubt this is an issue.

As the application is available only in Germany I could not test, but logs are always welcome.
Thanks

**Comment by 9000h** [comment]
do we respect the spec here, due limited time I did not check the code

The TTL value of each IP multicast SSDP packet should default to 2.

**Comment by catalinii** [comment]
We dont, but this will limit the usage out of the local network.

I think because sat>ip can use rtp behaves much better in internet than tcp based protocols...so I do not see it really usefull to force it to be used just locally.

**Comment by 9000h** [comment]
btw the HD+ app did sends the M-Search as shown below

[10/02 16:28:41.132745]: Received SSDP packet from 192.168.178.195:50992 -> handle 3
M-SEARCH * HTTP/1.1
Man: "ssdp:discover"
Mx: 3
Host: 239.255.255.250:1900
St: urn:ses-com:device:SatIPServer:1

**Comment by catalinii** [comment]
Now HD+ is fixed. Can you test as well?

**Comment by catalinii** [comment]
Closing as hd+ works and ssdp is fully implemented
