### ISSUE TITLE
Auto QAM not allowed for DVB-C according to SAT>IP 1.2.2 specification

### ISSUE THREAD

**Issue by retrofan1979** [catalinii/minisatip#891]
you can try this not complete test for QAM_256 only
```
--- satipc.c.orig	2021-07-16 19:53:55.477965456 +0200
+++ satipc.c	2021-07-16 19:56:12.080336610 +0200
@@ -1105,6 +1105,10 @@
     satipc *sip = get_satip(ad->id);
     if (!sip)
         return;
+//quirk for Auroa client
+    if(tp->mtype == QAM_AUTO)
+        tp->mtype = QAM_256;
+
     url[0] = 0;
     FILL("freq=%.1f", tp->freq, 0, tp->freq / 1000.0);
     if (sip->use_fe && sip->satip_fe > 0)
```
@catalinii any idea how to workaround servers that do not handle QAM_AUTO like the AVM Fritzbox(the issue only happens when a client did not request 64qam or 256qam)
the AVM did reply withe 408 for PLAY in this case

_Originally posted by @9000h in https://github.com/catalinii/minisatip/issues/879#issuecomment-881620732_

**Comment by retrofan1979** [comment]
This quirk isn't embedded in the last commit. Can you please make a workaround for both 64qam and 256qam please?
AUTO QAM isn't allowed in SAT>IP specifications, mtype is mandatory.

**Comment by 9000h** [comment]
it's in but for 256qam as @catalinii only agree to to it this way, but you can patch your private version easy
https://github.com/catalinii/minisatip/blob/3ccdc47891db84eb863eeca7c738bec601cb64f0/src/satipc.c#L204-213

**Comment by retrofan1979** [comment]
Okay, thanks, I will try again. If it does work, I will let you know.

**Comment by retrofan1979** [comment]
Thanks, but it doesn't work perfectly. I need QAM64 for the homing channel which scans for available muxes/channels.
However, I need to try 3 or 4 times to finally get a stream for QAM64. The same goes after scanning channels.
I have to try to start the stream several times. Most of the time it works when the adapter is reset after x seconds.
I tried with 1 tuner, so I know for sure if the code works fine or not.

If this cannot be changed, please remove this 'fix' from commit as it doesn't help this way. Anyway thanks for your help so far.

**Comment by 9000h** [comment]
It‘s only a workaround and at the moment there is no better solution in your case

**Comment by retrofan1979** [comment]
Thanks, but it doesn't work perfectly. I need QAM64 for the homing channel which scans for available muxes/channels.
However, I need to try 3 or 4 times to finally get a stream for QAM64. The same goes after scanning channels.
I have to try to start the stream several times. Most of the time it works when the adapter is reset after x seconds.
I tried with 1 tuner, so I know for sure if the code works fine or not.

If this cannot be changed, please remove this 'fix' from commit as it doesn't help this way. Anyway thanks for your help so far.
