### ISSUE TITLE
Multistream support potentially broken

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#897]
Copied from https://github.com/Jalle19/satip-axe/issues/11

> Hello,
>
> I tried the latest firmware release from this fork today. Unfortunately, it couldn't tune in to any multistream signal.
I had to roll back to the latest version uploaded by perexg (2018) to get it working again. I'm using Digibit R1.
>
>Did I miss something or do you confirm that multistream reception is no longer working?
>
>Thank you and keep up the good work!

ping @tipexfm

**Comment by catalinii** [comment]
Is this related to the axe binary or in general ?

**Comment by Jalle19** [comment]
I'm not sure, maybe @lars18th or some other active Enigma user could check whether multi-stream works on Enigma? If so then this would seem to be limited to Axe devices.

**Comment by Jalle19** [comment]
Closing this since the original reporter never responded to this ticket
