### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#9]
I have some  warnings during compile here

gcc -ggdb -fPIC  -c -o minisatip.o minisatip.c 
minisatip.c: In function 'hexDump':
minisatip.c:221:24: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
minisatip.c: In function 'read_rtsp':
minisatip.c:435:56: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
minisatip.c:441:5: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
minisatip.c: In function 'posix_signal_handler':
minisatip.c:703:3: warning: #warning No arch defined [-Wcpp]
minisatip.c: In function 'mymalloc':
minisatip.c:779:3: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
minisatip.c: In function 'myfree':
minisatip.c:789:3: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
gcc -ggdb -fPIC  -c -o socketworks.o socketworks.c 
gcc -ggdb -fPIC  -c -o stream.o stream.c
gcc -ggdb -fPIC  -c -o dvb.o dvb.c
gcc -ggdb -fPIC  -c -o adapter.o adapter.c
gcc -ggdb -fPIC  -o minisatip minisatip.o socketworks.o stream.o dvb.o adapter.o -lpthread -lrt
root@yavdr:/home/yavdr/satip/minisatip-master# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

**Comment by catalinii** [comment]
This part is still work in progress, I am thinking of adding execinfo for the platforms that supports it.
The warnings are because of trying to figure out myself what is going on rather than using any library (easier to debug on embedded systems).

At this point they can be ignored, as they don't impact the functionality of the application.

**Comment by catalinii** [comment]
I had some time today so I fixed those...
please let me  know if you get another warnings.

Thanks

**Comment by 9000h** [comment]
will do so this afternoon

**Comment by 9000h** [comment]
looks good now
