### ISSUE TITLE
TEARDOWN issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#90]
a TEARDOWN should look like the sample below, but we miss the Session part

and send the TEARDOWN before close

TEARDOWN rtsp://192.168.178.21:554/stream=18 RTSP/1.0
CSeq:6
Session:ADB555E0
Server Response in 8 ms
RTSP/1.0 200 OK
CSeq: 6
Session:ADB555E0
Date: Fri, Jan 07 2000 00:57:55 GMT

**Comment by catalinii** [comment]
Can you test this ?

**Comment by catalinii** [comment]
This is fixed as well...
