### ISSUE TITLE
[Q] How to create fake signal values?

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#906]
Hi @catalinii ,

I've a new Linux E2 STB with satellite and terrestrial tuners. Futhermore I've installed on it one aditional unexpensive USB DUAL DVB-T tuner with the af9035 driver. Alls tuners work like a charm with minisatip inside OpenATV, so related to this I don't have any problem.

The problem is with the _third_ DVB-T tuner and minisatip. Tuner 2 and 3 for DVB-T are from the USB external tuner. And in this case the tuner has 0 signal/quality. It seems that the minisatip can't handle correctly _dual_ tuners using the Linux DVB API (with the `dvb-fe-tool` I can get only values from the device as it's one-tuner only). But as I've a central minisatip that receives signal from this STB using the `satipc` module, then I have no signal from this third tuner in the centralized minisatip. Then I want to know if I can provide a fake values of signal/quality for this specific tuner from the STB. The objective is that even the signal value received is fake, we can have values different from zero.

You've any idea to fix this?
Thank you.

**Comment by catalinii** [comment]
Hey @lars18th ,

Do you get value 0 or the call to get signal fails?
If it fails, we can the default to a non zero value. 
If it returns 0, then we may need some code added to handle this.

**Comment by lars18th** [comment]
Hi @catalinii ,

The `state.json` in the user interface receives a 0 value from the core. However, I suspect you want to know if the syscall that receives the data from the tuner inside the core fails or gets zero, right? Please, can you point to the code that gets the value from the tuner? I'll check it.

Regards.

**Comment by catalinii** [comment]
https://github.com/catalinii/minisatip/blob/master/src/dvb.c#L1451

Generally if the syscall fails you should see a message ineicating that.

Are the drivers used open source or included in the kernel?

**Comment by lars18th** [comment]
> Are the drivers used open source or included in the kernel?

It's a OpenATV Linux Enigma2 STB, so the drivers are mainly opensource in the stock kernel. The driver is the regular af9035, and with the linux stock firmware. I'll do a check in foreground enabling the log in minisatip.

Regards.

**Comment by lars18th** [comment]
Hi @catalinii ,

In the E2 STB the `dmesg` continously prints messages like:
```
[191415.121000] af9033 0-003a: i2c rd failed=-5 reg=8000f7 len=1
[191415.122000] af9033 0-003a: i2c rd failed=-5 reg=80f903 len=1
[191415.123000] af9033 0-003a: i2c rd failed=-5 reg=8000f7 len=1
[191415.124000] af9033 0-003a: i2c rd failed=-5 reg=80f903 len=1
[191415.138000] af9033 0-003a: i2c rd failed=-5 reg=800047 len=1
 ```

And the command `dvb-fe-tool -m -a 2` every time reports zero values: `(0x00) UCB= 0 postBER= 0`

So, I suspect the minisatip is receiving `0`. Then we need to patch/hack/replace this value.

**Comment by lars18th** [comment]
Hi @catalinii ,

When running minisatip in foreground and with DVB debug enabled, I see this in the LOG:
```
[09/12 13:05:40.192 signal]: get_signal_new: unable to query frontend 13: Remote I/O error
[09/12 13:05:40.192 signal]: get_signal_new adapter 3: status 0, strength 0 (none) -> 0, snr 0 (none) -> 0, BER: 0, err 101
[09/12 13:05:40.192 signal]: get_signal adapter 3: status 0, strength 0, snr 0, BER: 0
[09/12 13:05:40.192 signal]: get_signal took 1 ms for adapter 3 handle 13 (status: 0, ber: 0, strength:0, snr: 0, force scan 0)
[09/12 13:05:40.494 signal]: get_signal adapter 3: status 0, strength 0, snr 0, BER: 0
```

So, the `get_signal_new()` fails in the ioctl call, and then the old `get_signal()` is used. However, in this function the ioctl calls don't fail, but the values reported are 0.

You think this could fixed?

**Comment by lars18th** [comment]
Hi @catalinii ,

Finally I discovered that the issue is with the USB driver. If I reboot the STB, when restarting the device, then the second tuner initialization _partially_ fails. So the tuner/frontend works, but the read of the signal fails. So it's a driver problem, not related with minisatip.

However, perhaps for a future enhancement you will want to add some support for a fake tuner signal.
Anyway, thank you for your help.
Regards.

**Comment by catalinii** [comment]
Probably the easiest fix is to define some arbitrary values https://github.com/catalinii/minisatip/blob/master/src/adapter.c#L115 and use them to set the signal absolute value to maximum

**Comment by lars18th** [comment]
> Probably the easiest fix is to define some arbitrary values https://github.com/catalinii/minisatip/blob/master/src/adapter.c#L115 and use them to set the signal absolute value to maximum

Great idea. For example, setting to MAXINT (or lower funcional value, like 9999), then the function that calculates the value, in this case will returns the max value. 👍

**Comment by lars18th** [comment]
Hi,

I prefer to close this issue as we're adding some improvements based on #911 .
