### ISSUE TITLE
Crashes on connect

### ISSUE THREAD

**Issue by robbieb43** [catalinii/minisatip#907]
Hi 

I have been using the old pre-compiled binary (minisatip version 0.5.69, compiled with s2api version: 0504) on my DM800 for some years and it works OK with a few limitations. I decided to compile the latest release   1.1.51 which I cross compiled for mipsel.  Runs OK, webif works OK but it exits when I make a satip request.  In foreground mode it  does not exit but fails with a 404 error to the client.

[minisatip.log](https://github.com/catalinii/minisatip/files/7654145/minisatip.log)

I notice the Frequency seems to be changed and then there is a frequency out of range error.

Many thanks

Rob

**Comment by catalinii** [comment]
Can you download the latest binary for mips from here: https://github.com/catalinii/minisatip/releases

Or install using opkg ? (opkg update && opkg install minisatip)

**Comment by robbieb43** [comment]
Many thanks catalinii.  The latest release in your link works fine (except for a crash issue on one particular URL that existed in 0.5.69) which I will fully investigate and report if and once I have verified that it is minisatip issue. The feed for my elderly image seems not to include minisatip. This is a very helpful.  For the record my version was built with stbgcc-8.3-0.4 toolchain.  I will close this issue.
