### ISSUE TITLE
OPTIONS issue

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#91]
looks like we miss the Session: here

Request>
OPTIONS rtsp://192.168.178.57:554/ RTSP/1.0
CSeq:5
Session:2180f601c42957d
Connection:close

Response>
RTSP/1.0 200 OK
Public:OPTIONS,SETUP,PLAY,TEARDOWN,DESCRIBE
CSeq:5
Session:2180f601c42957d

**Comment by catalinii** [comment]
this should not be an issue if the session is established.
Can u post logs ?
