### ISSUE TITLE
Potential error: warning overflow

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#927]
Hi @catalinii ,

Compiling with a recent compiler the current master I see this:
```
minisatip.c: In function ‘ssdp_notify’:
minisatip.c:1615:28: warning: ‘%s’ directive writing up to 49 bytes into a region of size 43 [-Wformat-overflow=]
 1615 |     sprintf(nt[1], "::uuid:%s", uuid);
      |                            ^~   ~~~~
minisatip.c:1615:5: note: ‘sprintf’ output between 8 and 57 bytes into a destination of size 50
 1615 |     sprintf(nt[1], "::uuid:%s", uuid);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Perhaps you want to fix it increasing the size of the variable: `char nt[3][50];` to `char nt[3][60];`

**Comment by lars18th** [comment]
Hi @catalinii ,

You don't think it's safe to change the size of the array to overcome the warning?

**Comment by catalinii** [comment]
Yes it is safe, feel free to make a PR.

**Comment by lars18th** [comment]
> Yes it is safe, feel free to make a PR.

Done #937
