### ISSUE TITLE
CAS encryption

### ISSUE THREAD

**Issue by odehalaa** [catalinii/minisatip#929]
Hi, 

Many thanks  for your kindly support

I need to ask if possible to add like TVCAS with Minisatip to encrypt FTA channels please ?

Best Regards

**Comment by catalinii** [comment]
Hey,

There are 2 issues:
1) no user requests for this feature
2) no access to SW/HW

**Comment by odehalaa** [comment]
Hi,

Please if possible I can provide you everything you want and I can send you cards and programmers ?

here is the software free 

https://tvcas.com/


Best Regards

**Comment by Jalle19** [comment]
This seems completely out of scopr for minisatip. TVCAS is for _encrypting_ channels, right?

**Comment by odehalaa** [comment]
yes for encryption channels, or at least if you can add BISS encryption for security if possible please ?

**Comment by Jalle19** [comment]
There are probably other ready solutions for adding your own CA to streams. I doubt it would make sense to support this in ministatip.
