### ISSUE TITLE
RFE: IEEE 802.1Q VLAN standard QoS 

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#93]
low prio, we may can add QoS tags to the stream packets

**Comment by lars18th** [comment]
Hi @catalinii ,

TVHeadEnd has this implemented: http://tvheadend.org/issues/2701

Mainly, the change is based on "mark" the udp socket. See the code:

```
  if (config.dscp >= 0) {
    socket_set_dscp(rtp->fd_rtp, config.dscp, NULL, 0);
    socket_set_dscp(rtp->fd_rtcp, config.dscp, NULL, 0);
  } else {
    socket_set_dscp(rtp->fd_rtp, IPTOS_DSCP_EF, NULL, 0);
    socket_set_dscp(rtp->fd_rtcp, IPTOS_DSCP_EF, NULL, 0);
  }
```

As the function is easy to implement, please, can you add this option?
Thank you!

**Comment by lars18th** [comment]
> low prio, we may can add QoS tags to the stream packets

Already implemented: https://github.com/catalinii/minisatip/commit/ea0f5bd168f9edc8b816e94831e9b2fcb59578a2
:wink: 

Just to report it.
