### ISSUE TITLE
HTTP client timeout

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#930]
Hi @catalinii ,

I discovered this use case: Some HTTP client connects to minisatip, and minisatip doesn't have signal from the requested stream (the adapter source is the `satipc` module). However, the client _never_ closes the socket. And in this case the socket continues opened forever.

So, I feel it will interesting to have a _no-action-timeout_ parameter for HTTP sessions (almost, but perhaps for RTSP as well). This parameter indicates the time to close the session from the SERVER side.

What you think?

**Comment by catalinii** [comment]
Hey @lars18th ,

WhileI understand that there is benefit to such implemention I am generally against going against standard definition as this can create bugs and hard to debug issues.

**Comment by lars18th** [comment]
OK. This has only a suggestion.
