### ISSUE TITLE
Ship a decent systemd unit

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#938]
Everyone wants to run minisatip in the background, with automatic restarts and PID files and other bells and whistles. Currently everyone has to roll their own, leading to sub-par solutions (nohup scripts, /etc/rc.local etc.).

I suggest we ship a systemd unit and explain in the README how to use it. Custom platforms like axe or Enigma2 already have their own ways of starting minisatip, but generic PC users are currently left to figure it out for themselves.

**Comment by bccrew** [comment]
@Jalle19 I wrote a guide a while ago :)

https://github.com/catalinii/minisatip/blob/master/tools/autostart.readme

**Comment by Jalle19** [comment]
Will try running minisatip as an unprivileged user, using systemd's `AmbientCapabilities`. If it works I'll write up a PR.

**Comment by Jalle19** [comment]
Closed by #986
