### ISSUE TITLE
[Req] Improve client info in UI

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#940]
Hi,

I request if someone wants to implement this in the UI:
- At time for each used tuner a simple "client:" tag is printed when the client is HTTP and provides an identification header. Hover, this info it's insufficient to know how is using a tuner when multiple clients/tuners are in use.
- So the idea is to add more info: source address, src-port, protocol, name. Example
  - `Client: 192.168.1.100:10554/RTSP-UDP/vlc`
  - `Client: 192.168.1.101:50001/HTTP/Chrome`
  - `Client: 192.168.1.102:34567/RTSP-TCP/minisatip`
- And _optionally_, if this could be added, also the list of requested pids fron each user with a mapping of the corresponding PMTs to the name of the channel. Example:
  - `Client: 192.168.1.102:34567/RTSP-TCP/minisatip - TV1HD,TV2HD`
  - `Pids (minisatip): 0,16,18,20,21,100,101,200,201`

And also for the Tuner status of satipc modules, instead of printing only the server ip address, add the port and the protocol too. This last will be useful to know if the connection is configured for UDP RTSP or RTSP-over-TCP. And the port to distinguish different daemons (running of example in the loopback).

Thank you.

**Comment by lars18th** [comment]
I forgot to mention to add a button or link for closing a specific client.

You agree?

**Comment by Jalle19** [comment]
I'd like more client info as well, but personally I'd prefer it if the web interface was strictly read-only, i.e. no way to control anything. Kicking a client will only make it re-subscribe a moment later for example.

**Comment by lars18th** [comment]
Hi @Jalle19 ,

I've already implemented this, without the option to disconnect clients that you prefer. Please, check it and merge.

Regards.

**Comment by lars18th** [comment]
I close it because the enhacement is completed.
