### ISSUE TITLE
Signal strength and SNR values (doesn't take -M parameters)

### ISSUE THREAD

**Issue by retrofan1979** [catalinii/minisatip#965]
When using -M parameter, it doesn't do anything with it when I set the STR/SNR values to 0 for all adapters for example (to get 100%) or any other value in the status page of minisatip on port 8080. Is this a bug?

![capture str snr](https://user-images.githubusercontent.com/30625590/166099887-7e737f91-24ed-4e9e-9df7-563953fef947.png)

**Comment by Jalle19** [comment]
@retrofan1979 does it work correctly if you specify the adapters manually (e.g. `0:0-0,1:0-0`) instead of using `*:0-0`?

**Comment by retrofan1979** [comment]
No, unfortunately not.

**Comment by Jalle19** [comment]
Can you post a log with `-l general,dvb`?

**Comment by retrofan1979** [comment]
Sure!
[minisatip.log](https://github.com/catalinii/minisatip/files/9269202/minisatip.log)

**Comment by Jalle19** [comment]
@retrofan1979 can you try https://github.com/Jalle19/minisatip/commit/daf83620c0c30c65b91f7a6a606bdcdadb4a1298 ?

**Comment by retrofan1979** [comment]
I did recompile minisatip again, but no change. Here's the log again.
