### ISSUE TITLE
Incorrect URL mentioned on status page

### ISSUE THREAD

**Issue by ghost** [catalinii/minisatip#966]
The RTSP and HTTP links are mentioned on the status page of minisatip on port 8080.
However, the URL's are incorrect for DVB-C.

the following parameters aren't allowed for DVB-C:

- fe
- src
- pol

For example how it should look like:
http://192.168.0.10:8080/?freq=378&msys=dvbc&sr=6900&mtype=256qam&pids=0,16,17,18,20,2300,2301,2401,2311

With RTSP link also @ is mentioned and with HTTP link http in address is missing at the beginng of the url.

![capture rtsp link](https://user-images.githubusercontent.com/30625590/166100000-91436805-dbdd-434c-a63d-55311e210224.png)

![capture http link](https://user-images.githubusercontent.com/30625590/166099994-6832f03c-5d27-417f-8ace-e44bcaceced5.png)

**Comment by Jalle19** [comment]
Where does it say that fe, src and pol are invalid for DVB-C?

**Comment by retrofan1979** [comment]
Hi, it can be found in the SAT>IP protocol. See query example for DVB-C as well. And fe, src and pol aren't mentioned for DVB-C. Those are for DVB-S.

![image](https://user-images.githubusercontent.com/30625590/166212984-e442cdb0-5a59-443e-a821-1da7707405a2.png)

**Comment by Jalle19** [comment]
This is a bug in `status.html`, it should be smarter about adding parameters to the URL.

**Comment by catalinii** [comment]
fe cannot be removed as it selects which DVB C/T adapter is being used. The other 2 (src, pol) were removed in this PR.
cc @Jalle19

**Comment by Jalle19** [comment]
Looks good, at some point we should refactor and clean up some of this logic.

**Comment by retrofan1979** [comment]
Great, thanks! If Netstream 4C SAT>IP device is used, fe isn't allowed. It would be nice if the URL in this case also doesn't show fe parameter.

**Comment by patacalas** [comment]
"isi" and "plsc" params are missing on multistream HTTP and RTSP links.

![image](https://user-images.githubusercontent.com/46358037/182579789-eed0d939-694c-4bd5-8bb6-a05c99a6ec01.png)

In addition, alternative audio pids are missing too. URL link only shows the selected audio on Sat-IP client which is playing the channel.

**Comment by catalinii** [comment]
@retrofan1979 are you talking about the request to the satip server Netstream 4C SAT>IP  not involving the URL from minisatip web page ? Or you are talking about copying the URL from web and then sending it to netstream?

**Comment by retrofan1979** [comment]
@catalinii yes, the real executed URL isn't displayed on the webpage of minisatip.
In case of the Netstream 4C the fe parameter isn't allowed as the device does control itself.

**Comment by catalinii** [comment]
@retrofan1979 not sure I got the answer to my questions.
1) Is the issue with the satip client module in minisatip making the request to Netstream 4C ? [Yes/No]
2) The URL from the web page includes fe= (as is the case now) causing issues with Netstream 4C ? [Yes/No].
3) Related to the URL executed is not displayed on minisatip page, what is missing ? Please test https://github.com/catalinii/minisatip/tree/issue_966

**Comment by retrofan1979** [comment]
Is the issue with the satip client module in minisatip making the request to Netstream 4C ? [Yes/No] NO
The URL from the web page includes fe= (as is the case now) causing issues with Netstream 4C ? [Yes/No]. NO
Related to the URL executed is not displayed on minisatip page, what is missing ? Nothing is missing, but the Netstream 4C doesn't support the frontend (fe) parameter, so I expect this parameter will not be displayed at the minisatip page. The same goes for pol and src parameters which are not supported for DVB-C, so in my opinion it may not be displayed in the URL.

**Comment by catalinii** [comment]
Can you check how is it now with the latest master?

**Comment by 9000h** [comment]
looks like the channel names get mixed up when you have multiple delsys like dvbs and dvbc

**Comment by catalinii** [comment]
can you upload the logs? (make debug)
also can you provide more info for the "channel names getting mixed up" ?

**Comment by 9000h** [comment]
here is a sample showing the same channel name for dvb-s and dvb-c which is wrong
![Unbenannt](https://user-images.githubusercontent.com/3009073/194302320-6760463b-ff1c-4c47-bd38-28e833450ecc.PNG)

**Comment by 9000h** [comment]
probably releated to #1000

**Comment by catalinii** [comment]
Channel names are fixed

**Comment by Jalle19** [comment]
Can this be closed?
