### ISSUE TITLE
Minisatip development

### ISSUE THREAD

**Issue by engalaaodeh** [catalinii/minisatip#969]
Dears,

Kindly I Need to build simple script to send http request to Minisatip with pid=all to response all services names with pids with signal quality and please which command or tool or javascript I can use it please ?

Best Regards

**Comment by odehalaa** [comment]
I need to build simple script to response channels received on frequency to generate m3u8 file 
by http resquest and pid=all

**Comment by odehalaa** [comment]
http://192.168.1.20:8080/?fe=0&src=1&freq=12284&pol=V&msys=DVBS2&mtype=8psk&sr=27500&pids=all

**Comment by Jalle19** [comment]
I forgot to come back to this issue. I'm not sure if there's anything that minisatip specifically can do to help with your problem, you'll have to figure out how to create the script on your own. You can see what HTTP requests the web interface makes if you want to see how the signal strength is determined per tuner.
