### ISSUE TITLE
Roadmap proposal

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#97]
what do you think about a road map for the project.

topic's I have in mind are:

- unicable pin support 
- monitoring/web/config interface
- ipv6
- multicast
- en50221 (could be also a plugin)
- multi thread support

**Comment by catalinii** [comment]
I propose to put an item in the new system for each request (if there is not already one).

If the users feel stronger about some of them can comment on them....

**Comment by lars18th** [comment]
Hi, I suggest first transparent en50221 support.
Then Multicast support. Las multi-thread for better performance.

Web interface and IPv6 isn't a high priority!

This is my point of view. :)

**Comment by 9000h** [comment]
so as most of the list are already implemented I close the case
