### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by lars18th** [catalinii/minisatip#974]
Please fix this error with the CI build:

```
Run wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=$PROJECT" -O cov-analysis-linux64.tar.gz
  wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=$PROJECT" -O cov-analysis-linux64.tar.gz
  mkdir cov-analysis-linux64
  tar xzf cov-analysis-linux64.tar.gz --strip [1](https://github.com/catalinii/minisatip/runs/6688521382?check_suite_focus=true#step:7:1) -C cov-analysis-linux64
  shell: /usr/bin/bash -e {0}
  env:
    TOKEN: 
    PROJECT: minisatip[2](https://github.com/catalinii/minisatip/runs/6688521382?check_suite_focus=true#step:7:2)
Error: Process completed with exit code [6](https://github.com/catalinii/minisatip/runs/6688521382?check_suite_focus=true#step:7:6).
```

**Comment by catalinii** [comment]
@lars18th where do u see this?

**Comment by Jalle19** [comment]
https://github.com/catalinii/minisatip/runs/6688521382?check_suite_focus=true

**Comment by Jalle19** [comment]
I'm don't think that's a good idea. Does the wget work locally when you supply the token?

**Comment by catalinii** [comment]
Yeah it does. The only other option is to bake the binary in minisatip-build-image and there I can use the token. But then will need to update the (docker) image regularly which probably is an acceptable compromise.

**Comment by Jalle19** [comment]
Surely there must be a way to specify secret environment variables in GitHub Actions? 🤔

**Comment by Jalle19** [comment]
@catalinii could we consider hosting a copy of the Coverity ZIP file on minisatip.org?

**Comment by catalinii** [comment]
Whatever you prefer I am fine with both

**Comment by Jalle19** [comment]
I'm fine with any solution really 🤷

**Comment by catalinii** [comment]
I changed the minisatip-build-image and just involed coverity in PRs and it works.
