### ISSUE TITLE
Problems tuning Eutelsat 9ºE multistream channels

### ISSUE THREAD

**Issue by patacalas** [catalinii/minisatip#978]
Hi!
I have a Gigablue UHD Quad 4K running Minisatip standalone. 
My receiver is enhanced with the PnP DVB-S2X dual tuner so I can receive all Italian multistream channels from Eutelsat 9ºE on Enigma2.
I've enabled frontends 1,5-7,9 on Minisatip, the first four are connected to Unicable LNBs serving Astra, Hotbird and Hispasat using the FBC tuner (no problem with this part) and frontend number 9 is connected to a Legacy LNB to Eutelsat 9ºE to receive Italian channels.

I have 2 problems with Eutelsat 9ºE multistream channels and Minisatip: 

The first one is that Minisatip can't tune transponders with 16APSK modulation (I have good reception of this channels using Enigma2). My client receiver is a Vu+Solo SE using Enigma2 Sat-IP Client. I guessed the problem should be the client receiver, as it isn't a DVB-S2X, but generating the rstp request with VLC and mtype=16apsk param it doesn't work either.

The second problem is related to the transponder 12149V. I have no problems tuning 8PSK multistream transponders, with the exception of 12149V. For some reason, this transponder works like a charm using Enigma2 but Minisatip can't tune it.  The rest of 8PSK multistream transponders work great in both Enigma2 and Minisatip.

I've tested different releases of Minisatip, from v1.1.81 to v1.2.7 and those problems happen in all of them. 
After several tests, I have installed v1.1.92 because Oscam (running on client receiver) doesn't work in newer versions, I get DEC-ERRORS on Minisatip and the client receiver isn't able to decrypt channels. I guess this problem with Oscam could be solved with some configuration parameter that I can't find (I'm a newbie in Minisatip).

I use the following command to start Minisatip:
`minisatip -e 1,5-7,9 -S 5-7:1 -j 1:16-1530,5:17-1566,6:18-1602,7:19-1638 --satip-xml http://192.168.194.39:8554/ -R
/usr/share/minisatip/html`

Thanks in advance.

**Comment by catalinii** [comment]
Hi,

Can you try to upload the logs of:

./minisatip -f -l http,dvb

And then try the vlc using that URL?

**Comment by patacalas** [comment]
Hi @catalinii 
I'm sharing logs related to the issues.

### First issue: tuning 16APSK modulation transponders is impossible in Minisatip.
I've tried to tune in channels on 12303V using Enigma2 SatIP client on Vu+Solo SE and VLC.

![image](https://user-images.githubusercontent.com/46358037/182054471-f4995c44-f8e2-48a6-86a2-075187a58114.png)

Enigma2 SatIP Client is sending requests using a wrong mtype param (mtype=qpsk), that's why I've also tested with VLC to ensure right params on RSTP request.
 
[tuning_12303V_client_receiver.txt](https://github.com/catalinii/minisatip/files/9230158/tuning_12303V_client_receiver.txt)
[tuning_12303V_vlc.txt](https://github.com/catalinii/minisatip/files/9230159/tuning_12303V_vlc.txt)

If I tune in this channel on Gigablue UHD Quad 4K (server) using Enigma2, it works great.

![image](https://user-images.githubusercontent.com/46358037/182054689-5a59f099-ac5d-4f99-a4f8-7c4de84403ab.png)

### Second issue: Minisatip can't tune multistream transponder 12149V - 8PSK modulated. 
[tuning_12149V_client_receiver.txt](https://github.com/catalinii/minisatip/files/9230214/tuning_12149V_client_receiver.txt)

Minisatip works fine with the rest of 8PSK multistream transponders in Eutelsat 9E, but tuning 12149V is impossible. As in the previous case, Gigablue receiver has no problems with this transponder under Enigma2.
 
![image](https://user-images.githubusercontent.com/46358037/182055106-fc7031c3-1106-4e69-b744-d3d0a77adc64.png)

I can do more tests to try to solve the problem if needed. Don't hesitate to ask me.

Greetings.

**Comment by catalinii** [comment]
Hi,

can you add "&plsm=gold"  to the VLC url ?

and let me know if it works.

Thanks

**Comment by patacalas** [comment]
Hi,  @catalinii 

I've tested the last version (v1.2.10) with VLC adding the &plsm=gold param and I got VLC can't open url error.

I've tried these URLS:
/?fe=5&src=1&freq=12303&mtype=16apsk&pol=V&msys=DVBS2&sr=31400&plsm=gold&pids=0,1,16,17,18,201,3500,3501
/?fe=5&src=1&pol=V&freq=12466&msys=DVBS2&plsm=gold&mtype=8psk&sr=41950&pids=801,803,18,804,0,800,1 

**LOGS**
[vlc_12303v.txt](https://github.com/catalinii/minisatip/files/9245415/vlc_12303v.txt)
[vlc_12466v.txt](https://github.com/catalinii/minisatip/files/9245416/vlc_12466v.txt)

In addition, I still can't use OSCAM on SatIP clients with Minisatip release v1.2.10. Minisatip webif shows DEC-ERRORS and Oscam doesn't work. Is there a parameter that I am forgetting to solve decryption problem?

Thanks

**Comment by catalinii** [comment]
I see in the logs I see
02/08 22:06:50.064 main]: dvb_tune: set property failed 22 Invalid argument

Can you provide remote access?

**Comment by patacalas** [comment]
plsm=gold doesn't work.
If I add the plsm=gold parameter to a correct url which works, it stops working.

**URL working**
/?fe=5&src=1&pol=V&freq=12341&msys=DVBS2&mtype=8psk&sr=31400&plsc=262140&isi=35&pids=701,703,18,0,700
[log_working.txt](https://github.com/catalinii/minisatip/files/9246167/log_working.txt)


**URL not working**
//?fe=5&src=1&pol=V&freq=12341&msys=DVBS2&mtype=8psk&sr=31400&plsm=gold&plsc=262140&isi=35&pids=701,703,18,0,700
[log_not_working.txt](https://github.com/catalinii/minisatip/files/9246168/log_not_working.txt)

**Comment by catalinii** [comment]
As I said, if you are open to provide remote access I can take a look atthis.

**Comment by catalinii** [comment]
Does this work with the latest master?

**Comment by Jalle19** [comment]
@patacalas ?

**Comment by patacalas** [comment]
Sorry for my late reply,  I've been very busy.

I've tested last release v1.2.44 and the problems continue. Client receiver only can tune 8PSK modulated multistream transponders (except 12149V). 16APSK transponders still missing.

**Comment by catalinii** [comment]
Can you upload the log (minisatip -f -l http,dvb)

**Comment by Jalle19** [comment]
@patacalas when you tested 16APSK last time you used the wrong URL and thus the wrong modulation: `tuning to 12303000(1703000) pol: v (1) sr:31400000 fec: delsys:dvbs2 mod:8psk`

Please try again (make a new log) with the latest version and re-open this issue if you still can't play 16APSK transponders.
