### ISSUE TITLE
Show service CAID in Cryptinto column

### ISSUE THREAD

**Issue by Jalle19** [catalinii/minisatip#982]
At least when using CI modules this piece of information is not present anywhere.

**Comment by catalinii** [comment]
I am not aware of any message back from the CAM which would indicate which CAID is being used. In general you can find out the instersection of CAID of the PMT and CAM, but there are CAMs reporting multiple CAIDs (such as Alphacrypt).

**Comment by Jalle19** [comment]
Yeah, it can be difficult to present the correct value to the user. Maybe we could start by showing the CAIDs the CAM supports in the Cryptinfo column for the CAM itself (maybe along with name)?
