### ISSUE TITLE
Auto QAM: set qam parameter if it's not specified by client

### ISSUE THREAD

**Issue by retrofan1979** [catalinii/minisatip#988]
Can you please also let minisatip set qam parameter if it's not specified by client?
Normally it's qam256 at default, but sometimes it's qam64.

**Comment by Jalle19** [comment]
@retrofan1979 what's the use case for this? AFAICT the client should always specify `mtype`?

**Comment by retrofan1979** [comment]
Yes, you're right, but I'm using an old client which I like very much, but it's not maintained anymore, so I was hoping minisatip could fix this. By the way, my Panasonic TV works correctly with this app, so indeed because it's non-spec, the Panasonic does correct it as it should. Maybe minisatip can do the same.

If not, please guide me which changes I have to make, so I can compile a private build ;-)
Thanks!

**Comment by Jalle19** [comment]
The default value should be QAM_AUTO, do you have a tuner which doesn't support that?

**Comment by Jalle19** [comment]
You can change the default in init_dvb_parameters in dvb.c if you want to test

**Comment by retrofan1979** [comment]
Okay, thanks. I have the Elgato Netstream 4C.

**Comment by retrofan1979** [comment]
Maybe you can put the needed code here? That would be nice!

**Comment by retrofan1979** [comment]
I also tried the Fritz!WLAN Repeater DVB-C and Fritz!Box 6660 Cable and they have the same behaviour as the Elgato Netstream 4C. Only my Panasonic TV with build-in SAT>IP server is capable to correct it adding the correct qam parameter if the client doesn't supply it.

**Comment by Jalle19** [comment]
Do you know which QAM your TV adds? 64, 128, 256?

**Comment by retrofan1979** [comment]
Yes, both 64 and 256. For scanning channels my cable operator uses qam64 and for watching channels qam256.
https://dvblogic.com/wiki/index.php/Fast_channel_search_parameters

**Comment by 9000h** [comment]
https://github.com/catalinii/minisatip/issues/879#issuecomment-881907436

**Comment by Jalle19** [comment]
So this is an issue specifically when using minisatip client mode (satipc) with a server that doesn't support QAM_AUTO? I'm confused. Coumd it just be that the Panasonic TV handles QAM_AUTO correctly as it should?

**Comment by Jalle19** [comment]
@retrofan1979 ?

**Comment by retrofan1979** [comment]
Yes, with Panasonic TV as SAT>IP server, I have to problems with this old client (Android app). Probably the Panasonic TV adds this parameter when the client doesn't request it and tries different modulations like 64 and 256. The other mentioned SAT>IP servers don't do this, but I think the way of how Panasonic implemented is the correct one, as this parameter is mandatory according to the SAT>IP protocol, so it will be corrected by the server.

**Comment by Jalle19** [comment]
I'm not sure it's feasible to implement this. QAM can vary per mux, so there may not be a default value that works for all channels.

**Comment by Jalle19** [comment]
I'm closing this for now, until we maybe come up with a good enough workaround.
