### ISSUE TITLE
Some problem minisatip....

### ISSUE THREAD

**Issue by emulate45** [catalinii/minisatip#994]
Google translator:
Hello. Unable to start CL module on TBS6590. After many attempts, I get the same problem, FTA channels show perfectly, CL and CL + do not react at all. I installed the certificates, the module is being checked according to the logs, but there is no image ... Can you help me?

**Comment by Jalle19** [comment]
Start by uploading a log here with `-l general`

**Comment by emulate45** [comment]
we use minisatip --> astra
[log.txt](https://github.com/catalinii/minisatip/files/9634546/log.txt)

**Comment by catalinii** [comment]
Please use the master from today (as I see you're using version 1.1) and provide the log again:

./minisatip -l http,ca

**Comment by Yuri666** [comment]
CAM can't process all pids from tansponder - you should filter pids for one neded channel in astra. (or for two channels, if you use -c options in minisatip for your MTS TV CAM)
