### ISSUE TITLE
with todays update (latest commit) orf channels are not shown anymore after few channel switches

### ISSUE THREAD

**Issue by holli73** [catalinii/minisatip#998]
hello,

today i updated since a long time ago minisatip again but it broke my orf channels.
if i switch few times between them - i do not get a picture anymore and the dec-error increases but within oscam log no error is reported - from oscam log all looks ok - as it still delivers the key.

i tried with the -c switch - removed it changed it to 1 now to 2 but still after few switches no more video is available.

what kind of log/trace might be helpfull to figure out why the channels are not shown anymore?

this is my start command:

`  /home/holli/BUILD/minisatip/minisatip-master/minisatip-latest -a 8:0:0 -D 1 -e 0-7 -o 192.168.248.248:11234 -x 8080 -m 661122334455 -O -y 554 -c 0:2,1:2,2:2,3:2,4:2,5:2,6:2,7:2 &`

thanks
holli

attached is a log - i switched 3-4 times between orf channels but did not get any video/picture anymore after the 3rd channel switch...

[minisatip.log](https://github.com/catalinii/minisatip/files/9719136/minisatip.log)

**Comment by catalinii** [comment]
Can you check if commit 79edc6ec893c4fa05e68d66e2553b2760716b429 works good ?

**Comment by catalinii** [comment]
@holli73 can oyu provide remote access ?

**Comment by catalinii** [comment]
Can you upload a new log (same flags is fine), and note the time a specific channel stops decrypting.

Tell me the channel and time it stopped.

**Comment by holli73** [comment]
@catalinii i could provide teamviewer access if still needed.

**Comment by catalinii** [comment]
Can you try the latest master ?
thanks

**Comment by Jalle19** [comment]
@catalinii latest master has some warnings now (related to PMT)

**Comment by catalinii** [comment]
I fixed the warnings, thanks for letting me know.

**Comment by holli73** [comment]
i just did a new pull and now i can switch again between the channels 
thanks
holli
